portal.registration.dao.IdpDAOImpl Class Reference
Public Member Functions
void save (Idp transientInstance)
void delete (Idp persistentInstance)
Idp findById (Integer id)
List< Idp > getAllIdp ()
Private Attributes
SessionFactory sessionFactory
Static Private Attributes
static final Logger log = Logger.getLogger(IdpDAOImpl.class)
Detailed Description
Definition at line 15 of file IdpDAOImpl.java.
Member Function Documentation
void portal.registration.dao.IdpDAOImpl.delete (Idp persistentInstance)
Implements portal.registration.dao.IdpDAO.
Definition at line 34 of file IdpDAOImpl.java.
References portal.registration.dao.IdpDAOImpl.log, and portal.registration.dao.IdpDAOImpl.sessionFactory.
                                                   
                log.debug("removing Idp instance");
                try
                        Session session = sessionFactory.getCurrentSession();
                        session.delete(persistentInstance);
                        log.debug("remove successful");
                 catch (RuntimeException re)
                        log.error("remove failed", re);
                        throw re;
                
        
Idp portal.registration.dao.IdpDAOImpl.findById (Integer id)
Implements portal.registration.dao.IdpDAO.
Definition at line 46 of file IdpDAOImpl.java.
References portal.registration.dao.IdpDAOImpl.log, and portal.registration.dao.IdpDAOImpl.sessionFactory.
                                        
                log.debug("getting Idp instance with id: " + id);
                try
                        Session session = sessionFactory.getCurrentSession();
                        Idp instance = (Idp) session.get(Idp.class, id);
                        log.debug("get successful");
                        return instance;
                 catch (RuntimeException re)
                        log.error("get failed", re);
                        throw re;
                
        
List<Idp> portal.registration.dao.IdpDAOImpl.getAllIdp ()
Implements portal.registration.dao.IdpDAO.
Definition at line 60 of file IdpDAOImpl.java.
References portal.registration.dao.IdpDAOImpl.log, and portal.registration.dao.IdpDAOImpl.sessionFactory.
                                     
                log.debug("getting all Idp instance");
                try
                        Session session = sessionFactory.getCurrentSession();
                        // Create a Hibernate query (HQL)
                        Query query = session.createQuery("FROM Idp");
                        // Retrieve all
                        return query.list();
                 catch (RuntimeException re)
                        log.error("get failed", re);
                        throw re;
                
        
void portal.registration.dao.IdpDAOImpl.save (Idp transientInstance)
Implements portal.registration.dao.IdpDAO.
Definition at line 22 of file IdpDAOImpl.java.
References portal.registration.dao.IdpDAOImpl.log, and portal.registration.dao.IdpDAOImpl.sessionFactory.
                                                
                log.debug("persisting Idp instance");
                try
                        Session session = sessionFactory.getCurrentSession();
                        session.save(transientInstance);
                        log.debug("persist successful");
                 catch (RuntimeException re)
                        log.error("persist failed", re);
                        throw re;
                
        
Member Data Documentation
final Logger portal.registration.dao.IdpDAOImpl.log = Logger.getLogger(IdpDAOImpl.class) [static, private]
Definition at line 17 of file IdpDAOImpl.java.
Referenced by portal.registration.dao.IdpDAOImpl.delete(), portal.registration.dao.IdpDAOImpl.findById(), portal.registration.dao.IdpDAOImpl.getAllIdp(), and portal.registration.dao.IdpDAOImpl.save().
SessionFactory portal.registration.dao.IdpDAOImpl.sessionFactory [private]
Definition at line 20 of file IdpDAOImpl.java.
Referenced by portal.registration.dao.IdpDAOImpl.delete(), portal.registration.dao.IdpDAOImpl.findById(), portal.registration.dao.IdpDAOImpl.getAllIdp(), and portal.registration.dao.IdpDAOImpl.save().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/dao/IdpDAOImpl.java