org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator Class Reference
Public Member Functions
VOMSCompatibilityServiceLocator ()
VOMSCompatibilityServiceLocator (org.apache.axis.EngineConfiguration config)
VOMSCompatibilityServiceLocator (java.lang.String wsdlLoc, javax.xml.namespace.QName sName) throws javax.xml.rpc.ServiceException
java.lang.String getVOMSCompatibilityAddress ()
java.lang.String getVOMSCompatibilityWSDDServiceName ()
void setVOMSCompatibilityWSDDServiceName (java.lang.String name)
org.glite.security.voms.service.compatibility.VOMSCompatibility getVOMSCompatibility () throws javax.xml.rpc.ServiceException
org.glite.security.voms.service.compatibility.VOMSCompatibility getVOMSCompatibility (java.net.URL portAddress) throws javax.xml.rpc.ServiceException
void setVOMSCompatibilityEndpointAddress (java.lang.String address)
java.rmi.Remote getPort (Class serviceEndpointInterface) throws javax.xml.rpc.ServiceException
java.rmi.Remote getPort (javax.xml.namespace.QName portName, Class serviceEndpointInterface) throws javax.xml.rpc.ServiceException
namespace::QName getServiceName ()
java.util.Iterator getPorts ()
void setEndpointAddress (java.lang.String portName, java.lang.String address) throws javax.xml.rpc.ServiceException
void setEndpointAddress (javax.xml.namespace.QName portName, java.lang.String address) throws javax.xml.rpc.ServiceException
Private Attributes
java.lang.String VOMSCompatibility_address = `https://localhost:8443/glite-security-voms-admin-interface/VOMSCompatibility`
java.lang.String VOMSCompatibilityWSDDServiceName = `VOMSCompatibility`
java.util.HashSet ports = null
Detailed Description
Definition at line 10 of file VOMSCompatibilityServiceLocator.java.
Constructor & Destructor Documentation
org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.VOMSCompatibilityServiceLocator ()
Definition at line 12 of file VOMSCompatibilityServiceLocator.java.
                                             
    
org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.VOMSCompatibilityServiceLocator (org.apache.axis.EngineConfiguration config)
Definition at line 16 of file VOMSCompatibilityServiceLocator.java.
                                                                                 
            
        super(config);
    
org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.VOMSCompatibilityServiceLocator (java.lang.String wsdlLoc, javax.xml.namespace.QName sName) throws javax.xml.rpc.ServiceException
Definition at line 20 of file VOMSCompatibilityServiceLocator.java.
                                                                                 
                                                                 
        super(wsdlLoc, sName);
    
Member Function Documentation
java.rmi.Remote org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getPort (Class serviceEndpointInterface) throws javax.xml.rpc.ServiceException
For the given interface, get the stub implementation. If this service has no port for the given interface, then ServiceException is thrown.
Definition at line 73 of file VOMSCompatibilityServiceLocator.java.
References org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getVOMSCompatibilityWSDDServiceName(), and org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.VOMSCompatibility_address.
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getPort().
                                                                                 
                              
        try
            if (org.glite.security.voms.service.compatibility.VOMSCompatibility.c
      lass.isAssignableFrom(serviceEndpointInterface))
                org.glite.security.voms.service.compatibility.VOMSCompatibilitySo
      apBindingStub _stub = new org.glite.security.voms.service.compatibility.VOMSCompa
      tibilitySoapBindingStub(new java.net.URL(VOMSCompatibility_address), this);
                _stub.setPortName(getVOMSCompatibilityWSDDServiceName());
                return _stub;
            
        
        catch (java.lang.Throwable t)
            throw new javax.xml.rpc.ServiceException(t);
        
        throw new javax.xml.rpc.ServiceException("There is no stub implementation
       for the interface: " + (serviceEndpointInterface == null ? "null" : serviceEndp
      ointInterface.getName()));
    
java.rmi.Remote org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getPort (javax.xml.namespace.QName portName, Class serviceEndpointInterface) throws javax.xml.rpc.ServiceException
For the given interface, get the stub implementation. If this service has no port for the given interface, then ServiceException is thrown.
Definition at line 92 of file VOMSCompatibilityServiceLocator.java.
References org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getPort(), and org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getVOMSCompatibility().
                                                                                 
                                                                  
        if (portName == null)
            return getPort(serviceEndpointInterface);
        
        java.lang.String inputPortName = portName.getLocalPart();
        if ("VOMSCompatibility".equals(inputPortName))
            return getVOMSCompatibility();
        
        else
            java.rmi.Remote _stub = getPort(serviceEndpointInterface);
            ((org.apache.axis.client.Stub) _stub).setPortName(portName);
            return _stub;
        
    
java.util.Iterator org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getPorts ()
Definition at line 113 of file VOMSCompatibilityServiceLocator.java.
References org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.ports.
                                         
        if (ports == null)
            ports = new java.util.HashSet();
            ports.add(new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.compatibility", "VOMSCompatibility"));
        
        return ports.iterator();
    
namespace ::QName org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getServiceName ()
Definition at line 107 of file VOMSCompatibilityServiceLocator.java.
                                                      
        return new javax.xml.namespace.QName("http://glite.org/wsdl/services/org.
      glite.security.voms.service.compatibility", "VOMSCompatibilityService");
    
org.glite.security.voms.service.compatibility.VOMSCompatibility org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getVOMSCompatibility (java.net.URL portAddress) throws javax.xml.rpc.ServiceException
Implements org.glite.security.voms.service.compatibility.VOMSCompatibilityService.
Definition at line 53 of file VOMSCompatibilityServiceLocator.java.
References org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getVOMSCompatibilityWSDDServiceName().
                                                                                 
                                                                                     
        try
            org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBi
      ndingStub _stub = new org.glite.security.voms.service.compatibility.VOMSCompatibi
      litySoapBindingStub(portAddress, this);
            _stub.setPortName(getVOMSCompatibilityWSDDServiceName());
            return _stub;
        
        catch (org.apache.axis.AxisFault e)
            return null;
        
    
org.glite.security.voms.service.compatibility.VOMSCompatibility org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getVOMSCompatibility () throws javax.xml.rpc.ServiceException
Implements org.glite.security.voms.service.compatibility.VOMSCompatibilityService.
Definition at line 42 of file VOMSCompatibilityServiceLocator.java.
References org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.VOMSCompatibility_address.
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getPort().
                                                                                 
                                                             
       java.net.URL endpoint;
        try
            endpoint = new java.net.URL(VOMSCompatibility_address);
        
        catch (java.net.MalformedURLException e)
            throw new javax.xml.rpc.ServiceException(e);
        
        return getVOMSCompatibility(endpoint);
    
java.lang.String org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getVOMSCompatibilityAddress ()
Implements org.glite.security.voms.service.compatibility.VOMSCompatibilityService.
Definition at line 27 of file VOMSCompatibilityServiceLocator.java.
References org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.VOMSCompatibility_address.
                                                          
        return VOMSCompatibility_address;
    
java.lang.String org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getVOMSCompatibilityWSDDServiceName ()
Definition at line 34 of file VOMSCompatibilityServiceLocator.java.
References org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.VOMSCompatibilityWSDDServiceName.
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getPort(), and org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getVOMSCompatibility().
                                                                  
        return VOMSCompatibilityWSDDServiceName;
    
void org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.setEndpointAddress (java.lang.String portName, java.lang.String address) throws javax.xml.rpc.ServiceException
Set the endpoint address for the specified port name.
Definition at line 124 of file VOMSCompatibilityServiceLocator.java.
References org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.setVOMSCompatibilityEndpointAddress().
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.setEndpointAddress().
                                                                                 
                                                   
        
if ("VOMSCompatibility".equals(portName))
            setVOMSCompatibilityEndpointAddress(address);
        
        else
 // Unknown Port Name
            throw new javax.xml.rpc.ServiceException(" Cannot set Endpoint Addres
      s for Unknown Port" + portName);
        
    
void org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.setEndpointAddress (javax.xml.namespace.QName portName, java.lang.String address) throws javax.xml.rpc.ServiceException
Set the endpoint address for the specified port name.
Definition at line 138 of file VOMSCompatibilityServiceLocator.java.
References org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.setEndpointAddress().
                                                                                 
                                                            
        setEndpointAddress(portName.getLocalPart(), address);
    
void org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.setVOMSCompatibilityEndpointAddress (java.lang.String address)
Definition at line 64 of file VOMSCompatibilityServiceLocator.java.
References org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.VOMSCompatibility_address.
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.setEndpointAddress().
                                                                              
        VOMSCompatibility_address = address;
    
void org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.setVOMSCompatibilityWSDDServiceName (java.lang.String name)
Definition at line 38 of file VOMSCompatibilityServiceLocator.java.
References org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.VOMSCompatibilityWSDDServiceName.
                                                                           
        VOMSCompatibilityWSDDServiceName = name;
    
Member Data Documentation
java.util.HashSet org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.ports = null [private]
Definition at line 111 of file VOMSCompatibilityServiceLocator.java.
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getPorts().
java.lang.String org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.VOMSCompatibility_address = `https://localhost:8443/glite-security-voms-admin-interface/VOMSCompatibility` [private]
Definition at line 25 of file VOMSCompatibilityServiceLocator.java.
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getPort(), org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getVOMSCompatibility(), org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getVOMSCompatibilityAddress(), and org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.setVOMSCompatibilityEndpointAddress().
java.lang.String org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.VOMSCompatibilityWSDDServiceName = `VOMSCompatibility` [private]
Definition at line 32 of file VOMSCompatibilityServiceLocator.java.
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getVOMSCompatibilityWSDDServiceName(), and org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.setVOMSCompatibilityWSDDServiceName().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/compatibility/VOMSCompatibilityServiceLocator.java