portal.registration.domain.Certificate Class Reference
Public Member Functions
Certificate ()
Certificate (UserInfo userInfo, String subject, Date expirationDate, String caonline, String primaryCert, String issuer, String usernameCert)
int getIdCert ()
void setIdCert (int idCert)
UserInfo getUserInfo ()
void setUserInfo (UserInfo userInfo)
String getSubject ()
void setSubject (String subject)
Date getExpirationDate ()
void setExpirationDate (Date expirationDate)
String getCaonline ()
void setCaonline (String caonline)
String getPrimaryCert ()
void setPrimaryCert (String primaryCert)
String getIssuer ()
void setIssuer (String issuer)
String getUsernameCert ()
void setUsernameCert (String usernameCert)
boolean equals (Certificate cert)
Private Attributes
int idCert
UserInfo userInfo
String subject
Date expirationDate
String caonline
String primaryCert
String issuer
String usernameCert
Static Private Attributes
static final long serialVersionUID = -4219251531396625106L
Detailed Description
Certificate generated by hbm2java
Definition at line 23 of file Certificate.java.
Constructor & Destructor Documentation
portal.registration.domain.Certificate.Certificate ()
Definition at line 38 of file Certificate.java.
                             
        
portal.registration.domain.Certificate.Certificate (UserInfo userInfo, String subject, Date expirationDate, String caonline, String primaryCert, String issuer, String usernameCert)
Definition at line 41 of file Certificate.java.
                                             
                this.userInfo = userInfo;
                this.subject = subject;
                this.expirationDate = expirationDate;
                this.caonline = caonline;
                this.primaryCert = primaryCert;
                this.issuer = issuer;
                this.usernameCert = usernameCert;
        
Member Function Documentation
boolean portal.registration.domain.Certificate.equals (Certificate cert)
Definition at line 129 of file Certificate.java.
References portal.registration.domain.Certificate.issuer, and portal.registration.domain.Certificate.subject.
Referenced by portal.registration.controller.UploadCertController.uploadCert().
                                                
                if (this.subject.equals(cert.subject)
                                && this.issuer.equals(cert.issuer))
                        return true;
                return false;
        
String portal.registration.domain.Certificate.getCaonline ()
Definition at line 94 of file Certificate.java.
Referenced by portal.registration.dao.CertificateDAOImpl.edit().
                                    
                return this.caonline;
        
Date portal.registration.domain.Certificate.getExpirationDate ()
Definition at line 85 of file Certificate.java.
Referenced by portal.registration.dao.CertificateDAOImpl.edit().
                                        
                return this.expirationDate;
        
int portal.registration.domain.Certificate.getIdCert ()
Definition at line 56 of file Certificate.java.
Referenced by portal.registration.dao.CertificateDAOImpl.edit(), and portal.registration.services.CertificateServiceImpl.save().
                               
                return this.idCert;
        
String portal.registration.domain.Certificate.getIssuer ()
Definition at line 112 of file Certificate.java.
Referenced by portal.registration.dao.CertificateDAOImpl.edit().
                                  
                return this.issuer;
        
String portal.registration.domain.Certificate.getPrimaryCert ()
Definition at line 103 of file Certificate.java.
Referenced by portal.registration.dao.CertificateDAOImpl.edit(), portal.registration.services.CertificateServiceImpl.save(), and portal.registration.services.CertificateServiceImpl.setDefault().
                                       
                return this.primaryCert;
        
String portal.registration.domain.Certificate.getSubject ()
Definition at line 75 of file Certificate.java.
Referenced by portal.registration.dao.CertificateDAOImpl.edit().
                                   
                return this.subject;
        
UserInfo portal.registration.domain.Certificate.getUserInfo ()
Definition at line 66 of file Certificate.java.
Referenced by portal.registration.dao.CertificateDAOImpl.edit().
                                      
                return this.userInfo;
        
String portal.registration.domain.Certificate.getUsernameCert ()
Definition at line 121 of file Certificate.java.
Referenced by portal.registration.dao.CertificateDAOImpl.edit().
                                        
                return this.usernameCert;
        
void portal.registration.domain.Certificate.setCaonline (String caonline)
Definition at line 98 of file Certificate.java.
Referenced by portal.registration.dao.CertificateDAOImpl.edit(), and portal.registration.controller.UploadCertController.uploadCert().
                                                 
                this.caonline = caonline;
        
void portal.registration.domain.Certificate.setExpirationDate (Date expirationDate)
Definition at line 89 of file Certificate.java.
Referenced by portal.registration.dao.CertificateDAOImpl.edit(), and portal.registration.controller.UploadCertController.uploadCert().
                                                           
                this.expirationDate = expirationDate;
        
void portal.registration.domain.Certificate.setIdCert (int idCert)
Definition at line 60 of file Certificate.java.
Referenced by portal.registration.controller.UploadCertController.uploadCert().
                                          
                this.idCert = idCert;
        
void portal.registration.domain.Certificate.setIssuer (String issuer)
Definition at line 116 of file Certificate.java.
Referenced by portal.registration.dao.CertificateDAOImpl.edit(), and portal.registration.controller.UploadCertController.uploadCert().
                                             
                this.issuer = issuer;
        
void portal.registration.domain.Certificate.setPrimaryCert (String primaryCert)
Definition at line 107 of file Certificate.java.
Referenced by portal.registration.dao.CertificateDAOImpl.edit(), portal.registration.services.CertificateServiceImpl.save(), portal.registration.services.CertificateServiceImpl.setDefault(), and portal.registration.controller.UploadCertController.uploadCert().
                                                       
                this.primaryCert = primaryCert;
        
void portal.registration.domain.Certificate.setSubject (String subject)
Definition at line 79 of file Certificate.java.
Referenced by portal.registration.dao.CertificateDAOImpl.edit(), and portal.registration.controller.UploadCertController.uploadCert().
                                               
                this.subject = subject;
        
void portal.registration.domain.Certificate.setUserInfo (UserInfo userInfo)
Definition at line 70 of file Certificate.java.
Referenced by portal.registration.dao.CertificateDAOImpl.edit(), and portal.registration.services.CertificateServiceImpl.save().
                                                   
                this.userInfo = userInfo;
        
void portal.registration.domain.Certificate.setUsernameCert (String usernameCert)
Definition at line 125 of file Certificate.java.
Referenced by portal.registration.dao.CertificateDAOImpl.edit(), and portal.registration.services.CertificateServiceImpl.save().
                                                         
                this.usernameCert = usernameCert;
        
Member Data Documentation
String portal.registration.domain.Certificate.caonline [private]
Definition at line 33 of file Certificate.java.
Date portal.registration.domain.Certificate.expirationDate [private]
Definition at line 32 of file Certificate.java.
int portal.registration.domain.Certificate.idCert [private]
Definition at line 29 of file Certificate.java.
String portal.registration.domain.Certificate.issuer [private]
Definition at line 35 of file Certificate.java.
Referenced by portal.registration.domain.Certificate.equals().
String portal.registration.domain.Certificate.primaryCert [private]
Definition at line 34 of file Certificate.java.
final long portal.registration.domain.Certificate.serialVersionUID = -4219251531396625106L [static, private]
Definition at line 28 of file Certificate.java.
String portal.registration.domain.Certificate.subject [private]
Definition at line 31 of file Certificate.java.
Referenced by portal.registration.domain.Certificate.equals().
UserInfo portal.registration.domain.Certificate.userInfo [private]
Definition at line 30 of file Certificate.java.
String portal.registration.domain.Certificate.usernameCert [private]
Definition at line 36 of file Certificate.java.
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/domain/Certificate.java