org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub Class Reference
Public Member Functions
VOMSCompatibilitySoapBindingStub () throws org.apache.axis.AxisFault
VOMSCompatibilitySoapBindingStub (java.net.URL endpointURL, javax.xml.rpc.Service service) throws org.apache.axis.AxisFault
VOMSCompatibilitySoapBindingStub (javax.xml.rpc.Service service) throws org.apache.axis.AxisFault
int getMajorVersionNumber () throws java.rmi.RemoteException
int getMinorVersionNumber () throws java.rmi.RemoteException
int getPatchVersionNumber () throws java.rmi.RemoteException
java.lang.String[] getGridmapUsers () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
java.lang.String[] getGridmapUsers (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Protected Member Functions
org.apache.axis.client.Call createCall () throws java.rmi.RemoteException
Static Package Functions
[static initializer]
Static Package Attributes
static org.apache.axis.description.OperationDesc[] _operations
Static Private Member Functions
static void _initOperationDesc1 ()
Private Attributes
java.util.Vector cachedSerClasses = new java.util.Vector()
java.util.Vector cachedSerQNames = new java.util.Vector()
java.util.Vector cachedSerFactories = new java.util.Vector()
java.util.Vector cachedDeserFactories = new java.util.Vector()
Detailed Description
Definition at line 10 of file VOMSCompatibilitySoapBindingStub.java.
Constructor & Destructor Documentation
org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.VOMSCompatibilitySoapBindingStub () throws org.apache.axis.AxisFault
Definition at line 87 of file VOMSCompatibilitySoapBindingStub.java.
                                                                               
         this(null);
    
org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.VOMSCompatibilitySoapBindingStub (java.net.URL endpointURL, javax.xml.rpc.Service service) throws org.apache.axis.AxisFault
Definition at line 91 of file VOMSCompatibilitySoapBindingStub.java.
                                                                                 
                                                           
         this(service);
         super.cachedEndpoint = endpointURL;
    
org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.VOMSCompatibilitySoapBindingStub (javax.xml.rpc.Service service) throws org.apache.axis.AxisFault
Definition at line 96 of file VOMSCompatibilitySoapBindingStub.java.
References org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.cachedDeserFactories, org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.cachedSerClasses, org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.cachedSerFactories, and org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.cachedSerQNames.
                                                                                 
                                 
        if (service == null)
            super.service = new org.apache.axis.client.Service();
         else
            super.service = service;
        
        ((org.apache.axis.client.Service)super.service).setTypeMappingVersion("1.
      2");
            java.lang.Class cls;
            javax.xml.namespace.QName qName;
            javax.xml.namespace.QName qName2;
            java.lang.Class beansf = org.apache.axis.encoding.ser.BeanSerializerF
      actory.class;
            java.lang.Class beandf = org.apache.axis.encoding.ser.BeanDeserialize
      rFactory.class;
            java.lang.Class enumsf = org.apache.axis.encoding.ser.EnumSerializerF
      actory.class;
            java.lang.Class enumdf = org.apache.axis.encoding.ser.EnumDeserialize
      rFactory.class;
            java.lang.Class arraysf = org.apache.axis.encoding.ser.ArraySerialize
      rFactory.class;
            java.lang.Class arraydf = org.apache.axis.encoding.ser.ArrayDeseriali
      zerFactory.class;
            java.lang.Class simplesf = org.apache.axis.encoding.ser.SimpleSeriali
      zerFactory.class;
            java.lang.Class simpledf = org.apache.axis.encoding.ser.SimpleDeseria
      lizerFactory.class;
            java.lang.Class simplelistsf = org.apache.axis.encoding.ser.SimpleLis
      tSerializerFactory.class;
            java.lang.Class simplelistdf = org.apache.axis.encoding.ser.SimpleLis
      tDeserializerFactory.class;
            qName = new javax.xml.namespace.QName("http://glite.org/wsdl/services
      /org.glite.security.voms.service.compatibility", "ArrayOf_soapenc_string");
            cachedSerQNames.add(qName);
            cls = java.lang.String[].class;
            cachedSerClasses.add(cls);
            qName = new javax.xml.namespace.QName("http://schemas.xmlsoap.org/soa
      p/encoding/", "string");
            qName2 = null;
            cachedSerFactories.add(new org.apache.axis.encoding.ser.ArraySerializ
      erFactory(qName, qName2));
            cachedDeserFactories.add(new org.apache.axis.encoding.ser.ArrayDeseri
      alizerFactory());
            qName = new javax.xml.namespace.QName("http://glite.org/wsdl/services
      /org.glite.security.voms", "VOMSException");
            cachedSerQNames.add(qName);
            cls = org.glite.security.voms.VOMSException.class;
            cachedSerClasses.add(cls);
            cachedSerFactories.add(beansf);
            cachedDeserFactories.add(beandf);
    
Member Function Documentation
org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.[static initializer] () [static, package]
static void org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub._initOperationDesc1 () [static, private]
Definition at line 23 of file VOMSCompatibilitySoapBindingStub.java.
References org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub._operations.
                                             
        org.apache.axis.description.OperationDesc oper;
        org.apache.axis.description.ParameterDesc param;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("getMajorVersionNumber");
        oper.setReturnType(new javax.xml.namespace.QName("http://www.w3.org/2001/
      XMLSchema", "int"));
        oper.setReturnClass(int.class);
        oper.setReturnQName(new javax.xml.namespace.QName("", "getMajorVersionNum
      berReturn"));
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        _operations[0] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("getMinorVersionNumber");
        oper.setReturnType(new javax.xml.namespace.QName("http://www.w3.org/2001/
      XMLSchema", "int"));
        oper.setReturnClass(int.class);
        oper.setReturnQName(new javax.xml.namespace.QName("", "getMinorVersionNum
      berReturn"));
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        _operations[1] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("getPatchVersionNumber");
        oper.setReturnType(new javax.xml.namespace.QName("http://www.w3.org/2001/
      XMLSchema", "int"));
        oper.setReturnClass(int.class);
        oper.setReturnQName(new javax.xml.namespace.QName("", "getPatchVersionNum
      berReturn"));
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        _operations[2] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("getGridmapUsers");
        oper.setReturnType(new javax.xml.namespace.QName("http://glite.org/wsdl/s
      ervices/org.glite.security.voms.service.compatibility", "ArrayOf_soapenc_string")
      );
        oper.setReturnClass(java.lang.String[].class);
        oper.setReturnQName(new javax.xml.namespace.QName("", "getGridmapUsersRet
      urn"));
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.compatibility", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[3] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("getGridmapUsers");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(new javax.xml.namespace.QName("http://glite.org/wsdl/s
      ervices/org.glite.security.voms.service.compatibility", "ArrayOf_soapenc_string")
      );
        oper.setReturnClass(java.lang.String[].class);
        oper.setReturnQName(new javax.xml.namespace.QName("", "getGridmapUsersRet
      urn"));
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.compatibility", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[4] = oper;
    
org.apache.axis.client.Call org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.createCall () throws java.rmi.RemoteException [protected]
Definition at line 134 of file VOMSCompatibilitySoapBindingStub.java.
References org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.cachedDeserFactories, org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.cachedSerClasses, org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.cachedSerFactories, and org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.cachedSerQNames.
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.getMajorVersionNumber().
                                                                                 
            
        try
            org.apache.axis.client.Call _call = super._createCall();
            if (super.maintainSessionSet)
                _call.setMaintainSession(super.maintainSession);
            
            if (super.cachedUsername != null)
                _call.setUsername(super.cachedUsername);
            
            if (super.cachedPassword != null)
                _call.setPassword(super.cachedPassword);
            
            if (super.cachedEndpoint != null)
                _call.setTargetEndpointAddress(super.cachedEndpoint);
            
            if (super.cachedTimeout != null)
                _call.setTimeout(super.cachedTimeout);
            
            if (super.cachedPortName != null)
                _call.setPortName(super.cachedPortName);
            
            java.util.Enumeration keys = super.cachedProperties.keys();
            while (keys.hasMoreElements())
                java.lang.String key = (java.lang.String) keys.nextElement();
                _call.setProperty(key, super.cachedProperties.get(key));
            
            // All the type mapping information is registered
            // when the first call is made.
            // The type mapping information is actually registered in
            // the TypeMappingRegistry of the service, which
            // is the reason why registration is only needed for the first call.
            synchronized (this)
                if (firstCall())
                    // must set encoding style before registering serializers
                    _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP1
      1_CONSTANTS);
                    _call.setEncodingStyle(org.apache.axis.Constants.URI_SOAP11_E
      NC);
                    for (int i = 0; i < cachedSerFactories.size(); ++i)
                        java.lang.Class cls = (java.lang.Class) cachedSerClasses.
      get(i);
                        javax.xml.namespace.QName qName =
                                (javax.xml.namespace.QName) cachedSerQNames.get(i
      );
                        java.lang.Object x = cachedSerFactories.get(i);
                        if (x instanceof Class)
                            java.lang.Class sf = (java.lang.Class)
                                 cachedSerFactories.get(i);
                            java.lang.Class df = (java.lang.Class)
                                 cachedDeserFactories.get(i);
                            _call.registerTypeMapping(cls, qName, sf, df, false);
      
                        
                        else if (x instanceof javax.xml.rpc.encoding.SerializerFa
      ctory)
                            org.apache.axis.encoding.SerializerFactory sf = (org.
      apache.axis.encoding.SerializerFactory)
                                 cachedSerFactories.get(i);
                            org.apache.axis.encoding.DeserializerFactory df = (or
      g.apache.axis.encoding.DeserializerFactory)
                                 cachedDeserFactories.get(i);
                            _call.registerTypeMapping(cls, qName, sf, df, false);
      
                        
                    
                
            
            return _call;
        
        catch (java.lang.Throwable _t)
            throw new org.apache.axis.AxisFault("Failure trying to get the Call o
      bject", _t);
        
    
java.lang.String [] org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.getGridmapUsers (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.compatibility.VOMSCompatibility.
Definition at line 331 of file VOMSCompatibilitySoapBindingStub.java.
                                                                                 
                                                                
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[4]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.compatibility", "getGridmapUsers"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0)
      ;
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        else
            extractAttachments(_call);
            try
                return (java.lang.String[]) _resp;
             catch (java.lang.Exception _exception)
                return (java.lang.String[]) org.apache.axis.utils.JavaUtils.conve
      rt(_resp, java.lang.String[].class);
            
        
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
java.lang.String [] org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.getGridmapUsers () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.compatibility.VOMSCompatibility.
Definition at line 292 of file VOMSCompatibilitySoapBindingStub.java.
                                                                                 
                                            
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[3]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.compatibility", "getGridmapUsers"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[]);
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        else
            extractAttachments(_call);
            try
                return (java.lang.String[]) _resp;
             catch (java.lang.Exception _exception)
                return (java.lang.String[]) org.apache.axis.utils.JavaUtils.conve
      rt(_resp, java.lang.String[].class);
            
        
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
int org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.getMajorVersionNumber () throws java.rmi.RemoteException
Implements org.glite.security.voms.service.compatibility.VOMSCompatibility.
Definition at line 199 of file VOMSCompatibilitySoapBindingStub.java.
References org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub._operations, and org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.createCall().
                                                                       
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[0]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.compatibility", "getMajorVersionNumbe
      r"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[]);
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        else
            extractAttachments(_call);
            try
                return ((java.lang.Integer) _resp).intValue();
             catch (java.lang.Exception _exception)
                return ((java.lang.Integer) org.apache.axis.utils.JavaUtils.conve
      rt(_resp, int.class)).intValue();
            
        
   catch (org.apache.axis.AxisFault axisFaultException)
  throw axisFaultException;
    
int org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.getMinorVersionNumber () throws java.rmi.RemoteException
Implements org.glite.security.voms.service.compatibility.VOMSCompatibility.
Definition at line 230 of file VOMSCompatibilitySoapBindingStub.java.
                                                                       
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[1]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.compatibility", "getMinorVersionNumbe
      r"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[]);
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        else
            extractAttachments(_call);
            try
                return ((java.lang.Integer) _resp).intValue();
             catch (java.lang.Exception _exception)
                return ((java.lang.Integer) org.apache.axis.utils.JavaUtils.conve
      rt(_resp, int.class)).intValue();
            
        
   catch (org.apache.axis.AxisFault axisFaultException)
  throw axisFaultException;
    
int org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.getPatchVersionNumber () throws java.rmi.RemoteException
Implements org.glite.security.voms.service.compatibility.VOMSCompatibility.
Definition at line 261 of file VOMSCompatibilitySoapBindingStub.java.
                                                                       
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[2]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.compatibility", "getPatchVersionNumbe
      r"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[]);
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        else
            extractAttachments(_call);
            try
                return ((java.lang.Integer) _resp).intValue();
             catch (java.lang.Exception _exception)
                return ((java.lang.Integer) org.apache.axis.utils.JavaUtils.conve
      rt(_resp, int.class)).intValue();
            
        
   catch (org.apache.axis.AxisFault axisFaultException)
  throw axisFaultException;
    
Member Data Documentation
org.apache.axis.description.OperationDesc [] org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub._operations [static, package]
Definition at line 16 of file VOMSCompatibilitySoapBindingStub.java.
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub._initOperationDesc1(), and org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.getMajorVersionNumber().
java.util.Vector org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.cachedDeserFactories = new java.util.Vector() [private]
Definition at line 14 of file VOMSCompatibilitySoapBindingStub.java.
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.createCall(), and org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.VOMSCompatibilitySoapBindingStub().
java.util.Vector org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.cachedSerClasses = new java.util.Vector() [private]
Definition at line 11 of file VOMSCompatibilitySoapBindingStub.java.
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.createCall(), and org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.VOMSCompatibilitySoapBindingStub().
java.util.Vector org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.cachedSerFactories = new java.util.Vector() [private]
Definition at line 13 of file VOMSCompatibilitySoapBindingStub.java.
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.createCall(), and org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.VOMSCompatibilitySoapBindingStub().
java.util.Vector org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.cachedSerQNames = new java.util.Vector() [private]
Definition at line 12 of file VOMSCompatibilitySoapBindingStub.java.
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.createCall(), and org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.VOMSCompatibilitySoapBindingStub().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/compatibility/VOMSCompatibilitySoapBindingStub.java