portal.registration.domain.UserInfo Class Reference
Public Member Functions
UserInfo ()
UserInfo (Idp idp, String firstName, String lastName, String institute, String mail, String username)
UserInfo (Idp idp, String firstName, String lastName, String institute, String phone, String mail, String username, Set< Certificate > certificates, Set< UserToVo > userToVos)
int getUserId ()
void setUserId (int userId)
Idp getIdp ()
void setIdp (Idp idp)
String getFirstName ()
void setFirstName (String firstName)
String getLastName ()
void setLastName (String lastName)
String getInstitute ()
void setInstitute (String institute)
String getPhone ()
void setPhone (String phone)
String getMail ()
void setMail (String mail)
String getUsername ()
void setUsername (String username)
String getRegistrationComplete ()
void setRegistrationComplete (String registrationComplete)
Set< Certificate > getCertificates ()
void setCertificates (Set< Certificate > certificates)
Set< UserToVo > getUserToVos ()
void setUserToVos (Set< UserToVo > userToVos)
Private Attributes
int userId
Idp idp
String firstName
String lastName
String institute
String phone
String mail
String username
String registrationComplete
Set< Certificate > certificates = new HashSet<Certificate>(0)
Set< UserToVo > userToVos = new HashSet<UserToVo>(0)
Static Private Attributes
static final long serialVersionUID = -8793989934172666454L
Detailed Description
UserInfo generated by hbm2java
Definition at line 23 of file UserInfo.java.
Constructor & Destructor Documentation
portal.registration.domain.UserInfo.UserInfo ()
Definition at line 41 of file UserInfo.java.
                          
        
portal.registration.domain.UserInfo.UserInfo (Idp idp, String firstName, String lastName, String institute, String mail, String username)
Definition at line 44 of file UserInfo.java.
                                                                        
                this.idp = idp;
                this.firstName = firstName;
                this.lastName = lastName;
                this.institute = institute;
                this.mail = mail;
                this.username = username;
        
portal.registration.domain.UserInfo.UserInfo (Idp idp, String firstName, String lastName, String institute, String phone, String mail, String username, Set< Certificate > certificates, Set< UserToVo > userToVos)
Definition at line 54 of file UserInfo.java.
                                                                                
      
                this.idp = idp;
                this.firstName = firstName;
                this.lastName = lastName;
                this.institute = institute;
                this.phone = phone;
                this.mail = mail;
                this.username = username;
                this.certificates = certificates;
                this.userToVos = userToVos;
        
Member Function Documentation
Set<Certificate> portal.registration.domain.UserInfo.getCertificates ()
Definition at line 153 of file UserInfo.java.
                                                  
                return this.certificates;
        
String portal.registration.domain.UserInfo.getFirstName ()
Definition at line 90 of file UserInfo.java.
Referenced by portal.registration.dao.UserInfoDAOImpl.edit().
                                     
                return this.firstName;
        
Idp portal.registration.domain.UserInfo.getIdp ()
Definition at line 81 of file UserInfo.java.
                            
                return this.idp;
        
String portal.registration.domain.UserInfo.getInstitute ()
Definition at line 108 of file UserInfo.java.
Referenced by portal.registration.dao.UserInfoDAOImpl.edit().
                                     
                return this.institute;
        
String portal.registration.domain.UserInfo.getLastName ()
Definition at line 99 of file UserInfo.java.
Referenced by portal.registration.dao.UserInfoDAOImpl.edit().
                                    
                return this.lastName;
        
String portal.registration.domain.UserInfo.getMail ()
Definition at line 126 of file UserInfo.java.
Referenced by portal.registration.dao.UserInfoDAOImpl.edit().
                                
                return this.mail;
        
String portal.registration.domain.UserInfo.getPhone ()
Definition at line 117 of file UserInfo.java.
Referenced by portal.registration.dao.UserInfoDAOImpl.edit().
                                 
                return this.phone;
        
String portal.registration.domain.UserInfo.getRegistrationComplete ()
Definition at line 144 of file UserInfo.java.
Referenced by portal.registration.controller.AddUserToVOController.addUserToVo(), portal.registration.controller.EditUserInfoController.deactivateUser(), and portal.registration.controller.AddUserToVoPresentsController.deactivateUser().
                                                
                return this.registrationComplete;
        
int portal.registration.domain.UserInfo.getUserId ()
Definition at line 71 of file UserInfo.java.
Referenced by portal.registration.dao.UserInfoDAOImpl.edit().
                               
                return this.userId;
        
String portal.registration.domain.UserInfo.getUsername ()
Definition at line 135 of file UserInfo.java.
Referenced by portal.registration.controller.AddUserToVOController.activateUser(), portal.registration.controller.EditUserInfoController.deactivateUser(), portal.registration.controller.AddUserToVoPresentsController.deactivateUser(), portal.registration.dao.UserInfoDAOImpl.edit(), portal.registration.controller.RemoveUserInfoController.removeUserInfo(), and portal.registration.services.CertificateServiceImpl.save().
                                    
                return this.username;
        
Set<UserToVo> portal.registration.domain.UserInfo.getUserToVos ()
Definition at line 162 of file UserInfo.java.
                                            
                return this.userToVos;
        
void portal.registration.domain.UserInfo.setCertificates (Set< Certificate > certificates)
Definition at line 157 of file UserInfo.java.
                                                                   
                this.certificates = certificates;
        
void portal.registration.domain.UserInfo.setFirstName (String firstName)
Definition at line 94 of file UserInfo.java.
Referenced by portal.registration.dao.UserInfoDAOImpl.edit(), and portal.registration.controller.EditUserInfoController.editUserInfo().
                                                   
                this.firstName = firstName;
        
void portal.registration.domain.UserInfo.setIdp (Idp idp)
Definition at line 85 of file UserInfo.java.
Referenced by portal.registration.services.UserInfoServiceImpl.save().
                                    
                this.idp = idp;
        
void portal.registration.domain.UserInfo.setInstitute (String institute)
Definition at line 112 of file UserInfo.java.
Referenced by portal.registration.dao.UserInfoDAOImpl.edit().
                                                   
                this.institute = institute;
        
void portal.registration.domain.UserInfo.setLastName (String lastName)
Definition at line 103 of file UserInfo.java.
Referenced by portal.registration.dao.UserInfoDAOImpl.edit().
                                                 
                this.lastName = lastName;
        
void portal.registration.domain.UserInfo.setMail (String mail)
Definition at line 130 of file UserInfo.java.
Referenced by portal.registration.dao.UserInfoDAOImpl.edit().
                                         
                this.mail = mail;
        
void portal.registration.domain.UserInfo.setPhone (String phone)
Definition at line 121 of file UserInfo.java.
Referenced by portal.registration.dao.UserInfoDAOImpl.edit().
                                           
                this.phone = phone;
        
void portal.registration.domain.UserInfo.setRegistrationComplete (String registrationComplete)
Definition at line 148 of file UserInfo.java.
Referenced by portal.registration.controller.AddUserToVOController.activateUser(), portal.registration.controller.EditUserInfoController.deactivateUser(), portal.registration.controller.AddUserToVoPresentsController.deactivateUser(), and portal.registration.dao.UserInfoDAOImpl.edit().
                                                                         
                this.registrationComplete = registrationComplete;
        
void portal.registration.domain.UserInfo.setUserId (int userId)
Definition at line 75 of file UserInfo.java.
                                          
                this.userId = userId;
        
void portal.registration.domain.UserInfo.setUsername (String username)
Definition at line 139 of file UserInfo.java.
Referenced by portal.registration.dao.UserInfoDAOImpl.edit().
                                                 
                this.username = username;
        
void portal.registration.domain.UserInfo.setUserToVos (Set< UserToVo > userToVos)
Definition at line 166 of file UserInfo.java.
                                                          
                this.userToVos = userToVos;
        
Member Data Documentation
Set<Certificate> portal.registration.domain.UserInfo.certificates = new HashSet<Certificate>(0) [private]
Definition at line 38 of file UserInfo.java.
String portal.registration.domain.UserInfo.firstName [private]
Definition at line 31 of file UserInfo.java.
Idp portal.registration.domain.UserInfo.idp [private]
Definition at line 30 of file UserInfo.java.
String portal.registration.domain.UserInfo.institute [private]
Definition at line 33 of file UserInfo.java.
String portal.registration.domain.UserInfo.lastName [private]
Definition at line 32 of file UserInfo.java.
String portal.registration.domain.UserInfo.mail [private]
Definition at line 35 of file UserInfo.java.
String portal.registration.domain.UserInfo.phone [private]
Definition at line 34 of file UserInfo.java.
String portal.registration.domain.UserInfo.registrationComplete [private]
Definition at line 37 of file UserInfo.java.
final long portal.registration.domain.UserInfo.serialVersionUID = -8793989934172666454L [static, private]
Definition at line 28 of file UserInfo.java.
int portal.registration.domain.UserInfo.userId [private]
Definition at line 29 of file UserInfo.java.
String portal.registration.domain.UserInfo.username [private]
Definition at line 36 of file UserInfo.java.
Set<UserToVo> portal.registration.domain.UserInfo.userToVos = new HashSet<UserToVo>(0) [private]
Definition at line 39 of file UserInfo.java.
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/domain/UserInfo.java