org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator Class Reference
Public Member Functions
VOMSRegistrationServiceLocator ()
VOMSRegistrationServiceLocator (org.apache.axis.EngineConfiguration config)
VOMSRegistrationServiceLocator (java.lang.String wsdlLoc, javax.xml.namespace.QName sName) throws javax.xml.rpc.ServiceException
java.lang.String getVOMSRegistrationAddress ()
java.lang.String getVOMSRegistrationWSDDServiceName ()
void setVOMSRegistrationWSDDServiceName (java.lang.String name)
org.glite.security.voms.service.registration.VOMSRegistration getVOMSRegistration () throws javax.xml.rpc.ServiceException
org.glite.security.voms.service.registration.VOMSRegistration getVOMSRegistration (java.net.URL portAddress) throws javax.xml.rpc.ServiceException
void setVOMSRegistrationEndpointAddress (java.lang.String address)
java.rmi.Remote getPort (Class serviceEndpointInterface) throws javax.xml.rpc.ServiceException
java.rmi.Remote getPort (javax.xml.namespace.QName portName, Class serviceEndpointInterface) throws javax.xml.rpc.ServiceException
namespace::QName getServiceName ()
java.util.Iterator getPorts ()
void setEndpointAddress (java.lang.String portName, java.lang.String address) throws javax.xml.rpc.ServiceException
void setEndpointAddress (javax.xml.namespace.QName portName, java.lang.String address) throws javax.xml.rpc.ServiceException
Private Attributes
java.lang.String VOMSRegistration_address = `https://localhost:8443/glite-security-voms-admin-interface/VOMSRegistration`
java.lang.String VOMSRegistrationWSDDServiceName = `VOMSRegistration`
java.util.HashSet ports = null
Detailed Description
Definition at line 10 of file VOMSRegistrationServiceLocator.java.
Constructor & Destructor Documentation
org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.VOMSRegistrationServiceLocator ()
Definition at line 12 of file VOMSRegistrationServiceLocator.java.
                                            
    
org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.VOMSRegistrationServiceLocator (org.apache.axis.EngineConfiguration config)
Definition at line 16 of file VOMSRegistrationServiceLocator.java.
                                                                                 
           
        super(config);
    
org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.VOMSRegistrationServiceLocator (java.lang.String wsdlLoc, javax.xml.namespace.QName sName) throws javax.xml.rpc.ServiceException
Definition at line 20 of file VOMSRegistrationServiceLocator.java.
                                                                                 
                                                                
        super(wsdlLoc, sName);
    
Member Function Documentation
java.rmi.Remote org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.getPort (Class serviceEndpointInterface) throws javax.xml.rpc.ServiceException
For the given interface, get the stub implementation. If this service has no port for the given interface, then ServiceException is thrown.
Definition at line 73 of file VOMSRegistrationServiceLocator.java.
References org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.getVOMSRegistrationWSDDServiceName(), and org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.VOMSRegistration_address.
Referenced by org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.getPort().
                                                                                 
                              
        try
            if (org.glite.security.voms.service.registration.VOMSRegistration.cla
      ss.isAssignableFrom(serviceEndpointInterface))
                org.glite.security.voms.service.registration.VOMSRegistrationSoap
      BindingStub _stub = new org.glite.security.voms.service.registration.VOMSRegistra
      tionSoapBindingStub(new java.net.URL(VOMSRegistration_address), this);
                _stub.setPortName(getVOMSRegistrationWSDDServiceName());
                return _stub;
            
        
        catch (java.lang.Throwable t)
            throw new javax.xml.rpc.ServiceException(t);
        
        throw new javax.xml.rpc.ServiceException("There is no stub implementation
       for the interface: " + (serviceEndpointInterface == null ? "null" : serviceEndp
      ointInterface.getName()));
    
java.rmi.Remote org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.getPort (javax.xml.namespace.QName portName, Class serviceEndpointInterface) throws javax.xml.rpc.ServiceException
For the given interface, get the stub implementation. If this service has no port for the given interface, then ServiceException is thrown.
Definition at line 92 of file VOMSRegistrationServiceLocator.java.
References org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.getPort(), and org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.getVOMSRegistration().
                                                                                 
                                                                  
        if (portName == null)
            return getPort(serviceEndpointInterface);
        
        java.lang.String inputPortName = portName.getLocalPart();
        if ("VOMSRegistration".equals(inputPortName))
            return getVOMSRegistration();
        
        else
            java.rmi.Remote _stub = getPort(serviceEndpointInterface);
            ((org.apache.axis.client.Stub) _stub).setPortName(portName);
            return _stub;
        
    
java.util.Iterator org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.getPorts ()
Definition at line 113 of file VOMSRegistrationServiceLocator.java.
References org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.ports.
                                         
        if (ports == null)
            ports = new java.util.HashSet();
            ports.add(new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.registration", "VOMSRegistration"));
        
        return ports.iterator();
    
namespace ::QName org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.getServiceName ()
Definition at line 107 of file VOMSRegistrationServiceLocator.java.
                                                      
        return new javax.xml.namespace.QName("http://glite.org/wsdl/services/org.
      glite.security.voms.service.registration", "VOMSRegistrationService");
    
org.glite.security.voms.service.registration.VOMSRegistration org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.getVOMSRegistration (java.net.URL portAddress) throws javax.xml.rpc.ServiceException
Implements org.glite.security.voms.service.registration.VOMSRegistrationService.
Definition at line 53 of file VOMSRegistrationServiceLocator.java.
References org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.getVOMSRegistrationWSDDServiceName().
                                                                                 
                                                                                  
        try
            org.glite.security.voms.service.registration.VOMSRegistrationSoapBind
      ingStub _stub = new org.glite.security.voms.service.registration.VOMSRegistration
      SoapBindingStub(portAddress, this);
            _stub.setPortName(getVOMSRegistrationWSDDServiceName());
            return _stub;
        
        catch (org.apache.axis.AxisFault e)
            return null;
        
    
org.glite.security.voms.service.registration.VOMSRegistration org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.getVOMSRegistration () throws javax.xml.rpc.ServiceException
Implements org.glite.security.voms.service.registration.VOMSRegistrationService.
Definition at line 42 of file VOMSRegistrationServiceLocator.java.
References org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.VOMSRegistration_address.
Referenced by org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.getPort().
                                                                                 
                                                          
       java.net.URL endpoint;
        try
            endpoint = new java.net.URL(VOMSRegistration_address);
        
        catch (java.net.MalformedURLException e)
            throw new javax.xml.rpc.ServiceException(e);
        
        return getVOMSRegistration(endpoint);
    
java.lang.String org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.getVOMSRegistrationAddress ()
Implements org.glite.security.voms.service.registration.VOMSRegistrationService.
Definition at line 27 of file VOMSRegistrationServiceLocator.java.
References org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.VOMSRegistration_address.
                                                         
        return VOMSRegistration_address;
    
java.lang.String org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.getVOMSRegistrationWSDDServiceName ()
Definition at line 34 of file VOMSRegistrationServiceLocator.java.
References org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.VOMSRegistrationWSDDServiceName.
Referenced by org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.getPort(), and org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.getVOMSRegistration().
                                                                 
        return VOMSRegistrationWSDDServiceName;
    
void org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.setEndpointAddress (java.lang.String portName, java.lang.String address) throws javax.xml.rpc.ServiceException
Set the endpoint address for the specified port name.
Definition at line 124 of file VOMSRegistrationServiceLocator.java.
References org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.setVOMSRegistrationEndpointAddress().
Referenced by org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.setEndpointAddress().
                                                                                 
                                                   
        
if ("VOMSRegistration".equals(portName))
            setVOMSRegistrationEndpointAddress(address);
        
        else
 // Unknown Port Name
            throw new javax.xml.rpc.ServiceException(" Cannot set Endpoint Addres
      s for Unknown Port" + portName);
        
    
void org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.setEndpointAddress (javax.xml.namespace.QName portName, java.lang.String address) throws javax.xml.rpc.ServiceException
Set the endpoint address for the specified port name.
Definition at line 138 of file VOMSRegistrationServiceLocator.java.
References org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.setEndpointAddress().
                                                                                 
                                                            
        setEndpointAddress(portName.getLocalPart(), address);
    
void org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.setVOMSRegistrationEndpointAddress (java.lang.String address)
Definition at line 64 of file VOMSRegistrationServiceLocator.java.
References org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.VOMSRegistration_address.
Referenced by org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.setEndpointAddress().
                                                                             
        VOMSRegistration_address = address;
    
void org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.setVOMSRegistrationWSDDServiceName (java.lang.String name)
Definition at line 38 of file VOMSRegistrationServiceLocator.java.
References org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.VOMSRegistrationWSDDServiceName.
                                                                          
        VOMSRegistrationWSDDServiceName = name;
    
Member Data Documentation
java.util.HashSet org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.ports = null [private]
Definition at line 111 of file VOMSRegistrationServiceLocator.java.
Referenced by org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.getPorts().
java.lang.String org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.VOMSRegistration_address = `https://localhost:8443/glite-security-voms-admin-interface/VOMSRegistration` [private]
Definition at line 25 of file VOMSRegistrationServiceLocator.java.
Referenced by org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.getPort(), org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.getVOMSRegistration(), org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.getVOMSRegistrationAddress(), and org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.setVOMSRegistrationEndpointAddress().
java.lang.String org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.VOMSRegistrationWSDDServiceName = `VOMSRegistration` [private]
Definition at line 32 of file VOMSRegistrationServiceLocator.java.
Referenced by org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.getVOMSRegistrationWSDDServiceName(), and org.glite.security.voms.service.registration.VOMSRegistrationServiceLocator.setVOMSRegistrationWSDDServiceName().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/registration/VOMSRegistrationServiceLocator.java