portal.registration.domain.UserToVoId Class Reference
Public Member Functions
UserToVoId ()
UserToVoId (int userId, int idVo)
int getUserId ()
void setUserId (int userId)
int getIdVo ()
void setIdVo (int idVo)
boolean equals (Object other)
int hashCode ()
Private Attributes
int userId
int idVo
Static Private Attributes
static final long serialVersionUID = 2017618900651289298L
Detailed Description
UserToVoId generated by hbm2java
Definition at line 12 of file UserToVoId.java.
Constructor & Destructor Documentation
portal.registration.domain.UserToVoId.UserToVoId ()
Definition at line 21 of file UserToVoId.java.
Referenced by portal.registration.domain.UserToVoId.equals().
                            
        
portal.registration.domain.UserToVoId.UserToVoId (int userId, int idVo)
Definition at line 24 of file UserToVoId.java.
References portal.registration.domain.UserToVoId.idVo, and portal.registration.domain.UserToVoId.userId.
                                                
                this.userId = userId;
                this.idVo = idVo;
        
Member Function Documentation
boolean portal.registration.domain.UserToVoId.equals (Object other)
Definition at line 47 of file UserToVoId.java.
References portal.registration.domain.UserToVoId.getIdVo(), portal.registration.domain.UserToVoId.getUserId(), and portal.registration.domain.UserToVoId.UserToVoId().
                                            
                if ((this == other))
                        return true;
                if ((other == null))
                        return false;
                if (!(other instanceof UserToVoId))
                        return false;
                UserToVoId castOther = (UserToVoId) other;
                return (this.getUserId() == castOther.getUserId())
                                && (this.getIdVo() == castOther.getIdVo());
        
int portal.registration.domain.UserToVoId.getIdVo ()
Definition at line 39 of file UserToVoId.java.
References portal.registration.domain.UserToVoId.idVo.
Referenced by portal.registration.domain.UserToVoId.equals(), portal.registration.services.UserToVoServiceImpl.findDefaultVo(), and portal.registration.domain.UserToVoId.hashCode().
                             
                return this.idVo;
        
int portal.registration.domain.UserToVoId.getUserId ()
Definition at line 30 of file UserToVoId.java.
References portal.registration.domain.UserToVoId.userId.
Referenced by portal.registration.domain.UserToVoId.equals(), and portal.registration.domain.UserToVoId.hashCode().
                               
                return this.userId;
        
int portal.registration.domain.UserToVoId.hashCode ()
Definition at line 60 of file UserToVoId.java.
References portal.registration.domain.UserToVoId.getIdVo(), and portal.registration.domain.UserToVoId.getUserId().
                              
                int result = 17;
                result = 37 * result + this.getUserId();
                result = 37 * result + this.getIdVo();
                return result;
        
void portal.registration.domain.UserToVoId.setIdVo (int idVo)
Definition at line 43 of file UserToVoId.java.
References portal.registration.domain.UserToVoId.idVo.
                                      
                this.idVo = idVo;
        
void portal.registration.domain.UserToVoId.setUserId (int userId)
Definition at line 34 of file UserToVoId.java.
References portal.registration.domain.UserToVoId.userId.
                                          
                this.userId = userId;
        
Member Data Documentation
int portal.registration.domain.UserToVoId.idVo [private]
Definition at line 19 of file UserToVoId.java.
Referenced by portal.registration.domain.UserToVoId.getIdVo(), portal.registration.domain.UserToVoId.setIdVo(), and portal.registration.domain.UserToVoId.UserToVoId().
final long portal.registration.domain.UserToVoId.serialVersionUID = 2017618900651289298L [static, private]
Definition at line 17 of file UserToVoId.java.
int portal.registration.domain.UserToVoId.userId [private]
Definition at line 18 of file UserToVoId.java.
Referenced by portal.registration.domain.UserToVoId.getUserId(), portal.registration.domain.UserToVoId.setUserId(), and portal.registration.domain.UserToVoId.UserToVoId().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/domain/UserToVoId.java