portal.registration.controller.RemoveUserInfoController Class Reference
Public Member Functions
void removeUserInfo (@RequestParam int userId, ActionRequest request) throws PortalException, SystemException
Private Attributes
UserInfoService userInfoService
Detailed Description
RemoveUserInfoController handles removal of UserInfo from the Catalog.
Author
asarin
Definition at line 29 of file RemoveUserInfoController.java.
Member Function Documentation
void portal.registration.controller.RemoveUserInfoController.removeUserInfo (@RequestParam int userId, ActionRequest request) throws PortalException, SystemException
Definition at line 35 of file RemoveUserInfoController.java.
References portal.registration.services.UserInfoService.delete(), portal.registration.services.UserInfoService.findById(), and portal.registration.domain.UserInfo.getUsername().
                                                                                 
                                                 
                
                UserInfo userInfo = userInfoService.findById(userId);
                String username = userInfo.getUsername();
                
                long companyId = PortalUtil.getCompanyId(request);
                
                User user = UserLocalServiceUtil.getUserByScreenName(companyId,
                                username);
                
                UserLocalServiceUtil.deleteUser(user);
        
                userInfoService.delete(userId);
                
                SessionMessages.add(request, "user-delated-successufully");
        
Member Data Documentation
UserInfoService portal.registration.controller.RemoveUserInfoController.userInfoService [private]
Definition at line 32 of file RemoveUserInfoController.java.
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/controller/RemoveUserInfoController.java