org.glite.security.voms.ACLEntry Class Reference
Public Member Functions
ACLEntry ()
ACLEntry (java.lang.String adminCA, java.lang.String adminDN, boolean allow, java.lang.String operationName)
java.lang.String getAdminCA ()
void setAdminCA (java.lang.String adminCA)
java.lang.String getAdminDN ()
void setAdminDN (java.lang.String adminDN)
boolean isAllow ()
void setAllow (boolean allow)
java.lang.String getOperationName ()
void setOperationName (java.lang.String operationName)
synchronized boolean equals (java.lang.Object obj)
synchronized int hashCode ()
Private Attributes
java.lang.String adminCA
java.lang.String adminDN
boolean allow
java.lang.String operationName
java.lang.Object __equalsCalc = null
boolean __hashCodeCalc = false
Detailed Description
Definition at line 10 of file ACLEntry.java.
Constructor & Destructor Documentation
org.glite.security.voms.ACLEntry.ACLEntry ()
Definition at line 19 of file ACLEntry.java.
Referenced by org.glite.security.voms.ACLEntry.equals().
                      
    
org.glite.security.voms.ACLEntry.ACLEntry (java.lang.String adminCA, java.lang.String adminDN, boolean allow, java.lang.String operationName)
Definition at line 22 of file ACLEntry.java.
References org.glite.security.voms.ACLEntry.adminCA, org.glite.security.voms.ACLEntry.adminDN, org.glite.security.voms.ACLEntry.allow, and org.glite.security.voms.ACLEntry.operationName.
                                           
           this.adminCA = adminCA;
           this.adminDN = adminDN;
           this.allow = allow;
           this.operationName = operationName;
    
Member Function Documentation
synchronized boolean org.glite.security.voms.ACLEntry.equals (java.lang.Object obj)
Definition at line 114 of file ACLEntry.java.
References org.glite.security.voms.ACLEntry.__equalsCalc, org.glite.security.voms.ACLEntry.ACLEntry(), org.glite.security.voms.ACLEntry.adminCA, org.glite.security.voms.ACLEntry.adminDN, org.glite.security.voms.ACLEntry.allow, org.glite.security.voms.ACLEntry.getAdminCA(), org.glite.security.voms.ACLEntry.getAdminDN(), org.glite.security.voms.ACLEntry.getOperationName(), org.glite.security.voms.ACLEntry.isAllow(), and org.glite.security.voms.ACLEntry.operationName.
                                                             
        if (!(obj instanceof ACLEntry)) return false;
        ACLEntry other = (ACLEntry) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null)
            return (__equalsCalc == obj);
        
        __equalsCalc = obj;
        boolean _equals;
        _equals = true &&
            ((this.adminCA==null && other.getAdminCA()==null) ||
             (this.adminCA!=null &&
              this.adminCA.equals(other.getAdminCA()))) &&
            ((this.adminDN==null && other.getAdminDN()==null) ||
             (this.adminDN!=null &&
              this.adminDN.equals(other.getAdminDN()))) &&
            this.allow == other.isAllow() &&
            ((this.operationName==null && other.getOperationName()==null) ||
             (this.operationName!=null &&
              this.operationName.equals(other.getOperationName())));
        __equalsCalc = null;
        return _equals;
    
java.lang.String org.glite.security.voms.ACLEntry.getAdminCA ()
Gets the adminCA value for this ACLEntry.
Returns
adminCA
Definition at line 39 of file ACLEntry.java.
References org.glite.security.voms.ACLEntry.adminCA.
Referenced by org.glite.security.voms.ACLEntry.equals(), and org.glite.security.voms.ACLEntry.hashCode().
                                         
        return adminCA;
    
java.lang.String org.glite.security.voms.ACLEntry.getAdminDN ()
Gets the adminDN value for this ACLEntry.
Returns
adminDN
Definition at line 59 of file ACLEntry.java.
References org.glite.security.voms.ACLEntry.adminDN.
Referenced by org.glite.security.voms.ACLEntry.equals(), and org.glite.security.voms.ACLEntry.hashCode().
                                         
        return adminDN;
    
java.lang.String org.glite.security.voms.ACLEntry.getOperationName ()
Gets the operationName value for this ACLEntry.
Returns
operationName
Definition at line 99 of file ACLEntry.java.
References org.glite.security.voms.ACLEntry.operationName.
Referenced by org.glite.security.voms.ACLEntry.equals(), and org.glite.security.voms.ACLEntry.hashCode().
                                               
        return operationName;
    
synchronized int org.glite.security.voms.ACLEntry.hashCode ()
Definition at line 140 of file ACLEntry.java.
References org.glite.security.voms.ACLEntry.__hashCodeCalc, org.glite.security.voms.ACLEntry.getAdminCA(), org.glite.security.voms.ACLEntry.getAdminDN(), org.glite.security.voms.ACLEntry.getOperationName(), and org.glite.security.voms.ACLEntry.isAllow().
                                       
        if (__hashCodeCalc)
            return 0;
        
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getAdminCA() != null)
            _hashCode += getAdminCA().hashCode();
        
        if (getAdminDN() != null)
            _hashCode += getAdminDN().hashCode();
        
        _hashCode += (isAllow() ? Boolean.TRUE : Boolean.FALSE).hashCode();
        if (getOperationName() != null)
            _hashCode += getOperationName().hashCode();
        
        __hashCodeCalc = false;
        return _hashCode;
    
boolean org.glite.security.voms.ACLEntry.isAllow ()
Gets the allow value for this ACLEntry.
Returns
allow
Definition at line 79 of file ACLEntry.java.
References org.glite.security.voms.ACLEntry.allow.
Referenced by org.glite.security.voms.ACLEntry.equals(), and org.glite.security.voms.ACLEntry.hashCode().
                             
        return allow;
    
void org.glite.security.voms.ACLEntry.setAdminCA (java.lang.String adminCA)
Sets the adminCA value for this ACLEntry.
Parameters
adminCA
Definition at line 49 of file ACLEntry.java.
References org.glite.security.voms.ACLEntry.adminCA.
                                                     
        this.adminCA = adminCA;
    
void org.glite.security.voms.ACLEntry.setAdminDN (java.lang.String adminDN)
Sets the adminDN value for this ACLEntry.
Parameters
adminDN
Definition at line 69 of file ACLEntry.java.
References org.glite.security.voms.ACLEntry.adminDN.
                                                     
        this.adminDN = adminDN;
    
void org.glite.security.voms.ACLEntry.setAllow (boolean allow)
Sets the allow value for this ACLEntry.
Parameters
allow
Definition at line 89 of file ACLEntry.java.
References org.glite.security.voms.ACLEntry.allow.
                                        
        this.allow = allow;
    
void org.glite.security.voms.ACLEntry.setOperationName (java.lang.String operationName)
Sets the operationName value for this ACLEntry.
Parameters
operationName
Definition at line 109 of file ACLEntry.java.
References org.glite.security.voms.ACLEntry.operationName.
                                                                 
        this.operationName = operationName;
    
Member Data Documentation
java.lang.Object org.glite.security.voms.ACLEntry.__equalsCalc = null [private]
Definition at line 113 of file ACLEntry.java.
Referenced by org.glite.security.voms.ACLEntry.equals().
boolean org.glite.security.voms.ACLEntry.__hashCodeCalc = false [private]
Definition at line 139 of file ACLEntry.java.
Referenced by org.glite.security.voms.ACLEntry.hashCode().
java.lang.String org.glite.security.voms.ACLEntry.adminCA [private]
Definition at line 11 of file ACLEntry.java.
Referenced by org.glite.security.voms.ACLEntry.ACLEntry(), org.glite.security.voms.ACLEntry.equals(), org.glite.security.voms.ACLEntry.getAdminCA(), and org.glite.security.voms.ACLEntry.setAdminCA().
java.lang.String org.glite.security.voms.ACLEntry.adminDN [private]
Definition at line 13 of file ACLEntry.java.
Referenced by org.glite.security.voms.ACLEntry.ACLEntry(), org.glite.security.voms.ACLEntry.equals(), org.glite.security.voms.ACLEntry.getAdminDN(), and org.glite.security.voms.ACLEntry.setAdminDN().
boolean org.glite.security.voms.ACLEntry.allow [private]
Definition at line 15 of file ACLEntry.java.
Referenced by org.glite.security.voms.ACLEntry.ACLEntry(), org.glite.security.voms.ACLEntry.equals(), org.glite.security.voms.ACLEntry.isAllow(), and org.glite.security.voms.ACLEntry.setAllow().
java.lang.String org.glite.security.voms.ACLEntry.operationName [private]
Definition at line 17 of file ACLEntry.java.
Referenced by org.glite.security.voms.ACLEntry.ACLEntry(), org.glite.security.voms.ACLEntry.equals(), org.glite.security.voms.ACLEntry.getOperationName(), and org.glite.security.voms.ACLEntry.setOperationName().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/ACLEntry.java