org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton Class Reference
Public Member Functions
VOMSCompatibilitySoapBindingSkeleton ()
VOMSCompatibilitySoapBindingSkeleton (org.glite.security.voms.service.compatibility.VOMSCompatibility impl)
int getMajorVersionNumber () throws java.rmi.RemoteException
int getMinorVersionNumber () throws java.rmi.RemoteException
int getPatchVersionNumber () throws java.rmi.RemoteException
java.lang.String[] getGridmapUsers () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
java.lang.String[] getGridmapUsers (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Static Public Member Functions
static java.util.List getOperationDescByName (java.lang.String methodName)
static java.util.Collection getOperationDescs ()
Static Package Functions
[static initializer]
Private Attributes
org.glite.security.voms.service.compatibility.VOMSCompatibility impl
Static Private Attributes
static java.util.Map _myOperations = new java.util.Hashtable()
static java.util.Collection _myOperationsList = new java.util.ArrayList()
Detailed Description
Definition at line 10 of file VOMSCompatibilitySoapBindingSkeleton.java.
Constructor & Destructor Documentation
org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.VOMSCompatibilitySoapBindingSkeleton ()
Definition at line 103 of file VOMSCompatibilitySoapBindingSkeleton.java.
References org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.impl.
                                                  
        this.impl = new org.glite.security.voms.service.compatibility.VOMSCompati
      bilitySoapBindingImpl();
    
org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.VOMSCompatibilitySoapBindingSkeleton (org.glite.security.voms.service.compatibility.VOMSCompatibility impl)
Definition at line 107 of file VOMSCompatibilitySoapBindingSkeleton.java.
References org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.impl.
                                                                                 
                                           
        this.impl = impl;
    
Member Function Documentation
org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.[static initializer] () [static, package]
java.lang.String [] org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.getGridmapUsers (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.compatibility.VOMSCompatibility.
Definition at line 134 of file VOMSCompatibilitySoapBindingSkeleton.java.
References org.glite.security.voms.service.compatibility.VOMSCompatibility.getGridmapUsers(), and org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.impl.
    
        java.lang.String[] ret = impl.getGridmapUsers(in0);
        return ret;
    
java.lang.String [] org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.getGridmapUsers () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.compatibility.VOMSCompatibility.
Definition at line 128 of file VOMSCompatibilitySoapBindingSkeleton.java.
References org.glite.security.voms.service.compatibility.VOMSCompatibility.getGridmapUsers(), and org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.impl.
    
        java.lang.String[] ret = impl.getGridmapUsers();
        return ret;
    
int org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.getMajorVersionNumber () throws java.rmi.RemoteException
Implements org.glite.security.voms.service.compatibility.VOMSCompatibility.
Definition at line 110 of file VOMSCompatibilitySoapBindingSkeleton.java.
References org.glite.security.voms.service.compatibility.VOMSCompatibility.getMajorVersionNumber(), and org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.impl.
    
        int ret = impl.getMajorVersionNumber();
        return ret;
    
int org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.getMinorVersionNumber () throws java.rmi.RemoteException
Implements org.glite.security.voms.service.compatibility.VOMSCompatibility.
Definition at line 116 of file VOMSCompatibilitySoapBindingSkeleton.java.
References org.glite.security.voms.service.compatibility.VOMSCompatibility.getMinorVersionNumber(), and org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.impl.
    
        int ret = impl.getMinorVersionNumber();
        return ret;
    
static java.util.List org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.getOperationDescByName (java.lang.String methodName) [static]
Returns List of OperationDesc objects with this name
Definition at line 18 of file VOMSCompatibilitySoapBindingSkeleton.java.
References org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton._myOperations.
                                                                                 
          
        return (java.util.List)_myOperations.get(methodName);
    
static java.util.Collection org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.getOperationDescs () [static]
Returns Collection of OperationDescs
Definition at line 25 of file VOMSCompatibilitySoapBindingSkeleton.java.
References org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton._myOperationsList.
                                                           
        return _myOperationsList;
    
int org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.getPatchVersionNumber () throws java.rmi.RemoteException
Implements org.glite.security.voms.service.compatibility.VOMSCompatibility.
Definition at line 122 of file VOMSCompatibilitySoapBindingSkeleton.java.
References org.glite.security.voms.service.compatibility.VOMSCompatibility.getPatchVersionNumber(), and org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.impl.
    
        int ret = impl.getPatchVersionNumber();
        return ret;
    
Member Data Documentation
java.util.Map org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton._myOperations = new java.util.Hashtable() [static, private]
Definition at line 12 of file VOMSCompatibilitySoapBindingSkeleton.java.
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.getOperationDescByName().
java.util.Collection org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton._myOperationsList = new java.util.ArrayList() [static, private]
Definition at line 13 of file VOMSCompatibilitySoapBindingSkeleton.java.
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.getOperationDescs().
org.glite.security.voms.service.compatibility.VOMSCompatibility org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.impl [private]
Definition at line 11 of file VOMSCompatibilitySoapBindingSkeleton.java.
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.getGridmapUsers(), org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.getMajorVersionNumber(), org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.getMinorVersionNumber(), org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.getPatchVersionNumber(), and org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.VOMSCompatibilitySoapBindingSkeleton().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/compatibility/VOMSCompatibilitySoapBindingSkeleton.java