org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton Class Reference
Public Member Functions
VOMSCertificatesSoapBindingSkeleton ()
VOMSCertificatesSoapBindingSkeleton (org.glite.security.voms.service.certificates.VOMSCertificates impl)
org.glite.security.voms.service.certificates.X509Certificate[] getCertificates (long in0) throws java.rmi.RemoteException
org.glite.security.voms.service.certificates.X509Certificate[] getCertificates (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException
long getUserIdFromDn (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException
void addCertificate (long in0, org.glite.security.voms.service.certificates.X509Certificate in1) throws java.rmi.RemoteException
void addCertificate (java.lang.String in0, java.lang.String in1, org.glite.security.voms.service.certificates.X509Certificate in2) throws java.rmi.RemoteException
void suspendCertificate (org.glite.security.voms.service.certificates.X509Certificate in0, java.lang.String in1) throws java.rmi.RemoteException
void restoreCertificate (org.glite.security.voms.service.certificates.X509Certificate in0) throws java.rmi.RemoteException
void removeCertificate (org.glite.security.voms.service.certificates.X509Certificate in0) throws java.rmi.RemoteException
Static Public Member Functions
static java.util.List getOperationDescByName (java.lang.String methodName)
static java.util.Collection getOperationDescs ()
Static Package Functions
[static initializer]
Private Attributes
org.glite.security.voms.service.certificates.VOMSCertificates impl
Static Private Attributes
static java.util.Map _myOperations = new java.util.Hashtable()
static java.util.Collection _myOperationsList = new java.util.ArrayList()
Detailed Description
Definition at line 10 of file VOMSCertificatesSoapBindingSkeleton.java.
Constructor & Destructor Documentation
org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.VOMSCertificatesSoapBindingSkeleton ()
Definition at line 132 of file VOMSCertificatesSoapBindingSkeleton.java.
References org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.impl.
                                                 
        this.impl = new org.glite.security.voms.service.certificates.VOMSCertific
      atesSoapBindingImpl();
    
org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.VOMSCertificatesSoapBindingSkeleton (org.glite.security.voms.service.certificates.VOMSCertificates impl)
Definition at line 136 of file VOMSCertificatesSoapBindingSkeleton.java.
References org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.impl.
                                                                                 
                                        
        this.impl = impl;
    
Member Function Documentation
org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.[static initializer] () [static, package]
void org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.addCertificate (java.lang.String in0, java.lang.String in1, org.glite.security.voms.service.certificates.X509Certificate in2) throws java.rmi.RemoteException
Implements org.glite.security.voms.service.certificates.VOMSCertificates.
Definition at line 162 of file VOMSCertificatesSoapBindingSkeleton.java.
References org.glite.security.voms.service.certificates.VOMSCertificates.addCertificate(), and org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.impl.
    
        impl.addCertificate(in0, in1, in2);
    
void org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.addCertificate (long in0, org.glite.security.voms.service.certificates.X509Certificate in1) throws java.rmi.RemoteException
Implements org.glite.security.voms.service.certificates.VOMSCertificates.
Definition at line 157 of file VOMSCertificatesSoapBindingSkeleton.java.
References org.glite.security.voms.service.certificates.VOMSCertificates.addCertificate(), and org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.impl.
    
        impl.addCertificate(in0, in1);
    
org.glite.security.voms.service.certificates.X509Certificate [] org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.getCertificates (long in0) throws java.rmi.RemoteException
Implements org.glite.security.voms.service.certificates.VOMSCertificates.
Definition at line 139 of file VOMSCertificatesSoapBindingSkeleton.java.
References org.glite.security.voms.service.certificates.VOMSCertificates.getCertificates(), org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.impl, and org.glite.security.voms.service.certificates.X509Certificate.X509Certificate().
    
        org.glite.security.voms.service.certificates.X509Certificate[] ret =
      impl.getCertificates(in0);
        return ret;
    
org.glite.security.voms.service.certificates.X509Certificate [] org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.getCertificates (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException
Implements org.glite.security.voms.service.certificates.VOMSCertificates.
Definition at line 145 of file VOMSCertificatesSoapBindingSkeleton.java.
References org.glite.security.voms.service.certificates.VOMSCertificates.getCertificates(), org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.impl, and org.glite.security.voms.service.certificates.X509Certificate.X509Certificate().
    
        org.glite.security.voms.service.certificates.X509Certificate[] ret =
      impl.getCertificates(in0, in1);
        return ret;
    
static java.util.List org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.getOperationDescByName (java.lang.String methodName) [static]
Returns List of OperationDesc objects with this name
Definition at line 18 of file VOMSCertificatesSoapBindingSkeleton.java.
References org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton._myOperations.
                                                                                 
          
        return (java.util.List)_myOperations.get(methodName);
    
static java.util.Collection org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.getOperationDescs () [static]
Returns Collection of OperationDescs
Definition at line 25 of file VOMSCertificatesSoapBindingSkeleton.java.
References org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton._myOperationsList.
                                                           
        return _myOperationsList;
    
long org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.getUserIdFromDn (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException
Implements org.glite.security.voms.service.certificates.VOMSCertificates.
Definition at line 151 of file VOMSCertificatesSoapBindingSkeleton.java.
References org.glite.security.voms.service.certificates.VOMSCertificates.getUserIdFromDn(), and org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.impl.
    
        long ret = impl.getUserIdFromDn(in0, in1);
        return ret;
    
void org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.removeCertificate (org.glite.security.voms.service.certificates.X509Certificate in0) throws java.rmi.RemoteException
Implements org.glite.security.voms.service.certificates.VOMSCertificates.
Definition at line 177 of file VOMSCertificatesSoapBindingSkeleton.java.
References org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.impl, and org.glite.security.voms.service.certificates.VOMSCertificates.removeCertificate().
    
        impl.removeCertificate(in0);
    
void org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.restoreCertificate (org.glite.security.voms.service.certificates.X509Certificate in0) throws java.rmi.RemoteException
Implements org.glite.security.voms.service.certificates.VOMSCertificates.
Definition at line 172 of file VOMSCertificatesSoapBindingSkeleton.java.
References org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.impl, and org.glite.security.voms.service.certificates.VOMSCertificates.restoreCertificate().
    
        impl.restoreCertificate(in0);
    
void org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.suspendCertificate (org.glite.security.voms.service.certificates.X509Certificate in0, java.lang.String in1) throws java.rmi.RemoteException
Implements org.glite.security.voms.service.certificates.VOMSCertificates.
Definition at line 167 of file VOMSCertificatesSoapBindingSkeleton.java.
References org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.impl, and org.glite.security.voms.service.certificates.VOMSCertificates.suspendCertificate().
    
        impl.suspendCertificate(in0, in1);
    
Member Data Documentation
java.util.Map org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton._myOperations = new java.util.Hashtable() [static, private]
Definition at line 12 of file VOMSCertificatesSoapBindingSkeleton.java.
Referenced by org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.getOperationDescByName().
java.util.Collection org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton._myOperationsList = new java.util.ArrayList() [static, private]
Definition at line 13 of file VOMSCertificatesSoapBindingSkeleton.java.
Referenced by org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.getOperationDescs().
org.glite.security.voms.service.certificates.VOMSCertificates org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.impl [private]
Definition at line 11 of file VOMSCertificatesSoapBindingSkeleton.java.
Referenced by org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.addCertificate(), org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.getCertificates(), org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.getUserIdFromDn(), org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.removeCertificate(), org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.restoreCertificate(), org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.suspendCertificate(), and org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.VOMSCertificatesSoapBindingSkeleton().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/certificates/VOMSCertificatesSoapBindingSkeleton.java