org.glite.security.voms.User Class Reference
Public Member Functions
User ()
User (java.lang.String CA, java.lang.String CN, java.lang.String DN, java.lang.String certUri, java.lang.String mail)
java.lang.String getCA ()
void setCA (java.lang.String CA)
java.lang.String getCN ()
void setCN (java.lang.String CN)
java.lang.String getDN ()
void setDN (java.lang.String DN)
java.lang.String getCertUri ()
void setCertUri (java.lang.String certUri)
java.lang.String getMail ()
void setMail (java.lang.String mail)
synchronized boolean equals (java.lang.Object obj)
synchronized int hashCode ()
Private Attributes
java.lang.String CA
java.lang.String CN
java.lang.String DN
java.lang.String certUri
java.lang.String mail
java.lang.Object __equalsCalc = null
boolean __hashCodeCalc = false
Detailed Description
Definition at line 10 of file User.java.
Constructor & Destructor Documentation
org.glite.security.voms.User.User ()
Definition at line 21 of file User.java.
Referenced by org.glite.security.voms.User.equals().
                  
    
org.glite.security.voms.User.User (java.lang.String CA, java.lang.String CN, java.lang.String DN, java.lang.String certUri, java.lang.String mail)
Definition at line 24 of file User.java.
References org.glite.security.voms.User.CA, org.glite.security.voms.User.certUri, org.glite.security.voms.User.CN, org.glite.security.voms.User.DN, and org.glite.security.voms.User.mail.
                                  
           this.CA = CA;
           this.CN = CN;
           this.DN = DN;
           this.certUri = certUri;
           this.mail = mail;
    
Member Function Documentation
synchronized boolean org.glite.security.voms.User.equals (java.lang.Object obj)
Definition at line 138 of file User.java.
References org.glite.security.voms.User.__equalsCalc, org.glite.security.voms.User.CA, org.glite.security.voms.User.certUri, org.glite.security.voms.User.CN, org.glite.security.voms.User.DN, org.glite.security.voms.User.getCA(), org.glite.security.voms.User.getCertUri(), org.glite.security.voms.User.getCN(), org.glite.security.voms.User.getDN(), org.glite.security.voms.User.getMail(), org.glite.security.voms.User.mail, and org.glite.security.voms.User.User().
                                                             
        if (!(obj instanceof User)) return false;
        User other = (User) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null)
            return (__equalsCalc == obj);
        
        __equalsCalc = obj;
        boolean _equals;
        _equals = true &&
            ((this.CA==null && other.getCA()==null) ||
             (this.CA!=null &&
              this.CA.equals(other.getCA()))) &&
            ((this.CN==null && other.getCN()==null) ||
             (this.CN!=null &&
              this.CN.equals(other.getCN()))) &&
            ((this.DN==null && other.getDN()==null) ||
             (this.DN!=null &&
              this.DN.equals(other.getDN()))) &&
            ((this.certUri==null && other.getCertUri()==null) ||
             (this.certUri!=null &&
              this.certUri.equals(other.getCertUri()))) &&
            ((this.mail==null && other.getMail()==null) ||
             (this.mail!=null &&
              this.mail.equals(other.getMail())));
        __equalsCalc = null;
        return _equals;
    
java.lang.String org.glite.security.voms.User.getCA ()
Gets the CA value for this User.
Returns
CA
Definition at line 43 of file User.java.
References org.glite.security.voms.User.CA.
Referenced by org.glite.security.voms.User.equals(), and org.glite.security.voms.User.hashCode().
                                    
        return CA;
    
java.lang.String org.glite.security.voms.User.getCertUri ()
Gets the certUri value for this User.
Returns
certUri
Definition at line 103 of file User.java.
References org.glite.security.voms.User.certUri.
Referenced by org.glite.security.voms.User.equals(), and org.glite.security.voms.User.hashCode().
                                         
        return certUri;
    
java.lang.String org.glite.security.voms.User.getCN ()
Gets the CN value for this User.
Returns
CN
Definition at line 63 of file User.java.
References org.glite.security.voms.User.CN.
Referenced by org.glite.security.voms.User.equals(), and org.glite.security.voms.User.hashCode().
                                    
        return CN;
    
java.lang.String org.glite.security.voms.User.getDN ()
Gets the DN value for this User.
Returns
DN
Definition at line 83 of file User.java.
References org.glite.security.voms.User.DN.
Referenced by org.glite.security.voms.User.equals(), and org.glite.security.voms.User.hashCode().
                                    
        return DN;
    
java.lang.String org.glite.security.voms.User.getMail ()
Gets the mail value for this User.
Returns
mail
Definition at line 123 of file User.java.
References org.glite.security.voms.User.mail.
Referenced by org.glite.security.voms.User.equals(), and org.glite.security.voms.User.hashCode().
                                      
        return mail;
    
synchronized int org.glite.security.voms.User.hashCode ()
Definition at line 169 of file User.java.
References org.glite.security.voms.User.__hashCodeCalc, org.glite.security.voms.User.getCA(), org.glite.security.voms.User.getCertUri(), org.glite.security.voms.User.getCN(), org.glite.security.voms.User.getDN(), and org.glite.security.voms.User.getMail().
                                       
        if (__hashCodeCalc)
            return 0;
        
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getCA() != null)
            _hashCode += getCA().hashCode();
        
        if (getCN() != null)
            _hashCode += getCN().hashCode();
        
        if (getDN() != null)
            _hashCode += getDN().hashCode();
        
        if (getCertUri() != null)
            _hashCode += getCertUri().hashCode();
        
        if (getMail() != null)
            _hashCode += getMail().hashCode();
        
        __hashCodeCalc = false;
        return _hashCode;
    
void org.glite.security.voms.User.setCA (java.lang.String CA)
Sets the CA value for this User.
Parameters
CA
Definition at line 53 of file User.java.
References org.glite.security.voms.User.CA.
                                           
        this.CA = CA;
    
void org.glite.security.voms.User.setCertUri (java.lang.String certUri)
Sets the certUri value for this User.
Parameters
certUri
Definition at line 113 of file User.java.
References org.glite.security.voms.User.certUri.
                                                     
        this.certUri = certUri;
    
void org.glite.security.voms.User.setCN (java.lang.String CN)
Sets the CN value for this User.
Parameters
CN
Definition at line 73 of file User.java.
References org.glite.security.voms.User.CN.
                                           
        this.CN = CN;
    
void org.glite.security.voms.User.setDN (java.lang.String DN)
Sets the DN value for this User.
Parameters
DN
Definition at line 93 of file User.java.
References org.glite.security.voms.User.DN.
                                           
        this.DN = DN;
    
void org.glite.security.voms.User.setMail (java.lang.String mail)
Sets the mail value for this User.
Parameters
mail
Definition at line 133 of file User.java.
References org.glite.security.voms.User.mail.
                                               
        this.mail = mail;
    
Member Data Documentation
java.lang.Object org.glite.security.voms.User.__equalsCalc = null [private]
Definition at line 137 of file User.java.
Referenced by org.glite.security.voms.User.equals().
boolean org.glite.security.voms.User.__hashCodeCalc = false [private]
Definition at line 168 of file User.java.
Referenced by org.glite.security.voms.User.hashCode().
java.lang.String org.glite.security.voms.User.CA [private]
Definition at line 11 of file User.java.
Referenced by org.glite.security.voms.User.equals(), org.glite.security.voms.User.getCA(), org.glite.security.voms.User.setCA(), and org.glite.security.voms.User.User().
java.lang.String org.glite.security.voms.User.certUri [private]
Definition at line 17 of file User.java.
Referenced by org.glite.security.voms.User.equals(), org.glite.security.voms.User.getCertUri(), org.glite.security.voms.User.setCertUri(), and org.glite.security.voms.User.User().
java.lang.String org.glite.security.voms.User.CN [private]
Definition at line 13 of file User.java.
Referenced by org.glite.security.voms.User.equals(), org.glite.security.voms.User.getCN(), org.glite.security.voms.User.setCN(), and org.glite.security.voms.User.User().
java.lang.String org.glite.security.voms.User.DN [private]
Definition at line 15 of file User.java.
Referenced by org.glite.security.voms.User.equals(), org.glite.security.voms.User.getDN(), org.glite.security.voms.User.setDN(), and org.glite.security.voms.User.User().
java.lang.String org.glite.security.voms.User.mail [private]
Definition at line 19 of file User.java.
Referenced by org.glite.security.voms.User.equals(), org.glite.security.voms.User.getMail(), org.glite.security.voms.User.setMail(), and org.glite.security.voms.User.User().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/User.java