org.glite.security.voms.service.certificates.X509Certificate Class Reference
Public Member Functions
X509Certificate ()
X509Certificate (byte[] bytes, long id, java.lang.String issuer, java.lang.String notAfter, java.lang.String subject)
byte[] getBytes ()
void setBytes (byte[] bytes)
long getId ()
void setId (long id)
java.lang.String getIssuer ()
void setIssuer (java.lang.String issuer)
java.lang.String getNotAfter ()
void setNotAfter (java.lang.String notAfter)
java.lang.String getSubject ()
void setSubject (java.lang.String subject)
synchronized boolean equals (java.lang.Object obj)
synchronized int hashCode ()
Private Attributes
byte[] bytes
long id
java.lang.String issuer
java.lang.String notAfter
java.lang.String subject
java.lang.Object __equalsCalc = null
boolean __hashCodeCalc = false
Detailed Description
Definition at line 10 of file X509Certificate.java.
Constructor & Destructor Documentation
org.glite.security.voms.service.certificates.X509Certificate.X509Certificate ()
Definition at line 21 of file X509Certificate.java.
Referenced by org.glite.security.voms.service.certificates.X509Certificate.equals(), and org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.getCertificates().
                             
    
org.glite.security.voms.service.certificates.X509Certificate.X509Certificate (byte[] bytes, long id, java.lang.String issuer, java.lang.String notAfter, java.lang.String subject)
Definition at line 24 of file X509Certificate.java.
References org.glite.security.voms.service.certificates.X509Certificate.bytes, org.glite.security.voms.service.certificates.X509Certificate.id, org.glite.security.voms.service.certificates.X509Certificate.issuer, org.glite.security.voms.service.certificates.X509Certificate.notAfter, and org.glite.security.voms.service.certificates.X509Certificate.subject.
                                     
           this.bytes = bytes;
           this.id = id;
           this.issuer = issuer;
           this.notAfter = notAfter;
           this.subject = subject;
    
Member Function Documentation
synchronized boolean org.glite.security.voms.service.certificates.X509Certificate.equals (java.lang.Object obj)
Definition at line 138 of file X509Certificate.java.
References org.glite.security.voms.service.certificates.X509Certificate.__equalsCalc, org.glite.security.voms.service.certificates.X509Certificate.bytes, org.glite.security.voms.service.certificates.X509Certificate.getBytes(), org.glite.security.voms.service.certificates.X509Certificate.getId(), org.glite.security.voms.service.certificates.X509Certificate.getIssuer(), org.glite.security.voms.service.certificates.X509Certificate.getNotAfter(), org.glite.security.voms.service.certificates.X509Certificate.getSubject(), org.glite.security.voms.service.certificates.X509Certificate.issuer, org.glite.security.voms.service.certificates.X509Certificate.notAfter, org.glite.security.voms.service.certificates.X509Certificate.subject, and org.glite.security.voms.service.certificates.X509Certificate.X509Certificate().
                                                             
        if (!(obj instanceof X509Certificate)) return false;
        X509Certificate other = (X509Certificate) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null)
            return (__equalsCalc == obj);
        
        __equalsCalc = obj;
        boolean _equals;
        _equals = true &&
            ((this.bytes==null && other.getBytes()==null) ||
             (this.bytes!=null &&
              java.util.Arrays.equals(this.bytes, other.getBytes()))) &&
            this.id == other.getId() &&
            ((this.issuer==null && other.getIssuer()==null) ||
             (this.issuer!=null &&
              this.issuer.equals(other.getIssuer()))) &&
            ((this.notAfter==null && other.getNotAfter()==null) ||
             (this.notAfter!=null &&
              this.notAfter.equals(other.getNotAfter()))) &&
            ((this.subject==null && other.getSubject()==null) ||
             (this.subject!=null &&
              this.subject.equals(other.getSubject())));
        __equalsCalc = null;
        return _equals;
    
byte [] org.glite.security.voms.service.certificates.X509Certificate.getBytes ()
Gets the bytes value for this X509Certificate.
Returns
bytes
Definition at line 43 of file X509Certificate.java.
References org.glite.security.voms.service.certificates.X509Certificate.bytes.
Referenced by org.glite.security.voms.service.certificates.X509Certificate.equals(), and org.glite.security.voms.service.certificates.X509Certificate.hashCode().
                             
        return bytes;
    
long org.glite.security.voms.service.certificates.X509Certificate.getId ()
Gets the id value for this X509Certificate.
Returns
id
Definition at line 63 of file X509Certificate.java.
References org.glite.security.voms.service.certificates.X509Certificate.id.
Referenced by org.glite.security.voms.service.certificates.X509Certificate.equals(), and org.glite.security.voms.service.certificates.X509Certificate.hashCode().
                        
        return id;
    
java.lang.String org.glite.security.voms.service.certificates.X509Certificate.getIssuer ()
Gets the issuer value for this X509Certificate.
Returns
issuer
Definition at line 83 of file X509Certificate.java.
References org.glite.security.voms.service.certificates.X509Certificate.issuer.
Referenced by org.glite.security.voms.service.certificates.X509Certificate.equals(), and org.glite.security.voms.service.certificates.X509Certificate.hashCode().
                                        
        return issuer;
    
java.lang.String org.glite.security.voms.service.certificates.X509Certificate.getNotAfter ()
Gets the notAfter value for this X509Certificate.
Returns
notAfter
Definition at line 103 of file X509Certificate.java.
References org.glite.security.voms.service.certificates.X509Certificate.notAfter.
Referenced by org.glite.security.voms.service.certificates.X509Certificate.equals(), and org.glite.security.voms.service.certificates.X509Certificate.hashCode().
                                          
        return notAfter;
    
java.lang.String org.glite.security.voms.service.certificates.X509Certificate.getSubject ()
Gets the subject value for this X509Certificate.
Returns
subject
Definition at line 123 of file X509Certificate.java.
References org.glite.security.voms.service.certificates.X509Certificate.subject.
Referenced by org.glite.security.voms.service.certificates.X509Certificate.equals(), and org.glite.security.voms.service.certificates.X509Certificate.hashCode().
                                         
        return subject;
    
synchronized int org.glite.security.voms.service.certificates.X509Certificate.hashCode ()
Definition at line 167 of file X509Certificate.java.
References org.glite.security.voms.service.certificates.X509Certificate.__hashCodeCalc, org.glite.security.voms.service.certificates.X509Certificate.getBytes(), org.glite.security.voms.service.certificates.X509Certificate.getId(), org.glite.security.voms.service.certificates.X509Certificate.getIssuer(), org.glite.security.voms.service.certificates.X509Certificate.getNotAfter(), and org.glite.security.voms.service.certificates.X509Certificate.getSubject().
                                       
        if (__hashCodeCalc)
            return 0;
        
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getBytes() != null)
            for (int i=0;
                 i<java.lang.reflect.Array.getLength(getBytes());
                 i++)
                java.lang.Object obj = java.lang.reflect.Array.get(getBytes(), i)
      ;
                if (obj != null &&
                    !obj.getClass().isArray())
                    _hashCode += obj.hashCode();
                
            
        
        _hashCode += new Long(getId()).hashCode();
        if (getIssuer() != null)
            _hashCode += getIssuer().hashCode();
        
        if (getNotAfter() != null)
            _hashCode += getNotAfter().hashCode();
        
        if (getSubject() != null)
            _hashCode += getSubject().hashCode();
        
        __hashCodeCalc = false;
        return _hashCode;
    
void org.glite.security.voms.service.certificates.X509Certificate.setBytes (byte[] bytes)
Sets the bytes value for this X509Certificate.
Parameters
bytes
Definition at line 53 of file X509Certificate.java.
References org.glite.security.voms.service.certificates.X509Certificate.bytes.
                                       
        this.bytes = bytes;
    
void org.glite.security.voms.service.certificates.X509Certificate.setId (long id)
Sets the id value for this X509Certificate.
Parameters
id
Definition at line 73 of file X509Certificate.java.
References org.glite.security.voms.service.certificates.X509Certificate.id.
                               
        this.id = id;
    
void org.glite.security.voms.service.certificates.X509Certificate.setIssuer (java.lang.String issuer)
Sets the issuer value for this X509Certificate.
Parameters
issuer
Definition at line 93 of file X509Certificate.java.
References org.glite.security.voms.service.certificates.X509Certificate.issuer.
                                                   
        this.issuer = issuer;
    
void org.glite.security.voms.service.certificates.X509Certificate.setNotAfter (java.lang.String notAfter)
Sets the notAfter value for this X509Certificate.
Parameters
notAfter
Definition at line 113 of file X509Certificate.java.
References org.glite.security.voms.service.certificates.X509Certificate.notAfter.
                                                       
        this.notAfter = notAfter;
    
void org.glite.security.voms.service.certificates.X509Certificate.setSubject (java.lang.String subject)
Sets the subject value for this X509Certificate.
Parameters
subject
Definition at line 133 of file X509Certificate.java.
References org.glite.security.voms.service.certificates.X509Certificate.subject.
                                                     
        this.subject = subject;
    
Member Data Documentation
java.lang.Object org.glite.security.voms.service.certificates.X509Certificate.__equalsCalc = null [private]
Definition at line 137 of file X509Certificate.java.
Referenced by org.glite.security.voms.service.certificates.X509Certificate.equals().
boolean org.glite.security.voms.service.certificates.X509Certificate.__hashCodeCalc = false [private]
Definition at line 166 of file X509Certificate.java.
Referenced by org.glite.security.voms.service.certificates.X509Certificate.hashCode().
byte [] org.glite.security.voms.service.certificates.X509Certificate.bytes [private]
Definition at line 11 of file X509Certificate.java.
Referenced by org.glite.security.voms.service.certificates.X509Certificate.equals(), org.glite.security.voms.service.certificates.X509Certificate.getBytes(), org.glite.security.voms.service.certificates.X509Certificate.setBytes(), and org.glite.security.voms.service.certificates.X509Certificate.X509Certificate().
long org.glite.security.voms.service.certificates.X509Certificate.id [private]
Definition at line 13 of file X509Certificate.java.
Referenced by org.glite.security.voms.service.certificates.X509Certificate.getId(), org.glite.security.voms.service.certificates.X509Certificate.setId(), and org.glite.security.voms.service.certificates.X509Certificate.X509Certificate().
java.lang.String org.glite.security.voms.service.certificates.X509Certificate.issuer [private]
Definition at line 15 of file X509Certificate.java.
Referenced by org.glite.security.voms.service.certificates.X509Certificate.equals(), org.glite.security.voms.service.certificates.X509Certificate.getIssuer(), org.glite.security.voms.service.certificates.X509Certificate.setIssuer(), and org.glite.security.voms.service.certificates.X509Certificate.X509Certificate().
java.lang.String org.glite.security.voms.service.certificates.X509Certificate.notAfter [private]
Definition at line 17 of file X509Certificate.java.
Referenced by org.glite.security.voms.service.certificates.X509Certificate.equals(), org.glite.security.voms.service.certificates.X509Certificate.getNotAfter(), org.glite.security.voms.service.certificates.X509Certificate.setNotAfter(), and org.glite.security.voms.service.certificates.X509Certificate.X509Certificate().
java.lang.String org.glite.security.voms.service.certificates.X509Certificate.subject [private]
Definition at line 19 of file X509Certificate.java.
Referenced by org.glite.security.voms.service.certificates.X509Certificate.equals(), org.glite.security.voms.service.certificates.X509Certificate.getSubject(), org.glite.security.voms.service.certificates.X509Certificate.setSubject(), and org.glite.security.voms.service.certificates.X509Certificate.X509Certificate().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/certificates/X509Certificate.java