org.glite.security.voms.service.acl.ACLEntry Class Reference
Public Member Functions
ACLEntry ()
ACLEntry (java.lang.String adminIssuer, java.lang.String adminSubject, int vomsPermissionBits)
java.lang.String getAdminIssuer ()
void setAdminIssuer (java.lang.String adminIssuer)
java.lang.String getAdminSubject ()
void setAdminSubject (java.lang.String adminSubject)
int getVomsPermissionBits ()
void setVomsPermissionBits (int vomsPermissionBits)
synchronized boolean equals (java.lang.Object obj)
synchronized int hashCode ()
Private Attributes
java.lang.String adminIssuer
java.lang.String adminSubject
int vomsPermissionBits
java.lang.Object __equalsCalc = null
boolean __hashCodeCalc = false
Detailed Description
Definition at line 10 of file ACLEntry.java.
Constructor & Destructor Documentation
org.glite.security.voms.service.acl.ACLEntry.ACLEntry ()
Definition at line 17 of file ACLEntry.java.
Referenced by org.glite.security.voms.service.acl.ACLEntry.equals().
                      
    
org.glite.security.voms.service.acl.ACLEntry.ACLEntry (java.lang.String adminIssuer, java.lang.String adminSubject, int vomsPermissionBits)
Definition at line 20 of file ACLEntry.java.
References org.glite.security.voms.service.acl.ACLEntry.adminIssuer, org.glite.security.voms.service.acl.ACLEntry.adminSubject, and org.glite.security.voms.service.acl.ACLEntry.vomsPermissionBits.
                                   
           this.adminIssuer = adminIssuer;
           this.adminSubject = adminSubject;
           this.vomsPermissionBits = vomsPermissionBits;
    
Member Function Documentation
synchronized boolean org.glite.security.voms.service.acl.ACLEntry.equals (java.lang.Object obj)
Definition at line 90 of file ACLEntry.java.
References org.glite.security.voms.service.acl.ACLEntry.__equalsCalc, org.glite.security.voms.service.acl.ACLEntry.ACLEntry(), org.glite.security.voms.service.acl.ACLEntry.adminIssuer, org.glite.security.voms.service.acl.ACLEntry.adminSubject, org.glite.security.voms.service.acl.ACLEntry.getAdminIssuer(), org.glite.security.voms.service.acl.ACLEntry.getAdminSubject(), org.glite.security.voms.service.acl.ACLEntry.getVomsPermissionBits(), and org.glite.security.voms.service.acl.ACLEntry.vomsPermissionBits.
                                                             
        if (!(obj instanceof ACLEntry)) return false;
        ACLEntry other = (ACLEntry) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null)
            return (__equalsCalc == obj);
        
        __equalsCalc = obj;
        boolean _equals;
        _equals = true &&
            ((this.adminIssuer==null && other.getAdminIssuer()==null) ||
             (this.adminIssuer!=null &&
              this.adminIssuer.equals(other.getAdminIssuer()))) &&
            ((this.adminSubject==null && other.getAdminSubject()==null) ||
             (this.adminSubject!=null &&
              this.adminSubject.equals(other.getAdminSubject()))) &&
            this.vomsPermissionBits == other.getVomsPermissionBits();
        __equalsCalc = null;
        return _equals;
    
java.lang.String org.glite.security.voms.service.acl.ACLEntry.getAdminIssuer ()
Gets the adminIssuer value for this ACLEntry.
Returns
adminIssuer
Definition at line 35 of file ACLEntry.java.
References org.glite.security.voms.service.acl.ACLEntry.adminIssuer.
Referenced by org.glite.security.voms.service.acl.ACLEntry.equals(), and org.glite.security.voms.service.acl.ACLEntry.hashCode().
                                             
        return adminIssuer;
    
java.lang.String org.glite.security.voms.service.acl.ACLEntry.getAdminSubject ()
Gets the adminSubject value for this ACLEntry.
Returns
adminSubject
Definition at line 55 of file ACLEntry.java.
References org.glite.security.voms.service.acl.ACLEntry.adminSubject.
Referenced by org.glite.security.voms.service.acl.ACLEntry.equals(), and org.glite.security.voms.service.acl.ACLEntry.hashCode().
                                              
        return adminSubject;
    
int org.glite.security.voms.service.acl.ACLEntry.getVomsPermissionBits ()
Gets the vomsPermissionBits value for this ACLEntry.
Returns
vomsPermissionBits
Definition at line 75 of file ACLEntry.java.
References org.glite.security.voms.service.acl.ACLEntry.vomsPermissionBits.
Referenced by org.glite.security.voms.service.acl.ACLEntry.equals(), and org.glite.security.voms.service.acl.ACLEntry.hashCode().
                                       
        return vomsPermissionBits;
    
synchronized int org.glite.security.voms.service.acl.ACLEntry.hashCode ()
Definition at line 113 of file ACLEntry.java.
References org.glite.security.voms.service.acl.ACLEntry.__hashCodeCalc, org.glite.security.voms.service.acl.ACLEntry.getAdminIssuer(), org.glite.security.voms.service.acl.ACLEntry.getAdminSubject(), and org.glite.security.voms.service.acl.ACLEntry.getVomsPermissionBits().
                                       
        if (__hashCodeCalc)
            return 0;
        
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getAdminIssuer() != null)
            _hashCode += getAdminIssuer().hashCode();
        
        if (getAdminSubject() != null)
            _hashCode += getAdminSubject().hashCode();
        
        _hashCode += getVomsPermissionBits();
        __hashCodeCalc = false;
        return _hashCode;
    
void org.glite.security.voms.service.acl.ACLEntry.setAdminIssuer (java.lang.String adminIssuer)
Sets the adminIssuer value for this ACLEntry.
Parameters
adminIssuer
Definition at line 45 of file ACLEntry.java.
References org.glite.security.voms.service.acl.ACLEntry.adminIssuer.
                                                             
        this.adminIssuer = adminIssuer;
    
void org.glite.security.voms.service.acl.ACLEntry.setAdminSubject (java.lang.String adminSubject)
Sets the adminSubject value for this ACLEntry.
Parameters
adminSubject
Definition at line 65 of file ACLEntry.java.
References org.glite.security.voms.service.acl.ACLEntry.adminSubject.
                                                               
        this.adminSubject = adminSubject;
    
void org.glite.security.voms.service.acl.ACLEntry.setVomsPermissionBits (int vomsPermissionBits)
Sets the vomsPermissionBits value for this ACLEntry.
Parameters
vomsPermissionBits
Definition at line 85 of file ACLEntry.java.
References org.glite.security.voms.service.acl.ACLEntry.vomsPermissionBits.
                                                              
        this.vomsPermissionBits = vomsPermissionBits;
    
Member Data Documentation
java.lang.Object org.glite.security.voms.service.acl.ACLEntry.__equalsCalc = null [private]
Definition at line 89 of file ACLEntry.java.
Referenced by org.glite.security.voms.service.acl.ACLEntry.equals().
boolean org.glite.security.voms.service.acl.ACLEntry.__hashCodeCalc = false [private]
Definition at line 112 of file ACLEntry.java.
Referenced by org.glite.security.voms.service.acl.ACLEntry.hashCode().
java.lang.String org.glite.security.voms.service.acl.ACLEntry.adminIssuer [private]
Definition at line 11 of file ACLEntry.java.
Referenced by org.glite.security.voms.service.acl.ACLEntry.ACLEntry(), org.glite.security.voms.service.acl.ACLEntry.equals(), org.glite.security.voms.service.acl.ACLEntry.getAdminIssuer(), and org.glite.security.voms.service.acl.ACLEntry.setAdminIssuer().
java.lang.String org.glite.security.voms.service.acl.ACLEntry.adminSubject [private]
Definition at line 13 of file ACLEntry.java.
Referenced by org.glite.security.voms.service.acl.ACLEntry.ACLEntry(), org.glite.security.voms.service.acl.ACLEntry.equals(), org.glite.security.voms.service.acl.ACLEntry.getAdminSubject(), and org.glite.security.voms.service.acl.ACLEntry.setAdminSubject().
int org.glite.security.voms.service.acl.ACLEntry.vomsPermissionBits [private]
Definition at line 15 of file ACLEntry.java.
Referenced by org.glite.security.voms.service.acl.ACLEntry.ACLEntry(), org.glite.security.voms.service.acl.ACLEntry.equals(), org.glite.security.voms.service.acl.ACLEntry.getVomsPermissionBits(), and org.glite.security.voms.service.acl.ACLEntry.setVomsPermissionBits().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/acl/ACLEntry.java