portal.registration.domain.Vo Class Reference
Public Member Functions
Vo ()
Vo (String vo, String host, String description, String discipline, String longDiscipline, Date insertTime, String aup)
Vo (String vo, String host, String description, String voManagerMail, String enrollementUrl, String discipline, String longDiscipline, Date insertTime, String aup, Set< UserToVo > userToVos, Set< Fqan > fqans)
int getIdVo ()
void setIdVo (int idVo)
String getVo ()
void setVo (String vo)
String getHost ()
void setHost (String host)
String getDescription ()
void setDescription (String description)
String getVoManagerMail ()
void setVoManagerMail (String voManagerMail)
String getEnrollementUrl ()
void setEnrollementUrl (String enrollementUrl)
String getDiscipline ()
void setDiscipline (String discipline)
String getLongDiscipline ()
void setLongDiscipline (String longDiscipline)
Date getInsertTime ()
void setInsertTime (Date insertTime)
String getAup ()
void setAup (String aup)
Set< UserToVo > getUserToVos ()
void setUserToVos (Set< UserToVo > userToVos)
Set< Fqan > getFqans ()
void setFqans (Set< Fqan > fqans)
Private Attributes
int idVo
String vo
String host
String description
String voManagerMail
String enrollementUrl
String discipline
String longDiscipline
Date insertTime
String aup
Set< UserToVo > userToVos = new HashSet<UserToVo>(0)
Set< Fqan > fqans = new HashSet<Fqan>(0)
Static Private Attributes
static final long serialVersionUID = -9053612297786722393L
Detailed Description
Vo generated by hbm2java
Definition at line 25 of file Vo.java.
Constructor & Destructor Documentation
portal.registration.domain.Vo.Vo ()
Definition at line 44 of file Vo.java.
                    
        
portal.registration.domain.Vo.Vo (String vo, String host, String description, String discipline, String longDiscipline, Date insertTime, String aup)
Definition at line 47 of file Vo.java.
                                                                            
                this.vo = vo;
                this.host = host;
                this.description = description;
                this.discipline = discipline;
                this.longDiscipline = longDiscipline;
                this.insertTime = insertTime;
                this.aup = aup;
        
portal.registration.domain.Vo.Vo (String vo, String host, String description, String voManagerMail, String enrollementUrl, String discipline, String longDiscipline, Date insertTime, String aup, Set< UserToVo > userToVos, Set< Fqan > fqans)
Definition at line 58 of file Vo.java.
                                         
                this.vo = vo;
                this.host = host;
                this.description = description;
                this.voManagerMail = voManagerMail;
                this.enrollementUrl = enrollementUrl;
                this.discipline = discipline;
                this.longDiscipline = longDiscipline;
                this.insertTime = insertTime;
                this.aup = aup;
                this.userToVos = userToVos;
                this.fqans = fqans;
        
Member Function Documentation
String portal.registration.domain.Vo.getAup ()
Definition at line 160 of file Vo.java.
                               
                return this.aup;
        
String portal.registration.domain.Vo.getDescription ()
Definition at line 105 of file Vo.java.
                                       
                return this.description;
        
String portal.registration.domain.Vo.getDiscipline ()
Definition at line 132 of file Vo.java.
                                      
                return this.discipline;
        
String portal.registration.domain.Vo.getEnrollementUrl ()
Definition at line 123 of file Vo.java.
                                          
                return this.enrollementUrl;
        
Set<Fqan> portal.registration.domain.Vo.getFqans ()
Definition at line 178 of file Vo.java.
                                    
                return this.fqans;
        
String portal.registration.domain.Vo.getHost ()
Definition at line 96 of file Vo.java.
Referenced by portal.registration.controller.AddUserToVOController.checkVO().
                                
                return this.host;
        
int portal.registration.domain.Vo.getIdVo ()
Definition at line 78 of file Vo.java.
Referenced by portal.registration.services.VoServiceImpl.findByVo().
                             
                return this.idVo;
        
Date portal.registration.domain.Vo.getInsertTime ()
Definition at line 151 of file Vo.java.
                                    
                return this.insertTime;
        
String portal.registration.domain.Vo.getLongDiscipline ()
Definition at line 141 of file Vo.java.
                                          
                return this.longDiscipline;
        
Set<UserToVo> portal.registration.domain.Vo.getUserToVos ()
Definition at line 169 of file Vo.java.
                                            
                return this.userToVos;
        
String portal.registration.domain.Vo.getVo ()
Definition at line 87 of file Vo.java.
Referenced by portal.registration.controller.AddUserToVOController.checkVO(), and portal.registration.services.UserToVoServiceImpl.findDefaultVo().
                              
                return this.vo;
        
String portal.registration.domain.Vo.getVoManagerMail ()
Definition at line 114 of file Vo.java.
                                         
                return this.voManagerMail;
        
void portal.registration.domain.Vo.setAup (String aup)
Definition at line 164 of file Vo.java.
                                       
                this.aup = aup;
        
void portal.registration.domain.Vo.setDescription (String description)
Definition at line 109 of file Vo.java.
                                                       
                this.description = description;
        
void portal.registration.domain.Vo.setDiscipline (String discipline)
Definition at line 136 of file Vo.java.
                                                     
                this.discipline = discipline;
        
void portal.registration.domain.Vo.setEnrollementUrl (String enrollementUrl)
Definition at line 127 of file Vo.java.
                                                             
                this.enrollementUrl = enrollementUrl;
        
void portal.registration.domain.Vo.setFqans (Set< Fqan > fqans)
Definition at line 182 of file Vo.java.
                                              
                this.fqans = fqans;
        
void portal.registration.domain.Vo.setHost (String host)
Definition at line 100 of file Vo.java.
                                         
                this.host = host;
        
void portal.registration.domain.Vo.setIdVo (int idVo)
Definition at line 82 of file Vo.java.
                                      
                this.idVo = idVo;
        
void portal.registration.domain.Vo.setInsertTime (Date insertTime)
Definition at line 155 of file Vo.java.
                                                   
                this.insertTime = insertTime;
        
void portal.registration.domain.Vo.setLongDiscipline (String longDiscipline)
Definition at line 145 of file Vo.java.
                                                             
                this.longDiscipline = longDiscipline;
        
void portal.registration.domain.Vo.setUserToVos (Set< UserToVo > userToVos)
Definition at line 173 of file Vo.java.
                                                          
                this.userToVos = userToVos;
        
void portal.registration.domain.Vo.setVo (String vo)
Definition at line 91 of file Vo.java.
                                     
                this.vo = vo;
        
void portal.registration.domain.Vo.setVoManagerMail (String voManagerMail)
Definition at line 118 of file Vo.java.
                                                           
                this.voManagerMail = voManagerMail;
        
Member Data Documentation
String portal.registration.domain.Vo.aup [private]
Definition at line 40 of file Vo.java.
String portal.registration.domain.Vo.description [private]
Definition at line 34 of file Vo.java.
String portal.registration.domain.Vo.discipline [private]
Definition at line 37 of file Vo.java.
String portal.registration.domain.Vo.enrollementUrl [private]
Definition at line 36 of file Vo.java.
Set<Fqan> portal.registration.domain.Vo.fqans = new HashSet<Fqan>(0) [private]
Definition at line 42 of file Vo.java.
String portal.registration.domain.Vo.host [private]
Definition at line 33 of file Vo.java.
int portal.registration.domain.Vo.idVo [private]
Definition at line 31 of file Vo.java.
Date portal.registration.domain.Vo.insertTime [private]
Definition at line 39 of file Vo.java.
String portal.registration.domain.Vo.longDiscipline [private]
Definition at line 38 of file Vo.java.
final long portal.registration.domain.Vo.serialVersionUID = -9053612297786722393L [static, private]
Definition at line 30 of file Vo.java.
Set<UserToVo> portal.registration.domain.Vo.userToVos = new HashSet<UserToVo>(0) [private]
Definition at line 41 of file Vo.java.
String portal.registration.domain.Vo.vo [private]
Definition at line 32 of file Vo.java.
String portal.registration.domain.Vo.voManagerMail [private]
Definition at line 35 of file Vo.java.
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/domain/Vo.java