portal.registration.utils.MyValidator Class Reference
Static Public Member Functions
static boolean validate (UserInfo target, List< String > errors) throws SystemException
static boolean validateCert (String pwd, String pwd1, String pwd2, List< String > errors) throws SystemException
static boolean validateUpdate (UserInfo target, UserInfo check, List< String > errors) throws SystemException
Static Private Attributes
static final Logger log = Logger.getLogger(MyValidator.class)
Detailed Description
Definition at line 13 of file MyValidator.java.
Member Function Documentation
static boolean portal.registration.utils.MyValidator.validate (UserInfo target, List< String > errors) throws SystemException [static]
Definition at line 17 of file MyValidator.java.
References portal.registration.utils.MyValidator.log.
Referenced by portal.registration.controller.AddUserInfoController.addUserInfo().
                                               
                boolean result = true;
                if (Validator.isNull(target.getFirstName()))
                        errors.add("user-first-name-required");
                        result = false;
                        log.info("nome sbagliato");
                
                if (Validator.isNull(target.getLastName()))
                        errors.add("user-last-name-required");
                        result = false;
                        log.info("cognome sbagliato");
                
                if (Validator.isNull(target.getInstitute()))
                        errors.add("user-institute-required");
                        result = false;
                        log.info("istituto sbagliato");
                
                if (Validator.isNull(target.getMail()))
                        errors.add("user-mail-required");
                        result = false;
                        log.info("mail sbagliato");
                
                if (Validator.isNotNull(target.getMail()))
                        if (!Validator.isEmailAddress(target.getMail()))
                                errors.add("user-valid-mail-required");
                                result = false;
                                log.info("mail invalida sbagliato");
                        
                
                if (Validator.isNull(target.getUsername()))
                        errors.add("user-username-required");
                        result = false;
                        log.info("usename vuoto sbagliato");
                
                if (Validator.isNotNull(target.getPhone()))
                        if (!Validator.isPhoneNumber(target.getPhone()))
                                errors.add("user-phone-valid");
                                result = false;
                                log.info("telefono sbagliato");
                        
                
                List<User> liferayUsers = UserLocalServiceUtil.getUsers(0,
                                UserLocalServiceUtil.getUsersCount());
                for (int i = 0; i < UserLocalServiceUtil.getUsersCount(); i++)
                        if (liferayUsers.get(i).getScreenName()
                                        .equals(target.getUsername()))
                                errors.add("user-username-duplicate");
                                result = false;
                                log.info("username duplicato sbagliato");
                        
                        if (liferayUsers.get(i).getEmailAddress().equals(target.g
      etMail()))
                                errors.add("user-mail-duplicate");
                                result = false;
                                log.info("mail duplicato sbagliato " + target.get
      Mail() + " = "
                                                + liferayUsers.get(i).getEmailAdd
      ress());
                        
                
                return result;
        
static boolean portal.registration.utils.MyValidator.validateCert (String pwd, String pwd1, String pwd2, List< String > errors) throws SystemException [static]
Definition at line 88 of file MyValidator.java.
References portal.registration.utils.MyValidator.log.
Referenced by portal.registration.controller.UploadCertController.uploadCert().
                                                                    
                boolean result = true;
                if (!pwd1.equals(pwd2))
                        errors.add("cert-password-incorrect");
                        result = false;
                        log.info("Le Password devono essere uguali");
                
                if (Validator.isNull(pwd))
                        errors.add("key-pass-required");
                        result = false;
                        log.info("Inserire Password");
                
                if (Validator.isNull(pwd1))
                        errors.add("cert-pass1-required");
                        result = false;
                        log.info("Inserire Password");
                
                if (Validator.isNull(pwd2))
                        errors.add("cert-pass2-required");
                        result = false;
                        log.info("Inserire Password di controllo");
                
                return result;
        
static boolean portal.registration.utils.MyValidator.validateUpdate (UserInfo target, UserInfo check, List< String > errors) throws SystemException [static]
Definition at line 119 of file MyValidator.java.
References portal.registration.utils.MyValidator.log.
Referenced by portal.registration.controller.EditUserInfoController.editUserInfo().
                                                                    
                boolean result = true;
                if (Validator.isNull(target.getFirstName()))
                        errors.add("user-first-name-required");
                        result = false;
                        log.info("nome sbagliato");
                
                if (Validator.isNull(target.getLastName()))
                        errors.add("user-last-name-required");
                        result = false;
                        log.info("cognome sbagliato");
                
                if (Validator.isNull(target.getInstitute()))
                        errors.add("user-institute-required");
                        result = false;
                        log.info("istituto sbagliato");
                
                if (Validator.isNull(target.getMail()))
                        errors.add("user-mail-required");
                        result = false;
                        log.info("mail sbagliato");
                
                if (!target.getMail().equals(check.getMail()))
                        result = false;
                        errors.add("user-mail-must-same");
                
                if (Validator.isNotNull(target.getMail()))
                        if (!Validator.isEmailAddress(target.getMail()))
                                errors.add("user-valid-mail-required");
                                result = false;
                                log.info("mail invalida sbagliato");
                        
                
                if (Validator.isNull(target.getUsername()))
                        errors.add("user-username-required");
                        result = false;
                        log.info("usename vuoto sbagliato");
                
                if (!target.getUsername().equals(check.getUsername()))
                        result = false;
                        errors.add("user-username-must-same");
                
                if (Validator.isNotNull(target.getPhone()))
                        if (!Validator.isPhoneNumber(target.getPhone()))
                                errors.add("user-phone-valid");
                                result = false;
                                log.info("telefono sbagliato");
                        
                
                return result;
        
Member Data Documentation
final Logger portal.registration.utils.MyValidator.log = Logger.getLogger(MyValidator.class) [static, private]
Definition at line 15 of file MyValidator.java.
Referenced by portal.registration.utils.MyValidator.validate(), portal.registration.utils.MyValidator.validateCert(), and portal.registration.utils.MyValidator.validateUpdate().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/utils/MyValidator.java