org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton Class Reference
Public Member Functions
VOMSAttributesSoapBindingSkeleton ()
VOMSAttributesSoapBindingSkeleton (org.glite.security.voms.service.attributes.VOMSAttributes impl)
void createAttributeClass (java.lang.String in0, java.lang.String in1, boolean in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void createAttributeClass (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void createAttributeClass (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.service.attributes.AttributeClass getAttributeClass (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void saveAttributeClass (org.glite.security.voms.service.attributes.AttributeClass in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteAttributeClass (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteAttributeClass (org.glite.security.voms.service.attributes.AttributeClass in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.service.attributes.AttributeClass[] listAttributeClasses () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.service.attributes.AttributeValue[] listUserAttributes (org.glite.security.voms.User in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void setUserAttribute (org.glite.security.voms.User in0, org.glite.security.voms.service.attributes.AttributeValue in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteUserAttribute (org.glite.security.voms.User in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteUserAttribute (org.glite.security.voms.User in0, org.glite.security.voms.service.attributes.AttributeValue in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void setGroupAttribute (java.lang.String in0, org.glite.security.voms.service.attributes.AttributeValue in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteGroupAttribute (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteGroupAttribute (java.lang.String in0, org.glite.security.voms.service.attributes.AttributeValue in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.service.attributes.AttributeValue[] listGroupAttributes (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void setRoleAttribute (java.lang.String in0, java.lang.String in1, org.glite.security.voms.service.attributes.AttributeValue in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteRoleAttribute (java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteRoleAttribute (java.lang.String in0, java.lang.String in1, org.glite.security.voms.service.attributes.AttributeValue in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.service.attributes.AttributeValue[] listRoleAttributes (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Static Public Member Functions
static java.util.List getOperationDescByName (java.lang.String methodName)
static java.util.Collection getOperationDescs ()
Static Package Functions
[static initializer]
Private Attributes
org.glite.security.voms.service.attributes.VOMSAttributes impl
Static Private Attributes
static java.util.Map _myOperations = new java.util.Hashtable()
static java.util.Collection _myOperationsList = new java.util.ArrayList()
Detailed Description
Definition at line 10 of file VOMSAttributesSoapBindingSkeleton.java.
Constructor & Destructor Documentation
org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.VOMSAttributesSoapBindingSkeleton ()
Definition at line 395 of file VOMSAttributesSoapBindingSkeleton.java.
References org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.impl.
                                               
        this.impl = new org.glite.security.voms.service.attributes.VOMSAttributes
      SoapBindingImpl();
    
org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.VOMSAttributesSoapBindingSkeleton (org.glite.security.voms.service.attributes.VOMSAttributes impl)
Definition at line 399 of file VOMSAttributesSoapBindingSkeleton.java.
References org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.impl.
                                                                                 
                                  
        this.impl = impl;
    
Member Function Documentation
org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.[static initializer] () [static, package]
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.createAttributeClass (java.lang.String in0, java.lang.String in1, boolean in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 402 of file VOMSAttributesSoapBindingSkeleton.java.
References org.glite.security.voms.service.attributes.VOMSAttributes.createAttributeClass(), and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.impl.
    
        impl.createAttributeClass(in0, in1, in2);
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.createAttributeClass (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 407 of file VOMSAttributesSoapBindingSkeleton.java.
References org.glite.security.voms.service.attributes.VOMSAttributes.createAttributeClass(), and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.impl.
    
        impl.createAttributeClass(in0, in1);
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.createAttributeClass (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 412 of file VOMSAttributesSoapBindingSkeleton.java.
References org.glite.security.voms.service.attributes.VOMSAttributes.createAttributeClass(), and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.impl.
    
        impl.createAttributeClass(in0);
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.deleteAttributeClass (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 428 of file VOMSAttributesSoapBindingSkeleton.java.
References org.glite.security.voms.service.attributes.VOMSAttributes.deleteAttributeClass(), and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.impl.
    
        impl.deleteAttributeClass(in0);
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.deleteAttributeClass (org.glite.security.voms.service.attributes.AttributeClass in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 433 of file VOMSAttributesSoapBindingSkeleton.java.
References org.glite.security.voms.service.attributes.VOMSAttributes.deleteAttributeClass(), and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.impl.
    
        impl.deleteAttributeClass(in0);
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.deleteGroupAttribute (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 470 of file VOMSAttributesSoapBindingSkeleton.java.
References org.glite.security.voms.service.attributes.VOMSAttributes.deleteGroupAttribute(), and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.impl.
    
        impl.deleteGroupAttribute(in0, in1);
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.deleteGroupAttribute (java.lang.String in0, org.glite.security.voms.service.attributes.AttributeValue in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 475 of file VOMSAttributesSoapBindingSkeleton.java.
References org.glite.security.voms.service.attributes.VOMSAttributes.deleteGroupAttribute(), and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.impl.
    
        impl.deleteGroupAttribute(in0, in1);
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.deleteRoleAttribute (java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 491 of file VOMSAttributesSoapBindingSkeleton.java.
References org.glite.security.voms.service.attributes.VOMSAttributes.deleteRoleAttribute(), and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.impl.
    
        impl.deleteRoleAttribute(in0, in1, in2);
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.deleteRoleAttribute (java.lang.String in0, java.lang.String in1, org.glite.security.voms.service.attributes.AttributeValue in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 496 of file VOMSAttributesSoapBindingSkeleton.java.
References org.glite.security.voms.service.attributes.VOMSAttributes.deleteRoleAttribute(), and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.impl.
    
        impl.deleteRoleAttribute(in0, in1, in2);
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.deleteUserAttribute (org.glite.security.voms.User in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 455 of file VOMSAttributesSoapBindingSkeleton.java.
References org.glite.security.voms.service.attributes.VOMSAttributes.deleteUserAttribute(), and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.impl.
    
        impl.deleteUserAttribute(in0, in1);
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.deleteUserAttribute (org.glite.security.voms.User in0, org.glite.security.voms.service.attributes.AttributeValue in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 460 of file VOMSAttributesSoapBindingSkeleton.java.
References org.glite.security.voms.service.attributes.VOMSAttributes.deleteUserAttribute(), and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.impl.
    
        impl.deleteUserAttribute(in0, in1);
    
org.glite.security.voms.service.attributes.AttributeClass org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.getAttributeClass (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 417 of file VOMSAttributesSoapBindingSkeleton.java.
References org.glite.security.voms.service.attributes.VOMSAttributes.getAttributeClass(), and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.impl.
    
        org.glite.security.voms.service.attributes.AttributeClass ret = impl.getA
      ttributeClass(in0);
        return ret;
    
static java.util.List org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.getOperationDescByName (java.lang.String methodName) [static]
Returns List of OperationDesc objects with this name
Definition at line 18 of file VOMSAttributesSoapBindingSkeleton.java.
References org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton._myOperations.
                                                                                 
          
        return (java.util.List)_myOperations.get(methodName);
    
static java.util.Collection org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.getOperationDescs () [static]
Returns Collection of OperationDescs
Definition at line 25 of file VOMSAttributesSoapBindingSkeleton.java.
References org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton._myOperationsList.
                                                           
        return _myOperationsList;
    
org.glite.security.voms.service.attributes.AttributeClass [] org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.listAttributeClasses () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 438 of file VOMSAttributesSoapBindingSkeleton.java.
References org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.impl, and org.glite.security.voms.service.attributes.VOMSAttributes.listAttributeClasses().
    
        org.glite.security.voms.service.attributes.AttributeClass[] ret = impl.li
      stAttributeClasses();
        return ret;
    
org.glite.security.voms.service.attributes.AttributeValue [] org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.listGroupAttributes (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 480 of file VOMSAttributesSoapBindingSkeleton.java.
References org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.impl, and org.glite.security.voms.service.attributes.VOMSAttributes.listGroupAttributes().
    
        org.glite.security.voms.service.attributes.AttributeValue[] ret = impl.li
      stGroupAttributes(in0);
        return ret;
    
org.glite.security.voms.service.attributes.AttributeValue [] org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.listRoleAttributes (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 501 of file VOMSAttributesSoapBindingSkeleton.java.
References org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.impl, and org.glite.security.voms.service.attributes.VOMSAttributes.listRoleAttributes().
    
        org.glite.security.voms.service.attributes.AttributeValue[] ret = impl.li
      stRoleAttributes(in0, in1);
        return ret;
    
org.glite.security.voms.service.attributes.AttributeValue [] org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.listUserAttributes (org.glite.security.voms.User in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 444 of file VOMSAttributesSoapBindingSkeleton.java.
References org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.impl, and org.glite.security.voms.service.attributes.VOMSAttributes.listUserAttributes().
    
        org.glite.security.voms.service.attributes.AttributeValue[] ret = impl.li
      stUserAttributes(in0);
        return ret;
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.saveAttributeClass (org.glite.security.voms.service.attributes.AttributeClass in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 423 of file VOMSAttributesSoapBindingSkeleton.java.
References org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.impl, and org.glite.security.voms.service.attributes.VOMSAttributes.saveAttributeClass().
    
        impl.saveAttributeClass(in0);
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.setGroupAttribute (java.lang.String in0, org.glite.security.voms.service.attributes.AttributeValue in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 465 of file VOMSAttributesSoapBindingSkeleton.java.
References org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.impl, and org.glite.security.voms.service.attributes.VOMSAttributes.setGroupAttribute().
    
        impl.setGroupAttribute(in0, in1);
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.setRoleAttribute (java.lang.String in0, java.lang.String in1, org.glite.security.voms.service.attributes.AttributeValue in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 486 of file VOMSAttributesSoapBindingSkeleton.java.
References org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.impl, and org.glite.security.voms.service.attributes.VOMSAttributes.setRoleAttribute().
    
        impl.setRoleAttribute(in0, in1, in2);
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.setUserAttribute (org.glite.security.voms.User in0, org.glite.security.voms.service.attributes.AttributeValue in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 450 of file VOMSAttributesSoapBindingSkeleton.java.
References org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.impl, and org.glite.security.voms.service.attributes.VOMSAttributes.setUserAttribute().
    
        impl.setUserAttribute(in0, in1);
    
Member Data Documentation
java.util.Map org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton._myOperations = new java.util.Hashtable() [static, private]
Definition at line 12 of file VOMSAttributesSoapBindingSkeleton.java.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.getOperationDescByName().
java.util.Collection org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton._myOperationsList = new java.util.ArrayList() [static, private]
Definition at line 13 of file VOMSAttributesSoapBindingSkeleton.java.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.getOperationDescs().
org.glite.security.voms.service.attributes.VOMSAttributes org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.impl [private]
Definition at line 11 of file VOMSAttributesSoapBindingSkeleton.java.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.createAttributeClass(), org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.deleteAttributeClass(), org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.deleteGroupAttribute(), org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.deleteRoleAttribute(), org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.deleteUserAttribute(), org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.getAttributeClass(), org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.listAttributeClasses(), org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.listGroupAttributes(), org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.listRoleAttributes(), org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.listUserAttributes(), org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.saveAttributeClass(), org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.setGroupAttribute(), org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.setRoleAttribute(), org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.setUserAttribute(), and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.VOMSAttributesSoapBindingSkeleton().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/attributes/VOMSAttributesSoapBindingSkeleton.java