portal.registration.controller.AddUserInfoController Class Reference
Public Member Functions
UserInfo getCommandObject ()
String showUserInfoForm (RenderResponse response)
void initBinder (WebDataBinder binder)
void addUserInfo (@Valid @ModelAttribute UserInfo userInfo, BindingResult bindingResult, ActionRequest request, ActionResponse response, SessionStatus sessionStatus) throws PortalException, SystemException
List< Idp > getIdps ()
Private Attributes
IdpService idpService
UserInfoService userInfoService
Static Private Attributes
static final Logger log
Detailed Description
Definition at line 47 of file AddUserInfoController.java.
Member Function Documentation
void portal.registration.controller.AddUserInfoController.addUserInfo (@Valid @ModelAttribute UserInfo userInfo, BindingResult bindingResult, ActionRequest request, ActionResponse response, SessionStatus sessionStatus) throws PortalException, SystemException
Definition at line 74 of file AddUserInfoController.java.
References portal.registration.services.IdpService.findById(), portal.registration.services.UserInfoService.save(), and portal.registration.utils.MyValidator.validate().
                                                                
                log.info("sono dentro");
                if (!bindingResult.hasErrors())
                        ArrayList<String> errors = new ArrayList<String>();
                        boolean allOk = true;
                        int userId = 0;
                        if (request.getParameter("useCondition").equals("true"))
      
                                if (MyValidator.validate(userInfo, errors))
                                        log.info("Valore passato idp "
                                                        + Integer.parseInt(reques
      t.getParameter("idpId")));
                                        log.info("Valore passato havecert "
                                                        + request.getParameter("h
      aveCert"));
                                        if (Integer.parseInt(request.getParameter
      ("idpId")) != 0)
                                                Idp idp = idpService.findById(Int
      eger.parseInt(request
                                                                .getParameter("id
      pId")));
                                                userInfo.setIdp(idp);
                                                log.info("Settato idp "
                                                                + Integer.parseIn
      t(request
                                                                                .
      getParameter("idpId")));
                                                try
                                                        long companyId = PortalUt
      il.getCompanyId(request);
                                                        log.info("companyid = " +
       companyId);
                                                        log.info("settate variabi
      li di supporto ora si aggiunge un utenti a liferay!!");
                                                        User u = UserLocalService
      Util.addUser(0L,
                                                                        companyId
      , false, "settedByPortal",
                                                                        "settedBy
      Portal", false, userInfo
                                                                                        .
      getUsername(), userInfo.getMail(),
                                                                        0L, "", n
      ew Locale("en"), userInfo
                                                                                        .
      getFirstName(), "", userInfo
                                                                                        .
      getLastName(), 0, 0, true,
                                                                        Calendar.
      JANUARY, 1, 1970, "", null, null,
                                                                        null, nul
      l, true, ServiceContextFactory
                                                                                        .
      getInstance(User.class.getName(),
                                                                                                        r
      equest));
                                                        if (u == null)
                                                                log.info("nulla d
      i fatto");
                                                 catch (Exception e)
                                                        errors.add("user-liferay-
      problem");
                                                        log.info("Inserimento ute
      nte in liferay" + e);
                                                        allOk = false;
                                                        request.setAttribute("fir
      stReg", "true");
                                                
                                                if (allOk)
                                                        try
                                                                log.info("aggiunt
      o utente in liferay, ora aggiungo in PortalUser");
                                                                userInfo.setRegis
      trationComplete("false");
                                                                userId =
      userInfoService.save(userInfo,
                                                                                I
      nteger.parseInt(request
                                                                                                .
      getParameter("idpId")));
                                                                log.info("Utente
      aggiunto in PortalUsert con UserId = "
                                                                                +
       userId);
                                                         catch (Exception e)
                                                                errors.add("user-
      PortalUser-problem");
                                                                log.info("Inserim
      ento utente in PortalUser");
                                                                e.printStackTrace
      ();
                                                                allOk = false;
                                                        
                                                
                                         else
                                                errors.add("user-idp-problem");
                                                allOk = false;
                                        
                                 else
                                        allOk = false;
                                
                                if (allOk)
                                        SessionMessages.add(request, "user-saved-
      successufully");
                                        if (request.getParameter("haveCert").equa
      ls("true"))
                                                response.setRenderParameter("myac
      tion",
                                                                "showUploadCert")
      ;
                                                request.setAttribute("userId", us
      erId);
                                                request.setAttribute("username",
      userInfo.getUsername());
                                                request.setAttribute("firstReg",
      "true");
                                         else
                                                response.setRenderParameter("myac
      tion",
                                                                "showRequestCerti
      ficate");
                                        
                                        sessionStatus.setComplete();
                                 else
                                        errors.add("error-saving-registration");
                                        for (String error : errors)
                                                log.info("Errore: " + error);
                                                SessionErrors.add(request, error)
      ;
                                        
                                        log.info("non va bene");
                                        response.setRenderParameter("myaction", "
      addUserInfoForm");
                                        request.setAttribute("idpValue",
                                                        Integer.parseInt(request.
      getParameter("idpId")));
                                        request.setAttribute("userInfo", userInfo
      );
                                        request.setAttribute("checked",
                                                        request.getParameter("hav
      eCert"));
                                        log.info("non va bene");
                                
                         else
                                log.info("condizioni d'uso non accettate");
                                SessionErrors.add(request, "use-condition-not-ace
      pted");
                                response.setRenderParameter("myaction", "userInfo
      s");
                        
                 else
                        log.info("Errore errore");
                        response.setRenderParameter("myaction", "addUserInfoForm"
      );
                
        
UserInfo portal.registration.controller.AddUserInfoController.getCommandObject ()
Definition at line 59 of file AddUserInfoController.java.
                                           
                return new UserInfo();
        
List<Idp> portal.registration.controller.AddUserInfoController.getIdps ()
Definition at line 215 of file AddUserInfoController.java.
References portal.registration.services.IdpService.getAllIdp().
                                   
                return idpService.getAllIdp();
        
void portal.registration.controller.AddUserInfoController.initBinder (WebDataBinder binder)
Definition at line 69 of file AddUserInfoController.java.
                                                     
                binder.registerCustomEditor(Long.class, new LongNumberEditor());
        
String portal.registration.controller.AddUserInfoController.showUserInfoForm (RenderResponse response)
Definition at line 64 of file AddUserInfoController.java.
                                                                
                return "addUserInfoForm";
        
Member Data Documentation
IdpService portal.registration.controller.AddUserInfoController.idpService [private]
Definition at line 53 of file AddUserInfoController.java.
final Logger portal.registration.controller.AddUserInfoController.log [static, private]
Initial value:
 Logger
                        .getLogger(AddUserInfoController.class)
Definition at line 49 of file AddUserInfoController.java.
UserInfoService portal.registration.controller.AddUserInfoController.userInfoService [private]
Definition at line 56 of file AddUserInfoController.java.
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/controller/AddUserInfoController.java