portal.registration.dao.CertificateDAOImpl Class Reference
Public Member Functions
Integer save (Certificate transientInstance)
void delete (Certificate persistentInstance)
Certificate findById (Integer id)
List< Certificate > findById (UserInfo userInfo)
void edit (Certificate certificate)
Private Attributes
SessionFactory sessionFactory
Static Private Attributes
static final Logger log
Detailed Description
Definition at line 16 of file CertificateDAOImpl.java.
Member Function Documentation
void portal.registration.dao.CertificateDAOImpl.delete (Certificate persistentInstance)
Implements portal.registration.dao.CertificateDAO.
Definition at line 37 of file CertificateDAOImpl.java.
References portal.registration.dao.CertificateDAOImpl.log, and portal.registration.dao.CertificateDAOImpl.sessionFactory.
                                                           
                log.debug("removing UserInfo instance");
                try
                        Session session = sessionFactory.getCurrentSession();
                        session.delete(persistentInstance);
                        log.debug("remove successful");
                 catch (RuntimeException re)
                        log.error("remove failed", re);
                        throw re;
                
        
void portal.registration.dao.CertificateDAOImpl.edit (Certificate certificate)
Implements portal.registration.dao.CertificateDAO.
Definition at line 83 of file CertificateDAOImpl.java.
References portal.registration.domain.Certificate.getCaonline(), portal.registration.domain.Certificate.getExpirationDate(), portal.registration.domain.Certificate.getIdCert(), portal.registration.domain.Certificate.getIssuer(), portal.registration.domain.Certificate.getPrimaryCert(), portal.registration.domain.Certificate.getSubject(), portal.registration.domain.Certificate.getUserInfo(), portal.registration.domain.Certificate.getUsernameCert(), portal.registration.dao.CertificateDAOImpl.log, portal.registration.dao.CertificateDAOImpl.sessionFactory, portal.registration.domain.Certificate.setCaonline(), portal.registration.domain.Certificate.setExpirationDate(), portal.registration.domain.Certificate.setIssuer(), portal.registration.domain.Certificate.setPrimaryCert(), portal.registration.domain.Certificate.setSubject(), portal.registration.domain.Certificate.setUserInfo(), and portal.registration.domain.Certificate.setUsernameCert().
                                                  
                log.debug("Editing existing certificate");
                // Retrieve session from Hibernate
                Session session = sessionFactory.getCurrentSession();
                // Retrieve existing userInfo via id
                Certificate existingCertificate = (Certificate) session.get(
                                Certificate.class, certificate.getIdCert());
                // Assign updated values to this userInfo
                existingCertificate.setCaonline(certificate.getCaonline());
                existingCertificate.setExpirationDate(certificate.getExpirationDa
      te());
                existingCertificate.setIssuer(certificate.getIssuer());
                existingCertificate.setPrimaryCert(certificate.getPrimaryCert());
      
                existingCertificate.setSubject(certificate.getSubject());
                existingCertificate.setUserInfo(certificate.getUserInfo());
                existingCertificate.setUsernameCert(certificate.getUsernameCert()
      );
                // Save updates
                session.save(existingCertificate);
        
List<Certificate> portal.registration.dao.CertificateDAOImpl.findById (UserInfo userInfo)
Implements portal.registration.dao.CertificateDAO.
Definition at line 64 of file CertificateDAOImpl.java.
References portal.registration.dao.CertificateDAOImpl.log, and portal.registration.dao.CertificateDAOImpl.sessionFactory.
                                                             
                log.debug("getting all Certificate instance of user");
                try
                        Session session = sessionFactory.getCurrentSession();
                        // Create a Hibernate query (HQL)
                        Query query = session
                                        .createQuery("FROM Certificate WHERE use
      rId = "
                                                        + userInfo.getUserId());
                        // Retrieve all
                        return query.list();
                 catch (RuntimeException re)
                        log.error("get failed", re);
                        throw re;
                
        
Certificate portal.registration.dao.CertificateDAOImpl.findById (Integer id)
Implements portal.registration.dao.CertificateDAO.
Definition at line 49 of file CertificateDAOImpl.java.
References portal.registration.dao.CertificateDAOImpl.log, and portal.registration.dao.CertificateDAOImpl.sessionFactory.
                                                
                log.debug("getting Certificate instance with id: " + id);
                try
                        Session session = sessionFactory.getCurrentSession();
                        Certificate instance = (Certificate) session.get(Certific
      ate.class,
                                        id);
                        log.debug("get successful");
                        return instance;
                 catch (RuntimeException re)
                        log.error("get failed", re);
                        throw re;
                
        
Integer portal.registration.dao.CertificateDAOImpl.save (Certificate transientInstance)
Implements portal.registration.dao.CertificateDAO.
Definition at line 24 of file CertificateDAOImpl.java.
References portal.registration.dao.CertificateDAOImpl.log, and portal.registration.dao.CertificateDAOImpl.sessionFactory.
                                                           
                log.debug("persisting UserInfo instance");
                try
                        Session session = sessionFactory.getCurrentSession();
                        int id = (Integer) session.save(transientInstance);
                        log.debug("persist successful");
                        return id;
                 catch (RuntimeException re)
                        log.error("persist failed", re);
                        throw re;
                
        
Member Data Documentation
final Logger portal.registration.dao.CertificateDAOImpl.log [static, private]
Initial value:
 Logger
                        .getLogger(CertificateDAOImpl.class)
Definition at line 18 of file CertificateDAOImpl.java.
Referenced by portal.registration.dao.CertificateDAOImpl.delete(), portal.registration.dao.CertificateDAOImpl.edit(), portal.registration.dao.CertificateDAOImpl.findById(), and portal.registration.dao.CertificateDAOImpl.save().
SessionFactory portal.registration.dao.CertificateDAOImpl.sessionFactory [private]
Definition at line 22 of file CertificateDAOImpl.java.
Referenced by portal.registration.dao.CertificateDAOImpl.delete(), portal.registration.dao.CertificateDAOImpl.edit(), portal.registration.dao.CertificateDAOImpl.findById(), and portal.registration.dao.CertificateDAOImpl.save().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/dao/CertificateDAOImpl.java