org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub Class Reference
Public Member Functions
VOMSCertificatesSoapBindingStub () throws org.apache.axis.AxisFault
VOMSCertificatesSoapBindingStub (java.net.URL endpointURL, javax.xml.rpc.Service service) throws org.apache.axis.AxisFault
VOMSCertificatesSoapBindingStub (javax.xml.rpc.Service service) throws org.apache.axis.AxisFault
org.glite.security.voms.service.certificates.X509Certificate[] getCertificates (long in0) throws java.rmi.RemoteException
org.glite.security.voms.service.certificates.X509Certificate[] getCertificates (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException
long getUserIdFromDn (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException
void addCertificate (long in0, org.glite.security.voms.service.certificates.X509Certificate in1) throws java.rmi.RemoteException
void addCertificate (java.lang.String in0, java.lang.String in1, org.glite.security.voms.service.certificates.X509Certificate in2) throws java.rmi.RemoteException
void suspendCertificate (org.glite.security.voms.service.certificates.X509Certificate in0, java.lang.String in1) throws java.rmi.RemoteException
void restoreCertificate (org.glite.security.voms.service.certificates.X509Certificate in0) throws java.rmi.RemoteException
void removeCertificate (org.glite.security.voms.service.certificates.X509Certificate in0) throws java.rmi.RemoteException
Protected Member Functions
org.apache.axis.client.Call createCall () throws java.rmi.RemoteException
Static Package Functions
[static initializer]
Static Package Attributes
static org.apache.axis.description.OperationDesc[] _operations
Static Private Member Functions
static void _initOperationDesc1 ()
Private Attributes
java.util.Vector cachedSerClasses = new java.util.Vector()
java.util.Vector cachedSerQNames = new java.util.Vector()
java.util.Vector cachedSerFactories = new java.util.Vector()
java.util.Vector cachedDeserFactories = new java.util.Vector()
Detailed Description
Definition at line 10 of file VOMSCertificatesSoapBindingStub.java.
Constructor & Destructor Documentation
org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.VOMSCertificatesSoapBindingStub () throws org.apache.axis.AxisFault
Definition at line 118 of file VOMSCertificatesSoapBindingStub.java.
                                                                              
         this(null);
    
org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.VOMSCertificatesSoapBindingStub (java.net.URL endpointURL, javax.xml.rpc.Service service) throws org.apache.axis.AxisFault
Definition at line 122 of file VOMSCertificatesSoapBindingStub.java.
                                                                                 
                                                          
         this(service);
         super.cachedEndpoint = endpointURL;
    
org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.VOMSCertificatesSoapBindingStub (javax.xml.rpc.Service service) throws org.apache.axis.AxisFault
Definition at line 127 of file VOMSCertificatesSoapBindingStub.java.
References org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.cachedDeserFactories, org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.cachedSerClasses, org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.cachedSerFactories, and org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.cachedSerQNames.
                                                                                 
                                
        if (service == null)
            super.service = new org.apache.axis.client.Service();
         else
            super.service = service;
        
        ((org.apache.axis.client.Service)super.service).setTypeMappingVersion("1.
      2");
            java.lang.Class cls;
            javax.xml.namespace.QName qName;
            javax.xml.namespace.QName qName2;
            java.lang.Class beansf = org.apache.axis.encoding.ser.BeanSerializerF
      actory.class;
            java.lang.Class beandf = org.apache.axis.encoding.ser.BeanDeserialize
      rFactory.class;
            java.lang.Class enumsf = org.apache.axis.encoding.ser.EnumSerializerF
      actory.class;
            java.lang.Class enumdf = org.apache.axis.encoding.ser.EnumDeserialize
      rFactory.class;
            java.lang.Class arraysf = org.apache.axis.encoding.ser.ArraySerialize
      rFactory.class;
            java.lang.Class arraydf = org.apache.axis.encoding.ser.ArrayDeseriali
      zerFactory.class;
            java.lang.Class simplesf = org.apache.axis.encoding.ser.SimpleSeriali
      zerFactory.class;
            java.lang.Class simpledf = org.apache.axis.encoding.ser.SimpleDeseria
      lizerFactory.class;
            java.lang.Class simplelistsf = org.apache.axis.encoding.ser.SimpleLis
      tSerializerFactory.class;
            java.lang.Class simplelistdf = org.apache.axis.encoding.ser.SimpleLis
      tDeserializerFactory.class;
            qName = new javax.xml.namespace.QName("http://glite.org/wsdl/services
      /org.glite.security.voms.service.certificates", "ArrayOfX509Certificate");
            cachedSerQNames.add(qName);
            cls = org.glite.security.voms.service.certificates.X509Certificate[].
      class;
            cachedSerClasses.add(cls);
            qName = new javax.xml.namespace.QName("http://glite.org/wsdl/services
      /org.glite.security.voms.service.certificates", "X509Certificate");
            qName2 = null;
            cachedSerFactories.add(new org.apache.axis.encoding.ser.ArraySerializ
      erFactory(qName, qName2));
            cachedDeserFactories.add(new org.apache.axis.encoding.ser.ArrayDeseri
      alizerFactory());
            qName = new javax.xml.namespace.QName("http://glite.org/wsdl/services
      /org.glite.security.voms.service.certificates", "X509Certificate");
            cachedSerQNames.add(qName);
            cls = org.glite.security.voms.service.certificates.X509Certificate.cl
      ass;
            cachedSerClasses.add(cls);
            cachedSerFactories.add(beansf);
            cachedDeserFactories.add(beandf);
    
Member Function Documentation
org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.[static initializer] () [static, package]
static void org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub._initOperationDesc1 () [static, private]
Definition at line 23 of file VOMSCertificatesSoapBindingStub.java.
References org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub._operations.
                                             
        org.apache.axis.description.OperationDesc oper;
        org.apache.axis.description.ParameterDesc param;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("getCertificates");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://www.w3.org/2001/XMLSchema", "long"), long.class, false,
       false);
        oper.addParameter(param);
        oper.setReturnType(new javax.xml.namespace.QName("http://glite.org/wsdl/s
      ervices/org.glite.security.voms.service.certificates", "ArrayOfX509Certificate"))
      ;
        oper.setReturnClass(org.glite.security.voms.service.certificates.X509Cert
      ificate[].class);
        oper.setReturnQName(new javax.xml.namespace.QName("", "getCertificatesRet
      urn"));
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        _operations[0] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("getCertificates");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in1"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(new javax.xml.namespace.QName("http://glite.org/wsdl/s
      ervices/org.glite.security.voms.service.certificates", "ArrayOfX509Certificate"))
      ;
        oper.setReturnClass(org.glite.security.voms.service.certificates.X509Cert
      ificate[].class);
        oper.setReturnQName(new javax.xml.namespace.QName("", "getCertificatesRet
      urn"));
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        _operations[1] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("getUserIdFromDn");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in1"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(new javax.xml.namespace.QName("http://www.w3.org/2001/
      XMLSchema", "long"));
        oper.setReturnClass(long.class);
        oper.setReturnQName(new javax.xml.namespace.QName("", "getUserIdFromDnRet
      urn"));
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        _operations[2] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("addCertificate");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://www.w3.org/2001/XMLSchema", "long"), long.class, false,
       false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in1"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://glite.org/wsdl/services/org.glite.security.voms.service
      .certificates", "X509Certificate"), org.glite.security.voms.service.certificates.
      X509Certificate.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        _operations[3] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("addCertificate");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in1"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in2"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://glite.org/wsdl/services/org.glite.security.voms.service
      .certificates", "X509Certificate"), org.glite.security.voms.service.certificates.
      X509Certificate.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        _operations[4] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("suspendCertificate");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://glite.org/wsdl/services/org.glite.security.voms.service
      .certificates", "X509Certificate"), org.glite.security.voms.service.certificates.
      X509Certificate.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in1"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        _operations[5] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("restoreCertificate");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://glite.org/wsdl/services/org.glite.security.voms.service
      .certificates", "X509Certificate"), org.glite.security.voms.service.certificates.
      X509Certificate.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        _operations[6] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("removeCertificate");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://glite.org/wsdl/services/org.glite.security.voms.service
      .certificates", "X509Certificate"), org.glite.security.voms.service.certificates.
      X509Certificate.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        _operations[7] = oper;
    
void org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.addCertificate (java.lang.String in0, java.lang.String in1, org.glite.security.voms.service.certificates.X509Certificate in2) throws java.rmi.RemoteException
Implements org.glite.security.voms.service.certificates.VOMSCertificates.
Definition at line 347 of file VOMSCertificatesSoapBindingStub.java.
                                                                                 
                                                                                       
                 
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[4]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.certificates", "addCertificate"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0,
      in1, in2);
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
  throw axisFaultException;
    
void org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.addCertificate (long in0, org.glite.security.voms.service.certificates.X509Certificate in1) throws java.rmi.RemoteException
Implements org.glite.security.voms.service.certificates.VOMSCertificates.
Definition at line 323 of file VOMSCertificatesSoapBindingStub.java.
                                                                                 
                                                                
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[3]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.certificates", "addCertificate"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] new j
      ava.lang.Long(in0), in1);
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
  throw axisFaultException;
    
org.apache.axis.client.Call org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.createCall () throws java.rmi.RemoteException [protected]
Definition at line 165 of file VOMSCertificatesSoapBindingStub.java.
References org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.cachedDeserFactories, org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.cachedSerClasses, org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.cachedSerFactories, and org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.cachedSerQNames.
Referenced by org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.getCertificates().
                                                                                 
            
        try
            org.apache.axis.client.Call _call = super._createCall();
            if (super.maintainSessionSet)
                _call.setMaintainSession(super.maintainSession);
            
            if (super.cachedUsername != null)
                _call.setUsername(super.cachedUsername);
            
            if (super.cachedPassword != null)
                _call.setPassword(super.cachedPassword);
            
            if (super.cachedEndpoint != null)
                _call.setTargetEndpointAddress(super.cachedEndpoint);
            
            if (super.cachedTimeout != null)
                _call.setTimeout(super.cachedTimeout);
            
            if (super.cachedPortName != null)
                _call.setPortName(super.cachedPortName);
            
            java.util.Enumeration keys = super.cachedProperties.keys();
            while (keys.hasMoreElements())
                java.lang.String key = (java.lang.String) keys.nextElement();
                _call.setProperty(key, super.cachedProperties.get(key));
            
            // All the type mapping information is registered
            // when the first call is made.
            // The type mapping information is actually registered in
            // the TypeMappingRegistry of the service, which
            // is the reason why registration is only needed for the first call.
            synchronized (this)
                if (firstCall())
                    // must set encoding style before registering serializers
                    _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP1
      1_CONSTANTS);
                    _call.setEncodingStyle(org.apache.axis.Constants.URI_SOAP11_E
      NC);
                    for (int i = 0; i < cachedSerFactories.size(); ++i)
                        java.lang.Class cls = (java.lang.Class) cachedSerClasses.
      get(i);
                        javax.xml.namespace.QName qName =
                                (javax.xml.namespace.QName) cachedSerQNames.get(i
      );
                        java.lang.Object x = cachedSerFactories.get(i);
                        if (x instanceof Class)
                            java.lang.Class sf = (java.lang.Class)
                                 cachedSerFactories.get(i);
                            java.lang.Class df = (java.lang.Class)
                                 cachedDeserFactories.get(i);
                            _call.registerTypeMapping(cls, qName, sf, df, false);
      
                        
                        else if (x instanceof javax.xml.rpc.encoding.SerializerFa
      ctory)
                            org.apache.axis.encoding.SerializerFactory sf = (org.
      apache.axis.encoding.SerializerFactory)
                                 cachedSerFactories.get(i);
                            org.apache.axis.encoding.DeserializerFactory df = (or
      g.apache.axis.encoding.DeserializerFactory)
                                 cachedDeserFactories.get(i);
                            _call.registerTypeMapping(cls, qName, sf, df, false);
      
                        
                    
                
            
            return _call;
        
        catch (java.lang.Throwable _t)
            throw new org.apache.axis.AxisFault("Failure trying to get the Call o
      bject", _t);
        
    
org.glite.security.voms.service.certificates.X509Certificate [] org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.getCertificates (long in0) throws java.rmi.RemoteException
Implements org.glite.security.voms.service.certificates.VOMSCertificates.
Definition at line 230 of file VOMSCertificatesSoapBindingStub.java.
References org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub._operations, and org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.createCall().
                                                                                 
                                                         
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[0]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.certificates", "getCertificates"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] new j
      ava.lang.Long(in0));
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        else
            extractAttachments(_call);
            try
                return (org.glite.security.voms.service.certificates.X509Certific
      ate[]) _resp;
             catch (java.lang.Exception _exception)
                return (org.glite.security.voms.service.certificates.X509Certific
      ate[]) org.apache.axis.utils.JavaUtils.convert(_resp, org.glite.security.voms.ser
      vice.certificates.X509Certificate[].class);
            
        
   catch (org.apache.axis.AxisFault axisFaultException)
  throw axisFaultException;
    
org.glite.security.voms.service.certificates.X509Certificate [] org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.getCertificates (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException
Implements org.glite.security.voms.service.certificates.VOMSCertificates.
Definition at line 261 of file VOMSCertificatesSoapBindingStub.java.
                                                                                 
                                                                                       
          
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[1]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.certificates", "getCertificates"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0,
      in1);
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        else
            extractAttachments(_call);
            try
                return (org.glite.security.voms.service.certificates.X509Certific
      ate[]) _resp;
             catch (java.lang.Exception _exception)
                return (org.glite.security.voms.service.certificates.X509Certific
      ate[]) org.apache.axis.utils.JavaUtils.convert(_resp, org.glite.security.voms.ser
      vice.certificates.X509Certificate[].class);
            
        
   catch (org.apache.axis.AxisFault axisFaultException)
  throw axisFaultException;
    
long org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.getUserIdFromDn (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException
Implements org.glite.security.voms.service.certificates.VOMSCertificates.
Definition at line 292 of file VOMSCertificatesSoapBindingStub.java.
                                                                                 
                                 
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[2]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.certificates", "getUserIdFromDn"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0,
      in1);
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        else
            extractAttachments(_call);
            try
                return ((java.lang.Long) _resp).longValue();
             catch (java.lang.Exception _exception)
                return ((java.lang.Long) org.apache.axis.utils.JavaUtils.convert(
      _resp, long.class)).longValue();
            
        
   catch (org.apache.axis.AxisFault axisFaultException)
  throw axisFaultException;
    
void org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.removeCertificate (org.glite.security.voms.service.certificates.X509Certificate in0) throws java.rmi.RemoteException
Implements org.glite.security.voms.service.certificates.VOMSCertificates.
Definition at line 419 of file VOMSCertificatesSoapBindingStub.java.
                                                                                 
                                                         
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[7]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.certificates", "removeCertificate"));
      
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0)
      ;
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
  throw axisFaultException;
    
void org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.restoreCertificate (org.glite.security.voms.service.certificates.X509Certificate in0) throws java.rmi.RemoteException
Implements org.glite.security.voms.service.certificates.VOMSCertificates.
Definition at line 395 of file VOMSCertificatesSoapBindingStub.java.
                                                                                 
                                                          
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[6]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.certificates", "restoreCertificate"))
      ;
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0)
      ;
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
  throw axisFaultException;
    
void org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.suspendCertificate (org.glite.security.voms.service.certificates.X509Certificate in0, java.lang.String in1) throws java.rmi.RemoteException
Implements org.glite.security.voms.service.certificates.VOMSCertificates.
Definition at line 371 of file VOMSCertificatesSoapBindingStub.java.
                                                                                 
                                                                                
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[5]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.certificates", "suspendCertificate"))
      ;
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0,
      in1);
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
  throw axisFaultException;
    
Member Data Documentation
org.apache.axis.description.OperationDesc [] org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub._operations [static, package]
Definition at line 16 of file VOMSCertificatesSoapBindingStub.java.
Referenced by org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub._initOperationDesc1(), and org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.getCertificates().
java.util.Vector org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.cachedDeserFactories = new java.util.Vector() [private]
Definition at line 14 of file VOMSCertificatesSoapBindingStub.java.
Referenced by org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.createCall(), and org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.VOMSCertificatesSoapBindingStub().
java.util.Vector org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.cachedSerClasses = new java.util.Vector() [private]
Definition at line 11 of file VOMSCertificatesSoapBindingStub.java.
Referenced by org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.createCall(), and org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.VOMSCertificatesSoapBindingStub().
java.util.Vector org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.cachedSerFactories = new java.util.Vector() [private]
Definition at line 13 of file VOMSCertificatesSoapBindingStub.java.
Referenced by org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.createCall(), and org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.VOMSCertificatesSoapBindingStub().
java.util.Vector org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.cachedSerQNames = new java.util.Vector() [private]
Definition at line 12 of file VOMSCertificatesSoapBindingStub.java.
Referenced by org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.createCall(), and org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.VOMSCertificatesSoapBindingStub().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/certificates/VOMSCertificatesSoapBindingStub.java