org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator Class Reference
Public Member Functions
VOMSAttributesServiceLocator ()
VOMSAttributesServiceLocator (org.apache.axis.EngineConfiguration config)
VOMSAttributesServiceLocator (java.lang.String wsdlLoc, javax.xml.namespace.QName sName) throws javax.xml.rpc.ServiceException
java.lang.String getVOMSAttributesAddress ()
java.lang.String getVOMSAttributesWSDDServiceName ()
void setVOMSAttributesWSDDServiceName (java.lang.String name)
org.glite.security.voms.service.attributes.VOMSAttributes getVOMSAttributes () throws javax.xml.rpc.ServiceException
org.glite.security.voms.service.attributes.VOMSAttributes getVOMSAttributes (java.net.URL portAddress) throws javax.xml.rpc.ServiceException
void setVOMSAttributesEndpointAddress (java.lang.String address)
java.rmi.Remote getPort (Class serviceEndpointInterface) throws javax.xml.rpc.ServiceException
java.rmi.Remote getPort (javax.xml.namespace.QName portName, Class serviceEndpointInterface) throws javax.xml.rpc.ServiceException
namespace::QName getServiceName ()
java.util.Iterator getPorts ()
void setEndpointAddress (java.lang.String portName, java.lang.String address) throws javax.xml.rpc.ServiceException
void setEndpointAddress (javax.xml.namespace.QName portName, java.lang.String address) throws javax.xml.rpc.ServiceException
Private Attributes
java.lang.String VOMSAttributes_address = `https://localhost:8443/glite-security-voms-admin-interface/VOMSAttributes`
java.lang.String VOMSAttributesWSDDServiceName = `VOMSAttributes`
java.util.HashSet ports = null
Detailed Description
Definition at line 10 of file VOMSAttributesServiceLocator.java.
Constructor & Destructor Documentation
org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.VOMSAttributesServiceLocator ()
Definition at line 12 of file VOMSAttributesServiceLocator.java.
                                          
    
org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.VOMSAttributesServiceLocator (org.apache.axis.EngineConfiguration config)
Definition at line 16 of file VOMSAttributesServiceLocator.java.
                                                                                 
         
        super(config);
    
org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.VOMSAttributesServiceLocator (java.lang.String wsdlLoc, javax.xml.namespace.QName sName) throws javax.xml.rpc.ServiceException
Definition at line 20 of file VOMSAttributesServiceLocator.java.
                                                                                 
                                                              
        super(wsdlLoc, sName);
    
Member Function Documentation
java.rmi.Remote org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.getPort (Class serviceEndpointInterface) throws javax.xml.rpc.ServiceException
For the given interface, get the stub implementation. If this service has no port for the given interface, then ServiceException is thrown.
Definition at line 73 of file VOMSAttributesServiceLocator.java.
References org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.getVOMSAttributesWSDDServiceName(), and org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.VOMSAttributes_address.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.getPort().
                                                                                 
                              
        try
            if (org.glite.security.voms.service.attributes.VOMSAttributes.class.i
      sAssignableFrom(serviceEndpointInterface))
                org.glite.security.voms.service.attributes.VOMSAttributesSoapBind
      ingStub _stub = new org.glite.security.voms.service.attributes.VOMSAttributesSoap
      BindingStub(new java.net.URL(VOMSAttributes_address), this);
                _stub.setPortName(getVOMSAttributesWSDDServiceName());
                return _stub;
            
        
        catch (java.lang.Throwable t)
            throw new javax.xml.rpc.ServiceException(t);
        
        throw new javax.xml.rpc.ServiceException("There is no stub implementation
       for the interface: " + (serviceEndpointInterface == null ? "null" : serviceEndp
      ointInterface.getName()));
    
java.rmi.Remote org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.getPort (javax.xml.namespace.QName portName, Class serviceEndpointInterface) throws javax.xml.rpc.ServiceException
For the given interface, get the stub implementation. If this service has no port for the given interface, then ServiceException is thrown.
Definition at line 92 of file VOMSAttributesServiceLocator.java.
References org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.getPort(), and org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.getVOMSAttributes().
                                                                                 
                                                                  
        if (portName == null)
            return getPort(serviceEndpointInterface);
        
        java.lang.String inputPortName = portName.getLocalPart();
        if ("VOMSAttributes".equals(inputPortName))
            return getVOMSAttributes();
        
        else
            java.rmi.Remote _stub = getPort(serviceEndpointInterface);
            ((org.apache.axis.client.Stub) _stub).setPortName(portName);
            return _stub;
        
    
java.util.Iterator org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.getPorts ()
Definition at line 113 of file VOMSAttributesServiceLocator.java.
References org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.ports.
                                         
        if (ports == null)
            ports = new java.util.HashSet();
            ports.add(new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.attributes", "VOMSAttributes"));
        
        return ports.iterator();
    
namespace ::QName org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.getServiceName ()
Definition at line 107 of file VOMSAttributesServiceLocator.java.
                                                      
        return new javax.xml.namespace.QName("http://glite.org/wsdl/services/org.
      glite.security.voms.service.attributes", "VOMSAttributesService");
    
org.glite.security.voms.service.attributes.VOMSAttributes org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.getVOMSAttributes (java.net.URL portAddress) throws javax.xml.rpc.ServiceException
Implements org.glite.security.voms.service.attributes.VOMSAttributesService.
Definition at line 53 of file VOMSAttributesServiceLocator.java.
References org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.getVOMSAttributesWSDDServiceName().
                                                                                 
                                                                            
        try
            org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingS
      tub _stub = new org.glite.security.voms.service.attributes.VOMSAttributesSoapBind
      ingStub(portAddress, this);
            _stub.setPortName(getVOMSAttributesWSDDServiceName());
            return _stub;
        
        catch (org.apache.axis.AxisFault e)
            return null;
        
    
org.glite.security.voms.service.attributes.VOMSAttributes org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.getVOMSAttributes () throws javax.xml.rpc.ServiceException
Implements org.glite.security.voms.service.attributes.VOMSAttributesService.
Definition at line 42 of file VOMSAttributesServiceLocator.java.
References org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.VOMSAttributes_address.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.getPort().
                                                                                 
                                                    
       java.net.URL endpoint;
        try
            endpoint = new java.net.URL(VOMSAttributes_address);
        
        catch (java.net.MalformedURLException e)
            throw new javax.xml.rpc.ServiceException(e);
        
        return getVOMSAttributes(endpoint);
    
java.lang.String org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.getVOMSAttributesAddress ()
Implements org.glite.security.voms.service.attributes.VOMSAttributesService.
Definition at line 27 of file VOMSAttributesServiceLocator.java.
References org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.VOMSAttributes_address.
                                                       
        return VOMSAttributes_address;
    
java.lang.String org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.getVOMSAttributesWSDDServiceName ()
Definition at line 34 of file VOMSAttributesServiceLocator.java.
References org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.VOMSAttributesWSDDServiceName.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.getPort(), and org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.getVOMSAttributes().
                                                               
        return VOMSAttributesWSDDServiceName;
    
void org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.setEndpointAddress (java.lang.String portName, java.lang.String address) throws javax.xml.rpc.ServiceException
Set the endpoint address for the specified port name.
Definition at line 124 of file VOMSAttributesServiceLocator.java.
References org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.setVOMSAttributesEndpointAddress().
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.setEndpointAddress().
                                                                                 
                                                   
        
if ("VOMSAttributes".equals(portName))
            setVOMSAttributesEndpointAddress(address);
        
        else
 // Unknown Port Name
            throw new javax.xml.rpc.ServiceException(" Cannot set Endpoint Addres
      s for Unknown Port" + portName);
        
    
void org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.setEndpointAddress (javax.xml.namespace.QName portName, java.lang.String address) throws javax.xml.rpc.ServiceException
Set the endpoint address for the specified port name.
Definition at line 138 of file VOMSAttributesServiceLocator.java.
References org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.setEndpointAddress().
                                                                                 
                                                            
        setEndpointAddress(portName.getLocalPart(), address);
    
void org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.setVOMSAttributesEndpointAddress (java.lang.String address)
Definition at line 64 of file VOMSAttributesServiceLocator.java.
References org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.VOMSAttributes_address.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.setEndpointAddress().
                                                                           
        VOMSAttributes_address = address;
    
void org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.setVOMSAttributesWSDDServiceName (java.lang.String name)
Definition at line 38 of file VOMSAttributesServiceLocator.java.
References org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.VOMSAttributesWSDDServiceName.
                                                                        
        VOMSAttributesWSDDServiceName = name;
    
Member Data Documentation
java.util.HashSet org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.ports = null [private]
Definition at line 111 of file VOMSAttributesServiceLocator.java.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.getPorts().
java.lang.String org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.VOMSAttributes_address = `https://localhost:8443/glite-security-voms-admin-interface/VOMSAttributes` [private]
Definition at line 25 of file VOMSAttributesServiceLocator.java.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.getPort(), org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.getVOMSAttributes(), org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.getVOMSAttributesAddress(), and org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.setVOMSAttributesEndpointAddress().
java.lang.String org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.VOMSAttributesWSDDServiceName = `VOMSAttributes` [private]
Definition at line 32 of file VOMSAttributesServiceLocator.java.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.getVOMSAttributesWSDDServiceName(), and org.glite.security.voms.service.attributes.VOMSAttributesServiceLocator.setVOMSAttributesWSDDServiceName().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/attributes/VOMSAttributesServiceLocator.java