portal.registration.controller.EditUserInfoController Class Reference
Public Member Functions
String showEditUserInfoForm (@RequestParam int userId, RenderRequest request)
void editUserInfo (@ModelAttribute(`userInfo`) UserInfo userInfo, ActionRequest request, ActionResponse response, SessionStatus sessionStatus) throws SystemException
String getDefaultVo (@RequestParam int userId)
String getDefaultFqan (@RequestParam int userId)
UserInfo getUserInfo (@RequestParam int userId)
List< Certificate > getListCert (@RequestParam int userId)
List< Vo > getUserToVoList (@RequestParam int userId)
void uploadComplete (ActionResponse response, SessionStatus sessionStatus)
Private Member Functions
void deactivateUser (int userId, RenderRequest request)
Private Attributes
UserInfoService userInfoService
CertificateService certificateService
UserToVoService userToVoService
Detailed Description
Definition at line 39 of file EditUserInfoController.java.
Member Function Documentation
void portal.registration.controller.EditUserInfoController.deactivateUser (int userId, RenderRequest request) [private]
Definition at line 62 of file EditUserInfoController.java.
References portal.registration.services.UserInfoService.edit(), portal.registration.services.UserInfoService.findById(), portal.registration.domain.UserInfo.getRegistrationComplete(), portal.registration.domain.UserInfo.getUsername(), and portal.registration.domain.UserInfo.setRegistrationComplete().
                                                                       
                UserInfo userInfo = userInfoService.findById(userId);
                if (userInfo.getRegistrationComplete().equals("true"))
                        String username = userInfo.getUsername();
                        long companyId = PortalUtil.getCompanyId(request);
                        User user;
                        try
                                user = UserLocalServiceUtil.getUserByScreenName(c
      ompanyId,
                                                username);
                                UserLocalServiceUtil.deleteRoleUser((long) 10140,
      
                                                user.getUserId());
                                userInfo.setRegistrationComplete("false");
                                userInfoService.edit(userInfo);
                         catch (PortalException e)
                                SessionErrors.add(request, "exception-deactivatio
      n-user");
                                e.printStackTrace();
                         catch (SystemException e)
                                SessionErrors.add(request, "exception-deactivatio
      n-user");
                                e.printStackTrace();
                        
                
        
void portal.registration.controller.EditUserInfoController.editUserInfo (@ModelAttribute(`userInfo`) UserInfo userInfo, ActionRequest request, ActionResponse response, SessionStatus sessionStatus) throws SystemException
Definition at line 95 of file EditUserInfoController.java.
References portal.registration.services.UserInfoService.edit(), portal.registration.services.UserInfoService.findById(), portal.registration.domain.UserInfo.setFirstName(), and portal.registration.utils.MyValidator.validateUpdate().
                                                                            
                ArrayList<String> errors = new ArrayList<String>();
                boolean allOk = true;
                UserInfo check = userInfoService.findById(userInfo.getUserId());
                if (MyValidator.validateUpdate(userInfo, check, errors))
                        try
                                long companyId = PortalUtil.getCompanyId(request)
      ;
                                User user = UserLocalServiceUtil.getUserByScreenN
      ame(companyId,
                                                userInfo.getUsername());
                                user.setFirstName(userInfo.getFirstName());
                                user.setLastName(userInfo.getLastName());
                                UserLocalServiceUtil.updateUser(user);
                         catch (Exception e)
                                errors.add("problem-update-user-liferay");
                                allOk = false;
                        
                        try
                                userInfoService.edit(userInfo);
                         catch (Exception e)
                                errors.add("problem-update-user");
                                allOk = false;
                        
                 else
                        allOk = false;
                
                if (allOk)
                        SessionMessages.add(request, "user-updated-successufully"
      );
                 else
                        errors.add("error-updating-user");
                        for (String error : errors)
                                SessionErrors.add(request, error);
                        
                
                response.setRenderParameter("myaction", "editUserInfoForm");
                response.setRenderParameter("userId",
                                Integer.toString(userInfo.getUserId()));
                sessionStatus.setComplete();
        
String portal.registration.controller.EditUserInfoController.getDefaultFqan (@RequestParam int userId)
Definition at line 151 of file EditUserInfoController.java.
References portal.registration.services.UserToVoService.getDefaultFqan().
                                                               
                return userToVoService.getDefaultFqan(userId);
        
String portal.registration.controller.EditUserInfoController.getDefaultVo (@RequestParam int userId)
Definition at line 146 of file EditUserInfoController.java.
References portal.registration.services.UserToVoService.findDefaultVo().
                                                             
                return userToVoService.findDefaultVo(userId);
        
List<Certificate> portal.registration.controller.EditUserInfoController.getListCert (@RequestParam int userId)
Definition at line 161 of file EditUserInfoController.java.
References portal.registration.services.CertificateService.findById().
                                                                       
                return certificateService.findById(userId);
        
UserInfo portal.registration.controller.EditUserInfoController.getUserInfo (@RequestParam int userId)
Definition at line 156 of file EditUserInfoController.java.
References portal.registration.services.UserInfoService.findById().
                                                              
                return userInfoService.findById(userId);
        
List<Vo> portal.registration.controller.EditUserInfoController.getUserToVoList (@RequestParam int userId)
Definition at line 166 of file EditUserInfoController.java.
References portal.registration.services.UserToVoService.findVoByUserId().
                                                                  
                return userToVoService.findVoByUserId(userId);
        
String portal.registration.controller.EditUserInfoController.showEditUserInfoForm (@RequestParam int userId, RenderRequest request)
Definition at line 51 of file EditUserInfoController.java.
References portal.registration.services.UserToVoService.findById().
                                               
                if (userToVoService.findById(userId).size() == 0)
                        deactivateUser(userId, request);
                        SessionMessages.add(request, "user-deactivate");
                
                return "editUserInfoForm";
        
void portal.registration.controller.EditUserInfoController.uploadComplete (ActionResponse response, SessionStatus sessionStatus)
Definition at line 172 of file EditUserInfoController.java.
                                                     
                response.setRenderParameter("myaction", "userInfos");
                sessionStatus.setComplete();
        
Member Data Documentation
CertificateService portal.registration.controller.EditUserInfoController.certificateService [private]
Definition at line 45 of file EditUserInfoController.java.
UserInfoService portal.registration.controller.EditUserInfoController.userInfoService [private]
Definition at line 42 of file EditUserInfoController.java.
UserToVoService portal.registration.controller.EditUserInfoController.userToVoService [private]
Definition at line 48 of file EditUserInfoController.java.
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/controller/EditUserInfoController.java