org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub Class Reference
Public Member Functions
VOMSAttributesSoapBindingStub () throws org.apache.axis.AxisFault
VOMSAttributesSoapBindingStub (java.net.URL endpointURL, javax.xml.rpc.Service service) throws org.apache.axis.AxisFault
VOMSAttributesSoapBindingStub (javax.xml.rpc.Service service) throws org.apache.axis.AxisFault
void createAttributeClass (java.lang.String in0, java.lang.String in1, boolean in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void createAttributeClass (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void createAttributeClass (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.service.attributes.AttributeClass getAttributeClass (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void saveAttributeClass (org.glite.security.voms.service.attributes.AttributeClass in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteAttributeClass (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteAttributeClass (org.glite.security.voms.service.attributes.AttributeClass in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.service.attributes.AttributeClass[] listAttributeClasses () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.service.attributes.AttributeValue[] listUserAttributes (org.glite.security.voms.User in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void setUserAttribute (org.glite.security.voms.User in0, org.glite.security.voms.service.attributes.AttributeValue in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteUserAttribute (org.glite.security.voms.User in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteUserAttribute (org.glite.security.voms.User in0, org.glite.security.voms.service.attributes.AttributeValue in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void setGroupAttribute (java.lang.String in0, org.glite.security.voms.service.attributes.AttributeValue in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteGroupAttribute (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteGroupAttribute (java.lang.String in0, org.glite.security.voms.service.attributes.AttributeValue in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.service.attributes.AttributeValue[] listGroupAttributes (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void setRoleAttribute (java.lang.String in0, java.lang.String in1, org.glite.security.voms.service.attributes.AttributeValue in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteRoleAttribute (java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteRoleAttribute (java.lang.String in0, java.lang.String in1, org.glite.security.voms.service.attributes.AttributeValue in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.service.attributes.AttributeValue[] listRoleAttributes (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Protected Member Functions
org.apache.axis.client.Call createCall () throws java.rmi.RemoteException
Static Package Functions
[static initializer]
Static Package Attributes
static org.apache.axis.description.OperationDesc[] _operations
Static Private Member Functions
static void _initOperationDesc1 ()
static void _initOperationDesc2 ()
Private Attributes
java.util.Vector cachedSerClasses = new java.util.Vector()
java.util.Vector cachedSerQNames = new java.util.Vector()
java.util.Vector cachedSerFactories = new java.util.Vector()
java.util.Vector cachedDeserFactories = new java.util.Vector()
Detailed Description
Definition at line 10 of file VOMSAttributesSoapBindingStub.java.
Constructor & Destructor Documentation
org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.VOMSAttributesSoapBindingStub () throws org.apache.axis.AxisFault
Definition at line 374 of file VOMSAttributesSoapBindingStub.java.
                                                                            
         this(null);
    
org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.VOMSAttributesSoapBindingStub (java.net.URL endpointURL, javax.xml.rpc.Service service) throws org.apache.axis.AxisFault
Definition at line 378 of file VOMSAttributesSoapBindingStub.java.
                                                                                 
                                                        
         this(service);
         super.cachedEndpoint = endpointURL;
    
org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.VOMSAttributesSoapBindingStub (javax.xml.rpc.Service service) throws org.apache.axis.AxisFault
Definition at line 383 of file VOMSAttributesSoapBindingStub.java.
References org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.cachedDeserFactories, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.cachedSerClasses, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.cachedSerFactories, and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.cachedSerQNames.
                                                                                 
                              
        if (service == null)
            super.service = new org.apache.axis.client.Service();
         else
            super.service = service;
        
        ((org.apache.axis.client.Service)super.service).setTypeMappingVersion("1.
      2");
            java.lang.Class cls;
            javax.xml.namespace.QName qName;
            javax.xml.namespace.QName qName2;
            java.lang.Class beansf = org.apache.axis.encoding.ser.BeanSerializerF
      actory.class;
            java.lang.Class beandf = org.apache.axis.encoding.ser.BeanDeserialize
      rFactory.class;
            java.lang.Class enumsf = org.apache.axis.encoding.ser.EnumSerializerF
      actory.class;
            java.lang.Class enumdf = org.apache.axis.encoding.ser.EnumDeserialize
      rFactory.class;
            java.lang.Class arraysf = org.apache.axis.encoding.ser.ArraySerialize
      rFactory.class;
            java.lang.Class arraydf = org.apache.axis.encoding.ser.ArrayDeseriali
      zerFactory.class;
            java.lang.Class simplesf = org.apache.axis.encoding.ser.SimpleSeriali
      zerFactory.class;
            java.lang.Class simpledf = org.apache.axis.encoding.ser.SimpleDeseria
      lizerFactory.class;
            java.lang.Class simplelistsf = org.apache.axis.encoding.ser.SimpleLis
      tSerializerFactory.class;
            java.lang.Class simplelistdf = org.apache.axis.encoding.ser.SimpleLis
      tDeserializerFactory.class;
            qName = new javax.xml.namespace.QName("http://glite.org/wsdl/services
      /org.glite.security.voms.service.attributes", "ArrayOfAttributeClass");
            cachedSerQNames.add(qName);
            cls = org.glite.security.voms.service.attributes.AttributeClass[].cla
      ss;
            cachedSerClasses.add(cls);
            qName = new javax.xml.namespace.QName("http://glite.org/wsdl/services
      /org.glite.security.voms.service.attributes", "AttributeClass");
            qName2 = null;
            cachedSerFactories.add(new org.apache.axis.encoding.ser.ArraySerializ
      erFactory(qName, qName2));
            cachedDeserFactories.add(new org.apache.axis.encoding.ser.ArrayDeseri
      alizerFactory());
            qName = new javax.xml.namespace.QName("http://glite.org/wsdl/services
      /org.glite.security.voms.service.attributes", "ArrayOfAttributeValue");
            cachedSerQNames.add(qName);
            cls = org.glite.security.voms.service.attributes.AttributeValue[].cla
      ss;
            cachedSerClasses.add(cls);
            qName = new javax.xml.namespace.QName("http://glite.org/wsdl/services
      /org.glite.security.voms.service.attributes", "AttributeValue");
            qName2 = null;
            cachedSerFactories.add(new org.apache.axis.encoding.ser.ArraySerializ
      erFactory(qName, qName2));
            cachedDeserFactories.add(new org.apache.axis.encoding.ser.ArrayDeseri
      alizerFactory());
            qName = new javax.xml.namespace.QName("http://glite.org/wsdl/services
      /org.glite.security.voms.service.attributes", "AttributeClass");
            cachedSerQNames.add(qName);
            cls = org.glite.security.voms.service.attributes.AttributeClass.class
      ;
            cachedSerClasses.add(cls);
            cachedSerFactories.add(beansf);
            cachedDeserFactories.add(beandf);
            qName = new javax.xml.namespace.QName("http://glite.org/wsdl/services
      /org.glite.security.voms.service.attributes", "AttributeValue");
            cachedSerQNames.add(qName);
            cls = org.glite.security.voms.service.attributes.AttributeValue.class
      ;
            cachedSerClasses.add(cls);
            cachedSerFactories.add(beansf);
            cachedDeserFactories.add(beandf);
            qName = new javax.xml.namespace.QName("http://glite.org/wsdl/services
      /org.glite.security.voms", "User");
            cachedSerQNames.add(qName);
            cls = org.glite.security.voms.User.class;
            cachedSerClasses.add(cls);
            cachedSerFactories.add(beansf);
            cachedDeserFactories.add(beandf);
            qName = new javax.xml.namespace.QName("http://glite.org/wsdl/services
      /org.glite.security.voms", "VOMSException");
            cachedSerQNames.add(qName);
            cls = org.glite.security.voms.VOMSException.class;
            cachedSerClasses.add(cls);
            cachedSerFactories.add(beansf);
            cachedDeserFactories.add(beandf);
    
Member Function Documentation
org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.[static initializer] () [static, package]
static void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub._initOperationDesc1 () [static, private]
Definition at line 24 of file VOMSAttributesSoapBindingStub.java.
References org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub._operations.
                                             
        org.apache.axis.description.OperationDesc oper;
        org.apache.axis.description.ParameterDesc param;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("createAttributeClass");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in1"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in2"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://www.w3.org/2001/XMLSchema", "boolean"), boolean.class,
      false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.attributes", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[0] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("createAttributeClass");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in1"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.attributes", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[1] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("createAttributeClass");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.attributes", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[2] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("getAttributeClass");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(new javax.xml.namespace.QName("http://glite.org/wsdl/s
      ervices/org.glite.security.voms.service.attributes", "AttributeClass"));
        oper.setReturnClass(org.glite.security.voms.service.attributes.AttributeC
      lass.class);
        oper.setReturnQName(new javax.xml.namespace.QName("", "getAttributeClassR
      eturn"));
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.attributes", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[3] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("saveAttributeClass");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://glite.org/wsdl/services/org.glite.security.voms.service
      .attributes", "AttributeClass"), org.glite.security.voms.service.attributes.Attri
      buteClass.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.attributes", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[4] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("deleteAttributeClass");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.attributes", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[5] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("deleteAttributeClass");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://glite.org/wsdl/services/org.glite.security.voms.service
      .attributes", "AttributeClass"), org.glite.security.voms.service.attributes.Attri
      buteClass.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.attributes", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[6] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("listAttributeClasses");
        oper.setReturnType(new javax.xml.namespace.QName("http://glite.org/wsdl/s
      ervices/org.glite.security.voms.service.attributes", "ArrayOfAttributeClass"));
        oper.setReturnClass(org.glite.security.voms.service.attributes.AttributeC
      lass[].class);
        oper.setReturnQName(new javax.xml.namespace.QName("", "listAttributeClass
      esReturn"));
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.attributes", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[7] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("listUserAttributes");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://glite.org/wsdl/services/org.glite.security.voms", "User
      "), org.glite.security.voms.User.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(new javax.xml.namespace.QName("http://glite.org/wsdl/s
      ervices/org.glite.security.voms.service.attributes", "ArrayOfAttributeValue"));
        oper.setReturnClass(org.glite.security.voms.service.attributes.AttributeV
      alue[].class);
        oper.setReturnQName(new javax.xml.namespace.QName("", "listUserAttributes
      Return"));
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.attributes", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[8] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("setUserAttribute");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://glite.org/wsdl/services/org.glite.security.voms", "User
      "), org.glite.security.voms.User.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in1"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://glite.org/wsdl/services/org.glite.security.voms.service
      .attributes", "AttributeValue"), org.glite.security.voms.service.attributes.Attri
      buteValue.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.attributes", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[9] = oper;
    
static void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub._initOperationDesc2 () [static, private]
Definition at line 191 of file VOMSAttributesSoapBindingStub.java.
References org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub._operations.
                                             
        org.apache.axis.description.OperationDesc oper;
        org.apache.axis.description.ParameterDesc param;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("deleteUserAttribute");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://glite.org/wsdl/services/org.glite.security.voms", "User
      "), org.glite.security.voms.User.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in1"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.attributes", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[10] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("deleteUserAttribute");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://glite.org/wsdl/services/org.glite.security.voms", "User
      "), org.glite.security.voms.User.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in1"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://glite.org/wsdl/services/org.glite.security.voms.service
      .attributes", "AttributeValue"), org.glite.security.voms.service.attributes.Attri
      buteValue.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.attributes", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[11] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("setGroupAttribute");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in1"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://glite.org/wsdl/services/org.glite.security.voms.service
      .attributes", "AttributeValue"), org.glite.security.voms.service.attributes.Attri
      buteValue.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.attributes", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[12] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("deleteGroupAttribute");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in1"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.attributes", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[13] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("deleteGroupAttribute");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in1"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://glite.org/wsdl/services/org.glite.security.voms.service
      .attributes", "AttributeValue"), org.glite.security.voms.service.attributes.Attri
      buteValue.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.attributes", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[14] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("listGroupAttributes");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(new javax.xml.namespace.QName("http://glite.org/wsdl/s
      ervices/org.glite.security.voms.service.attributes", "ArrayOfAttributeValue"));
        oper.setReturnClass(org.glite.security.voms.service.attributes.AttributeV
      alue[].class);
        oper.setReturnQName(new javax.xml.namespace.QName("", "listGroupAttribute
      sReturn"));
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.attributes", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[15] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("setRoleAttribute");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in1"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in2"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://glite.org/wsdl/services/org.glite.security.voms.service
      .attributes", "AttributeValue"), org.glite.security.voms.service.attributes.Attri
      buteValue.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.attributes", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[16] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("deleteRoleAttribute");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in1"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in2"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.attributes", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[17] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("deleteRoleAttribute");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in1"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in2"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://glite.org/wsdl/services/org.glite.security.voms.service
      .attributes", "AttributeValue"), org.glite.security.voms.service.attributes.Attri
      buteValue.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.attributes", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[18] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("listRoleAttributes");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in1"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(new javax.xml.namespace.QName("http://glite.org/wsdl/s
      ervices/org.glite.security.voms.service.attributes", "ArrayOfAttributeValue"));
        oper.setReturnClass(org.glite.security.voms.service.attributes.AttributeV
      alue[].class);
        oper.setReturnQName(new javax.xml.namespace.QName("", "listRoleAttributes
      Return"));
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.attributes", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[19] = oper;
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.createAttributeClass (java.lang.String in0, java.lang.String in1, boolean in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 516 of file VOMSAttributesSoapBindingStub.java.
References org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub._operations, and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.createCall().
                                                                                 
                                                                                       
         
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[0]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.attributes", "createAttributeClass"))
      ;
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0,
      in1, new java.lang.Boolean(in2));
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.createAttributeClass (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 548 of file VOMSAttributesSoapBindingStub.java.
                                                                                 
                                                                             
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[1]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.attributes", "createAttributeClass"))
      ;
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0,
      in1);
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.createAttributeClass (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 580 of file VOMSAttributesSoapBindingStub.java.
                                                                                 
                                                       
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[2]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.attributes", "createAttributeClass"))
      ;
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0)
      ;
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
org.apache.axis.client.Call org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.createCall () throws java.rmi.RemoteException [protected]
Definition at line 451 of file VOMSAttributesSoapBindingStub.java.
References org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.cachedDeserFactories, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.cachedSerClasses, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.cachedSerFactories, and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.cachedSerQNames.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.createAttributeClass().
                                                                                 
            
        try
            org.apache.axis.client.Call _call = super._createCall();
            if (super.maintainSessionSet)
                _call.setMaintainSession(super.maintainSession);
            
            if (super.cachedUsername != null)
                _call.setUsername(super.cachedUsername);
            
            if (super.cachedPassword != null)
                _call.setPassword(super.cachedPassword);
            
            if (super.cachedEndpoint != null)
                _call.setTargetEndpointAddress(super.cachedEndpoint);
            
            if (super.cachedTimeout != null)
                _call.setTimeout(super.cachedTimeout);
            
            if (super.cachedPortName != null)
                _call.setPortName(super.cachedPortName);
            
            java.util.Enumeration keys = super.cachedProperties.keys();
            while (keys.hasMoreElements())
                java.lang.String key = (java.lang.String) keys.nextElement();
                _call.setProperty(key, super.cachedProperties.get(key));
            
            // All the type mapping information is registered
            // when the first call is made.
            // The type mapping information is actually registered in
            // the TypeMappingRegistry of the service, which
            // is the reason why registration is only needed for the first call.
            synchronized (this)
                if (firstCall())
                    // must set encoding style before registering serializers
                    _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP1
      1_CONSTANTS);
                    _call.setEncodingStyle(org.apache.axis.Constants.URI_SOAP11_E
      NC);
                    for (int i = 0; i < cachedSerFactories.size(); ++i)
                        java.lang.Class cls = (java.lang.Class) cachedSerClasses.
      get(i);
                        javax.xml.namespace.QName qName =
                                (javax.xml.namespace.QName) cachedSerQNames.get(i
      );
                        java.lang.Object x = cachedSerFactories.get(i);
                        if (x instanceof Class)
                            java.lang.Class sf = (java.lang.Class)
                                 cachedSerFactories.get(i);
                            java.lang.Class df = (java.lang.Class)
                                 cachedDeserFactories.get(i);
                            _call.registerTypeMapping(cls, qName, sf, df, false);
      
                        
                        else if (x instanceof javax.xml.rpc.encoding.SerializerFa
      ctory)
                            org.apache.axis.encoding.SerializerFactory sf = (org.
      apache.axis.encoding.SerializerFactory)
                                 cachedSerFactories.get(i);
                            org.apache.axis.encoding.DeserializerFactory df = (or
      g.apache.axis.encoding.DeserializerFactory)
                                 cachedDeserFactories.get(i);
                            _call.registerTypeMapping(cls, qName, sf, df, false);
      
                        
                    
                
            
            return _call;
        
        catch (java.lang.Throwable _t)
            throw new org.apache.axis.AxisFault("Failure trying to get the Call o
      bject", _t);
        
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.deleteAttributeClass (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 683 of file VOMSAttributesSoapBindingStub.java.
                                                                                 
                                                       
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[5]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.attributes", "deleteAttributeClass"))
      ;
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0)
      ;
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.deleteAttributeClass (org.glite.security.voms.service.attributes.AttributeClass in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 715 of file VOMSAttributesSoapBindingStub.java.
                                                                                 
                                                                                       
               
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[6]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.attributes", "deleteAttributeClass"))
      ;
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0)
      ;
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.deleteGroupAttribute (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 953 of file VOMSAttributesSoapBindingStub.java.
                                                                                 
                                                                             
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[13]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.attributes", "deleteGroupAttribute"))
      ;
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0,
      in1);
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.deleteGroupAttribute (java.lang.String in0, org.glite.security.voms.service.attributes.AttributeValue in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 985 of file VOMSAttributesSoapBindingStub.java.
                                                                                 
                                                                                       
                                     
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[14]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.attributes", "deleteGroupAttribute"))
      ;
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0,
      in1);
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.deleteRoleAttribute (java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 1088 of file VOMSAttributesSoapBindingStub.java.
                                                                                 
                                                                                       
                 
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[17]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.attributes", "deleteRoleAttribute"));
      
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0,
      in1, in2);
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.deleteRoleAttribute (java.lang.String in0, java.lang.String in1, org.glite.security.voms.service.attributes.AttributeValue in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 1120 of file VOMSAttributesSoapBindingStub.java.
                                                                                 
                                                                                       
                                                          
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[18]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.attributes", "deleteRoleAttribute"));
      
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0,
      in1, in2);
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.deleteUserAttribute (org.glite.security.voms.User in0, org.glite.security.voms.service.attributes.AttributeValue in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 889 of file VOMSAttributesSoapBindingStub.java.
                                                                                 
                                                                                       
                                                
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[11]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.attributes", "deleteUserAttribute"));
      
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0,
      in1);
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.deleteUserAttribute (org.glite.security.voms.User in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 857 of file VOMSAttributesSoapBindingStub.java.
                                                                                 
                                                                                       
       
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[10]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.attributes", "deleteUserAttribute"));
      
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0,
      in1);
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
org.glite.security.voms.service.attributes.AttributeClass org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.getAttributeClass (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 612 of file VOMSAttributesSoapBindingStub.java.
                                                                                 
                                                                                       
                        
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[3]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.attributes", "getAttributeClass"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0)
      ;
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        else
            extractAttachments(_call);
            try
                return (org.glite.security.voms.service.attributes.AttributeClass
      ) _resp;
             catch (java.lang.Exception _exception)
                return (org.glite.security.voms.service.attributes.AttributeClass
      ) org.apache.axis.utils.JavaUtils.convert(_resp, org.glite.security.voms.service.
      attributes.AttributeClass.class);
            
        
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
org.glite.security.voms.service.attributes.AttributeClass [] org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.listAttributeClasses () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 747 of file VOMSAttributesSoapBindingStub.java.
                                                                                 
                                                                                       
         
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[7]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.attributes", "listAttributeClasses"))
      ;
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[]);
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        else
            extractAttachments(_call);
            try
                return (org.glite.security.voms.service.attributes.AttributeClass
      []) _resp;
             catch (java.lang.Exception _exception)
                return (org.glite.security.voms.service.attributes.AttributeClass
      []) org.apache.axis.utils.JavaUtils.convert(_resp, org.glite.security.voms.servic
      e.attributes.AttributeClass[].class);
            
        
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
org.glite.security.voms.service.attributes.AttributeValue [] org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.listGroupAttributes (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 1017 of file VOMSAttributesSoapBindingStub.java.
                                                                                 
                                                                                       
                            
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[15]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.attributes", "listGroupAttributes"));
      
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0)
      ;
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        else
            extractAttachments(_call);
            try
                return (org.glite.security.voms.service.attributes.AttributeValue
      []) _resp;
             catch (java.lang.Exception _exception)
                return (org.glite.security.voms.service.attributes.AttributeValue
      []) org.apache.axis.utils.JavaUtils.convert(_resp, org.glite.security.voms.servic
      e.attributes.AttributeValue[].class);
            
        
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
org.glite.security.voms.service.attributes.AttributeValue [] org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.listRoleAttributes (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 1152 of file VOMSAttributesSoapBindingStub.java.
                                                                                 
                                                                                       
                                                 
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[19]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.attributes", "listRoleAttributes"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0,
      in1);
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        else
            extractAttachments(_call);
            try
                return (org.glite.security.voms.service.attributes.AttributeValue
      []) _resp;
             catch (java.lang.Exception _exception)
                return (org.glite.security.voms.service.attributes.AttributeValue
      []) org.apache.axis.utils.JavaUtils.convert(_resp, org.glite.security.voms.servic
      e.attributes.AttributeValue[].class);
            
        
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
org.glite.security.voms.service.attributes.AttributeValue [] org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.listUserAttributes (org.glite.security.voms.User in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 786 of file VOMSAttributesSoapBindingStub.java.
                                                                                 
                                                                                       
                                       
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[8]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.attributes", "listUserAttributes"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0)
      ;
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        else
            extractAttachments(_call);
            try
                return (org.glite.security.voms.service.attributes.AttributeValue
      []) _resp;
             catch (java.lang.Exception _exception)
                return (org.glite.security.voms.service.attributes.AttributeValue
      []) org.apache.axis.utils.JavaUtils.convert(_resp, org.glite.security.voms.servic
      e.attributes.AttributeValue[].class);
            
        
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.saveAttributeClass (org.glite.security.voms.service.attributes.AttributeClass in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 651 of file VOMSAttributesSoapBindingStub.java.
                                                                                 
                                                                                       
             
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[4]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.attributes", "saveAttributeClass"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0)
      ;
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.setGroupAttribute (java.lang.String in0, org.glite.security.voms.service.attributes.AttributeValue in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 921 of file VOMSAttributesSoapBindingStub.java.
                                                                                 
                                                                                       
                                  
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[12]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.attributes", "setGroupAttribute"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0,
      in1);
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.setRoleAttribute (java.lang.String in0, java.lang.String in1, org.glite.security.voms.service.attributes.AttributeValue in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 1056 of file VOMSAttributesSoapBindingStub.java.
                                                                                 
                                                                                       
                                                       
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[16]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.attributes", "setRoleAttribute"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0,
      in1, in2);
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.setUserAttribute (org.glite.security.voms.User in0, org.glite.security.voms.service.attributes.AttributeValue in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.attributes.VOMSAttributes.
Definition at line 825 of file VOMSAttributesSoapBindingStub.java.
                                                                                 
                                                                                       
                                             
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[9]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.attributes", "setUserAttribute"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0,
      in1);
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
Member Data Documentation
org.apache.axis.description.OperationDesc [] org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub._operations [static, package]
Definition at line 16 of file VOMSAttributesSoapBindingStub.java.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub._initOperationDesc1(), org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub._initOperationDesc2(), and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.createAttributeClass().
java.util.Vector org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.cachedDeserFactories = new java.util.Vector() [private]
Definition at line 14 of file VOMSAttributesSoapBindingStub.java.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.createCall(), and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.VOMSAttributesSoapBindingStub().
java.util.Vector org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.cachedSerClasses = new java.util.Vector() [private]
Definition at line 11 of file VOMSAttributesSoapBindingStub.java.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.createCall(), and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.VOMSAttributesSoapBindingStub().
java.util.Vector org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.cachedSerFactories = new java.util.Vector() [private]
Definition at line 13 of file VOMSAttributesSoapBindingStub.java.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.createCall(), and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.VOMSAttributesSoapBindingStub().
java.util.Vector org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.cachedSerQNames = new java.util.Vector() [private]
Definition at line 12 of file VOMSAttributesSoapBindingStub.java.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.createCall(), and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.VOMSAttributesSoapBindingStub().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/attributes/VOMSAttributesSoapBindingStub.java