portal.registration.utils.VOMSAdminCallOut Class Reference
Static Public Member Functions
static String[] getUserFQANs (String subject, String issuer, String voHost) throws MalformedURLException, ServiceException, 			VOMSException, RemoteException
Static Private Attributes
static final Logger log = Logger.getLogger(VOMSAdminCallOut.class)
Detailed Description
Definition at line 14 of file VOMSAdminCallOut.java.
Member Function Documentation
static String [] portal.registration.utils.VOMSAdminCallOut.getUserFQANs (String subject, String issuer, String voHost) throws MalformedURLException, ServiceException, 			VOMSException, RemoteException [static]
Definition at line 18 of file VOMSAdminCallOut.java.
References org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getVOMSAdmin(), org.glite.security.voms.service.admin.VOMSAdmin.listRoles(), and portal.registration.utils.VOMSAdminCallOut.log.
Referenced by portal.registration.utils.VOMSTest.main().
                                                       
                log.info("Contatto VOMSAdmin con URL = https://" + voHost
                                + "/services/VOMSAdmin");
                String url = "https://" + voHost + "/services/VOMSAdmin";
                log.info("Trovo VOMSAdmin Service");
                VOMSAdminServiceLocator locator = new VOMSAdminServiceLocator();
                log.info("Prendo VOMSAdmin Service");
                VOMSAdmin adminService = locator.getVOMSAdmin(new URL(url));
                log.info("Uso VOMSAdmin Service con subject = " + subject
                                + " e issuer = " + issuer);
                String[] roles = adminService.listRoles(subject, issuer);
                if (roles == null)
                        log.info("nessun risultato con subject = " + subject
                                        + " e issuer = " + issuer);
                        log.info("Contatto VOMSAdmin con URL = https://" + voHost
      
                                        + "/services/VOMSAdmin");
                        return null;
                
                return roles;
        
Member Data Documentation
final Logger portal.registration.utils.VOMSAdminCallOut.log = Logger.getLogger(VOMSAdminCallOut.class) [static, private]
Definition at line 16 of file VOMSAdminCallOut.java.
Referenced by portal.registration.utils.VOMSAdminCallOut.getUserFQANs().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/utils/VOMSAdminCallOut.java