org.glite.security.voms.service.admin.VOMSAdminServiceLocator Class Reference
Public Member Functions
VOMSAdminServiceLocator ()
VOMSAdminServiceLocator (org.apache.axis.EngineConfiguration config)
VOMSAdminServiceLocator (java.lang.String wsdlLoc, javax.xml.namespace.QName sName) throws javax.xml.rpc.ServiceException
java.lang.String getVOMSAdminAddress ()
java.lang.String getVOMSAdminWSDDServiceName ()
void setVOMSAdminWSDDServiceName (java.lang.String name)
org.glite.security.voms.service.admin.VOMSAdmin getVOMSAdmin () throws javax.xml.rpc.ServiceException
org.glite.security.voms.service.admin.VOMSAdmin getVOMSAdmin (java.net.URL portAddress) throws javax.xml.rpc.ServiceException
void setVOMSAdminEndpointAddress (java.lang.String address)
java.rmi.Remote getPort (Class serviceEndpointInterface) throws javax.xml.rpc.ServiceException
java.rmi.Remote getPort (javax.xml.namespace.QName portName, Class serviceEndpointInterface) throws javax.xml.rpc.ServiceException
namespace::QName getServiceName ()
java.util.Iterator getPorts ()
void setEndpointAddress (java.lang.String portName, java.lang.String address) throws javax.xml.rpc.ServiceException
void setEndpointAddress (javax.xml.namespace.QName portName, java.lang.String address) throws javax.xml.rpc.ServiceException
Private Attributes
java.lang.String VOMSAdmin_address = `https://localhost:8443/glite-security-voms-admin-interface/VOMSAdmin`
java.lang.String VOMSAdminWSDDServiceName = `VOMSAdmin`
java.util.HashSet ports = null
Detailed Description
Definition at line 10 of file VOMSAdminServiceLocator.java.
Constructor & Destructor Documentation
org.glite.security.voms.service.admin.VOMSAdminServiceLocator.VOMSAdminServiceLocator ()
Definition at line 12 of file VOMSAdminServiceLocator.java.
                                     
    
org.glite.security.voms.service.admin.VOMSAdminServiceLocator.VOMSAdminServiceLocator (org.apache.axis.EngineConfiguration config)
Definition at line 16 of file VOMSAdminServiceLocator.java.
                                                                               
        super(config);
    
org.glite.security.voms.service.admin.VOMSAdminServiceLocator.VOMSAdminServiceLocator (java.lang.String wsdlLoc, javax.xml.namespace.QName sName) throws javax.xml.rpc.ServiceException
Definition at line 20 of file VOMSAdminServiceLocator.java.
                                                                                 
                                                         
        super(wsdlLoc, sName);
    
Member Function Documentation
java.rmi.Remote org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getPort (Class serviceEndpointInterface) throws javax.xml.rpc.ServiceException
For the given interface, get the stub implementation. If this service has no port for the given interface, then ServiceException is thrown.
Definition at line 73 of file VOMSAdminServiceLocator.java.
References org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getVOMSAdminWSDDServiceName(), and org.glite.security.voms.service.admin.VOMSAdminServiceLocator.VOMSAdmin_address.
Referenced by org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getPort().
                                                                                 
                              
        try
            if (org.glite.security.voms.service.admin.VOMSAdmin.class.isAssignabl
      eFrom(serviceEndpointInterface))
                org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub _s
      tub = new org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub(new java
      .net.URL(VOMSAdmin_address), this);
                _stub.setPortName(getVOMSAdminWSDDServiceName());
                return _stub;
            
        
        catch (java.lang.Throwable t)
            throw new javax.xml.rpc.ServiceException(t);
        
        throw new javax.xml.rpc.ServiceException("There is no stub implementation
       for the interface: " + (serviceEndpointInterface == null ? "null" : serviceEndp
      ointInterface.getName()));
    
java.rmi.Remote org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getPort (javax.xml.namespace.QName portName, Class serviceEndpointInterface) throws javax.xml.rpc.ServiceException
For the given interface, get the stub implementation. If this service has no port for the given interface, then ServiceException is thrown.
Definition at line 92 of file VOMSAdminServiceLocator.java.
References org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getPort(), and org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getVOMSAdmin().
                                                                                 
                                                                  
        if (portName == null)
            return getPort(serviceEndpointInterface);
        
        java.lang.String inputPortName = portName.getLocalPart();
        if ("VOMSAdmin".equals(inputPortName))
            return getVOMSAdmin();
        
        else
            java.rmi.Remote _stub = getPort(serviceEndpointInterface);
            ((org.apache.axis.client.Stub) _stub).setPortName(portName);
            return _stub;
        
    
java.util.Iterator org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getPorts ()
Definition at line 113 of file VOMSAdminServiceLocator.java.
References org.glite.security.voms.service.admin.VOMSAdminServiceLocator.ports.
                                         
        if (ports == null)
            ports = new java.util.HashSet();
            ports.add(new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.admin", "VOMSAdmin"));
        
        return ports.iterator();
    
namespace ::QName org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getServiceName ()
Definition at line 107 of file VOMSAdminServiceLocator.java.
                                                      
        return new javax.xml.namespace.QName("http://glite.org/wsdl/services/org.
      glite.security.voms.service.admin", "VOMSAdminService");
    
org.glite.security.voms.service.admin.VOMSAdmin org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getVOMSAdmin (java.net.URL portAddress) throws javax.xml.rpc.ServiceException
Implements org.glite.security.voms.service.admin.VOMSAdminService.
Definition at line 53 of file VOMSAdminServiceLocator.java.
References org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getVOMSAdminWSDDServiceName().
                                                                                 
                                                             
        try
            org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub _stub
      = new org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub(portAddress,
       this);
            _stub.setPortName(getVOMSAdminWSDDServiceName());
            return _stub;
        
        catch (org.apache.axis.AxisFault e)
            return null;
        
    
org.glite.security.voms.service.admin.VOMSAdmin org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getVOMSAdmin () throws javax.xml.rpc.ServiceException
Implements org.glite.security.voms.service.admin.VOMSAdminService.
Definition at line 42 of file VOMSAdminServiceLocator.java.
References org.glite.security.voms.service.admin.VOMSAdminServiceLocator.VOMSAdmin_address.
Referenced by org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getPort(), and portal.registration.utils.VOMSAdminCallOut.getUserFQANs().
                                                                                 
                                     
       java.net.URL endpoint;
        try
            endpoint = new java.net.URL(VOMSAdmin_address);
        
        catch (java.net.MalformedURLException e)
            throw new javax.xml.rpc.ServiceException(e);
        
        return getVOMSAdmin(endpoint);
    
java.lang.String org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getVOMSAdminAddress ()
Implements org.glite.security.voms.service.admin.VOMSAdminService.
Definition at line 27 of file VOMSAdminServiceLocator.java.
References org.glite.security.voms.service.admin.VOMSAdminServiceLocator.VOMSAdmin_address.
                                                  
        return VOMSAdmin_address;
    
java.lang.String org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getVOMSAdminWSDDServiceName ()
Definition at line 34 of file VOMSAdminServiceLocator.java.
References org.glite.security.voms.service.admin.VOMSAdminServiceLocator.VOMSAdminWSDDServiceName.
Referenced by org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getPort(), and org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getVOMSAdmin().
                                                          
        return VOMSAdminWSDDServiceName;
    
void org.glite.security.voms.service.admin.VOMSAdminServiceLocator.setEndpointAddress (java.lang.String portName, java.lang.String address) throws javax.xml.rpc.ServiceException
Set the endpoint address for the specified port name.
Definition at line 124 of file VOMSAdminServiceLocator.java.
References org.glite.security.voms.service.admin.VOMSAdminServiceLocator.setVOMSAdminEndpointAddress().
Referenced by org.glite.security.voms.service.admin.VOMSAdminServiceLocator.setEndpointAddress().
                                                                                 
                                                   
        
if ("VOMSAdmin".equals(portName))
            setVOMSAdminEndpointAddress(address);
        
        else
 // Unknown Port Name
            throw new javax.xml.rpc.ServiceException(" Cannot set Endpoint Addres
      s for Unknown Port" + portName);
        
    
void org.glite.security.voms.service.admin.VOMSAdminServiceLocator.setEndpointAddress (javax.xml.namespace.QName portName, java.lang.String address) throws javax.xml.rpc.ServiceException
Set the endpoint address for the specified port name.
Definition at line 138 of file VOMSAdminServiceLocator.java.
References org.glite.security.voms.service.admin.VOMSAdminServiceLocator.setEndpointAddress().
                                                                                 
                                                            
        setEndpointAddress(portName.getLocalPart(), address);
    
void org.glite.security.voms.service.admin.VOMSAdminServiceLocator.setVOMSAdminEndpointAddress (java.lang.String address)
Definition at line 64 of file VOMSAdminServiceLocator.java.
References org.glite.security.voms.service.admin.VOMSAdminServiceLocator.VOMSAdmin_address.
Referenced by org.glite.security.voms.service.admin.VOMSAdminServiceLocator.setEndpointAddress().
                                                                      
        VOMSAdmin_address = address;
    
void org.glite.security.voms.service.admin.VOMSAdminServiceLocator.setVOMSAdminWSDDServiceName (java.lang.String name)
Definition at line 38 of file VOMSAdminServiceLocator.java.
References org.glite.security.voms.service.admin.VOMSAdminServiceLocator.VOMSAdminWSDDServiceName.
                                                                   
        VOMSAdminWSDDServiceName = name;
    
Member Data Documentation
java.util.HashSet org.glite.security.voms.service.admin.VOMSAdminServiceLocator.ports = null [private]
Definition at line 111 of file VOMSAdminServiceLocator.java.
Referenced by org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getPorts().
java.lang.String org.glite.security.voms.service.admin.VOMSAdminServiceLocator.VOMSAdmin_address = `https://localhost:8443/glite-security-voms-admin-interface/VOMSAdmin` [private]
Definition at line 25 of file VOMSAdminServiceLocator.java.
Referenced by org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getPort(), org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getVOMSAdmin(), org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getVOMSAdminAddress(), and org.glite.security.voms.service.admin.VOMSAdminServiceLocator.setVOMSAdminEndpointAddress().
java.lang.String org.glite.security.voms.service.admin.VOMSAdminServiceLocator.VOMSAdminWSDDServiceName = `VOMSAdmin` [private]
Definition at line 32 of file VOMSAdminServiceLocator.java.
Referenced by org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getVOMSAdminWSDDServiceName(), and org.glite.security.voms.service.admin.VOMSAdminServiceLocator.setVOMSAdminWSDDServiceName().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/admin/VOMSAdminServiceLocator.java