org.glite.security.voms.service.attributes.AttributeValue Class Reference
Public Member Functions
AttributeValue ()
AttributeValue (org.glite.security.voms.service.attributes.AttributeClass attributeClass, java.lang.String context, java.lang.String value)
org.glite.security.voms.service.attributes.AttributeClass getAttributeClass ()
void setAttributeClass (org.glite.security.voms.service.attributes.AttributeClass attributeClass)
java.lang.String getContext ()
void setContext (java.lang.String context)
java.lang.String getValue ()
void setValue (java.lang.String value)
synchronized boolean equals (java.lang.Object obj)
synchronized int hashCode ()
Private Attributes
org.glite.security.voms.service.attributes.AttributeClass attributeClass
java.lang.String context
java.lang.String value
java.lang.Object __equalsCalc = null
boolean __hashCodeCalc = false
Detailed Description
Definition at line 10 of file AttributeValue.java.
Constructor & Destructor Documentation
org.glite.security.voms.service.attributes.AttributeValue.AttributeValue ()
Definition at line 17 of file AttributeValue.java.
Referenced by org.glite.security.voms.service.attributes.AttributeValue.equals().
                            
    
org.glite.security.voms.service.attributes.AttributeValue.AttributeValue (org.glite.security.voms.service.attributes.AttributeClass attributeClass, java.lang.String context, java.lang.String value)
Definition at line 20 of file AttributeValue.java.
References org.glite.security.voms.service.attributes.AttributeValue.attributeClass, org.glite.security.voms.service.attributes.AttributeValue.context, and org.glite.security.voms.service.attributes.AttributeValue.value.
                                   
           this.attributeClass = attributeClass;
           this.context = context;
           this.value = value;
    
Member Function Documentation
synchronized boolean org.glite.security.voms.service.attributes.AttributeValue.equals (java.lang.Object obj)
Definition at line 90 of file AttributeValue.java.
References org.glite.security.voms.service.attributes.AttributeValue.__equalsCalc, org.glite.security.voms.service.attributes.AttributeValue.attributeClass, org.glite.security.voms.service.attributes.AttributeValue.AttributeValue(), org.glite.security.voms.service.attributes.AttributeValue.context, org.glite.security.voms.service.attributes.AttributeClass.equals(), org.glite.security.voms.service.attributes.AttributeValue.getAttributeClass(), org.glite.security.voms.service.attributes.AttributeValue.getContext(), org.glite.security.voms.service.attributes.AttributeValue.getValue(), and org.glite.security.voms.service.attributes.AttributeValue.value.
                                                             
        if (!(obj instanceof AttributeValue)) return false;
        AttributeValue other = (AttributeValue) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null)
            return (__equalsCalc == obj);
        
        __equalsCalc = obj;
        boolean _equals;
        _equals = true &&
            ((this.attributeClass==null && other.getAttributeClass()==null) ||
             (this.attributeClass!=null &&
              this.attributeClass.equals(other.getAttributeClass()))) &&
            ((this.context==null && other.getContext()==null) ||
             (this.context!=null &&
              this.context.equals(other.getContext()))) &&
            ((this.value==null && other.getValue()==null) ||
             (this.value!=null &&
              this.value.equals(other.getValue())));
        __equalsCalc = null;
        return _equals;
    
org.glite.security.voms.service.attributes.AttributeClass org.glite.security.voms.service.attributes.AttributeValue.getAttributeClass ()
Gets the attributeClass value for this AttributeValue.
Returns
attributeClass
Definition at line 35 of file AttributeValue.java.
References org.glite.security.voms.service.attributes.AttributeValue.attributeClass.
Referenced by org.glite.security.voms.service.attributes.AttributeValue.equals(), and org.glite.security.voms.service.attributes.AttributeValue.hashCode().
                                                                                 
              
        return attributeClass;
    
java.lang.String org.glite.security.voms.service.attributes.AttributeValue.getContext ()
Gets the context value for this AttributeValue.
Returns
context
Definition at line 55 of file AttributeValue.java.
References org.glite.security.voms.service.attributes.AttributeValue.context.
Referenced by org.glite.security.voms.service.attributes.AttributeValue.equals(), and org.glite.security.voms.service.attributes.AttributeValue.hashCode().
                                         
        return context;
    
java.lang.String org.glite.security.voms.service.attributes.AttributeValue.getValue ()
Gets the value value for this AttributeValue.
Returns
value
Definition at line 75 of file AttributeValue.java.
References org.glite.security.voms.service.attributes.AttributeValue.value.
Referenced by org.glite.security.voms.service.attributes.AttributeValue.equals(), and org.glite.security.voms.service.attributes.AttributeValue.hashCode().
                                       
        return value;
    
synchronized int org.glite.security.voms.service.attributes.AttributeValue.hashCode ()
Definition at line 115 of file AttributeValue.java.
References org.glite.security.voms.service.attributes.AttributeValue.__hashCodeCalc, org.glite.security.voms.service.attributes.AttributeValue.getAttributeClass(), org.glite.security.voms.service.attributes.AttributeValue.getContext(), org.glite.security.voms.service.attributes.AttributeValue.getValue(), and org.glite.security.voms.service.attributes.AttributeClass.hashCode().
                                       
        if (__hashCodeCalc)
            return 0;
        
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getAttributeClass() != null)
            _hashCode += getAttributeClass().hashCode();
        
        if (getContext() != null)
            _hashCode += getContext().hashCode();
        
        if (getValue() != null)
            _hashCode += getValue().hashCode();
        
        __hashCodeCalc = false;
        return _hashCode;
    
void org.glite.security.voms.service.attributes.AttributeValue.setAttributeClass (org.glite.security.voms.service.attributes.AttributeClass attributeClass)
Sets the attributeClass value for this AttributeValue.
Parameters
attributeClass
Definition at line 45 of file AttributeValue.java.
References org.glite.security.voms.service.attributes.AttributeValue.attributeClass.
                                                                                 
                                 
        this.attributeClass = attributeClass;
    
void org.glite.security.voms.service.attributes.AttributeValue.setContext (java.lang.String context)
Sets the context value for this AttributeValue.
Parameters
context
Definition at line 65 of file AttributeValue.java.
References org.glite.security.voms.service.attributes.AttributeValue.context.
                                                     
        this.context = context;
    
void org.glite.security.voms.service.attributes.AttributeValue.setValue (java.lang.String value)
Sets the value value for this AttributeValue.
Parameters
value
Definition at line 85 of file AttributeValue.java.
References org.glite.security.voms.service.attributes.AttributeValue.value.
                                                 
        this.value = value;
    
Member Data Documentation
java.lang.Object org.glite.security.voms.service.attributes.AttributeValue.__equalsCalc = null [private]
Definition at line 89 of file AttributeValue.java.
Referenced by org.glite.security.voms.service.attributes.AttributeValue.equals().
boolean org.glite.security.voms.service.attributes.AttributeValue.__hashCodeCalc = false [private]
Definition at line 114 of file AttributeValue.java.
Referenced by org.glite.security.voms.service.attributes.AttributeValue.hashCode().
org.glite.security.voms.service.attributes.AttributeClass org.glite.security.voms.service.attributes.AttributeValue.attributeClass [private]
Definition at line 11 of file AttributeValue.java.
Referenced by org.glite.security.voms.service.attributes.AttributeValue.AttributeValue(), org.glite.security.voms.service.attributes.AttributeValue.equals(), org.glite.security.voms.service.attributes.AttributeValue.getAttributeClass(), and org.glite.security.voms.service.attributes.AttributeValue.setAttributeClass().
java.lang.String org.glite.security.voms.service.attributes.AttributeValue.context [private]
Definition at line 13 of file AttributeValue.java.
Referenced by org.glite.security.voms.service.attributes.AttributeValue.AttributeValue(), org.glite.security.voms.service.attributes.AttributeValue.equals(), org.glite.security.voms.service.attributes.AttributeValue.getContext(), and org.glite.security.voms.service.attributes.AttributeValue.setContext().
java.lang.String org.glite.security.voms.service.attributes.AttributeValue.value [private]
Definition at line 15 of file AttributeValue.java.
Referenced by org.glite.security.voms.service.attributes.AttributeValue.AttributeValue(), org.glite.security.voms.service.attributes.AttributeValue.equals(), org.glite.security.voms.service.attributes.AttributeValue.getValue(), and org.glite.security.voms.service.attributes.AttributeValue.setValue().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/attributes/AttributeValue.java