portal.registration.server.PortalContextListener Class Reference
Public Member Functions
void contextDestroyed (ServletContextEvent arg0)
void contextInitialized (ServletContextEvent arg0)
Protected Member Functions
void initializeAxisProperties ()
Static Private Attributes
static final Logger log = Logger.getLogger(PortalContextListener.class)
static final String DEFAULT_SSL_CERT_FILE = `/etc/grid-security/hostcert.pem`
static final String DEFAULT_SSL_KEY = `/etc/grid-security/hostkey.pem`
Detailed Description
Definition at line 13 of file PortalContextListener.java.
Member Function Documentation
void portal.registration.server.PortalContextListener.contextDestroyed (ServletContextEvent arg0)
Definition at line 19 of file PortalContextListener.java.
References portal.registration.server.PortalContextListener.log.
                                                               
                // TODO Auto-generated method stub
                log.info("Registration Shutdown");
        
void portal.registration.server.PortalContextListener.contextInitialized (ServletContextEvent arg0)
Definition at line 24 of file PortalContextListener.java.
References portal.registration.server.PortalContextListener.initializeAxisProperties(), and portal.registration.server.PortalContextListener.log.
                                                                 
                // TODO Auto-generated method stub
                log.info("Registration Startup");
                initializeAxisProperties();
        
void portal.registration.server.PortalContextListener.initializeAxisProperties () [protected]
Definition at line 31 of file PortalContextListener.java.
References portal.registration.server.PortalContextListener.DEFAULT_SSL_CERT_FILE, and portal.registration.server.PortalContextListener.DEFAULT_SSL_KEY.
Referenced by portal.registration.server.PortalContextListener.contextInitialized().
                                                  
                AxisProperties.setProperty("axis.socketSecureFactory",
                                "org.glite.security.trustmanager.axis.AXISSocketF
      actory");
                // need to pass property to AXISSocketFactory
                Properties properties = AXISSocketFactory.getCurrentProperties();
      
                // TODO will get cert and key from the configuration, with those
      as
                // default
                properties.setProperty("sslCertFile", DEFAULT_SSL_CERT_FILE); //
      hostcert.pem
                properties.setProperty("sslKey", DEFAULT_SSL_KEY); // hostkey.pem
      
                AXISSocketFactory.setCurrentProperties(properties);
                System.setProperties(properties);
        
Member Data Documentation
final String portal.registration.server.PortalContextListener.DEFAULT_SSL_CERT_FILE = `/etc/grid-security/hostcert.pem` [static, private]
Definition at line 16 of file PortalContextListener.java.
Referenced by portal.registration.server.PortalContextListener.initializeAxisProperties().
final String portal.registration.server.PortalContextListener.DEFAULT_SSL_KEY = `/etc/grid-security/hostkey.pem` [static, private]
Definition at line 17 of file PortalContextListener.java.
Referenced by portal.registration.server.PortalContextListener.initializeAxisProperties().
final Logger portal.registration.server.PortalContextListener.log = Logger.getLogger(PortalContextListener.class) [static, private]
Definition at line 15 of file PortalContextListener.java.
Referenced by portal.registration.server.PortalContextListener.contextDestroyed(), and portal.registration.server.PortalContextListener.contextInitialized().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/server/PortalContextListener.java