org.glite.security.voms.service.attributes.AttributeClass Class Reference
Public Member Functions
AttributeClass ()
AttributeClass (java.lang.String description, java.lang.String name, boolean uniquenessChecked)
java.lang.String getDescription ()
void setDescription (java.lang.String description)
java.lang.String getName ()
void setName (java.lang.String name)
boolean isUniquenessChecked ()
void setUniquenessChecked (boolean uniquenessChecked)
synchronized boolean equals (java.lang.Object obj)
synchronized int hashCode ()
Private Attributes
java.lang.String description
java.lang.String name
boolean uniquenessChecked
java.lang.Object __equalsCalc = null
boolean __hashCodeCalc = false
Detailed Description
Definition at line 10 of file AttributeClass.java.
Constructor & Destructor Documentation
org.glite.security.voms.service.attributes.AttributeClass.AttributeClass ()
Definition at line 17 of file AttributeClass.java.
Referenced by org.glite.security.voms.service.attributes.AttributeClass.equals().
                            
    
org.glite.security.voms.service.attributes.AttributeClass.AttributeClass (java.lang.String description, java.lang.String name, boolean uniquenessChecked)
Definition at line 20 of file AttributeClass.java.
References org.glite.security.voms.service.attributes.AttributeClass.description, org.glite.security.voms.service.attributes.AttributeClass.name, and org.glite.security.voms.service.attributes.AttributeClass.uniquenessChecked.
                                      
           this.description = description;
           this.name = name;
           this.uniquenessChecked = uniquenessChecked;
    
Member Function Documentation
synchronized boolean org.glite.security.voms.service.attributes.AttributeClass.equals (java.lang.Object obj)
Definition at line 90 of file AttributeClass.java.
References org.glite.security.voms.service.attributes.AttributeClass.__equalsCalc, org.glite.security.voms.service.attributes.AttributeClass.AttributeClass(), org.glite.security.voms.service.attributes.AttributeClass.description, org.glite.security.voms.service.attributes.AttributeClass.getDescription(), org.glite.security.voms.service.attributes.AttributeClass.getName(), org.glite.security.voms.service.attributes.AttributeClass.isUniquenessChecked(), org.glite.security.voms.service.attributes.AttributeClass.name, and org.glite.security.voms.service.attributes.AttributeClass.uniquenessChecked.
Referenced by org.glite.security.voms.service.attributes.AttributeValue.equals().
                                                             
        if (!(obj instanceof AttributeClass)) return false;
        AttributeClass other = (AttributeClass) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null)
            return (__equalsCalc == obj);
        
        __equalsCalc = obj;
        boolean _equals;
        _equals = true &&
            ((this.description==null && other.getDescription()==null) ||
             (this.description!=null &&
              this.description.equals(other.getDescription()))) &&
            ((this.name==null && other.getName()==null) ||
             (this.name!=null &&
              this.name.equals(other.getName()))) &&
            this.uniquenessChecked == other.isUniquenessChecked();
        __equalsCalc = null;
        return _equals;
    
java.lang.String org.glite.security.voms.service.attributes.AttributeClass.getDescription ()
Gets the description value for this AttributeClass.
Returns
description
Definition at line 35 of file AttributeClass.java.
References org.glite.security.voms.service.attributes.AttributeClass.description.
Referenced by org.glite.security.voms.service.attributes.AttributeClass.equals(), and org.glite.security.voms.service.attributes.AttributeClass.hashCode().
                                             
        return description;
    
java.lang.String org.glite.security.voms.service.attributes.AttributeClass.getName ()
Gets the name value for this AttributeClass.
Returns
name
Definition at line 55 of file AttributeClass.java.
References org.glite.security.voms.service.attributes.AttributeClass.name.
Referenced by org.glite.security.voms.service.attributes.AttributeClass.equals(), and org.glite.security.voms.service.attributes.AttributeClass.hashCode().
                                      
        return name;
    
synchronized int org.glite.security.voms.service.attributes.AttributeClass.hashCode ()
Definition at line 113 of file AttributeClass.java.
References org.glite.security.voms.service.attributes.AttributeClass.__hashCodeCalc, org.glite.security.voms.service.attributes.AttributeClass.getDescription(), org.glite.security.voms.service.attributes.AttributeClass.getName(), and org.glite.security.voms.service.attributes.AttributeClass.isUniquenessChecked().
Referenced by org.glite.security.voms.service.attributes.AttributeValue.hashCode().
                                       
        if (__hashCodeCalc)
            return 0;
        
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getDescription() != null)
            _hashCode += getDescription().hashCode();
        
        if (getName() != null)
            _hashCode += getName().hashCode();
        
        _hashCode += (isUniquenessChecked() ? Boolean.TRUE : Boolean.FALSE).
      hashCode();
        __hashCodeCalc = false;
        return _hashCode;
    
boolean org.glite.security.voms.service.attributes.AttributeClass.isUniquenessChecked ()
Gets the uniquenessChecked value for this AttributeClass.
Returns
uniquenessChecked
Definition at line 75 of file AttributeClass.java.
References org.glite.security.voms.service.attributes.AttributeClass.uniquenessChecked.
Referenced by org.glite.security.voms.service.attributes.AttributeClass.equals(), and org.glite.security.voms.service.attributes.AttributeClass.hashCode().
                                         
        return uniquenessChecked;
    
void org.glite.security.voms.service.attributes.AttributeClass.setDescription (java.lang.String description)
Sets the description value for this AttributeClass.
Parameters
description
Definition at line 45 of file AttributeClass.java.
References org.glite.security.voms.service.attributes.AttributeClass.description.
                                                             
        this.description = description;
    
void org.glite.security.voms.service.attributes.AttributeClass.setName (java.lang.String name)
Sets the name value for this AttributeClass.
Parameters
name
Definition at line 65 of file AttributeClass.java.
References org.glite.security.voms.service.attributes.AttributeClass.name.
                                               
        this.name = name;
    
void org.glite.security.voms.service.attributes.AttributeClass.setUniquenessChecked (boolean uniquenessChecked)
Sets the uniquenessChecked value for this AttributeClass.
Parameters
uniquenessChecked
Definition at line 85 of file AttributeClass.java.
References org.glite.security.voms.service.attributes.AttributeClass.uniquenessChecked.
                                                                
        this.uniquenessChecked = uniquenessChecked;
    
Member Data Documentation
java.lang.Object org.glite.security.voms.service.attributes.AttributeClass.__equalsCalc = null [private]
Definition at line 89 of file AttributeClass.java.
Referenced by org.glite.security.voms.service.attributes.AttributeClass.equals().
boolean org.glite.security.voms.service.attributes.AttributeClass.__hashCodeCalc = false [private]
Definition at line 112 of file AttributeClass.java.
Referenced by org.glite.security.voms.service.attributes.AttributeClass.hashCode().
java.lang.String org.glite.security.voms.service.attributes.AttributeClass.description [private]
Definition at line 11 of file AttributeClass.java.
Referenced by org.glite.security.voms.service.attributes.AttributeClass.AttributeClass(), org.glite.security.voms.service.attributes.AttributeClass.equals(), org.glite.security.voms.service.attributes.AttributeClass.getDescription(), and org.glite.security.voms.service.attributes.AttributeClass.setDescription().
java.lang.String org.glite.security.voms.service.attributes.AttributeClass.name [private]
Definition at line 13 of file AttributeClass.java.
Referenced by org.glite.security.voms.service.attributes.AttributeClass.AttributeClass(), org.glite.security.voms.service.attributes.AttributeClass.equals(), org.glite.security.voms.service.attributes.AttributeClass.getName(), and org.glite.security.voms.service.attributes.AttributeClass.setName().
boolean org.glite.security.voms.service.attributes.AttributeClass.uniquenessChecked [private]
Definition at line 15 of file AttributeClass.java.
Referenced by org.glite.security.voms.service.attributes.AttributeClass.AttributeClass(), org.glite.security.voms.service.attributes.AttributeClass.equals(), org.glite.security.voms.service.attributes.AttributeClass.isUniquenessChecked(), and org.glite.security.voms.service.attributes.AttributeClass.setUniquenessChecked().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/attributes/AttributeClass.java