portal.registration.controller.UserInfoController Class Reference
Public Member Functions
String showUserInfos (RenderResponse response)
List< UserInfo > getUserInfos ()
List< Idp > getIdps ()
Map< Object, Object > getIdpsName ()
Private Attributes
UserInfoService userInfoService
IdpService idpService
Detailed Description
Definition at line 22 of file UserInfoController.java.
Member Function Documentation
List<Idp> portal.registration.controller.UserInfoController.getIdps ()
Definition at line 41 of file UserInfoController.java.
References portal.registration.services.IdpService.getAllIdp().
                                   
                return idpService.getAllIdp();
        
Map<Object, Object> portal.registration.controller.UserInfoController.getIdpsName ()
Definition at line 46 of file UserInfoController.java.
References portal.registration.services.IdpService.findByIdp(), and portal.registration.services.UserInfoService.getAllUserInfo().
                                                 
                Map<Object, Object> x = new Properties();
                List<UserInfo> users = userInfoService.getAllUserInfo();
                for (int i = 0; i < users.size(); i++)
                        x.put(users.get(i).getUserId(),
                                        idpService.findByIdp(users.get(i).getIdp(
      )));
                
                return x;
        
List<UserInfo> portal.registration.controller.UserInfoController.getUserInfos ()
Definition at line 36 of file UserInfoController.java.
References portal.registration.services.UserInfoService.getAllUserInfo().
                                             
                return userInfoService.getAllUserInfo();
        
String portal.registration.controller.UserInfoController.showUserInfos (RenderResponse response)
Definition at line 31 of file UserInfoController.java.
                                                             
                return "home";
        
Member Data Documentation
IdpService portal.registration.controller.UserInfoController.idpService [private]
Definition at line 28 of file UserInfoController.java.
UserInfoService portal.registration.controller.UserInfoController.userInfoService [private]
Definition at line 25 of file UserInfoController.java.
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/controller/UserInfoController.java