org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator Class Reference
Public Member Functions
VOMSCertificatesServiceLocator ()
VOMSCertificatesServiceLocator (org.apache.axis.EngineConfiguration config)
VOMSCertificatesServiceLocator (java.lang.String wsdlLoc, javax.xml.namespace.QName sName) throws javax.xml.rpc.ServiceException
java.lang.String getVOMSCertificatesAddress ()
java.lang.String getVOMSCertificatesWSDDServiceName ()
void setVOMSCertificatesWSDDServiceName (java.lang.String name)
org.glite.security.voms.service.certificates.VOMSCertificates getVOMSCertificates () throws javax.xml.rpc.ServiceException
org.glite.security.voms.service.certificates.VOMSCertificates getVOMSCertificates (java.net.URL portAddress) throws javax.xml.rpc.ServiceException
void setVOMSCertificatesEndpointAddress (java.lang.String address)
java.rmi.Remote getPort (Class serviceEndpointInterface) throws javax.xml.rpc.ServiceException
java.rmi.Remote getPort (javax.xml.namespace.QName portName, Class serviceEndpointInterface) throws javax.xml.rpc.ServiceException
namespace::QName getServiceName ()
java.util.Iterator getPorts ()
void setEndpointAddress (java.lang.String portName, java.lang.String address) throws javax.xml.rpc.ServiceException
void setEndpointAddress (javax.xml.namespace.QName portName, java.lang.String address) throws javax.xml.rpc.ServiceException
Private Attributes
java.lang.String VOMSCertificates_address = `https://localhost:8443/glite-security-voms-admin-interface/VOMSCertificates`
java.lang.String VOMSCertificatesWSDDServiceName = `VOMSCertificates`
java.util.HashSet ports = null
Detailed Description
Definition at line 10 of file VOMSCertificatesServiceLocator.java.
Constructor & Destructor Documentation
org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.VOMSCertificatesServiceLocator ()
Definition at line 12 of file VOMSCertificatesServiceLocator.java.
                                            
    
org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.VOMSCertificatesServiceLocator (org.apache.axis.EngineConfiguration config)
Definition at line 16 of file VOMSCertificatesServiceLocator.java.
                                                                                 
           
        super(config);
    
org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.VOMSCertificatesServiceLocator (java.lang.String wsdlLoc, javax.xml.namespace.QName sName) throws javax.xml.rpc.ServiceException
Definition at line 20 of file VOMSCertificatesServiceLocator.java.
                                                                                 
                                                                
        super(wsdlLoc, sName);
    
Member Function Documentation
java.rmi.Remote org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.getPort (Class serviceEndpointInterface) throws javax.xml.rpc.ServiceException
For the given interface, get the stub implementation. If this service has no port for the given interface, then ServiceException is thrown.
Definition at line 73 of file VOMSCertificatesServiceLocator.java.
References org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.getVOMSCertificatesWSDDServiceName(), and org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.VOMSCertificates_address.
Referenced by org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.getPort().
                                                                                 
                              
        try
            if (org.glite.security.voms.service.certificates.VOMSCertificates.cla
      ss.isAssignableFrom(serviceEndpointInterface))
                org.glite.security.voms.service.certificates.VOMSCertificatesSoap
      BindingStub _stub = new org.glite.security.voms.service.certificates.VOMSCertific
      atesSoapBindingStub(new java.net.URL(VOMSCertificates_address), this);
                _stub.setPortName(getVOMSCertificatesWSDDServiceName());
                return _stub;
            
        
        catch (java.lang.Throwable t)
            throw new javax.xml.rpc.ServiceException(t);
        
        throw new javax.xml.rpc.ServiceException("There is no stub implementation
       for the interface: " + (serviceEndpointInterface == null ? "null" : serviceEndp
      ointInterface.getName()));
    
java.rmi.Remote org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.getPort (javax.xml.namespace.QName portName, Class serviceEndpointInterface) throws javax.xml.rpc.ServiceException
For the given interface, get the stub implementation. If this service has no port for the given interface, then ServiceException is thrown.
Definition at line 92 of file VOMSCertificatesServiceLocator.java.
References org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.getPort(), and org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.getVOMSCertificates().
                                                                                 
                                                                  
        if (portName == null)
            return getPort(serviceEndpointInterface);
        
        java.lang.String inputPortName = portName.getLocalPart();
        if ("VOMSCertificates".equals(inputPortName))
            return getVOMSCertificates();
        
        else
            java.rmi.Remote _stub = getPort(serviceEndpointInterface);
            ((org.apache.axis.client.Stub) _stub).setPortName(portName);
            return _stub;
        
    
java.util.Iterator org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.getPorts ()
Definition at line 113 of file VOMSCertificatesServiceLocator.java.
References org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.ports.
                                         
        if (ports == null)
            ports = new java.util.HashSet();
            ports.add(new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.certificates", "VOMSCertificates"));
        
        return ports.iterator();
    
namespace ::QName org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.getServiceName ()
Definition at line 107 of file VOMSCertificatesServiceLocator.java.
                                                      
        return new javax.xml.namespace.QName("http://glite.org/wsdl/services/org.
      glite.security.voms.service.certificates", "VOMSCertificatesService");
    
org.glite.security.voms.service.certificates.VOMSCertificates org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.getVOMSCertificates (java.net.URL portAddress) throws javax.xml.rpc.ServiceException
Implements org.glite.security.voms.service.certificates.VOMSCertificatesService.
Definition at line 53 of file VOMSCertificatesServiceLocator.java.
References org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.getVOMSCertificatesWSDDServiceName().
                                                                                 
                                                                                  
        try
            org.glite.security.voms.service.certificates.VOMSCertificatesSoapBind
      ingStub _stub = new org.glite.security.voms.service.certificates.VOMSCertificates
      SoapBindingStub(portAddress, this);
            _stub.setPortName(getVOMSCertificatesWSDDServiceName());
            return _stub;
        
        catch (org.apache.axis.AxisFault e)
            return null;
        
    
org.glite.security.voms.service.certificates.VOMSCertificates org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.getVOMSCertificates () throws javax.xml.rpc.ServiceException
Implements org.glite.security.voms.service.certificates.VOMSCertificatesService.
Definition at line 42 of file VOMSCertificatesServiceLocator.java.
References org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.VOMSCertificates_address.
Referenced by org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.getPort().
                                                                                 
                                                          
       java.net.URL endpoint;
        try
            endpoint = new java.net.URL(VOMSCertificates_address);
        
        catch (java.net.MalformedURLException e)
            throw new javax.xml.rpc.ServiceException(e);
        
        return getVOMSCertificates(endpoint);
    
java.lang.String org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.getVOMSCertificatesAddress ()
Implements org.glite.security.voms.service.certificates.VOMSCertificatesService.
Definition at line 27 of file VOMSCertificatesServiceLocator.java.
References org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.VOMSCertificates_address.
                                                         
        return VOMSCertificates_address;
    
java.lang.String org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.getVOMSCertificatesWSDDServiceName ()
Definition at line 34 of file VOMSCertificatesServiceLocator.java.
References org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.VOMSCertificatesWSDDServiceName.
Referenced by org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.getPort(), and org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.getVOMSCertificates().
                                                                 
        return VOMSCertificatesWSDDServiceName;
    
void org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.setEndpointAddress (java.lang.String portName, java.lang.String address) throws javax.xml.rpc.ServiceException
Set the endpoint address for the specified port name.
Definition at line 124 of file VOMSCertificatesServiceLocator.java.
References org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.setVOMSCertificatesEndpointAddress().
Referenced by org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.setEndpointAddress().
                                                                                 
                                                   
        
if ("VOMSCertificates".equals(portName))
            setVOMSCertificatesEndpointAddress(address);
        
        else
 // Unknown Port Name
            throw new javax.xml.rpc.ServiceException(" Cannot set Endpoint Addres
      s for Unknown Port" + portName);
        
    
void org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.setEndpointAddress (javax.xml.namespace.QName portName, java.lang.String address) throws javax.xml.rpc.ServiceException
Set the endpoint address for the specified port name.
Definition at line 138 of file VOMSCertificatesServiceLocator.java.
References org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.setEndpointAddress().
                                                                                 
                                                            
        setEndpointAddress(portName.getLocalPart(), address);
    
void org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.setVOMSCertificatesEndpointAddress (java.lang.String address)
Definition at line 64 of file VOMSCertificatesServiceLocator.java.
References org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.VOMSCertificates_address.
Referenced by org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.setEndpointAddress().
                                                                             
        VOMSCertificates_address = address;
    
void org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.setVOMSCertificatesWSDDServiceName (java.lang.String name)
Definition at line 38 of file VOMSCertificatesServiceLocator.java.
References org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.VOMSCertificatesWSDDServiceName.
                                                                          
        VOMSCertificatesWSDDServiceName = name;
    
Member Data Documentation
java.util.HashSet org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.ports = null [private]
Definition at line 111 of file VOMSCertificatesServiceLocator.java.
Referenced by org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.getPorts().
java.lang.String org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.VOMSCertificates_address = `https://localhost:8443/glite-security-voms-admin-interface/VOMSCertificates` [private]
Definition at line 25 of file VOMSCertificatesServiceLocator.java.
Referenced by org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.getPort(), org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.getVOMSCertificates(), org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.getVOMSCertificatesAddress(), and org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.setVOMSCertificatesEndpointAddress().
java.lang.String org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.VOMSCertificatesWSDDServiceName = `VOMSCertificates` [private]
Definition at line 32 of file VOMSCertificatesServiceLocator.java.
Referenced by org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.getVOMSCertificatesWSDDServiceName(), and org.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator.setVOMSCertificatesWSDDServiceName().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/certificates/VOMSCertificatesServiceLocator.java