portal.registration.controller.EditUserToVoController Class Reference
Public Member Functions
String showEditUserInfoForm ()
UserInfo getUserInfo (@RequestParam int userId)
UserToVo getUserToVo (@RequestParam int userId,@RequestParam int idVo)
Vo getVO (@RequestParam int idVo)
List< Fqan > getFqans (@RequestParam int userId,@RequestParam int idVo)
void addUserToVo (ActionRequest request, ActionResponse response, SessionStatus sessionStatus)
Private Attributes
UserInfoService userInfoService
VoService voService
UserToVoService userToVoService
FqanService fqanService
Static Private Attributes
static final Logger log
Detailed Description
Definition at line 31 of file EditUserToVoController.java.
Member Function Documentation
void portal.registration.controller.EditUserToVoController.addUserToVo (ActionRequest request, ActionResponse response, SessionStatus sessionStatus)
Definition at line 80 of file EditUserToVoController.java.
References portal.registration.services.UserToVoService.findById(), portal.registration.domain.UserToVo.setFqans(), and portal.registration.services.UserToVoService.update().
                                                     
                String[] fqans = request.getParameterValues("resultList");
                int userId = Integer.parseInt(request.getParameter("userId"));
                int idVo = Integer.parseInt(request.getParameter("idVo"));
                UserToVo utv = userToVoService.findById(userId, idVo);
                if (fqans != null && !fqans[0].equals(""))
                        log.info("prova =" + fqans[0] + ";fine");
                        String toSave = "";
                        for (int i = 0; i < fqans.length; i++)
                                toSave += fqans[i] + ";";
                        log.info("Stampa FQANS: " + toSave);
                        utv.setFqans(toSave);
                 else
                        utv.setFqans("");
                
                userToVoService.update(utv);
                SessionMessages.add(request, "userToVo-updated-successufully");
                response.setRenderParameter("myaction", "editUserInfoForm");
                response.setRenderParameter("userId", Integer.toString(userId));
                request.setAttribute("userId", userId);
                sessionStatus.setComplete();
        
List<Fqan> portal.registration.controller.EditUserToVoController.getFqans (@RequestParam int userId, @RequestParam int idVo)
Definition at line 75 of file EditUserToVoController.java.
References portal.registration.services.FqanService.findByIdVo().
                                                                                 
          
                return fqanService.findByIdVo(idVo);
        
UserInfo portal.registration.controller.EditUserToVoController.getUserInfo (@RequestParam int userId)
Definition at line 54 of file EditUserToVoController.java.
References portal.registration.services.UserInfoService.findById().
                                                              
                return userInfoService.findById(userId);
        
UserToVo portal.registration.controller.EditUserToVoController.getUserToVo (@RequestParam int userId, @RequestParam int idVo)
Definition at line 59 of file EditUserToVoController.java.
References portal.registration.services.UserToVoService.findById().
                                                                                 
           
                return userToVoService.findById(userId, idVo);
        
Vo portal.registration.controller.EditUserToVoController.getVO (@RequestParam int idVo)
Definition at line 64 of file EditUserToVoController.java.
References portal.registration.services.VoService.findById().
                                                
                return voService.findById(idVo);
        
String portal.registration.controller.EditUserToVoController.showEditUserInfoForm ()
Definition at line 49 of file EditUserToVoController.java.
                                             
                return "editUserToVo";
        
Member Data Documentation
FqanService portal.registration.controller.EditUserToVoController.fqanService [private]
Definition at line 46 of file EditUserToVoController.java.
final Logger portal.registration.controller.EditUserToVoController.log [static, private]
Initial value:
 Logger
                        .getLogger(EditUserToVoController.class)
Definition at line 33 of file EditUserToVoController.java.
UserInfoService portal.registration.controller.EditUserToVoController.userInfoService [private]
Definition at line 37 of file EditUserToVoController.java.
UserToVoService portal.registration.controller.EditUserToVoController.userToVoService [private]
Definition at line 43 of file EditUserToVoController.java.
VoService portal.registration.controller.EditUserToVoController.voService [private]
Definition at line 40 of file EditUserToVoController.java.
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/controller/EditUserToVoController.java