org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton Class Reference
Public Member Functions
VOMSRegistrationSoapBindingSkeleton ()
VOMSRegistrationSoapBindingSkeleton (org.glite.security.voms.service.registration.VOMSRegistration impl)
void submitRegistrationRequest (org.glite.security.voms.service.registration.RegistrationRequest in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void submitRegistrationRequestForUser (java.lang.String in0, java.lang.String in1, org.glite.security.voms.service.registration.RegistrationRequest in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Static Public Member Functions
static java.util.List getOperationDescByName (java.lang.String methodName)
static java.util.Collection getOperationDescs ()
Static Package Functions
[static initializer]
Private Attributes
org.glite.security.voms.service.registration.VOMSRegistration impl
Static Private Attributes
static java.util.Map _myOperations = new java.util.Hashtable()
static java.util.Collection _myOperationsList = new java.util.ArrayList()
Detailed Description
Definition at line 10 of file VOMSRegistrationSoapBindingSkeleton.java.
Constructor & Destructor Documentation
org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.VOMSRegistrationSoapBindingSkeleton ()
Definition at line 71 of file VOMSRegistrationSoapBindingSkeleton.java.
References org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.impl.
                                                 
        this.impl = new org.glite.security.voms.service.registration.VOMSRegistra
      tionSoapBindingImpl();
    
org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.VOMSRegistrationSoapBindingSkeleton (org.glite.security.voms.service.registration.VOMSRegistration impl)
Definition at line 75 of file VOMSRegistrationSoapBindingSkeleton.java.
References org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.impl.
                                                                                 
                                        
        this.impl = impl;
    
Member Function Documentation
org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.[static initializer] () [static, package]
static java.util.List org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.getOperationDescByName (java.lang.String methodName) [static]
Returns List of OperationDesc objects with this name
Definition at line 18 of file VOMSRegistrationSoapBindingSkeleton.java.
References org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton._myOperations.
                                                                                 
          
        return (java.util.List)_myOperations.get(methodName);
    
static java.util.Collection org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.getOperationDescs () [static]
Returns Collection of OperationDescs
Definition at line 25 of file VOMSRegistrationSoapBindingSkeleton.java.
References org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton._myOperationsList.
                                                           
        return _myOperationsList;
    
void org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.submitRegistrationRequest (org.glite.security.voms.service.registration.RegistrationRequest in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.registration.VOMSRegistration.
Definition at line 78 of file VOMSRegistrationSoapBindingSkeleton.java.
References org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.impl, and org.glite.security.voms.service.registration.VOMSRegistration.submitRegistrationRequest().
    
        impl.submitRegistrationRequest(in0);
    
void org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.submitRegistrationRequestForUser (java.lang.String in0, java.lang.String in1, org.glite.security.voms.service.registration.RegistrationRequest in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.registration.VOMSRegistration.
Definition at line 83 of file VOMSRegistrationSoapBindingSkeleton.java.
References org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.impl, and org.glite.security.voms.service.registration.VOMSRegistration.submitRegistrationRequestForUser().
    
        impl.submitRegistrationRequestForUser(in0, in1, in2);
    
Member Data Documentation
java.util.Map org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton._myOperations = new java.util.Hashtable() [static, private]
Definition at line 12 of file VOMSRegistrationSoapBindingSkeleton.java.
Referenced by org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.getOperationDescByName().
java.util.Collection org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton._myOperationsList = new java.util.ArrayList() [static, private]
Definition at line 13 of file VOMSRegistrationSoapBindingSkeleton.java.
Referenced by org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.getOperationDescs().
org.glite.security.voms.service.registration.VOMSRegistration org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.impl [private]
Definition at line 11 of file VOMSRegistrationSoapBindingSkeleton.java.
Referenced by org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.submitRegistrationRequest(), org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.submitRegistrationRequestForUser(), and org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.VOMSRegistrationSoapBindingSkeleton().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/registration/VOMSRegistrationSoapBindingSkeleton.java