portal.registration.dao.FqanDAOImpl Class Reference
Public Member Functions
void save (Fqan transientInstance)
void delete (Fqan persistentInstance)
Fqan findById (Integer id)
List< Fqan > getAllFqan ()
List< Fqan > findByIdVo (Integer id)
Private Attributes
SessionFactory sessionFactory
Static Private Attributes
static final Logger log = Logger.getLogger(FqanDAOImpl.class)
Detailed Description
Definition at line 15 of file FqanDAOImpl.java.
Member Function Documentation
void portal.registration.dao.FqanDAOImpl.delete (Fqan persistentInstance)
Implements portal.registration.dao.FqanDAO.
Definition at line 35 of file FqanDAOImpl.java.
References portal.registration.dao.FqanDAOImpl.log, and portal.registration.dao.FqanDAOImpl.sessionFactory.
                                                    
                log.debug("removing Fqan instance");
                try
                        Session session = sessionFactory.getCurrentSession();
                        session.delete(persistentInstance);
                        log.debug("remove successful");
                 catch (RuntimeException re)
                        log.error("remove failed", re);
                        throw re;
                
        
Fqan portal.registration.dao.FqanDAOImpl.findById (Integer id)
Implements portal.registration.dao.FqanDAO.
Definition at line 48 of file FqanDAOImpl.java.
References portal.registration.dao.FqanDAOImpl.log, and portal.registration.dao.FqanDAOImpl.sessionFactory.
                                         
                log.debug("getting Idp instance with id: " + id);
                try
                        Session session = sessionFactory.getCurrentSession();
                        Fqan instance = (Fqan) session.get(Fqan.class, id);
                        log.debug("get successful");
                        return instance;
                 catch (RuntimeException re)
                        log.error("get failed", re);
                        throw re;
                
        
List<Fqan> portal.registration.dao.FqanDAOImpl.findByIdVo (Integer id)
Implements portal.registration.dao.FqanDAO.
Definition at line 80 of file FqanDAOImpl.java.
References portal.registration.dao.FqanDAOImpl.log, and portal.registration.dao.FqanDAOImpl.sessionFactory.
                                                 
                log.debug("getting all Idp instance");
                try
                        Session session = sessionFactory.getCurrentSession();
                        // Create a Hibernate query (HQL)
                        Query query = session.createQuery("FROM Fqan WHERE idVo
      = " + id);
                        // Retrieve all
                        return query.list();
                 catch (RuntimeException re)
                        log.error("get failed", re);
                        throw re;
                
        
List<Fqan> portal.registration.dao.FqanDAOImpl.getAllFqan ()
Implements portal.registration.dao.FqanDAO.
Definition at line 62 of file FqanDAOImpl.java.
References portal.registration.dao.FqanDAOImpl.log, and portal.registration.dao.FqanDAOImpl.sessionFactory.
                                       
                log.debug("getting all Idp instance");
                try
                        Session session = sessionFactory.getCurrentSession();
                        // Create a Hibernate query (HQL)
                        Query query = session.createQuery("FROM Fqan");
                        // Retrieve all
                        return query.list();
                 catch (RuntimeException re)
                        log.error("get failed", re);
                        throw re;
                
        
void portal.registration.dao.FqanDAOImpl.save (Fqan transientInstance)
Implements portal.registration.dao.FqanDAO.
Definition at line 22 of file FqanDAOImpl.java.
References portal.registration.dao.FqanDAOImpl.log, and portal.registration.dao.FqanDAOImpl.sessionFactory.
                                                 
                log.debug("persisting Fqan instance");
                try
                        Session session = sessionFactory.getCurrentSession();
                        session.save(transientInstance);
                        log.debug("persist successful");
                 catch (RuntimeException re)
                        log.error("persist failed", re);
                        throw re;
                
        
Member Data Documentation
final Logger portal.registration.dao.FqanDAOImpl.log = Logger.getLogger(FqanDAOImpl.class) [static, private]
Definition at line 17 of file FqanDAOImpl.java.
Referenced by portal.registration.dao.FqanDAOImpl.delete(), portal.registration.dao.FqanDAOImpl.findById(), portal.registration.dao.FqanDAOImpl.findByIdVo(), portal.registration.dao.FqanDAOImpl.getAllFqan(), and portal.registration.dao.FqanDAOImpl.save().
SessionFactory portal.registration.dao.FqanDAOImpl.sessionFactory [private]
Definition at line 20 of file FqanDAOImpl.java.
Referenced by portal.registration.dao.FqanDAOImpl.delete(), portal.registration.dao.FqanDAOImpl.findById(), portal.registration.dao.FqanDAOImpl.findByIdVo(), portal.registration.dao.FqanDAOImpl.getAllFqan(), and portal.registration.dao.FqanDAOImpl.save().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/dao/FqanDAOImpl.java