portal.registration.dao.UserToVoDAOImpl Class Reference
Public Member Functions
void save (UserToVo transientInstance)
List< UserToVo > findById (UserInfo userInfo)
Vo getVoByUserToVo (UserToVo userToVo)
void delete (int userId, int idVo)
UserToVo findByIds (int userId, int idVo)
void update (UserToVo temp)
int getNumberOfUserToVo (int userId)
Private Attributes
SessionFactory sessionFactory
Static Private Attributes
static final Logger log = Logger.getLogger(UserToVoDAOImpl.class)
Detailed Description
Definition at line 19 of file UserToVoDAOImpl.java.
Member Function Documentation
void portal.registration.dao.UserToVoDAOImpl.delete (int userId, int idVo)
Implements portal.registration.dao.UserToVoDAO.
Definition at line 74 of file UserToVoDAOImpl.java.
References portal.registration.dao.UserToVoDAOImpl.findByIds(), portal.registration.dao.UserToVoDAOImpl.log, and portal.registration.dao.UserToVoDAOImpl.sessionFactory.
                                                 
                log.debug("getting all Certificate instance of user");
                try
                        Session session = sessionFactory.getCurrentSession();
                        // Create a Hibernate query (HQL)
                        UserToVo utv = findByIds(userId, idVo);
                        session.delete(utv);
                        session.flush();
                 catch (RuntimeException re)
                        log.error("get failed", re);
                        throw re;
                
        
List<UserToVo> portal.registration.dao.UserToVoDAOImpl.findById (UserInfo userInfo)
Implements portal.registration.dao.UserToVoDAO.
Definition at line 42 of file UserToVoDAOImpl.java.
References portal.registration.dao.UserToVoDAOImpl.log, and portal.registration.dao.UserToVoDAOImpl.sessionFactory.
                                                          
                log.debug("getting all Certificate instance of user");
                try
                        Session session = sessionFactory.getCurrentSession();
                        // Create a Hibernate query (HQL)
                        Query query = session.createQuery("FROM UserToVo WHERE u
      serId = "
                                        + userInfo.getUserId());
                        // Retrieve all
                        return query.list();
                 catch (RuntimeException re)
                        log.error("get failed", re);
                        throw re;
                
        
UserToVo portal.registration.dao.UserToVoDAOImpl.findByIds (int userId, int idVo)
Implements portal.registration.dao.UserToVoDAO.
Definition at line 91 of file UserToVoDAOImpl.java.
References portal.registration.dao.UserToVoDAOImpl.log, and portal.registration.dao.UserToVoDAOImpl.sessionFactory.
Referenced by portal.registration.dao.UserToVoDAOImpl.delete().
                                                        
                log.debug("getting all Certificate instance of user");
                try
                        Session session = sessionFactory.getCurrentSession();
                        UserToVoId userToVoId = new UserToVoId(userId, idVo);
                        // Create a Hibernate query (HQL)
                        return (UserToVo) session.get(UserToVo.class, userToVoId)
      ;
                 catch (RuntimeException re)
                        log.error("get failed", re);
                        throw re;
                
        
int portal.registration.dao.UserToVoDAOImpl.getNumberOfUserToVo (int userId)
Implements portal.registration.dao.UserToVoDAO.
Definition at line 132 of file UserToVoDAOImpl.java.
References portal.registration.dao.UserToVoDAOImpl.log, and portal.registration.dao.UserToVoDAOImpl.sessionFactory.
                                                   
                log.debug("getting the number of Vo fo userId = " + userId);
                try
                        Session session = sessionFactory.getCurrentSession();
                        int count = 0;
                        String SQL_QUERY = "SELECT count(*) FROM UserToVo WHERE u
      serId = "
                                        + userId;
                        Query query = session.createQuery(SQL_QUERY);
                        for (Iterator it = query.iterate(); it.hasNext();)
                                it.next();
                                count++;
                        
                        return count;
                 catch (RuntimeException re)
                        log.error("get failed", re);
                        throw re;
                
        
Vo portal.registration.dao.UserToVoDAOImpl.getVoByUserToVo (UserToVo userToVo)
Implements portal.registration.dao.UserToVoDAO.
Definition at line 60 of file UserToVoDAOImpl.java.
References portal.registration.domain.UserToVo.getVo(), portal.registration.dao.UserToVoDAOImpl.log, and portal.registration.dao.UserToVoDAOImpl.sessionFactory.
                                                     
                log.debug("getting all Certificate instance of user");
                try
                        Session session = sessionFactory.getCurrentSession();
                        return (Vo) session.get(Vo.class,
                                        session.getIdentifier(userToVo.getVo()));
      
                 catch (RuntimeException re)
                        log.error("get failed", re);
                        throw re;
                
        
void portal.registration.dao.UserToVoDAOImpl.save (UserToVo transientInstance)
Implements portal.registration.dao.UserToVoDAO.
Definition at line 26 of file UserToVoDAOImpl.java.
References portal.registration.dao.UserToVoDAOImpl.log, and portal.registration.dao.UserToVoDAOImpl.sessionFactory.
                                                     
                log.debug("persisting UserInfo instance");
                try
                        Session session = sessionFactory.getCurrentSession();
                        session.save(transientInstance);
                        //
                        session.flush();
                        session.refresh(transientInstance);
                        log.debug("persist successful");
                 catch (RuntimeException re)
                        log.error("persist failed", re);
                        throw re;
                
        
void portal.registration.dao.UserToVoDAOImpl.update (UserToVo temp)
Implements portal.registration.dao.UserToVoDAO.
Definition at line 109 of file UserToVoDAOImpl.java.
References portal.registration.domain.UserToVo.getFqans(), portal.registration.domain.UserToVo.getId(), portal.registration.domain.UserToVo.getIsDefault(), portal.registration.domain.UserToVo.getUserInfo(), portal.registration.domain.UserToVo.getVo(), portal.registration.dao.UserToVoDAOImpl.log, portal.registration.dao.UserToVoDAOImpl.sessionFactory, portal.registration.domain.UserToVo.setFqans(), portal.registration.domain.UserToVo.setIsDefault(), portal.registration.domain.UserToVo.setUserInfo(), and portal.registration.domain.UserToVo.setVo().
                                          
                log.debug("Editing existing userToVo");
                // Retrieve session from Hibernate
                Session session = sessionFactory.getCurrentSession();
                // Retrieve existing userInfo via id
                UserToVo existingUTV = (UserToVo) session.get(UserToVo.class,
                                temp.getId());
                // Assign updated values to this userInfo
                existingUTV.setFqans(temp.getFqans());
                existingUTV.setIsDefault(temp.getIsDefault());
                existingUTV.setUserInfo(temp.getUserInfo());
                existingUTV.setVo(temp.getVo());
                // Save updates
                session.save(existingUTV);
                session.flush();
                session.refresh(existingUTV);
        
Member Data Documentation
final Logger portal.registration.dao.UserToVoDAOImpl.log = Logger.getLogger(UserToVoDAOImpl.class) [static, private]
Definition at line 21 of file UserToVoDAOImpl.java.
Referenced by portal.registration.dao.UserToVoDAOImpl.delete(), portal.registration.dao.UserToVoDAOImpl.findById(), portal.registration.dao.UserToVoDAOImpl.findByIds(), portal.registration.dao.UserToVoDAOImpl.getNumberOfUserToVo(), portal.registration.dao.UserToVoDAOImpl.getVoByUserToVo(), portal.registration.dao.UserToVoDAOImpl.save(), and portal.registration.dao.UserToVoDAOImpl.update().
SessionFactory portal.registration.dao.UserToVoDAOImpl.sessionFactory [private]
Definition at line 24 of file UserToVoDAOImpl.java.
Referenced by portal.registration.dao.UserToVoDAOImpl.delete(), portal.registration.dao.UserToVoDAOImpl.findById(), portal.registration.dao.UserToVoDAOImpl.findByIds(), portal.registration.dao.UserToVoDAOImpl.getNumberOfUserToVo(), portal.registration.dao.UserToVoDAOImpl.getVoByUserToVo(), portal.registration.dao.UserToVoDAOImpl.save(), and portal.registration.dao.UserToVoDAOImpl.update().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/dao/UserToVoDAOImpl.java