portal.registration.services.FqanServiceImpl Class Reference
Public Member Functions
void save (Fqan transientInstance)
void delete (Fqan persistentInstance)
Fqan findById (Integer id)
String findByFqan (Fqan fqan)
List< Fqan > getAllFqan ()
List< Fqan > findByIdVo (int idVo)
Private Attributes
FqanDAO fqanDAO
Static Private Attributes
static final Logger log = Logger.getLogger(FqanServiceImpl.class)
Detailed Description
Definition at line 14 of file FqanServiceImpl.java.
Member Function Documentation
void portal.registration.services.FqanServiceImpl.delete (Fqan persistentInstance)
Implements portal.registration.services.FqanService.
Definition at line 28 of file FqanServiceImpl.java.
References portal.registration.dao.FqanDAO.delete(), portal.registration.services.FqanServiceImpl.fqanDAO, and portal.registration.services.FqanServiceImpl.log.
                                                    
                log.debug("removing Fqan instance");
                fqanDAO.delete(persistentInstance);
        
String portal.registration.services.FqanServiceImpl.findByFqan (Fqan fqan)
Implements portal.registration.services.FqanService.
Definition at line 41 of file FqanServiceImpl.java.
References portal.registration.dao.FqanDAO.findById(), portal.registration.services.FqanServiceImpl.fqanDAO, portal.registration.domain.Fqan.getIdFqan(), and portal.registration.services.FqanServiceImpl.log.
                                            
                log.debug("getting Fqan instance");
                return fqanDAO.findById(fqan.getIdFqan()).getFqanExpr();
        
Fqan portal.registration.services.FqanServiceImpl.findById (Integer id)
Implements portal.registration.services.FqanService.
Definition at line 35 of file FqanServiceImpl.java.
References portal.registration.dao.FqanDAO.findById(), portal.registration.services.FqanServiceImpl.fqanDAO, and portal.registration.services.FqanServiceImpl.log.
                                         
                log.debug("getting Fqan instance with id: " + id);
                return fqanDAO.findById(id);
        
List<Fqan> portal.registration.services.FqanServiceImpl.findByIdVo (int idVo)
Implements portal.registration.services.FqanService.
Definition at line 53 of file FqanServiceImpl.java.
References portal.registration.dao.FqanDAO.findByIdVo(), portal.registration.services.FqanServiceImpl.fqanDAO, and portal.registration.services.FqanServiceImpl.log.
                                               
                log.debug("getting Fqan list instance with idVo: " + idVo);
                return fqanDAO.findByIdVo(idVo);
        
List<Fqan> portal.registration.services.FqanServiceImpl.getAllFqan ()
Implements portal.registration.services.FqanService.
Definition at line 47 of file FqanServiceImpl.java.
References portal.registration.services.FqanServiceImpl.fqanDAO, portal.registration.dao.FqanDAO.getAllFqan(), and portal.registration.services.FqanServiceImpl.log.
                                       
                log.debug("getting all Fqan instance");
                return fqanDAO.getAllFqan();
        
void portal.registration.services.FqanServiceImpl.save (Fqan transientInstance)
Implements portal.registration.services.FqanService.
Definition at line 22 of file FqanServiceImpl.java.
References portal.registration.services.FqanServiceImpl.fqanDAO, portal.registration.services.FqanServiceImpl.log, and portal.registration.dao.FqanDAO.save().
                                                 
                log.debug("persisting Fqan instance");
                fqanDAO.save(transientInstance);
        
Member Data Documentation
FqanDAO portal.registration.services.FqanServiceImpl.fqanDAO [private]
Definition at line 19 of file FqanServiceImpl.java.
Referenced by portal.registration.services.FqanServiceImpl.delete(), portal.registration.services.FqanServiceImpl.findByFqan(), portal.registration.services.FqanServiceImpl.findById(), portal.registration.services.FqanServiceImpl.findByIdVo(), portal.registration.services.FqanServiceImpl.getAllFqan(), and portal.registration.services.FqanServiceImpl.save().
final Logger portal.registration.services.FqanServiceImpl.log = Logger.getLogger(FqanServiceImpl.class) [static, private]
Definition at line 16 of file FqanServiceImpl.java.
Referenced by portal.registration.services.FqanServiceImpl.delete(), portal.registration.services.FqanServiceImpl.findByFqan(), portal.registration.services.FqanServiceImpl.findById(), portal.registration.services.FqanServiceImpl.findByIdVo(), portal.registration.services.FqanServiceImpl.getAllFqan(), and portal.registration.services.FqanServiceImpl.save().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/services/FqanServiceImpl.java