portal.registration.domain.UserToVo Class Reference
Public Member Functions
UserToVo ()
UserToVo (UserToVoId id, Vo vo, UserInfo userInfo)
UserToVo (UserToVoId id, Vo vo, UserInfo userInfo, String isDefault, String fqans)
UserToVoId getId ()
void setId (UserToVoId id)
Vo getVo ()
void setVo (Vo vo)
UserInfo getUserInfo ()
void setUserInfo (UserInfo userInfo)
String getIsDefault ()
void setIsDefault (String isDefault)
String getFqans ()
void setFqans (String fqans)
Private Attributes
UserToVoId id
Vo vo
UserInfo userInfo
String isDefault
String fqans
Static Private Attributes
static final long serialVersionUID = -5434829959406617889L
Detailed Description
UserToVo generated by hbm2java
Definition at line 20 of file UserToVo.java.
Constructor & Destructor Documentation
portal.registration.domain.UserToVo.UserToVo ()
Definition at line 32 of file UserToVo.java.
                          
        
portal.registration.domain.UserToVo.UserToVo (UserToVoId id, Vo vo, UserInfo userInfo)
Definition at line 35 of file UserToVo.java.
                                                                 
                this.id = id;
                this.vo = vo;
                this.userInfo = userInfo;
        
portal.registration.domain.UserToVo.UserToVo (UserToVoId id, Vo vo, UserInfo userInfo, String isDefault, String fqans)
Definition at line 41 of file UserToVo.java.
                                      
                this.id = id;
                this.vo = vo;
                this.userInfo = userInfo;
                this.isDefault = isDefault;
                this.fqans = fqans;
        
Member Function Documentation
String portal.registration.domain.UserToVo.getFqans ()
Definition at line 92 of file UserToVo.java.
Referenced by portal.registration.dao.UserToVoDAOImpl.update().
                                 
                return this.fqans;
        
UserToVoId portal.registration.domain.UserToVo.getId ()
Definition at line 54 of file UserToVo.java.
Referenced by portal.registration.dao.UserToVoDAOImpl.update().
                                  
                return this.id;
        
String portal.registration.domain.UserToVo.getIsDefault ()
Definition at line 83 of file UserToVo.java.
Referenced by portal.registration.services.UserToVoServiceImpl.setDefault(), and portal.registration.dao.UserToVoDAOImpl.update().
                                     
                return this.isDefault;
        
UserInfo portal.registration.domain.UserToVo.getUserInfo ()
Definition at line 74 of file UserToVo.java.
Referenced by portal.registration.dao.UserToVoDAOImpl.update().
                                      
                return this.userInfo;
        
Vo portal.registration.domain.UserToVo.getVo ()
Definition at line 64 of file UserToVo.java.
Referenced by portal.registration.dao.UserToVoDAOImpl.getVoByUserToVo(), and portal.registration.dao.UserToVoDAOImpl.update().
                          
                return this.vo;
        
void portal.registration.domain.UserToVo.setFqans (String fqans)
Definition at line 96 of file UserToVo.java.
Referenced by portal.registration.controller.EditUserToVoController.addUserToVo(), and portal.registration.dao.UserToVoDAOImpl.update().
                                           
                this.fqans = fqans;
        
void portal.registration.domain.UserToVo.setId (UserToVoId id)
Definition at line 58 of file UserToVo.java.
Referenced by portal.registration.services.UserToVoServiceImpl.save().
                                         
                this.id = id;
        
void portal.registration.domain.UserToVo.setIsDefault (String isDefault)
Definition at line 87 of file UserToVo.java.
Referenced by portal.registration.services.UserToVoServiceImpl.save(), portal.registration.services.UserToVoServiceImpl.setDefault(), and portal.registration.dao.UserToVoDAOImpl.update().
                                                   
                this.isDefault = isDefault;
        
void portal.registration.domain.UserToVo.setUserInfo (UserInfo userInfo)
Definition at line 78 of file UserToVo.java.
Referenced by portal.registration.services.UserToVoServiceImpl.save(), and portal.registration.dao.UserToVoDAOImpl.update().
                                                   
                this.userInfo = userInfo;
        
void portal.registration.domain.UserToVo.setVo (Vo vo)
Definition at line 68 of file UserToVo.java.
Referenced by portal.registration.services.UserToVoServiceImpl.save(), and portal.registration.dao.UserToVoDAOImpl.update().
                                 
                this.vo = vo;
        
Member Data Documentation
String portal.registration.domain.UserToVo.fqans [private]
Definition at line 30 of file UserToVo.java.
UserToVoId portal.registration.domain.UserToVo.id [private]
Definition at line 26 of file UserToVo.java.
String portal.registration.domain.UserToVo.isDefault [private]
Definition at line 29 of file UserToVo.java.
final long portal.registration.domain.UserToVo.serialVersionUID = -5434829959406617889L [static, private]
Definition at line 25 of file UserToVo.java.
UserInfo portal.registration.domain.UserToVo.userInfo [private]
Definition at line 28 of file UserToVo.java.
Vo portal.registration.domain.UserToVo.vo [private]
Definition at line 27 of file UserToVo.java.
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/domain/UserToVo.java