portal.registration.services.UserToVoServiceImpl Class Reference
Public Member Functions
UserToVoServiceImpl ()
void save (UserToVo transientInstance)
void save (int userId, int idVo)
List< UserToVo > findById (int userId)
List< Vo > findVoByUserId (int userId)
void delete (int userId, int idVo)
boolean setDefault (int userId, int idVo)
UserToVo findById (int userId, int idVo)
void update (UserToVo utv)
String findDefaultVo (int userId)
String getDefaultFqan (int userId)
int getNumberOfUserToVo (int userId)
Private Attributes
UserToVoDAO userToVoDAO
UserInfoDAO userInfoDAO
VoDAO voDAO
Static Private Attributes
static final Logger log
Detailed Description
Home object for domain model class UserToVo.
See also
portal.registration.services.UserToVo
Author
Hibernate Tools
Definition at line 28 of file UserToVoServiceImpl.java.
Constructor & Destructor Documentation
portal.registration.services.UserToVoServiceImpl.UserToVoServiceImpl ()
Definition at line 42 of file UserToVoServiceImpl.java.
                                     
        
Member Function Documentation
void portal.registration.services.UserToVoServiceImpl.delete (int userId, int idVo)
Implements portal.registration.services.UserToVoService.
Definition at line 98 of file UserToVoServiceImpl.java.
References portal.registration.dao.UserToVoDAO.delete(), and portal.registration.services.UserToVoServiceImpl.userToVoDAO.
                                                 
                userToVoDAO.delete(userId, idVo);
        
List<UserToVo> portal.registration.services.UserToVoServiceImpl.findById (int userId)
Implements portal.registration.services.UserToVoService.
Definition at line 75 of file UserToVoServiceImpl.java.
References portal.registration.dao.UserToVoDAO.findById(), portal.registration.dao.UserInfoDAO.findById(), portal.registration.services.UserToVoServiceImpl.userInfoDAO, and portal.registration.services.UserToVoServiceImpl.userToVoDAO.
Referenced by portal.registration.services.UserToVoServiceImpl.findDefaultVo(), and portal.registration.services.UserToVoServiceImpl.getDefaultFqan().
                                                   
                UserInfo userInfo = userInfoDAO.findById(userId);
                return userToVoDAO.findById(userInfo);
        
UserToVo portal.registration.services.UserToVoServiceImpl.findById (int userId, int idVo)
Implements portal.registration.services.UserToVoService.
Definition at line 132 of file UserToVoServiceImpl.java.
References portal.registration.dao.UserToVoDAO.findByIds(), and portal.registration.services.UserToVoServiceImpl.userToVoDAO.
                                                       
                return userToVoDAO.findByIds(userId, idVo);
        
String portal.registration.services.UserToVoServiceImpl.findDefaultVo (int userId)
Implements portal.registration.services.UserToVoService.
Definition at line 143 of file UserToVoServiceImpl.java.
References portal.registration.dao.VoDAO.findById(), portal.registration.services.UserToVoServiceImpl.findById(), portal.registration.domain.UserToVoId.getIdVo(), portal.registration.domain.Vo.getVo(), and portal.registration.services.UserToVoServiceImpl.voDAO.
                                                
                List<UserToVo> utvs = findById(userId);
                UserToVoId utvId = null;
                Vo vo = null;
                String voName = null;
                for (int i = 0; i < utvs.size(); i++)
                        if (utvs.get(i).getIsDefault().equals("true"))
                                utvId = utvs.get(i).getId();
                                vo = voDAO.findById(utvId.getIdVo());
                                voName = vo.getVo();
                                break;
                        
                
                return voName;
        
List<Vo> portal.registration.services.UserToVoServiceImpl.findVoByUserId (int userId)
Implements portal.registration.services.UserToVoService.
Definition at line 81 of file UserToVoServiceImpl.java.
References portal.registration.dao.UserToVoDAO.findById(), portal.registration.dao.UserInfoDAO.findById(), portal.registration.dao.UserToVoDAO.getVoByUserToVo(), portal.registration.services.UserToVoServiceImpl.userInfoDAO, and portal.registration.services.UserToVoServiceImpl.userToVoDAO.
                                                   
                UserInfo userInfo = userInfoDAO.findById(userId);
                List<UserToVo> utvs = userToVoDAO.findById(userInfo);
                List<Vo> vos = new ArrayList<Vo>();
                for (int i = 0; i < utvs.size(); i++)
                        vos.add(userToVoDAO.getVoByUserToVo(utvs.get(i)));
                
                return vos;
        
String portal.registration.services.UserToVoServiceImpl.getDefaultFqan (int userId)
Implements portal.registration.services.UserToVoService.
Definition at line 160 of file UserToVoServiceImpl.java.
References portal.registration.services.UserToVoServiceImpl.findById().
                                                 
                List<UserToVo> utvs = findById(userId);
                String fqan = null;
                for (int i = 0; i < utvs.size(); i++)
                        if (utvs.get(i).getIsDefault().equals("true"))
                                fqan = utvs.get(i).getFqans();
                                break;
                        
                
                return fqan;
        
int portal.registration.services.UserToVoServiceImpl.getNumberOfUserToVo (int userId)
Implements portal.registration.services.UserToVoService.
Definition at line 174 of file UserToVoServiceImpl.java.
References portal.registration.dao.UserToVoDAO.getNumberOfUserToVo(), and portal.registration.services.UserToVoServiceImpl.userToVoDAO.
                                                   
                return userToVoDAO.getNumberOfUserToVo(userId);
        
void portal.registration.services.UserToVoServiceImpl.save (int userId, int idVo)
Implements portal.registration.services.UserToVoService.
Definition at line 53 of file UserToVoServiceImpl.java.
References portal.registration.dao.VoDAO.findById(), portal.registration.dao.UserInfoDAO.findById(), portal.registration.services.UserToVoServiceImpl.log, portal.registration.dao.UserToVoDAO.save(), portal.registration.domain.UserToVo.setId(), portal.registration.domain.UserToVo.setIsDefault(), portal.registration.domain.UserToVo.setUserInfo(), portal.registration.domain.UserToVo.setVo(), portal.registration.services.UserToVoServiceImpl.userInfoDAO, portal.registration.services.UserToVoServiceImpl.userToVoDAO, and portal.registration.services.UserToVoServiceImpl.voDAO.
                                               
                log.debug("persisting UserToVoService instance");
                UserToVo transientInstance = new UserToVo();
                UserToVoId utvid = new UserToVoId(userId, idVo);
                transientInstance.setId(utvid);
                UserInfo userInfo = userInfoDAO.findById(userId);
                Vo vo = voDAO.findById(idVo);
                transientInstance.setUserInfo(userInfo);
                transientInstance.setVo(vo);
                transientInstance.setIsDefault("false");
                userToVoDAO.save(transientInstance);
        
void portal.registration.services.UserToVoServiceImpl.save (UserToVo transientInstance)
Implements portal.registration.services.UserToVoService.
Definition at line 47 of file UserToVoServiceImpl.java.
References portal.registration.services.UserToVoServiceImpl.log, portal.registration.dao.UserToVoDAO.save(), and portal.registration.services.UserToVoServiceImpl.userToVoDAO.
                                                     
                log.debug("persisting UserToVoService instance");
                userToVoDAO.save(transientInstance);
        
boolean portal.registration.services.UserToVoServiceImpl.setDefault (int userId, int idVo)
Implements portal.registration.services.UserToVoService.
Definition at line 105 of file UserToVoServiceImpl.java.
References portal.registration.dao.UserToVoDAO.findById(), portal.registration.dao.UserInfoDAO.findById(), portal.registration.dao.UserToVoDAO.findByIds(), portal.registration.domain.UserToVo.getIsDefault(), portal.registration.domain.UserToVo.setIsDefault(), portal.registration.dao.UserToVoDAO.update(), portal.registration.services.UserToVoServiceImpl.userInfoDAO, and portal.registration.services.UserToVoServiceImpl.userToVoDAO.
                                                        
                UserToVo toUpdate = userToVoDAO.findByIds(userId, idVo);
                if (!toUpdate.getIsDefault().equals("true"))
                        UserInfo userInfo = userInfoDAO.findById(userId);
                        List<UserToVo> utvs = userToVoDAO.findById(userInfo);
                        UserToVo temp = null;
                        for (int i = 0; i < utvs.size(); i++)
                                temp = utvs.get(i);
                                temp.setIsDefault("false");
                                userToVoDAO.update(temp);
                        
                        toUpdate.setIsDefault("true");
                        userToVoDAO.update(temp);
                        return true;
                
                return false;
        
void portal.registration.services.UserToVoServiceImpl.update (UserToVo utv)
Implements portal.registration.services.UserToVoService.
Definition at line 137 of file UserToVoServiceImpl.java.
References portal.registration.dao.UserToVoDAO.update(), and portal.registration.services.UserToVoServiceImpl.userToVoDAO.
                                         
                userToVoDAO.update(utv);
        
Member Data Documentation
final Logger portal.registration.services.UserToVoServiceImpl.log [static, private]
Initial value:
 Logger
                        .getLogger(UserInfoServiceImpl.class)
Definition at line 30 of file UserToVoServiceImpl.java.
Referenced by portal.registration.services.UserToVoServiceImpl.save().
UserInfoDAO portal.registration.services.UserToVoServiceImpl.userInfoDAO [private]
Definition at line 37 of file UserToVoServiceImpl.java.
Referenced by portal.registration.services.UserToVoServiceImpl.findById(), portal.registration.services.UserToVoServiceImpl.findVoByUserId(), portal.registration.services.UserToVoServiceImpl.save(), and portal.registration.services.UserToVoServiceImpl.setDefault().
UserToVoDAO portal.registration.services.UserToVoServiceImpl.userToVoDAO [private]
Definition at line 34 of file UserToVoServiceImpl.java.
Referenced by portal.registration.services.UserToVoServiceImpl.delete(), portal.registration.services.UserToVoServiceImpl.findById(), portal.registration.services.UserToVoServiceImpl.findVoByUserId(), portal.registration.services.UserToVoServiceImpl.getNumberOfUserToVo(), portal.registration.services.UserToVoServiceImpl.save(), portal.registration.services.UserToVoServiceImpl.setDefault(), and portal.registration.services.UserToVoServiceImpl.update().
VoDAO portal.registration.services.UserToVoServiceImpl.voDAO [private]
Definition at line 40 of file UserToVoServiceImpl.java.
Referenced by portal.registration.services.UserToVoServiceImpl.findDefaultVo(), and portal.registration.services.UserToVoServiceImpl.save().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/services/UserToVoServiceImpl.java