org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton Class Reference
Public Member Functions
VOMSACLSoapBindingSkeleton ()
VOMSACLSoapBindingSkeleton (org.glite.security.voms.service.acl.VOMSACL impl)
org.glite.security.voms.service.acl.ACLEntry[] getACL (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void setACL (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry[] in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void addACLEntry (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry in1, boolean in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void removeACLEntry (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry in1, boolean in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.service.acl.ACLEntry[] getDefaultACL (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void setDefaultACL (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry[] in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void addDefaultACLEntry (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void removeDefaultACLEntry (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Static Public Member Functions
static java.util.List getOperationDescByName (java.lang.String methodName)
static java.util.Collection getOperationDescs ()
Static Package Functions
[static initializer]
Private Attributes
org.glite.security.voms.service.acl.VOMSACL impl
Static Private Attributes
static java.util.Map _myOperations = new java.util.Hashtable()
static java.util.Collection _myOperationsList = new java.util.ArrayList()
Detailed Description
Definition at line 10 of file VOMSACLSoapBindingSkeleton.java.
Constructor & Destructor Documentation
org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.VOMSACLSoapBindingSkeleton ()
Definition at line 181 of file VOMSACLSoapBindingSkeleton.java.
References org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.impl.
                                        
        this.impl = new org.glite.security.voms.service.acl.VOMSACLSoapBindingImp
      l();
    
org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.VOMSACLSoapBindingSkeleton (org.glite.security.voms.service.acl.VOMSACL impl)
Definition at line 185 of file VOMSACLSoapBindingSkeleton.java.
References org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.impl.
                                                                                 
             
        this.impl = impl;
    
Member Function Documentation
org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.[static initializer] () [static, package]
void org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.addACLEntry (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry in1, boolean in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.acl.VOMSACL.
Definition at line 199 of file VOMSACLSoapBindingSkeleton.java.
References org.glite.security.voms.service.acl.VOMSACL.addACLEntry(), and org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.impl.
    
        impl.addACLEntry(in0, in1, in2);
    
void org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.addDefaultACLEntry (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.acl.VOMSACL.
Definition at line 220 of file VOMSACLSoapBindingSkeleton.java.
References org.glite.security.voms.service.acl.VOMSACL.addDefaultACLEntry(), and org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.impl.
    
        impl.addDefaultACLEntry(in0, in1);
    
org.glite.security.voms.service.acl.ACLEntry [] org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.getACL (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.acl.VOMSACL.
Definition at line 188 of file VOMSACLSoapBindingSkeleton.java.
References org.glite.security.voms.service.acl.VOMSACL.getACL(), and org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.impl.
    
        org.glite.security.voms.service.acl.ACLEntry[] ret = impl.getACL(in0);
        return ret;
    
org.glite.security.voms.service.acl.ACLEntry [] org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.getDefaultACL (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.acl.VOMSACL.
Definition at line 209 of file VOMSACLSoapBindingSkeleton.java.
References org.glite.security.voms.service.acl.VOMSACL.getDefaultACL(), and org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.impl.
    
        org.glite.security.voms.service.acl.ACLEntry[] ret = impl.getDefaultACL(i
      n0);
        return ret;
    
static java.util.List org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.getOperationDescByName (java.lang.String methodName) [static]
Returns List of OperationDesc objects with this name
Definition at line 18 of file VOMSACLSoapBindingSkeleton.java.
References org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton._myOperations.
                                                                                 
          
        return (java.util.List)_myOperations.get(methodName);
    
static java.util.Collection org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.getOperationDescs () [static]
Returns Collection of OperationDescs
Definition at line 25 of file VOMSACLSoapBindingSkeleton.java.
References org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton._myOperationsList.
                                                           
        return _myOperationsList;
    
void org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.removeACLEntry (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry in1, boolean in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.acl.VOMSACL.
Definition at line 204 of file VOMSACLSoapBindingSkeleton.java.
References org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.impl, and org.glite.security.voms.service.acl.VOMSACL.removeACLEntry().
    
        impl.removeACLEntry(in0, in1, in2);
    
void org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.removeDefaultACLEntry (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.acl.VOMSACL.
Definition at line 225 of file VOMSACLSoapBindingSkeleton.java.
References org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.impl, and org.glite.security.voms.service.acl.VOMSACL.removeDefaultACLEntry().
    
        impl.removeDefaultACLEntry(in0, in1);
    
void org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.setACL (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry[] in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.acl.VOMSACL.
Definition at line 194 of file VOMSACLSoapBindingSkeleton.java.
References org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.impl, and org.glite.security.voms.service.acl.VOMSACL.setACL().
    
        impl.setACL(in0, in1);
    
void org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.setDefaultACL (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry[] in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.acl.VOMSACL.
Definition at line 215 of file VOMSACLSoapBindingSkeleton.java.
References org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.impl, and org.glite.security.voms.service.acl.VOMSACL.setDefaultACL().
    
        impl.setDefaultACL(in0, in1);
    
Member Data Documentation
java.util.Map org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton._myOperations = new java.util.Hashtable() [static, private]
Definition at line 12 of file VOMSACLSoapBindingSkeleton.java.
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.getOperationDescByName().
java.util.Collection org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton._myOperationsList = new java.util.ArrayList() [static, private]
Definition at line 13 of file VOMSACLSoapBindingSkeleton.java.
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.getOperationDescs().
org.glite.security.voms.service.acl.VOMSACL org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.impl [private]
Definition at line 11 of file VOMSACLSoapBindingSkeleton.java.
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.addACLEntry(), org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.addDefaultACLEntry(), org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.getACL(), org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.getDefaultACL(), org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.removeACLEntry(), org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.removeDefaultACLEntry(), org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.setACL(), org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.setDefaultACL(), and org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.VOMSACLSoapBindingSkeleton().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/acl/VOMSACLSoapBindingSkeleton.java