org.glite.security.voms.service.registration.RegistrationRequest Class Reference
Public Member Functions
RegistrationRequest ()
RegistrationRequest (boolean aupAccepted, java.lang.String comments, java.lang.String emailAddress, java.lang.String institute, java.lang.String phoneNumber)
boolean isAupAccepted ()
void setAupAccepted (boolean aupAccepted)
java.lang.String getComments ()
void setComments (java.lang.String comments)
java.lang.String getEmailAddress ()
void setEmailAddress (java.lang.String emailAddress)
java.lang.String getInstitute ()
void setInstitute (java.lang.String institute)
java.lang.String getPhoneNumber ()
void setPhoneNumber (java.lang.String phoneNumber)
synchronized boolean equals (java.lang.Object obj)
synchronized int hashCode ()
Private Attributes
boolean aupAccepted
java.lang.String comments
java.lang.String emailAddress
java.lang.String institute
java.lang.String phoneNumber
java.lang.Object __equalsCalc = null
boolean __hashCodeCalc = false
Detailed Description
Definition at line 10 of file RegistrationRequest.java.
Constructor & Destructor Documentation
org.glite.security.voms.service.registration.RegistrationRequest.RegistrationRequest ()
Definition at line 21 of file RegistrationRequest.java.
Referenced by org.glite.security.voms.service.registration.RegistrationRequest.equals().
                                 
    
org.glite.security.voms.service.registration.RegistrationRequest.RegistrationRequest (boolean aupAccepted, java.lang.String comments, java.lang.String emailAddress, java.lang.String institute, java.lang.String phoneNumber)
Definition at line 24 of file RegistrationRequest.java.
References org.glite.security.voms.service.registration.RegistrationRequest.aupAccepted, org.glite.security.voms.service.registration.RegistrationRequest.comments, org.glite.security.voms.service.registration.RegistrationRequest.emailAddress, org.glite.security.voms.service.registration.RegistrationRequest.institute, and org.glite.security.voms.service.registration.RegistrationRequest.phoneNumber.
                                         
           this.aupAccepted = aupAccepted;
           this.comments = comments;
           this.emailAddress = emailAddress;
           this.institute = institute;
           this.phoneNumber = phoneNumber;
    
Member Function Documentation
synchronized boolean org.glite.security.voms.service.registration.RegistrationRequest.equals (java.lang.Object obj)
Definition at line 138 of file RegistrationRequest.java.
References org.glite.security.voms.service.registration.RegistrationRequest.__equalsCalc, org.glite.security.voms.service.registration.RegistrationRequest.aupAccepted, org.glite.security.voms.service.registration.RegistrationRequest.comments, org.glite.security.voms.service.registration.RegistrationRequest.emailAddress, org.glite.security.voms.service.registration.RegistrationRequest.getComments(), org.glite.security.voms.service.registration.RegistrationRequest.getEmailAddress(), org.glite.security.voms.service.registration.RegistrationRequest.getInstitute(), org.glite.security.voms.service.registration.RegistrationRequest.getPhoneNumber(), org.glite.security.voms.service.registration.RegistrationRequest.institute, org.glite.security.voms.service.registration.RegistrationRequest.isAupAccepted(), org.glite.security.voms.service.registration.RegistrationRequest.phoneNumber, and org.glite.security.voms.service.registration.RegistrationRequest.RegistrationRequest().
                                                             
        if (!(obj instanceof RegistrationRequest)) return false;
        RegistrationRequest other = (RegistrationRequest) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null)
            return (__equalsCalc == obj);
        
        __equalsCalc = obj;
        boolean _equals;
        _equals = true &&
            this.aupAccepted == other.isAupAccepted() &&
            ((this.comments==null && other.getComments()==null) ||
             (this.comments!=null &&
              this.comments.equals(other.getComments()))) &&
            ((this.emailAddress==null && other.getEmailAddress()==null) ||
             (this.emailAddress!=null &&
              this.emailAddress.equals(other.getEmailAddress()))) &&
            ((this.institute==null && other.getInstitute()==null) ||
             (this.institute!=null &&
              this.institute.equals(other.getInstitute()))) &&
            ((this.phoneNumber==null && other.getPhoneNumber()==null) ||
             (this.phoneNumber!=null &&
              this.phoneNumber.equals(other.getPhoneNumber())));
        __equalsCalc = null;
        return _equals;
    
java.lang.String org.glite.security.voms.service.registration.RegistrationRequest.getComments ()
Gets the comments value for this RegistrationRequest.
Returns
comments
Definition at line 63 of file RegistrationRequest.java.
References org.glite.security.voms.service.registration.RegistrationRequest.comments.
Referenced by org.glite.security.voms.service.registration.RegistrationRequest.equals(), and org.glite.security.voms.service.registration.RegistrationRequest.hashCode().
                                          
        return comments;
    
java.lang.String org.glite.security.voms.service.registration.RegistrationRequest.getEmailAddress ()
Gets the emailAddress value for this RegistrationRequest.
Returns
emailAddress
Definition at line 83 of file RegistrationRequest.java.
References org.glite.security.voms.service.registration.RegistrationRequest.emailAddress.
Referenced by org.glite.security.voms.service.registration.RegistrationRequest.equals(), and org.glite.security.voms.service.registration.RegistrationRequest.hashCode().
                                              
        return emailAddress;
    
java.lang.String org.glite.security.voms.service.registration.RegistrationRequest.getInstitute ()
Gets the institute value for this RegistrationRequest.
Returns
institute
Definition at line 103 of file RegistrationRequest.java.
References org.glite.security.voms.service.registration.RegistrationRequest.institute.
Referenced by org.glite.security.voms.service.registration.RegistrationRequest.equals(), and org.glite.security.voms.service.registration.RegistrationRequest.hashCode().
                                           
        return institute;
    
java.lang.String org.glite.security.voms.service.registration.RegistrationRequest.getPhoneNumber ()
Gets the phoneNumber value for this RegistrationRequest.
Returns
phoneNumber
Definition at line 123 of file RegistrationRequest.java.
References org.glite.security.voms.service.registration.RegistrationRequest.phoneNumber.
Referenced by org.glite.security.voms.service.registration.RegistrationRequest.equals(), and org.glite.security.voms.service.registration.RegistrationRequest.hashCode().
                                             
        return phoneNumber;
    
synchronized int org.glite.security.voms.service.registration.RegistrationRequest.hashCode ()
Definition at line 167 of file RegistrationRequest.java.
References org.glite.security.voms.service.registration.RegistrationRequest.__hashCodeCalc, org.glite.security.voms.service.registration.RegistrationRequest.getComments(), org.glite.security.voms.service.registration.RegistrationRequest.getEmailAddress(), org.glite.security.voms.service.registration.RegistrationRequest.getInstitute(), org.glite.security.voms.service.registration.RegistrationRequest.getPhoneNumber(), and org.glite.security.voms.service.registration.RegistrationRequest.isAupAccepted().
                                       
        if (__hashCodeCalc)
            return 0;
        
        __hashCodeCalc = true;
        int _hashCode = 1;
        _hashCode += (isAupAccepted() ? Boolean.TRUE : Boolean.FALSE).hashCode();
      
        if (getComments() != null)
            _hashCode += getComments().hashCode();
        
        if (getEmailAddress() != null)
            _hashCode += getEmailAddress().hashCode();
        
        if (getInstitute() != null)
            _hashCode += getInstitute().hashCode();
        
        if (getPhoneNumber() != null)
            _hashCode += getPhoneNumber().hashCode();
        
        __hashCodeCalc = false;
        return _hashCode;
    
boolean org.glite.security.voms.service.registration.RegistrationRequest.isAupAccepted ()
Gets the aupAccepted value for this RegistrationRequest.
Returns
aupAccepted
Definition at line 43 of file RegistrationRequest.java.
References org.glite.security.voms.service.registration.RegistrationRequest.aupAccepted.
Referenced by org.glite.security.voms.service.registration.RegistrationRequest.equals(), and org.glite.security.voms.service.registration.RegistrationRequest.hashCode().
                                   
        return aupAccepted;
    
void org.glite.security.voms.service.registration.RegistrationRequest.setAupAccepted (boolean aupAccepted)
Sets the aupAccepted value for this RegistrationRequest.
Parameters
aupAccepted
Definition at line 53 of file RegistrationRequest.java.
References org.glite.security.voms.service.registration.RegistrationRequest.aupAccepted.
                                                    
        this.aupAccepted = aupAccepted;
    
void org.glite.security.voms.service.registration.RegistrationRequest.setComments (java.lang.String comments)
Sets the comments value for this RegistrationRequest.
Parameters
comments
Definition at line 73 of file RegistrationRequest.java.
References org.glite.security.voms.service.registration.RegistrationRequest.comments.
                                                       
        this.comments = comments;
    
void org.glite.security.voms.service.registration.RegistrationRequest.setEmailAddress (java.lang.String emailAddress)
Sets the emailAddress value for this RegistrationRequest.
Parameters
emailAddress
Definition at line 93 of file RegistrationRequest.java.
References org.glite.security.voms.service.registration.RegistrationRequest.emailAddress.
                                                               
        this.emailAddress = emailAddress;
    
void org.glite.security.voms.service.registration.RegistrationRequest.setInstitute (java.lang.String institute)
Sets the institute value for this RegistrationRequest.
Parameters
institute
Definition at line 113 of file RegistrationRequest.java.
References org.glite.security.voms.service.registration.RegistrationRequest.institute.
                                                         
        this.institute = institute;
    
void org.glite.security.voms.service.registration.RegistrationRequest.setPhoneNumber (java.lang.String phoneNumber)
Sets the phoneNumber value for this RegistrationRequest.
Parameters
phoneNumber
Definition at line 133 of file RegistrationRequest.java.
References org.glite.security.voms.service.registration.RegistrationRequest.phoneNumber.
                                                             
        this.phoneNumber = phoneNumber;
    
Member Data Documentation
java.lang.Object org.glite.security.voms.service.registration.RegistrationRequest.__equalsCalc = null [private]
Definition at line 137 of file RegistrationRequest.java.
Referenced by org.glite.security.voms.service.registration.RegistrationRequest.equals().
boolean org.glite.security.voms.service.registration.RegistrationRequest.__hashCodeCalc = false [private]
Definition at line 166 of file RegistrationRequest.java.
Referenced by org.glite.security.voms.service.registration.RegistrationRequest.hashCode().
boolean org.glite.security.voms.service.registration.RegistrationRequest.aupAccepted [private]
Definition at line 11 of file RegistrationRequest.java.
Referenced by org.glite.security.voms.service.registration.RegistrationRequest.equals(), org.glite.security.voms.service.registration.RegistrationRequest.isAupAccepted(), org.glite.security.voms.service.registration.RegistrationRequest.RegistrationRequest(), and org.glite.security.voms.service.registration.RegistrationRequest.setAupAccepted().
java.lang.String org.glite.security.voms.service.registration.RegistrationRequest.comments [private]
Definition at line 13 of file RegistrationRequest.java.
Referenced by org.glite.security.voms.service.registration.RegistrationRequest.equals(), org.glite.security.voms.service.registration.RegistrationRequest.getComments(), org.glite.security.voms.service.registration.RegistrationRequest.RegistrationRequest(), and org.glite.security.voms.service.registration.RegistrationRequest.setComments().
java.lang.String org.glite.security.voms.service.registration.RegistrationRequest.emailAddress [private]
Definition at line 15 of file RegistrationRequest.java.
Referenced by org.glite.security.voms.service.registration.RegistrationRequest.equals(), org.glite.security.voms.service.registration.RegistrationRequest.getEmailAddress(), org.glite.security.voms.service.registration.RegistrationRequest.RegistrationRequest(), and org.glite.security.voms.service.registration.RegistrationRequest.setEmailAddress().
java.lang.String org.glite.security.voms.service.registration.RegistrationRequest.institute [private]
Definition at line 17 of file RegistrationRequest.java.
Referenced by org.glite.security.voms.service.registration.RegistrationRequest.equals(), org.glite.security.voms.service.registration.RegistrationRequest.getInstitute(), org.glite.security.voms.service.registration.RegistrationRequest.RegistrationRequest(), and org.glite.security.voms.service.registration.RegistrationRequest.setInstitute().
java.lang.String org.glite.security.voms.service.registration.RegistrationRequest.phoneNumber [private]
Definition at line 19 of file RegistrationRequest.java.
Referenced by org.glite.security.voms.service.registration.RegistrationRequest.equals(), org.glite.security.voms.service.registration.RegistrationRequest.getPhoneNumber(), org.glite.security.voms.service.registration.RegistrationRequest.RegistrationRequest(), and org.glite.security.voms.service.registration.RegistrationRequest.setPhoneNumber().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/registration/RegistrationRequest.java