portal.registration.dao.UserInfoDAOImpl Class Reference
Public Member Functions
Integer save (UserInfo transientInstance)
void delete (UserInfo persistentInstance)
UserInfo findById (Integer id)
List< UserInfo > getAllUserInfo ()
void edit (UserInfo userInfo)
Private Attributes
SessionFactory sessionFactory
Static Private Attributes
static final Logger log = Logger.getLogger(UserInfoDAOImpl.class)
Detailed Description
Definition at line 15 of file UserInfoDAOImpl.java.
Member Function Documentation
void portal.registration.dao.UserInfoDAOImpl.delete (UserInfo persistentInstance)
Implements portal.registration.dao.UserInfoDAO.
Definition at line 35 of file UserInfoDAOImpl.java.
References portal.registration.dao.UserInfoDAOImpl.log, and portal.registration.dao.UserInfoDAOImpl.sessionFactory.
                                                        
                log.debug("removing UserInfo instance");
                try
                        Session session = sessionFactory.getCurrentSession();
                        session.delete(persistentInstance);
                        log.debug("remove successful");
                 catch (RuntimeException re)
                        log.error("remove failed", re);
                        throw re;
                
        
void portal.registration.dao.UserInfoDAOImpl.edit (UserInfo userInfo)
Implements portal.registration.dao.UserInfoDAO.
Definition at line 78 of file UserInfoDAOImpl.java.
References portal.registration.domain.UserInfo.getFirstName(), portal.registration.domain.UserInfo.getInstitute(), portal.registration.domain.UserInfo.getLastName(), portal.registration.domain.UserInfo.getMail(), portal.registration.domain.UserInfo.getPhone(), portal.registration.domain.UserInfo.getUserId(), portal.registration.domain.UserInfo.getUsername(), portal.registration.dao.UserInfoDAOImpl.log, portal.registration.dao.UserInfoDAOImpl.sessionFactory, portal.registration.domain.UserInfo.setFirstName(), portal.registration.domain.UserInfo.setInstitute(), portal.registration.domain.UserInfo.setLastName(), portal.registration.domain.UserInfo.setMail(), portal.registration.domain.UserInfo.setPhone(), portal.registration.domain.UserInfo.setRegistrationComplete(), and portal.registration.domain.UserInfo.setUsername().
                                            
                log.debug("Editing existing userInfo");
                // Retrieve session from Hibernate
                Session session = sessionFactory.getCurrentSession();
                // Retrieve existing userInfo via id
                UserInfo existingUserInfo = (UserInfo) session.get(UserInfo.class
      ,
                                userInfo.getUserId());
                // Assign updated values to this userInfo
                existingUserInfo.setFirstName(userInfo.getFirstName());
                existingUserInfo.setLastName(userInfo.getLastName());
                existingUserInfo.setInstitute(userInfo.getInstitute());
                existingUserInfo.setPhone(userInfo.getPhone());
                existingUserInfo.setMail(userInfo.getMail());
                existingUserInfo.setUsername(userInfo.getUsername());
                existingUserInfo.setRegistrationComplete(userInfo
                                .getRegistrationComplete());
                // Save updates
                session.save(existingUserInfo);
        
UserInfo portal.registration.dao.UserInfoDAOImpl.findById (Integer id)
Implements portal.registration.dao.UserInfoDAO.
Definition at line 47 of file UserInfoDAOImpl.java.
References portal.registration.dao.UserInfoDAOImpl.log, and portal.registration.dao.UserInfoDAOImpl.sessionFactory.
                                             
                log.debug("getting UserInfo instance with id: " + id);
                try
                        Session session = sessionFactory.getCurrentSession();
                        UserInfo instance = (UserInfo) session.get(UserInfo.class
      , id);
                        log.debug("get successful");
                        return instance;
                 catch (RuntimeException re)
                        log.error("get failed", re);
                        throw re;
                
        
List<UserInfo> portal.registration.dao.UserInfoDAOImpl.getAllUserInfo ()
Implements portal.registration.dao.UserInfoDAO.
Definition at line 61 of file UserInfoDAOImpl.java.
References portal.registration.dao.UserInfoDAOImpl.log, and portal.registration.dao.UserInfoDAOImpl.sessionFactory.
                                               
                log.debug("getting all UserInfo instance");
                try
                        Session session = sessionFactory.getCurrentSession();
                        // Create a Hibernate query (HQL)
                        Query query = session.createQuery("FROM UserInfo");
                        // Retrieve all
                        return query.list();
                 catch (RuntimeException re)
                        log.error("get failed", re);
                        throw re;
                
        
Integer portal.registration.dao.UserInfoDAOImpl.save (UserInfo transientInstance)
Implements portal.registration.dao.UserInfoDAO.
Definition at line 22 of file UserInfoDAOImpl.java.
References portal.registration.dao.UserInfoDAOImpl.log, and portal.registration.dao.UserInfoDAOImpl.sessionFactory.
                                                        
                log.debug("persisting UserInfo instance");
                try
                        Session session = sessionFactory.getCurrentSession();
                        int id = (Integer) session.save(transientInstance);
                        log.debug("persist successful");
                        return id;
                 catch (RuntimeException re)
                        log.error("persist failed", re);
                        throw re;
                
        
Member Data Documentation
final Logger portal.registration.dao.UserInfoDAOImpl.log = Logger.getLogger(UserInfoDAOImpl.class) [static, private]
Definition at line 17 of file UserInfoDAOImpl.java.
Referenced by portal.registration.dao.UserInfoDAOImpl.delete(), portal.registration.dao.UserInfoDAOImpl.edit(), portal.registration.dao.UserInfoDAOImpl.findById(), portal.registration.dao.UserInfoDAOImpl.getAllUserInfo(), and portal.registration.dao.UserInfoDAOImpl.save().
SessionFactory portal.registration.dao.UserInfoDAOImpl.sessionFactory [private]
Definition at line 20 of file UserInfoDAOImpl.java.
Referenced by portal.registration.dao.UserInfoDAOImpl.delete(), portal.registration.dao.UserInfoDAOImpl.edit(), portal.registration.dao.UserInfoDAOImpl.findById(), portal.registration.dao.UserInfoDAOImpl.getAllUserInfo(), and portal.registration.dao.UserInfoDAOImpl.save().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/dao/UserInfoDAOImpl.java