portal.registration.services.VoServiceImpl Class Reference
Public Member Functions
List< Vo > getAllVo ()
Vo findById (Integer id)
String findByVo (Vo vo)
List< String > getAllDiscplines ()
Private Attributes
VoDAO voDAO
Static Private Attributes
static final Logger log
Detailed Description
Definition at line 14 of file VoServiceImpl.java.
Member Function Documentation
Vo portal.registration.services.VoServiceImpl.findById (Integer id)
Implements portal.registration.services.VoService.
Definition at line 29 of file VoServiceImpl.java.
References portal.registration.dao.VoDAO.findById(), portal.registration.services.VoServiceImpl.log, and portal.registration.services.VoServiceImpl.voDAO.
                                       
                log.debug("getting UserInfo instance with id: " + id);
                return voDAO.findById(id);
        
String portal.registration.services.VoServiceImpl.findByVo (Vo vo)
Implements portal.registration.services.VoService.
Definition at line 35 of file VoServiceImpl.java.
References portal.registration.dao.VoDAO.findById(), portal.registration.domain.Vo.getIdVo(), portal.registration.services.VoServiceImpl.log, and portal.registration.services.VoServiceImpl.voDAO.
                                      
                log.debug("getting Vo instance");
                return voDAO.findById(vo.getIdVo()).getVo();
        
List<String> portal.registration.services.VoServiceImpl.getAllDiscplines ()
Implements portal.registration.services.VoService.
Definition at line 41 of file VoServiceImpl.java.
References portal.registration.dao.VoDAO.getAllDiscipline(), and portal.registration.services.VoServiceImpl.voDAO.
                                               
                return voDAO.getAllDiscipline();
        
List<Vo> portal.registration.services.VoServiceImpl.getAllVo ()
Implements portal.registration.services.VoService.
Definition at line 23 of file VoServiceImpl.java.
References portal.registration.dao.VoDAO.getAllVo(), portal.registration.services.VoServiceImpl.log, and portal.registration.services.VoServiceImpl.voDAO.
                                   
                log.debug("getting all Vo instance");
                return voDAO.getAllVo();
        
Member Data Documentation
final Logger portal.registration.services.VoServiceImpl.log [static, private]
Initial value:
 Logger
                        .getLogger(UserInfoServiceImpl.class)
Definition at line 16 of file VoServiceImpl.java.
Referenced by portal.registration.services.VoServiceImpl.findById(), portal.registration.services.VoServiceImpl.findByVo(), and portal.registration.services.VoServiceImpl.getAllVo().
VoDAO portal.registration.services.VoServiceImpl.voDAO [private]
Definition at line 20 of file VoServiceImpl.java.
Referenced by portal.registration.services.VoServiceImpl.findById(), portal.registration.services.VoServiceImpl.findByVo(), portal.registration.services.VoServiceImpl.getAllDiscplines(), and portal.registration.services.VoServiceImpl.getAllVo().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/services/VoServiceImpl.java