portal.registration.controller.AddUserToVoPresentsController Class Reference
Public Member Functions
UserInfo getCommandObject ()
List< Vo > getUserToVoList (@RequestParam int userId)
String showUserInfoForm (@RequestParam int userId, RenderRequest request)
void goToAddUserToVOForm (ActionRequest request, ActionResponse response, SessionStatus sessionStatus)
List< Vo > getVos ()
void userToVoComplete (ActionResponse response, SessionStatus sessionStatus)
Private Member Functions
void deactivateUser (int userId, RenderRequest request)
Private Attributes
VoService voService
UserToVoService userToVoService
UserInfoService userInfoService
Detailed Description
Definition at line 32 of file AddUserToVoPresentsController.java.
Member Function Documentation
void portal.registration.controller.AddUserToVoPresentsController.deactivateUser (int userId, RenderRequest request) [private]
Definition at line 65 of file AddUserToVoPresentsController.java.
References portal.registration.services.UserInfoService.edit(), portal.registration.services.UserInfoService.findById(), portal.registration.domain.UserInfo.getRegistrationComplete(), portal.registration.domain.UserInfo.getUsername(), and portal.registration.domain.UserInfo.setRegistrationComplete().
                                                                       
                UserInfo userInfo = userInfoService.findById(userId);
                if (userInfo.getRegistrationComplete().equals("true"))
                        String username = userInfo.getUsername();
                        long companyId = PortalUtil.getCompanyId(request);
                        User user;
                        try
                                user = UserLocalServiceUtil.getUserByScreenName(c
      ompanyId,
                                                username);
                                UserLocalServiceUtil.deleteRoleUser((long) 10140,
      
                                                user.getUserId());
                                userInfo.setRegistrationComplete("false");
                                userInfoService.edit(userInfo);
                         catch (PortalException e)
                                SessionErrors.add(request, "exception-deactivatio
      n-user");
                                e.printStackTrace();
                         catch (SystemException e)
                                SessionErrors.add(request, "exception-deactivatio
      n-user");
                                e.printStackTrace();
                        
                
        
UserInfo portal.registration.controller.AddUserToVoPresentsController.getCommandObject ()
Definition at line 44 of file AddUserToVoPresentsController.java.
                                           
                return new UserInfo();
        
List<Vo> portal.registration.controller.AddUserToVoPresentsController.getUserToVoList (@RequestParam int userId)
Definition at line 49 of file AddUserToVoPresentsController.java.
References portal.registration.services.UserToVoService.findVoByUserId().
                                                                  
                return userToVoService.findVoByUserId(userId);
        
List<Vo> portal.registration.controller.AddUserToVoPresentsController.getVos ()
Definition at line 114 of file AddUserToVoPresentsController.java.
References portal.registration.services.VoService.getAllVo().
                                 
                return voService.getAllVo();
        
void portal.registration.controller.AddUserToVoPresentsController.goToAddUserToVOForm (ActionRequest request, ActionResponse response, SessionStatus sessionStatus)
Definition at line 99 of file AddUserToVoPresentsController.java.
                                                                              
                int userId = Integer.parseInt(request.getParameter("userId"));
                response.setRenderParameter("myaction", "showAddUserToVO");
                response.setRenderParameter("userId", Integer.toString(userId));
                // log.info("firstReg = " +
                // ((request.getParameter("firstReg")==null)?"null":request.getPa
      rameter("firstReg")));
                request.setAttribute("firstReg", request.getParameter("firstReg")
      );
                sessionStatus.setComplete();
        
String portal.registration.controller.AddUserToVoPresentsController.showUserInfoForm (@RequestParam int userId, RenderRequest request)
Definition at line 55 of file AddUserToVoPresentsController.java.
References portal.registration.services.UserToVoService.findById().
                                               
                if (userToVoService.findById(userId).size() == 0)
                        deactivateUser(userId, request);
                        SessionMessages.add(request, "user-deactivate");
                
                return "addUserToVoPresents";
        
void portal.registration.controller.AddUserToVoPresentsController.userToVoComplete (ActionResponse response, SessionStatus sessionStatus)
Definition at line 119 of file AddUserToVoPresentsController.java.
                                                     
                response.setRenderParameter("myaction", "userInfos");
                sessionStatus.setComplete();
        
Member Data Documentation
UserInfoService portal.registration.controller.AddUserToVoPresentsController.userInfoService [private]
Definition at line 41 of file AddUserToVoPresentsController.java.
UserToVoService portal.registration.controller.AddUserToVoPresentsController.userToVoService [private]
Definition at line 38 of file AddUserToVoPresentsController.java.
VoService portal.registration.controller.AddUserToVoPresentsController.voService [private]
Definition at line 35 of file AddUserToVoPresentsController.java.
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/controller/AddUserToVoPresentsController.java