portal.registration.services.UserInfoServiceImpl Class Reference
Public Member Functions
Integer save (UserInfo transientInstance)
void delete (UserInfo persistentInstance)
void delete (int userId)
UserInfo findById (Integer id)
List< UserInfo > getAllUserInfo ()
void edit (UserInfo userInfo)
int save (UserInfo userInfo, int idIDP)
Private Attributes
UserInfoDAO userInfoDAO
IdpDAO idpDAO
Static Private Attributes
static final Logger log
Detailed Description
Definition at line 17 of file UserInfoServiceImpl.java.
Member Function Documentation
void portal.registration.services.UserInfoServiceImpl.delete (UserInfo persistentInstance)
Implements portal.registration.services.UserInfoService.
Definition at line 35 of file UserInfoServiceImpl.java.
References portal.registration.dao.UserInfoDAO.delete(), portal.registration.services.UserInfoServiceImpl.log, and portal.registration.services.UserInfoServiceImpl.userInfoDAO.
                                                        
                log.debug("removing UserInfo instance");
                userInfoDAO.delete(persistentInstance);
        
void portal.registration.services.UserInfoServiceImpl.delete (int userId)
Implements portal.registration.services.UserInfoService.
Definition at line 41 of file UserInfoServiceImpl.java.
References portal.registration.dao.UserInfoDAO.delete(), portal.registration.dao.UserInfoDAO.findById(), portal.registration.services.UserInfoServiceImpl.log, and portal.registration.services.UserInfoServiceImpl.userInfoDAO.
                                       
                log.debug("removing UserInfo instance");
                UserInfo persistentInstance = userInfoDAO.findById(userId);
                userInfoDAO.delete(persistentInstance);
        
void portal.registration.services.UserInfoServiceImpl.edit (UserInfo userInfo)
Implements portal.registration.services.UserInfoService.
Definition at line 60 of file UserInfoServiceImpl.java.
References portal.registration.dao.UserInfoDAO.edit(), portal.registration.services.UserInfoServiceImpl.log, and portal.registration.services.UserInfoServiceImpl.userInfoDAO.
                                            
                log.debug("Editing existing userInfo");
                userInfoDAO.edit(userInfo);
        
UserInfo portal.registration.services.UserInfoServiceImpl.findById (Integer id)
Implements portal.registration.services.UserInfoService.
Definition at line 48 of file UserInfoServiceImpl.java.
References portal.registration.dao.UserInfoDAO.findById(), portal.registration.services.UserInfoServiceImpl.log, and portal.registration.services.UserInfoServiceImpl.userInfoDAO.
                                             
                log.debug("getting UserInfo instance with id: " + id);
                return userInfoDAO.findById(id);
        
List<UserInfo> portal.registration.services.UserInfoServiceImpl.getAllUserInfo ()
Implements portal.registration.services.UserInfoService.
Definition at line 54 of file UserInfoServiceImpl.java.
References portal.registration.dao.UserInfoDAO.getAllUserInfo(), portal.registration.services.UserInfoServiceImpl.log, and portal.registration.services.UserInfoServiceImpl.userInfoDAO.
                                               
                log.debug("getting all UserInfo instance");
                return userInfoDAO.getAllUserInfo();
        
int portal.registration.services.UserInfoServiceImpl.save (UserInfo userInfo, int idIDP)
Implements portal.registration.services.UserInfoService.
Definition at line 66 of file UserInfoServiceImpl.java.
References portal.registration.dao.IdpDAO.findById(), portal.registration.services.UserInfoServiceImpl.idpDAO, portal.registration.services.UserInfoServiceImpl.log, portal.registration.dao.UserInfoDAO.save(), portal.registration.domain.UserInfo.setIdp(), and portal.registration.services.UserInfoServiceImpl.userInfoDAO.
                                                      
                log.debug("persisting UserInfo instance");
                Idp idp = idpDAO.findById(idIDP);
                userInfo.setIdp(idp);
                return userInfoDAO.save(userInfo);
        
Integer portal.registration.services.UserInfoServiceImpl.save (UserInfo transientInstance)
Implements portal.registration.services.UserInfoService.
Definition at line 29 of file UserInfoServiceImpl.java.
References portal.registration.services.UserInfoServiceImpl.log, portal.registration.dao.UserInfoDAO.save(), and portal.registration.services.UserInfoServiceImpl.userInfoDAO.
                                                        
                log.debug("persisting UserInfo instance");
                return userInfoDAO.save(transientInstance);
        
Member Data Documentation
IdpDAO portal.registration.services.UserInfoServiceImpl.idpDAO [private]
Definition at line 26 of file UserInfoServiceImpl.java.
Referenced by portal.registration.services.UserInfoServiceImpl.save().
final Logger portal.registration.services.UserInfoServiceImpl.log [static, private]
Initial value:
 Logger
                        .getLogger(UserInfoServiceImpl.class)
Definition at line 19 of file UserInfoServiceImpl.java.
Referenced by portal.registration.services.UserInfoServiceImpl.delete(), portal.registration.services.UserInfoServiceImpl.edit(), portal.registration.services.UserInfoServiceImpl.findById(), portal.registration.services.UserInfoServiceImpl.getAllUserInfo(), and portal.registration.services.UserInfoServiceImpl.save().
UserInfoDAO portal.registration.services.UserInfoServiceImpl.userInfoDAO [private]
Definition at line 23 of file UserInfoServiceImpl.java.
Referenced by portal.registration.services.UserInfoServiceImpl.delete(), portal.registration.services.UserInfoServiceImpl.edit(), portal.registration.services.UserInfoServiceImpl.findById(), portal.registration.services.UserInfoServiceImpl.getAllUserInfo(), and portal.registration.services.UserInfoServiceImpl.save().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/services/UserInfoServiceImpl.java