portal.registration.services.CertificateServiceImpl Class Reference
Public Member Functions
Integer save (Certificate transientInstance)
void delete (Certificate persistentInstance)
void delete (int idCert)
int save (Certificate certificate, int userId)
List< Certificate > findById (int userId)
boolean setDefault (int idCert)
Private Attributes
CertificateDAO certificateDAO
UserInfoDAO userInfoDAO
Static Private Attributes
static final Logger log
Detailed Description
Home object for domain model class UserInfo.
See also
portal.registration.services.UserInfo
Author
Hibernate Tools
Definition at line 28 of file CertificateServiceImpl.java.
Member Function Documentation
void portal.registration.services.CertificateServiceImpl.delete (Certificate persistentInstance)
Implements portal.registration.services.CertificateService.
Definition at line 46 of file CertificateServiceImpl.java.
References portal.registration.services.CertificateServiceImpl.certificateDAO, portal.registration.dao.CertificateDAO.delete(), and portal.registration.services.CertificateServiceImpl.log.
                                                           
                log.debug("removing UserInfo instance");
                certificateDAO.delete(persistentInstance);
        
void portal.registration.services.CertificateServiceImpl.delete (int idCert)
Implements portal.registration.services.CertificateService.
Definition at line 52 of file CertificateServiceImpl.java.
References portal.registration.services.CertificateServiceImpl.certificateDAO, portal.registration.dao.CertificateDAO.delete(), portal.registration.dao.CertificateDAO.findById(), and portal.registration.services.CertificateServiceImpl.log.
                                       
                log.debug("removing UserInfo instance");
                Certificate persistentInstance = certificateDAO.findById(idCert);
      
                certificateDAO.delete(persistentInstance);
        
List<Certificate> portal.registration.services.CertificateServiceImpl.findById (int userId)
Implements portal.registration.services.CertificateService.
Definition at line 91 of file CertificateServiceImpl.java.
References portal.registration.services.CertificateServiceImpl.certificateDAO, portal.registration.dao.CertificateDAO.findById(), portal.registration.dao.UserInfoDAO.findById(), and portal.registration.services.CertificateServiceImpl.userInfoDAO.
                                                      
                UserInfo userInfo = userInfoDAO.findById(userId);
                return certificateDAO.findById(userInfo);
        
int portal.registration.services.CertificateServiceImpl.save (Certificate certificate, int userId)
Implements portal.registration.services.CertificateService.
Definition at line 59 of file CertificateServiceImpl.java.
References portal.registration.services.CertificateServiceImpl.certificateDAO, portal.registration.dao.CertificateDAO.edit(), portal.registration.dao.CertificateDAO.findById(), portal.registration.dao.UserInfoDAO.findById(), portal.registration.domain.Certificate.getIdCert(), portal.registration.domain.Certificate.getPrimaryCert(), portal.registration.domain.UserInfo.getUsername(), portal.registration.services.CertificateServiceImpl.log, portal.registration.dao.CertificateDAO.save(), portal.registration.domain.Certificate.setPrimaryCert(), portal.registration.domain.Certificate.setUserInfo(), portal.registration.domain.Certificate.setUsernameCert(), and portal.registration.services.CertificateServiceImpl.userInfoDAO.
                                                             
                log.debug("persisting UserInfo instance");
                UserInfo userInfo = userInfoDAO.findById(userId);
                List<Certificate> lc = certificateDAO.findById(userInfo);
                certificate.setUserInfo(userInfo);
                certificate.setUsernameCert(userInfo.getUsername() + "_"
                                + certificate.getIdCert());
                if (certificate.getPrimaryCert().equals("true"))
                        Certificate tmp = null;
                        int i = 0;
                        for (i = 0; i < lc.size(); i++)
                                tmp = lc.get(i);
                                tmp.setPrimaryCert("false");
                                certificateDAO.edit(tmp);
                        
                
                int result = certificateDAO.save(certificate);
                certificate.setUsernameCert(userInfo.getUsername() + "_" + result
      );
                certificateDAO.edit(certificate);
                return result;
        
Integer portal.registration.services.CertificateServiceImpl.save (Certificate transientInstance)
Implements portal.registration.services.CertificateService.
Definition at line 40 of file CertificateServiceImpl.java.
References portal.registration.services.CertificateServiceImpl.certificateDAO, portal.registration.services.CertificateServiceImpl.log, and portal.registration.dao.CertificateDAO.save().
                                                           
                log.debug("persisting UserInfo instance");
                return certificateDAO.save(transientInstance);
        
boolean portal.registration.services.CertificateServiceImpl.setDefault (int idCert)
Implements portal.registration.services.CertificateService.
Definition at line 97 of file CertificateServiceImpl.java.
References portal.registration.services.CertificateServiceImpl.certificateDAO, portal.registration.dao.CertificateDAO.edit(), portal.registration.dao.CertificateDAO.findById(), portal.registration.domain.Certificate.getPrimaryCert(), portal.registration.services.CertificateServiceImpl.log, and portal.registration.domain.Certificate.setPrimaryCert().
                                              
                log.debug("ugrading Certificate instance");
                Certificate persistentInstance = certificateDAO.findById(idCert);
      
                if (persistentInstance.getPrimaryCert().equals("false"))
                        List<Certificate> lc = certificateDAO.findById(persistent
      Instance
                                        .getUserInfo());
                        Certificate tmp = null;
                        int i = 0;
                        for (i = 0; i < lc.size(); i++)
                                tmp = lc.get(i);
                                tmp.setPrimaryCert("false");
                                certificateDAO.edit(tmp);
                        
                        persistentInstance.setPrimaryCert("true");
                        certificateDAO.edit(persistentInstance);
                        return true;
                
                return false;
        
Member Data Documentation
CertificateDAO portal.registration.services.CertificateServiceImpl.certificateDAO [private]
Definition at line 34 of file CertificateServiceImpl.java.
Referenced by portal.registration.services.CertificateServiceImpl.delete(), portal.registration.services.CertificateServiceImpl.findById(), portal.registration.services.CertificateServiceImpl.save(), and portal.registration.services.CertificateServiceImpl.setDefault().
final Logger portal.registration.services.CertificateServiceImpl.log [static, private]
Initial value:
 Logger
                        .getLogger(CertificateServiceImpl.class)
Definition at line 30 of file CertificateServiceImpl.java.
Referenced by portal.registration.services.CertificateServiceImpl.delete(), portal.registration.services.CertificateServiceImpl.save(), and portal.registration.services.CertificateServiceImpl.setDefault().
UserInfoDAO portal.registration.services.CertificateServiceImpl.userInfoDAO [private]
Definition at line 37 of file CertificateServiceImpl.java.
Referenced by portal.registration.services.CertificateServiceImpl.findById(), and portal.registration.services.CertificateServiceImpl.save().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/services/CertificateServiceImpl.java