org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton Class Reference
Public Member Functions
VOMSAdminSoapBindingSkeleton ()
VOMSAdminSoapBindingSkeleton (org.glite.security.voms.service.admin.VOMSAdmin impl)
void createGroup (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.User getUser (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void setUser (org.glite.security.voms.User in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
int getMajorVersionNumber () throws java.rmi.RemoteException
java.lang.String getVOName () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void createUser (org.glite.security.voms.User in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteUser (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteGroup (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void createRole (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteRole (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void createCapability (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteCapability (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void addMember (java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void removeMember (java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void assignRole (java.lang.String in0, java.lang.String in1, java.lang.String in2, java.lang.String in3) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void dismissRole (java.lang.String in0, java.lang.String in1, java.lang.String in2, java.lang.String in3) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void assignCapability (java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void dismissCapability (java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.User[] listMembers (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.User[] listUsersWithRole (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.User[] listUsersWithCapability (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
java.lang.String[] getGroupPath (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
java.lang.String[] listSubGroups (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
java.lang.String[] listGroups (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
java.lang.String[] listRoles () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
java.lang.String[] listRoles (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
java.lang.String[] listCapabilities () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
java.lang.String[] listCapabilities (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
java.lang.String[] listCAs () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.ACLEntry[] getACL (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void setACL (java.lang.String in0, org.glite.security.voms.ACLEntry[] in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void addACLEntry (java.lang.String in0, org.glite.security.voms.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void removeACLEntry (java.lang.String in0, org.glite.security.voms.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.ACLEntry[] getDefaultACL (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void setDefaultACL (java.lang.String in0, org.glite.security.voms.ACLEntry[] in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void addDefaultACLEntry (java.lang.String in0, org.glite.security.voms.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void removeDefaultACLEntry (java.lang.String in0, org.glite.security.voms.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
int getMinorVersionNumber () throws java.rmi.RemoteException
int getPatchVersionNumber () throws java.rmi.RemoteException
Static Public Member Functions
static java.util.List getOperationDescByName (java.lang.String methodName)
static java.util.Collection getOperationDescs ()
Static Package Functions
[static initializer]
Private Attributes
org.glite.security.voms.service.admin.VOMSAdmin impl
Static Private Attributes
static java.util.Map _myOperations = new java.util.Hashtable()
static java.util.Collection _myOperationsList = new java.util.ArrayList()
Detailed Description
Definition at line 10 of file VOMSAdminSoapBindingSkeleton.java.
Constructor & Destructor Documentation
org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.VOMSAdminSoapBindingSkeleton ()
Definition at line 718 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl.
                                          
        this.impl = new org.glite.security.voms.service.admin.VOMSAdminSoapBindin
      gImpl();
    
org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.VOMSAdminSoapBindingSkeleton (org.glite.security.voms.service.admin.VOMSAdmin impl)
Definition at line 722 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl.
                                                                                 
                   
        this.impl = impl;
    
Member Function Documentation
org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.[static initializer] () [static, package]
void org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.addACLEntry (java.lang.String in0, org.glite.security.voms.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 895 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdmin.addACLEntry(), and org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl.
    
        impl.addACLEntry(in0, in1);
    
void org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.addDefaultACLEntry (java.lang.String in0, org.glite.security.voms.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 916 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdmin.addDefaultACLEntry(), and org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl.
    
        impl.addDefaultACLEntry(in0, in1);
    
void org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.addMember (java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 788 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdmin.addMember(), and org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl.
    
        impl.addMember(in0, in1, in2);
    
void org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.assignCapability (java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 808 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdmin.assignCapability(), and org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl.
    
        impl.assignCapability(in0, in1, in2);
    
void org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.assignRole (java.lang.String in0, java.lang.String in1, java.lang.String in2, java.lang.String in3) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 798 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdmin.assignRole(), and org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl.
    
        impl.assignRole(in0, in1, in2, in3);
    
void org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.createCapability (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 778 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdmin.createCapability(), and org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl.
    
        impl.createCapability(in0);
    
void org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.createGroup (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 725 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdmin.createGroup(), and org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl.
    
        impl.createGroup(in0, in1);
    
void org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.createRole (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 768 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdmin.createRole(), and org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl.
    
        impl.createRole(in0);
    
void org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.createUser (org.glite.security.voms.User in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 753 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdmin.createUser(), and org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl.
    
        impl.createUser(in0);
    
void org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.deleteCapability (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 783 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdmin.deleteCapability(), and org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl.
    
        impl.deleteCapability(in0);
    
void org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.deleteGroup (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 763 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdmin.deleteGroup(), and org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl.
    
        impl.deleteGroup(in0);
    
void org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.deleteRole (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 773 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdmin.deleteRole(), and org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl.
    
        impl.deleteRole(in0);
    
void org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.deleteUser (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 758 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdmin.deleteUser(), and org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl.
    
        impl.deleteUser(in0, in1);
    
void org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.dismissCapability (java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 813 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdmin.dismissCapability(), and org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl.
    
        impl.dismissCapability(in0, in1, in2);
    
void org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.dismissRole (java.lang.String in0, java.lang.String in1, java.lang.String in2, java.lang.String in3) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 803 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdmin.dismissRole(), and org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl.
    
        impl.dismissRole(in0, in1, in2, in3);
    
org.glite.security.voms.ACLEntry [] org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getACL (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 884 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdmin.getACL(), and org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl.
    
        org.glite.security.voms.ACLEntry[] ret = impl.getACL(in0);
        return ret;
    
org.glite.security.voms.ACLEntry [] org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getDefaultACL (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 905 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdmin.getDefaultACL(), and org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl.
    
        org.glite.security.voms.ACLEntry[] ret = impl.getDefaultACL(in0);
        return ret;
    
java.lang.String [] org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getGroupPath (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 836 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdmin.getGroupPath(), and org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl.
    
        java.lang.String[] ret = impl.getGroupPath(in0);
        return ret;
    
int org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getMajorVersionNumber () throws java.rmi.RemoteException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 741 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdmin.getMajorVersionNumber(), and org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl.
    
        int ret = impl.getMajorVersionNumber();
        return ret;
    
int org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getMinorVersionNumber () throws java.rmi.RemoteException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 926 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdmin.getMinorVersionNumber(), and org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl.
    
        int ret = impl.getMinorVersionNumber();
        return ret;
    
static java.util.List org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getOperationDescByName (java.lang.String methodName) [static]
Returns List of OperationDesc objects with this name
Definition at line 18 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton._myOperations.
                                                                                 
          
        return (java.util.List)_myOperations.get(methodName);
    
static java.util.Collection org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getOperationDescs () [static]
Returns Collection of OperationDescs
Definition at line 25 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton._myOperationsList.
                                                           
        return _myOperationsList;
    
int org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getPatchVersionNumber () throws java.rmi.RemoteException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 932 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdmin.getPatchVersionNumber(), and org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl.
    
        int ret = impl.getPatchVersionNumber();
        return ret;
    
org.glite.security.voms.User org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getUser (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 730 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdmin.getUser(), and org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl.
    
        org.glite.security.voms.User ret = impl.getUser(in0, in1);
        return ret;
    
java.lang.String org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getVOName () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 747 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdmin.getVOName(), and org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl.
    
        java.lang.String ret = impl.getVOName();
        return ret;
    
java.lang.String [] org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.listCapabilities () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 866 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl, and org.glite.security.voms.service.admin.VOMSAdmin.listCapabilities().
    
        java.lang.String[] ret = impl.listCapabilities();
        return ret;
    
java.lang.String [] org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.listCapabilities (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 872 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl, and org.glite.security.voms.service.admin.VOMSAdmin.listCapabilities().
    
        java.lang.String[] ret = impl.listCapabilities(in0, in1);
        return ret;
    
java.lang.String [] org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.listCAs () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 878 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl, and org.glite.security.voms.service.admin.VOMSAdmin.listCAs().
    
        java.lang.String[] ret = impl.listCAs();
        return ret;
    
java.lang.String [] org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.listGroups (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 848 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl, and org.glite.security.voms.service.admin.VOMSAdmin.listGroups().
    
        java.lang.String[] ret = impl.listGroups(in0, in1);
        return ret;
    
org.glite.security.voms.User [] org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.listMembers (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 818 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl, and org.glite.security.voms.service.admin.VOMSAdmin.listMembers().
    
        org.glite.security.voms.User[] ret = impl.listMembers(in0);
        return ret;
    
java.lang.String [] org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.listRoles (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 860 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl, and org.glite.security.voms.service.admin.VOMSAdmin.listRoles().
    
        java.lang.String[] ret = impl.listRoles(in0, in1);
        return ret;
    
java.lang.String [] org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.listRoles () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 854 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl, and org.glite.security.voms.service.admin.VOMSAdmin.listRoles().
    
        java.lang.String[] ret = impl.listRoles();
        return ret;
    
java.lang.String [] org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.listSubGroups (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 842 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl, and org.glite.security.voms.service.admin.VOMSAdmin.listSubGroups().
    
        java.lang.String[] ret = impl.listSubGroups(in0);
        return ret;
    
org.glite.security.voms.User [] org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.listUsersWithCapability (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 830 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl, and org.glite.security.voms.service.admin.VOMSAdmin.listUsersWithCapability().
    
        org.glite.security.voms.User[] ret = impl.listUsersWithCapability(in0);
        return ret;
    
org.glite.security.voms.User [] org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.listUsersWithRole (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 824 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl, and org.glite.security.voms.service.admin.VOMSAdmin.listUsersWithRole().
    
        org.glite.security.voms.User[] ret = impl.listUsersWithRole(in0, in1);
        return ret;
    
void org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.removeACLEntry (java.lang.String in0, org.glite.security.voms.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 900 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl, and org.glite.security.voms.service.admin.VOMSAdmin.removeACLEntry().
    
        impl.removeACLEntry(in0, in1);
    
void org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.removeDefaultACLEntry (java.lang.String in0, org.glite.security.voms.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 921 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl, and org.glite.security.voms.service.admin.VOMSAdmin.removeDefaultACLEntry().
    
        impl.removeDefaultACLEntry(in0, in1);
    
void org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.removeMember (java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 793 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl, and org.glite.security.voms.service.admin.VOMSAdmin.removeMember().
    
        impl.removeMember(in0, in1, in2);
    
void org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.setACL (java.lang.String in0, org.glite.security.voms.ACLEntry[] in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 890 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl, and org.glite.security.voms.service.admin.VOMSAdmin.setACL().
    
        impl.setACL(in0, in1);
    
void org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.setDefaultACL (java.lang.String in0, org.glite.security.voms.ACLEntry[] in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 911 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl, and org.glite.security.voms.service.admin.VOMSAdmin.setDefaultACL().
    
        impl.setDefaultACL(in0, in1);
    
void org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.setUser (org.glite.security.voms.User in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.admin.VOMSAdmin.
Definition at line 736 of file VOMSAdminSoapBindingSkeleton.java.
References org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl, and org.glite.security.voms.service.admin.VOMSAdmin.setUser().
    
        impl.setUser(in0);
    
Member Data Documentation
java.util.Map org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton._myOperations = new java.util.Hashtable() [static, private]
Definition at line 12 of file VOMSAdminSoapBindingSkeleton.java.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getOperationDescByName().
java.util.Collection org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton._myOperationsList = new java.util.ArrayList() [static, private]
Definition at line 13 of file VOMSAdminSoapBindingSkeleton.java.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getOperationDescs().
org.glite.security.voms.service.admin.VOMSAdmin org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.impl [private]
Definition at line 11 of file VOMSAdminSoapBindingSkeleton.java.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.addACLEntry(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.addDefaultACLEntry(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.addMember(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.assignCapability(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.assignRole(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.createCapability(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.createGroup(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.createRole(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.createUser(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.deleteCapability(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.deleteGroup(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.deleteRole(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.deleteUser(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.dismissCapability(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.dismissRole(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getACL(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getDefaultACL(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getGroupPath(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getMajorVersionNumber(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getMinorVersionNumber(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getPatchVersionNumber(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getUser(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getVOName(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.listCapabilities(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.listCAs(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.listGroups(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.listMembers(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.listRoles(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.listSubGroups(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.listUsersWithCapability(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.listUsersWithRole(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.removeACLEntry(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.removeDefaultACLEntry(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.removeMember(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.setACL(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.setDefaultACL(), org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.setUser(), and org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.VOMSAdminSoapBindingSkeleton().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/admin/VOMSAdminSoapBindingSkeleton.java