portal.registration.controller.AddUserToVOController Class Reference
Public Member Functions
UserInfo getCommandObject ()
String showUserInfoForm (RenderResponse response)
void addUserToVo (ActionRequest request, ActionResponse response, SessionStatus sessionStatus) throws PortalException, 			SystemException
List< Vo > getVos ()
List< String > getDisciplines ()
void setDefaultUserToVo (ActionRequest request, ActionResponse response, SessionStatus sessionStatus)
void removeUserToVo (ActionRequest request, ActionResponse response, SessionStatus sessionStatus)
void setDefaultUserToVoEdit (ActionRequest request, ActionResponse response, SessionStatus sessionStatus)
void removeUserToVoEdit (ActionRequest request, ActionResponse response, SessionStatus sessionStatus)
Private Member Functions
void activateUser (UserInfo userInfo, ActionRequest request, ArrayList< String > errors)
boolean checkVO (int idVo, int userId, List< String > errors)
Private Attributes
CertificateService certificateService
VoService voService
UserToVoService userToVoService
UserInfoService userInfoService
Static Private Attributes
static final Logger log
Detailed Description
Definition at line 42 of file AddUserToVOController.java.
Member Function Documentation
void portal.registration.controller.AddUserToVOController.activateUser (UserInfo userInfo, ActionRequest request, ArrayList< String > errors) [private]
Definition at line 144 of file AddUserToVOController.java.
References portal.registration.services.UserInfoService.edit(), portal.registration.domain.UserInfo.getUsername(), and portal.registration.domain.UserInfo.setRegistrationComplete().
                                                  
                String username = userInfo.getUsername();
                long companyId = PortalUtil.getCompanyId(request);
                User user;
                try
                        user = UserLocalServiceUtil
                                        .getUserByScreenName(companyId, username)
      ;
                        long[] users = user.getUserId() ;
                        UserLocalServiceUtil.setRoleUsers((long) 10140, users);
                        userInfo.setRegistrationComplete("true");
                        userInfoService.edit(userInfo);
                        SessionMessages.add(request, "user-activate");
                 catch (PortalException e)
                        errors.add("exception-activation-user");
                        e.printStackTrace();
                 catch (SystemException e)
                        errors.add("exception-activation-user");
                        e.printStackTrace();
                
        
void portal.registration.controller.AddUserToVOController.addUserToVo (ActionRequest request, ActionResponse response, SessionStatus sessionStatus) throws PortalException, 			SystemException
Definition at line 70 of file AddUserToVOController.java.
References portal.registration.services.UserInfoService.findById(), portal.registration.domain.UserInfo.getRegistrationComplete(), and portal.registration.services.UserToVoService.save().
                                        
                log.info("sono dentro");
                ArrayList<String> errors = new ArrayList<String>();
                boolean allOk = true;
                int userId = Integer.parseInt(request.getParameter("userId"));
                log.info("Valore passato userId " + userId);
                if (request.getParameterValues("VOids") != null)
                        log.info("recupero idVo");
                        int idVo = Integer.parseInt(request.getParameter("VOids")
      );
                        if (idVo != 0)
                                if (checkVO(idVo, userId, errors))
                                        log.info("Salvo sul DB la Vo " + idVo);
                                        UserInfo ui = userInfoService.findById(us
      erId);
                                        if (ui.getRegistrationComplete().equals("
      false"))
                                                activateUser(ui, request, errors)
      ;
                                        
                                        userToVoService.save(userId, idVo);
                                        log.info("Salvato sul DB ");
                                 else
                                        allOk = false;
                                
                        
                 else
                        allOk = false;
                        errors.add("user-vo-list-empty");
                
                if (allOk)
                        SessionMessages.add(request, "userToVo-adding-success");
                        if (request.getParameter("firstReg").equals("true"))
                                response.setRenderParameter("myaction",
                                                "showAddUserToVoPresents");
                         else
                                response.setRenderParameter("myaction", "editUser
      InfoForm");
                        
                        response.setRenderParameter("userId", Integer.toString(us
      erId));
                        request.setAttribute("userId", userId);
                        sessionStatus.setComplete();
                 else
                        errors.add("error-saving-registration");
                        for (String error : errors)
                                log.info("Errore: " + error);
                                SessionErrors.add(request, error);
                        
                        log.info("Errori in userToVO");
                        if (request.getParameter("firstReg").equals("true"))
                                response.setRenderParameter("myaction",
                                                "showAddUserToVoPresents");
                         else
                                response.setRenderParameter("myaction", "editUser
      InfoForm");
                        
                        response.setRenderParameter("userId", Integer.toString(us
      erId));
                        request.setAttribute("userId", userId);
                
        
boolean portal.registration.controller.AddUserToVOController.checkVO (int idVo, int userId, List< String > errors) [private]
Definition at line 186 of file AddUserToVOController.java.
References portal.registration.services.UserToVoService.findById(), portal.registration.services.CertificateService.findById(), portal.registration.services.VoService.findById(), portal.registration.domain.Vo.getHost(), and portal.registration.domain.Vo.getVo().
                                                                           
                boolean result = false;
                Vo vo = voService.findById(idVo);
                List<Certificate> certs = certificateService.findById(userId);
                if (certs.size() == 0)
                        errors.add("no-cert-for-user");
                        return false;
                
                if (userToVoService.findById(userId, idVo) != null)
                        errors.add("userToVo-already-exists");
                        return false;
                
                try
                        FileOutputStream file = new FileOutputStream(
                                        "/upload_files/edg-mkgridmap." + vo.getVo
      () + ".conf");
                        PrintStream conf = new PrintStream(file);
                        conf.println("group vomss://" + vo.getHost() + "?/" + vo.
      getVo()
                                        + " ." + vo.getVo());
                        for (int i = 0; i < certs.size(); i++)
                                String subject = certs.get(i).getSubject();
                                subject = subject.replaceAll(" ", "
 ");
                                String cmdCheck = "/opt/edg/sbin/edg-mkgridmap -
      -conf=/upload_files/edg-mkgridmap."
                                                + vo.getVo() + ".conf";
                                log.info("cmdCheck = " + cmdCheck);
                                Process pCheck = Runtime.getRuntime().exec(cmdChe
      ck);
                                InputStream stdout = pCheck.getInputStream();
                                InputStream stderr = pCheck.getErrorStream();
                                BufferedReader output = new BufferedReader(
                                                new InputStreamReader(stdout));
                                String line = null;
                                log.info("Ricerca questo: " + "" + subject + "
      " ."
                                                + vo.getVo());
                                while ((line = output.readLine()) != null)
                                        log.info("[Stdout] " + line);
                                        if (line.equals("" + subject + " ." +
       vo.getVo()))
                                                log.info("***********************
      **********************************");
                                                result = true;
                                        
                                
                                output.close();
                                BufferedReader brCleanUp = new BufferedReader(
                                                new InputStreamReader(stderr));
                                while ((line = brCleanUp.readLine()) != null)
                                        errors.add("edg-mkgridmap-problem");
                                        log.info("[Stderr] " + line);
                                        result = false;
                                
                                brCleanUp.close();
                        
                 catch (IOException e)
                        result = false;
                        errors.add("edg-mkgridmap-exception");
                        e.printStackTrace();
                
                if (!result)
                        errors.add("no-user-found-in-VO");
                return result;
        
UserInfo portal.registration.controller.AddUserToVOController.getCommandObject ()
Definition at line 60 of file AddUserToVOController.java.
                                           
                return new UserInfo();
        
List<String> portal.registration.controller.AddUserToVOController.getDisciplines ()
Definition at line 182 of file AddUserToVOController.java.
References portal.registration.services.VoService.getAllDiscplines().
                                             
                return voService.getAllDiscplines();
        
List<Vo> portal.registration.controller.AddUserToVOController.getVos ()
Definition at line 177 of file AddUserToVOController.java.
References portal.registration.services.VoService.getAllVo().
                                 
                return voService.getAllVo();
        
void portal.registration.controller.AddUserToVOController.removeUserToVo (ActionRequest request, ActionResponse response, SessionStatus sessionStatus)
Definition at line 289 of file AddUserToVOController.java.
References portal.registration.services.UserToVoService.delete().
                                                     
                int userId = Integer.parseInt(request.getParameter("userId"));
                int idVo = Integer.parseInt(request.getParameter("idVo"));
                try
                        log.info("Sto per cancellare il userToVo con userId = " +
       userId
                                        + "e idVo = " + idVo);
                        userToVoService.delete(userId, idVo);
                        log.info("userTo Vo cancellato");
                        SessionMessages.add(request, "userToVo-deleted-successufu
      lly");
                 catch (Exception e)
                        SessionErrors.add(request, "error-deleting-userToVo");
                
                response.setRenderParameter("myaction", "showAddUserToVoPresents"
      );
                response.setRenderParameter("userId", Integer.toString(userId));
                request.setAttribute("firstReg", request.getParameter("firstReg")
      );
                sessionStatus.setComplete();
        
void portal.registration.controller.AddUserToVOController.removeUserToVoEdit (ActionRequest request, ActionResponse response, SessionStatus sessionStatus)
Definition at line 343 of file AddUserToVOController.java.
References portal.registration.services.UserToVoService.delete(), and portal.registration.services.UserToVoService.findVoByUserId().
                                                                              
                int userId = Integer.parseInt(request.getParameter("userId"));
                int idVo = Integer.parseInt(request.getParameter("idVo"));
                try
                        log.info("Sto per cancellare il userToVo con userId = " +
       userId
                                        + "e idVo = " + idVo);
                        userToVoService.delete(userId, idVo);
                        log.info("userTo Vo cancellato");
                        SessionMessages.add(request, "userToVo-deleted-successufu
      lly");
                        userToVoService.findVoByUserId(userId);
                 catch (Exception e)
                        SessionErrors.add(request, "error-deleting-userToVo");
                
                response.setRenderParameter("myaction", "editUserInfoForm");
                response.setRenderParameter("userId", Integer.toString(userId));
                request.setAttribute("firstReg", request.getParameter("firstReg")
      );
                sessionStatus.setComplete();
        
void portal.registration.controller.AddUserToVOController.setDefaultUserToVo (ActionRequest request, ActionResponse response, SessionStatus sessionStatus)
Definition at line 261 of file AddUserToVOController.java.
References portal.registration.services.UserToVoService.findVoByUserId(), and portal.registration.services.UserToVoService.setDefault().
                                                                              
                int userId = Integer.parseInt(request.getParameter("userId"));
                int idVo = Integer.parseInt(request.getParameter("idVo"));
                try
                        log.info("Sto per settarea default il userToVo con userId
       = "
                                        + userId + "e idVo = " + idVo);
                        if (userToVoService.setDefault(userId, idVo))
                                SessionMessages.add(request, "userToVo-updated-su
      ccessufully");
                        else
                                SessionErrors.add(request, "error-default-userToV
      o");
                        log.info("UserToVoSettato");
                        userToVoService.findVoByUserId(userId);
                 catch (Exception e)
                        SessionErrors.add(request, "error-updating-certificate");
      
                
                response.setRenderParameter("myaction", "showAddUserToVoPresents"
      );
                response.setRenderParameter("userId", Integer.toString(userId));
                request.setAttribute("firstReg", request.getParameter("firstReg")
      );
                sessionStatus.setComplete();
        
void portal.registration.controller.AddUserToVOController.setDefaultUserToVoEdit (ActionRequest request, ActionResponse response, SessionStatus sessionStatus)
Definition at line 315 of file AddUserToVOController.java.
References portal.registration.services.UserToVoService.findVoByUserId(), and portal.registration.services.UserToVoService.setDefault().
                                                                              
                int userId = Integer.parseInt(request.getParameter("userId"));
                int idVo = Integer.parseInt(request.getParameter("idVo"));
                try
                        log.info("Sto per settarea default il userToVo con userId
       = "
                                        + userId + "e idVo = " + idVo);
                        if (userToVoService.setDefault(userId, idVo))
                                SessionMessages.add(request, "userToVo-updated-su
      ccessufully");
                        else
                                SessionErrors.add(request, "error-default-userToV
      o");
                        log.info("UserToVoSettato");
                        userToVoService.findVoByUserId(userId);
                 catch (Exception e)
                        SessionErrors.add(request, "error-updating-certificate");
      
                
                response.setRenderParameter("myaction", "editUserInfoForm");
                response.setRenderParameter("userId", Integer.toString(userId));
                request.setAttribute("firstReg", request.getParameter("firstReg")
      );
                sessionStatus.setComplete();
        
String portal.registration.controller.AddUserToVOController.showUserInfoForm (RenderResponse response)
Definition at line 65 of file AddUserToVOController.java.
                                                                
                return "addUserToVOForm";
        
Member Data Documentation
CertificateService portal.registration.controller.AddUserToVOController.certificateService [private]
Definition at line 48 of file AddUserToVOController.java.
final Logger portal.registration.controller.AddUserToVOController.log [static, private]
Initial value:
 Logger
                        .getLogger(AddUserToVOController.class)
Definition at line 44 of file AddUserToVOController.java.
UserInfoService portal.registration.controller.AddUserToVOController.userInfoService [private]
Definition at line 57 of file AddUserToVOController.java.
UserToVoService portal.registration.controller.AddUserToVOController.userToVoService [private]
Definition at line 54 of file AddUserToVOController.java.
VoService portal.registration.controller.AddUserToVOController.voService [private]
Definition at line 51 of file AddUserToVOController.java.
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/controller/AddUserToVOController.java