portal.registration.services.IdpServiceImpl Class Reference
Public Member Functions
void save (Idp transientInstance)
void delete (Idp persistentInstance)
Idp findById (Integer id)
String findByIdp (Idp idp)
List< Idp > getAllIdp ()
Private Attributes
IdpDAO idpDAO
Static Private Attributes
static final Log log = LogFactory.getLog(IdpServiceImpl.class)
Detailed Description
Definition at line 16 of file IdpServiceImpl.java.
Member Function Documentation
void portal.registration.services.IdpServiceImpl.delete (Idp persistentInstance)
Implements portal.registration.services.IdpService.
Definition at line 30 of file IdpServiceImpl.java.
References portal.registration.dao.IdpDAO.delete(), portal.registration.services.IdpServiceImpl.idpDAO, and portal.registration.services.IdpServiceImpl.log.
                                                   
                log.debug("removing Idp instance");
                idpDAO.delete(persistentInstance);
        
Idp portal.registration.services.IdpServiceImpl.findById (Integer id)
Implements portal.registration.services.IdpService.
Definition at line 36 of file IdpServiceImpl.java.
References portal.registration.dao.IdpDAO.findById(), portal.registration.services.IdpServiceImpl.idpDAO, and portal.registration.services.IdpServiceImpl.log.
                                        
                log.debug("getting Idp instance with id: " + id);
                return idpDAO.findById(id);
        
String portal.registration.services.IdpServiceImpl.findByIdp (Idp idp)
Implements portal.registration.services.IdpService.
Definition at line 42 of file IdpServiceImpl.java.
References portal.registration.dao.IdpDAO.findById(), portal.registration.domain.Idp.getIdIdp(), portal.registration.services.IdpServiceImpl.idpDAO, and portal.registration.services.IdpServiceImpl.log.
                                         
                log.debug("getting Idp instance");
                return idpDAO.findById(idp.getIdIdp()).getIdpname();
        
List<Idp> portal.registration.services.IdpServiceImpl.getAllIdp ()
Implements portal.registration.services.IdpService.
Definition at line 48 of file IdpServiceImpl.java.
References portal.registration.dao.IdpDAO.getAllIdp(), portal.registration.services.IdpServiceImpl.idpDAO, and portal.registration.services.IdpServiceImpl.log.
                                     
                log.debug("getting all Idp instance");
                return idpDAO.getAllIdp();
        
void portal.registration.services.IdpServiceImpl.save (Idp transientInstance)
Implements portal.registration.services.IdpService.
Definition at line 24 of file IdpServiceImpl.java.
References portal.registration.services.IdpServiceImpl.idpDAO, portal.registration.services.IdpServiceImpl.log, and portal.registration.dao.IdpDAO.save().
                                                
                log.debug("persisting Idp instance");
                idpDAO.save(transientInstance);
        
Member Data Documentation
IdpDAO portal.registration.services.IdpServiceImpl.idpDAO [private]
Definition at line 21 of file IdpServiceImpl.java.
Referenced by portal.registration.services.IdpServiceImpl.delete(), portal.registration.services.IdpServiceImpl.findById(), portal.registration.services.IdpServiceImpl.findByIdp(), portal.registration.services.IdpServiceImpl.getAllIdp(), and portal.registration.services.IdpServiceImpl.save().
final Log portal.registration.services.IdpServiceImpl.log = LogFactory.getLog(IdpServiceImpl.class) [static, private]
Definition at line 18 of file IdpServiceImpl.java.
Referenced by portal.registration.services.IdpServiceImpl.delete(), portal.registration.services.IdpServiceImpl.findById(), portal.registration.services.IdpServiceImpl.findByIdp(), portal.registration.services.IdpServiceImpl.getAllIdp(), and portal.registration.services.IdpServiceImpl.save().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/services/IdpServiceImpl.java