org.glite.security.voms.service.acl.VOMSACLServiceLocator Class Reference
Public Member Functions
VOMSACLServiceLocator ()
VOMSACLServiceLocator (org.apache.axis.EngineConfiguration config)
VOMSACLServiceLocator (java.lang.String wsdlLoc, javax.xml.namespace.QName sName) throws javax.xml.rpc.ServiceException
java.lang.String getVOMSACLAddress ()
java.lang.String getVOMSACLWSDDServiceName ()
void setVOMSACLWSDDServiceName (java.lang.String name)
org.glite.security.voms.service.acl.VOMSACL getVOMSACL () throws javax.xml.rpc.ServiceException
org.glite.security.voms.service.acl.VOMSACL getVOMSACL (java.net.URL portAddress) throws javax.xml.rpc.ServiceException
void setVOMSACLEndpointAddress (java.lang.String address)
java.rmi.Remote getPort (Class serviceEndpointInterface) throws javax.xml.rpc.ServiceException
java.rmi.Remote getPort (javax.xml.namespace.QName portName, Class serviceEndpointInterface) throws javax.xml.rpc.ServiceException
namespace::QName getServiceName ()
java.util.Iterator getPorts ()
void setEndpointAddress (java.lang.String portName, java.lang.String address) throws javax.xml.rpc.ServiceException
void setEndpointAddress (javax.xml.namespace.QName portName, java.lang.String address) throws javax.xml.rpc.ServiceException
Private Attributes
java.lang.String VOMSACL_address = `https://localhost:8443/glite-security-voms-admin-interface/VOMSACL`
java.lang.String VOMSACLWSDDServiceName = `VOMSACL`
java.util.HashSet ports = null
Detailed Description
Definition at line 10 of file VOMSACLServiceLocator.java.
Constructor & Destructor Documentation
org.glite.security.voms.service.acl.VOMSACLServiceLocator.VOMSACLServiceLocator ()
Definition at line 12 of file VOMSACLServiceLocator.java.
                                   
    
org.glite.security.voms.service.acl.VOMSACLServiceLocator.VOMSACLServiceLocator (org.apache.axis.EngineConfiguration config)
Definition at line 16 of file VOMSACLServiceLocator.java.
                                                                             
        super(config);
    
org.glite.security.voms.service.acl.VOMSACLServiceLocator.VOMSACLServiceLocator (java.lang.String wsdlLoc, javax.xml.namespace.QName sName) throws javax.xml.rpc.ServiceException
Definition at line 20 of file VOMSACLServiceLocator.java.
                                                                                 
                                                       
        super(wsdlLoc, sName);
    
Member Function Documentation
java.rmi.Remote org.glite.security.voms.service.acl.VOMSACLServiceLocator.getPort (Class serviceEndpointInterface) throws javax.xml.rpc.ServiceException
For the given interface, get the stub implementation. If this service has no port for the given interface, then ServiceException is thrown.
Definition at line 73 of file VOMSACLServiceLocator.java.
References org.glite.security.voms.service.acl.VOMSACLServiceLocator.getVOMSACLWSDDServiceName(), and org.glite.security.voms.service.acl.VOMSACLServiceLocator.VOMSACL_address.
Referenced by org.glite.security.voms.service.acl.VOMSACLServiceLocator.getPort().
                                                                                 
                              
        try
            if (org.glite.security.voms.service.acl.VOMSACL.class.isAssignableFro
      m(serviceEndpointInterface))
                org.glite.security.voms.service.acl.VOMSACLSoapBindingStub _stub
      = new org.glite.security.voms.service.acl.VOMSACLSoapBindingStub(new java.net.URL
      (VOMSACL_address), this);
                _stub.setPortName(getVOMSACLWSDDServiceName());
                return _stub;
            
        
        catch (java.lang.Throwable t)
            throw new javax.xml.rpc.ServiceException(t);
        
        throw new javax.xml.rpc.ServiceException("There is no stub implementation
       for the interface: " + (serviceEndpointInterface == null ? "null" : serviceEndp
      ointInterface.getName()));
    
java.rmi.Remote org.glite.security.voms.service.acl.VOMSACLServiceLocator.getPort (javax.xml.namespace.QName portName, Class serviceEndpointInterface) throws javax.xml.rpc.ServiceException
For the given interface, get the stub implementation. If this service has no port for the given interface, then ServiceException is thrown.
Definition at line 92 of file VOMSACLServiceLocator.java.
References org.glite.security.voms.service.acl.VOMSACLServiceLocator.getPort(), and org.glite.security.voms.service.acl.VOMSACLServiceLocator.getVOMSACL().
                                                                                 
                                                                  
        if (portName == null)
            return getPort(serviceEndpointInterface);
        
        java.lang.String inputPortName = portName.getLocalPart();
        if ("VOMSACL".equals(inputPortName))
            return getVOMSACL();
        
        else
            java.rmi.Remote _stub = getPort(serviceEndpointInterface);
            ((org.apache.axis.client.Stub) _stub).setPortName(portName);
            return _stub;
        
    
java.util.Iterator org.glite.security.voms.service.acl.VOMSACLServiceLocator.getPorts ()
Definition at line 113 of file VOMSACLServiceLocator.java.
References org.glite.security.voms.service.acl.VOMSACLServiceLocator.ports.
                                         
        if (ports == null)
            ports = new java.util.HashSet();
            ports.add(new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.acl", "VOMSACL"));
        
        return ports.iterator();
    
namespace ::QName org.glite.security.voms.service.acl.VOMSACLServiceLocator.getServiceName ()
Definition at line 107 of file VOMSACLServiceLocator.java.
                                                      
        return new javax.xml.namespace.QName("http://glite.org/wsdl/services/org.
      glite.security.voms.service.acl", "VOMSACLService");
    
org.glite.security.voms.service.acl.VOMSACL org.glite.security.voms.service.acl.VOMSACLServiceLocator.getVOMSACL (java.net.URL portAddress) throws javax.xml.rpc.ServiceException
Implements org.glite.security.voms.service.acl.VOMSACLService.
Definition at line 53 of file VOMSACLServiceLocator.java.
References org.glite.security.voms.service.acl.VOMSACLServiceLocator.getVOMSACLWSDDServiceName().
                                                                                 
                                                       
        try
            org.glite.security.voms.service.acl.VOMSACLSoapBindingStub _stub = ne
      w org.glite.security.voms.service.acl.VOMSACLSoapBindingStub(portAddress, this);
            _stub.setPortName(getVOMSACLWSDDServiceName());
            return _stub;
        
        catch (org.apache.axis.AxisFault e)
            return null;
        
    
org.glite.security.voms.service.acl.VOMSACL org.glite.security.voms.service.acl.VOMSACLServiceLocator.getVOMSACL () throws javax.xml.rpc.ServiceException
Implements org.glite.security.voms.service.acl.VOMSACLService.
Definition at line 42 of file VOMSACLServiceLocator.java.
References org.glite.security.voms.service.acl.VOMSACLServiceLocator.VOMSACL_address.
Referenced by org.glite.security.voms.service.acl.VOMSACLServiceLocator.getPort().
                                                                                 
                               
       java.net.URL endpoint;
        try
            endpoint = new java.net.URL(VOMSACL_address);
        
        catch (java.net.MalformedURLException e)
            throw new javax.xml.rpc.ServiceException(e);
        
        return getVOMSACL(endpoint);
    
java.lang.String org.glite.security.voms.service.acl.VOMSACLServiceLocator.getVOMSACLAddress ()
Implements org.glite.security.voms.service.acl.VOMSACLService.
Definition at line 27 of file VOMSACLServiceLocator.java.
References org.glite.security.voms.service.acl.VOMSACLServiceLocator.VOMSACL_address.
                                                
        return VOMSACL_address;
    
java.lang.String org.glite.security.voms.service.acl.VOMSACLServiceLocator.getVOMSACLWSDDServiceName ()
Definition at line 34 of file VOMSACLServiceLocator.java.
References org.glite.security.voms.service.acl.VOMSACLServiceLocator.VOMSACLWSDDServiceName.
Referenced by org.glite.security.voms.service.acl.VOMSACLServiceLocator.getPort(), and org.glite.security.voms.service.acl.VOMSACLServiceLocator.getVOMSACL().
                                                        
        return VOMSACLWSDDServiceName;
    
void org.glite.security.voms.service.acl.VOMSACLServiceLocator.setEndpointAddress (java.lang.String portName, java.lang.String address) throws javax.xml.rpc.ServiceException
Set the endpoint address for the specified port name.
Definition at line 124 of file VOMSACLServiceLocator.java.
References org.glite.security.voms.service.acl.VOMSACLServiceLocator.setVOMSACLEndpointAddress().
Referenced by org.glite.security.voms.service.acl.VOMSACLServiceLocator.setEndpointAddress().
                                                                                 
                                                   
        
if ("VOMSACL".equals(portName))
            setVOMSACLEndpointAddress(address);
        
        else
 // Unknown Port Name
            throw new javax.xml.rpc.ServiceException(" Cannot set Endpoint Addres
      s for Unknown Port" + portName);
        
    
void org.glite.security.voms.service.acl.VOMSACLServiceLocator.setEndpointAddress (javax.xml.namespace.QName portName, java.lang.String address) throws javax.xml.rpc.ServiceException
Set the endpoint address for the specified port name.
Definition at line 138 of file VOMSACLServiceLocator.java.
References org.glite.security.voms.service.acl.VOMSACLServiceLocator.setEndpointAddress().
                                                                                 
                                                            
        setEndpointAddress(portName.getLocalPart(), address);
    
void org.glite.security.voms.service.acl.VOMSACLServiceLocator.setVOMSACLEndpointAddress (java.lang.String address)
Definition at line 64 of file VOMSACLServiceLocator.java.
References org.glite.security.voms.service.acl.VOMSACLServiceLocator.VOMSACL_address.
Referenced by org.glite.security.voms.service.acl.VOMSACLServiceLocator.setEndpointAddress().
                                                                    
        VOMSACL_address = address;
    
void org.glite.security.voms.service.acl.VOMSACLServiceLocator.setVOMSACLWSDDServiceName (java.lang.String name)
Definition at line 38 of file VOMSACLServiceLocator.java.
References org.glite.security.voms.service.acl.VOMSACLServiceLocator.VOMSACLWSDDServiceName.
                                                                 
        VOMSACLWSDDServiceName = name;
    
Member Data Documentation
java.util.HashSet org.glite.security.voms.service.acl.VOMSACLServiceLocator.ports = null [private]
Definition at line 111 of file VOMSACLServiceLocator.java.
Referenced by org.glite.security.voms.service.acl.VOMSACLServiceLocator.getPorts().
java.lang.String org.glite.security.voms.service.acl.VOMSACLServiceLocator.VOMSACL_address = `https://localhost:8443/glite-security-voms-admin-interface/VOMSACL` [private]
Definition at line 25 of file VOMSACLServiceLocator.java.
Referenced by org.glite.security.voms.service.acl.VOMSACLServiceLocator.getPort(), org.glite.security.voms.service.acl.VOMSACLServiceLocator.getVOMSACL(), org.glite.security.voms.service.acl.VOMSACLServiceLocator.getVOMSACLAddress(), and org.glite.security.voms.service.acl.VOMSACLServiceLocator.setVOMSACLEndpointAddress().
java.lang.String org.glite.security.voms.service.acl.VOMSACLServiceLocator.VOMSACLWSDDServiceName = `VOMSACL` [private]
Definition at line 32 of file VOMSACLServiceLocator.java.
Referenced by org.glite.security.voms.service.acl.VOMSACLServiceLocator.getVOMSACLWSDDServiceName(), and org.glite.security.voms.service.acl.VOMSACLServiceLocator.setVOMSACLWSDDServiceName().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/acl/VOMSACLServiceLocator.java