org.glite.security.voms.service.acl.VOMSACLSoapBindingStub Class Reference
Public Member Functions
VOMSACLSoapBindingStub () throws org.apache.axis.AxisFault
VOMSACLSoapBindingStub (java.net.URL endpointURL, javax.xml.rpc.Service service) throws org.apache.axis.AxisFault
VOMSACLSoapBindingStub (javax.xml.rpc.Service service) throws org.apache.axis.AxisFault
org.glite.security.voms.service.acl.ACLEntry[] getACL (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void setACL (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry[] in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void addACLEntry (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry in1, boolean in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void removeACLEntry (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry in1, boolean in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.service.acl.ACLEntry[] getDefaultACL (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void setDefaultACL (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry[] in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void addDefaultACLEntry (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void removeDefaultACLEntry (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Protected Member Functions
org.apache.axis.client.Call createCall () throws java.rmi.RemoteException
Static Package Functions
[static initializer]
Static Package Attributes
static org.apache.axis.description.OperationDesc[] _operations
Static Private Member Functions
static void _initOperationDesc1 ()
Private Attributes
java.util.Vector cachedSerClasses = new java.util.Vector()
java.util.Vector cachedSerQNames = new java.util.Vector()
java.util.Vector cachedSerFactories = new java.util.Vector()
java.util.Vector cachedDeserFactories = new java.util.Vector()
Detailed Description
Definition at line 10 of file VOMSACLSoapBindingStub.java.
Constructor & Destructor Documentation
org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.VOMSACLSoapBindingStub () throws org.apache.axis.AxisFault
Definition at line 168 of file VOMSACLSoapBindingStub.java.
                                                                     
         this(null);
    
org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.VOMSACLSoapBindingStub (java.net.URL endpointURL, javax.xml.rpc.Service service) throws org.apache.axis.AxisFault
Definition at line 172 of file VOMSACLSoapBindingStub.java.
                                                                                 
                                                 
         this(service);
         super.cachedEndpoint = endpointURL;
    
org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.VOMSACLSoapBindingStub (javax.xml.rpc.Service service) throws org.apache.axis.AxisFault
Definition at line 177 of file VOMSACLSoapBindingStub.java.
References org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.cachedDeserFactories, org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.cachedSerClasses, org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.cachedSerFactories, and org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.cachedSerQNames.
                                                                                 
                       
        if (service == null)
            super.service = new org.apache.axis.client.Service();
         else
            super.service = service;
        
        ((org.apache.axis.client.Service)super.service).setTypeMappingVersion("1.
      2");
            java.lang.Class cls;
            javax.xml.namespace.QName qName;
            javax.xml.namespace.QName qName2;
            java.lang.Class beansf = org.apache.axis.encoding.ser.BeanSerializerF
      actory.class;
            java.lang.Class beandf = org.apache.axis.encoding.ser.BeanDeserialize
      rFactory.class;
            java.lang.Class enumsf = org.apache.axis.encoding.ser.EnumSerializerF
      actory.class;
            java.lang.Class enumdf = org.apache.axis.encoding.ser.EnumDeserialize
      rFactory.class;
            java.lang.Class arraysf = org.apache.axis.encoding.ser.ArraySerialize
      rFactory.class;
            java.lang.Class arraydf = org.apache.axis.encoding.ser.ArrayDeseriali
      zerFactory.class;
            java.lang.Class simplesf = org.apache.axis.encoding.ser.SimpleSeriali
      zerFactory.class;
            java.lang.Class simpledf = org.apache.axis.encoding.ser.SimpleDeseria
      lizerFactory.class;
            java.lang.Class simplelistsf = org.apache.axis.encoding.ser.SimpleLis
      tSerializerFactory.class;
            java.lang.Class simplelistdf = org.apache.axis.encoding.ser.SimpleLis
      tDeserializerFactory.class;
            qName = new javax.xml.namespace.QName("http://glite.org/wsdl/services
      /org.glite.security.voms.service.acl", "ACLEntry");
            cachedSerQNames.add(qName);
            cls = org.glite.security.voms.service.acl.ACLEntry.class;
            cachedSerClasses.add(cls);
            cachedSerFactories.add(beansf);
            cachedDeserFactories.add(beandf);
            qName = new javax.xml.namespace.QName("http://glite.org/wsdl/services
      /org.glite.security.voms.service.acl", "ArrayOfACLEntry");
            cachedSerQNames.add(qName);
            cls = org.glite.security.voms.service.acl.ACLEntry[].class;
            cachedSerClasses.add(cls);
            qName = new javax.xml.namespace.QName("http://glite.org/wsdl/services
      /org.glite.security.voms.service.acl", "ACLEntry");
            qName2 = null;
            cachedSerFactories.add(new org.apache.axis.encoding.ser.ArraySerializ
      erFactory(qName, qName2));
            cachedDeserFactories.add(new org.apache.axis.encoding.ser.ArrayDeseri
      alizerFactory());
            qName = new javax.xml.namespace.QName("http://glite.org/wsdl/services
      /org.glite.security.voms", "VOMSException");
            cachedSerQNames.add(qName);
            cls = org.glite.security.voms.VOMSException.class;
            cachedSerClasses.add(cls);
            cachedSerFactories.add(beansf);
            cachedDeserFactories.add(beandf);
    
Member Function Documentation
org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.[static initializer] () [static, package]
static void org.glite.security.voms.service.acl.VOMSACLSoapBindingStub._initOperationDesc1 () [static, private]
Definition at line 23 of file VOMSACLSoapBindingStub.java.
References org.glite.security.voms.service.acl.VOMSACLSoapBindingStub._operations.
                                             
        org.apache.axis.description.OperationDesc oper;
        org.apache.axis.description.ParameterDesc param;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("getACL");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(new javax.xml.namespace.QName("http://glite.org/wsdl/s
      ervices/org.glite.security.voms.service.acl", "ArrayOfACLEntry"));
        oper.setReturnClass(org.glite.security.voms.service.acl.ACLEntry[].class)
      ;
        oper.setReturnQName(new javax.xml.namespace.QName("", "getACLReturn"));
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.acl", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[0] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("setACL");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in1"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://glite.org/wsdl/services/org.glite.security.voms.service
      .acl", "ArrayOfACLEntry"), org.glite.security.voms.service.acl.ACLEntry[].class,
      false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.acl", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[1] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("addACLEntry");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in1"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://glite.org/wsdl/services/org.glite.security.voms.service
      .acl", "ACLEntry"), org.glite.security.voms.service.acl.ACLEntry.class, false, fa
      lse);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in2"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://www.w3.org/2001/XMLSchema", "boolean"), boolean.class,
      false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.acl", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[2] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("removeACLEntry");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in1"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://glite.org/wsdl/services/org.glite.security.voms.service
      .acl", "ACLEntry"), org.glite.security.voms.service.acl.ACLEntry.class, false, fa
      lse);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in2"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://www.w3.org/2001/XMLSchema", "boolean"), boolean.class,
      false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.acl", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[3] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("getDefaultACL");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(new javax.xml.namespace.QName("http://glite.org/wsdl/s
      ervices/org.glite.security.voms.service.acl", "ArrayOfACLEntry"));
        oper.setReturnClass(org.glite.security.voms.service.acl.ACLEntry[].class)
      ;
        oper.setReturnQName(new javax.xml.namespace.QName("", "getDefaultACLRetur
      n"));
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.acl", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[4] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("setDefaultACL");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in1"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://glite.org/wsdl/services/org.glite.security.voms.service
      .acl", "ArrayOfACLEntry"), org.glite.security.voms.service.acl.ACLEntry[].class,
      false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.acl", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[5] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("addDefaultACLEntry");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in1"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://glite.org/wsdl/services/org.glite.security.voms.service
      .acl", "ACLEntry"), org.glite.security.voms.service.acl.ACLEntry.class, false, fa
      lse);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.acl", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[6] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("removeDefaultACLEntry");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in1"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://glite.org/wsdl/services/org.glite.security.voms.service
      .acl", "ACLEntry"), org.glite.security.voms.service.acl.ACLEntry.class, false, fa
      lse);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.acl", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[7] = oper;
    
void org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.addACLEntry (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry in1, boolean in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.acl.VOMSACL.
Definition at line 358 of file VOMSACLSoapBindingStub.java.
                                                                                 
                                                                                       
                            
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[2]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.acl", "addACLEntry"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0,
      in1, new java.lang.Boolean(in2));
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
void org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.addDefaultACLEntry (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.acl.VOMSACL.
Definition at line 493 of file VOMSACLSoapBindingStub.java.
                                                                                 
                                                                                       
                      
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[6]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.acl", "addDefaultACLEntry"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0,
      in1);
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
org.apache.axis.client.Call org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.createCall () throws java.rmi.RemoteException [protected]
Definition at line 222 of file VOMSACLSoapBindingStub.java.
References org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.cachedDeserFactories, org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.cachedSerClasses, org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.cachedSerFactories, and org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.cachedSerQNames.
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.getACL().
                                                                                 
            
        try
            org.apache.axis.client.Call _call = super._createCall();
            if (super.maintainSessionSet)
                _call.setMaintainSession(super.maintainSession);
            
            if (super.cachedUsername != null)
                _call.setUsername(super.cachedUsername);
            
            if (super.cachedPassword != null)
                _call.setPassword(super.cachedPassword);
            
            if (super.cachedEndpoint != null)
                _call.setTargetEndpointAddress(super.cachedEndpoint);
            
            if (super.cachedTimeout != null)
                _call.setTimeout(super.cachedTimeout);
            
            if (super.cachedPortName != null)
                _call.setPortName(super.cachedPortName);
            
            java.util.Enumeration keys = super.cachedProperties.keys();
            while (keys.hasMoreElements())
                java.lang.String key = (java.lang.String) keys.nextElement();
                _call.setProperty(key, super.cachedProperties.get(key));
            
            // All the type mapping information is registered
            // when the first call is made.
            // The type mapping information is actually registered in
            // the TypeMappingRegistry of the service, which
            // is the reason why registration is only needed for the first call.
            synchronized (this)
                if (firstCall())
                    // must set encoding style before registering serializers
                    _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP1
      1_CONSTANTS);
                    _call.setEncodingStyle(org.apache.axis.Constants.URI_SOAP11_E
      NC);
                    for (int i = 0; i < cachedSerFactories.size(); ++i)
                        java.lang.Class cls = (java.lang.Class) cachedSerClasses.
      get(i);
                        javax.xml.namespace.QName qName =
                                (javax.xml.namespace.QName) cachedSerQNames.get(i
      );
                        java.lang.Object x = cachedSerFactories.get(i);
                        if (x instanceof Class)
                            java.lang.Class sf = (java.lang.Class)
                                 cachedSerFactories.get(i);
                            java.lang.Class df = (java.lang.Class)
                                 cachedDeserFactories.get(i);
                            _call.registerTypeMapping(cls, qName, sf, df, false);
      
                        
                        else if (x instanceof javax.xml.rpc.encoding.SerializerFa
      ctory)
                            org.apache.axis.encoding.SerializerFactory sf = (org.
      apache.axis.encoding.SerializerFactory)
                                 cachedSerFactories.get(i);
                            org.apache.axis.encoding.DeserializerFactory df = (or
      g.apache.axis.encoding.DeserializerFactory)
                                 cachedDeserFactories.get(i);
                            _call.registerTypeMapping(cls, qName, sf, df, false);
      
                        
                    
                
            
            return _call;
        
        catch (java.lang.Throwable _t)
            throw new org.apache.axis.AxisFault("Failure trying to get the Call o
      bject", _t);
        
    
org.glite.security.voms.service.acl.ACLEntry [] org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.getACL (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.acl.VOMSACL.
Definition at line 287 of file VOMSACLSoapBindingStub.java.
References org.glite.security.voms.service.acl.VOMSACLSoapBindingStub._operations, and org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.createCall().
                                                                                 
                                                                                   
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[0]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.acl", "getACL"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0)
      ;
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        else
            extractAttachments(_call);
            try
                return (org.glite.security.voms.service.acl.ACLEntry[]) _resp;
             catch (java.lang.Exception _exception)
                return (org.glite.security.voms.service.acl.ACLEntry[]) org.apach
      e.axis.utils.JavaUtils.convert(_resp, org.glite.security.voms.service.acl.ACLEntr
      y[].class);
            
        
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
org.glite.security.voms.service.acl.ACLEntry [] org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.getDefaultACL (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.acl.VOMSACL.
Definition at line 422 of file VOMSACLSoapBindingStub.java.
                                                                                 
                                                                                       
         
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[4]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.acl", "getDefaultACL"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0)
      ;
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        else
            extractAttachments(_call);
            try
                return (org.glite.security.voms.service.acl.ACLEntry[]) _resp;
             catch (java.lang.Exception _exception)
                return (org.glite.security.voms.service.acl.ACLEntry[]) org.apach
      e.axis.utils.JavaUtils.convert(_resp, org.glite.security.voms.service.acl.ACLEntr
      y[].class);
            
        
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
void org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.removeACLEntry (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry in1, boolean in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.acl.VOMSACL.
Definition at line 390 of file VOMSACLSoapBindingStub.java.
                                                                                 
                                                                                       
                               
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[3]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.acl", "removeACLEntry"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0,
      in1, new java.lang.Boolean(in2));
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
void org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.removeDefaultACLEntry (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.acl.VOMSACL.
Definition at line 525 of file VOMSACLSoapBindingStub.java.
                                                                                 
                                                                                       
                         
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[7]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.acl", "removeDefaultACLEntry"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0,
      in1);
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
void org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.setACL (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry[] in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.acl.VOMSACL.
Definition at line 326 of file VOMSACLSoapBindingStub.java.
                                                                                 
                                                                                       
            
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[1]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.acl", "setACL"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0,
      in1);
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
void org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.setDefaultACL (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry[] in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.acl.VOMSACL.
Definition at line 461 of file VOMSACLSoapBindingStub.java.
                                                                                 
                                                                                       
                   
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[5]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.acl", "setDefaultACL"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0,
      in1);
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
Member Data Documentation
org.apache.axis.description.OperationDesc [] org.glite.security.voms.service.acl.VOMSACLSoapBindingStub._operations [static, package]
Definition at line 16 of file VOMSACLSoapBindingStub.java.
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingStub._initOperationDesc1(), and org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.getACL().
java.util.Vector org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.cachedDeserFactories = new java.util.Vector() [private]
Definition at line 14 of file VOMSACLSoapBindingStub.java.
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.createCall(), and org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.VOMSACLSoapBindingStub().
java.util.Vector org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.cachedSerClasses = new java.util.Vector() [private]
Definition at line 11 of file VOMSACLSoapBindingStub.java.
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.createCall(), and org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.VOMSACLSoapBindingStub().
java.util.Vector org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.cachedSerFactories = new java.util.Vector() [private]
Definition at line 13 of file VOMSACLSoapBindingStub.java.
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.createCall(), and org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.VOMSACLSoapBindingStub().
java.util.Vector org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.cachedSerQNames = new java.util.Vector() [private]
Definition at line 12 of file VOMSACLSoapBindingStub.java.
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.createCall(), and org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.VOMSACLSoapBindingStub().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/acl/VOMSACLSoapBindingStub.java