portal.registration.controller.UploadCertController Class Reference
Public Member Functions
String showUploadCert (RenderResponse response)
void uploadCert (ActionRequest request, ActionResponse response, SessionStatus sessionStatus) throws PortalException, 			SystemException
void setDefaultCert (ActionRequest request, ActionResponse response, SessionStatus sessionStatus)
void removeCert (ActionRequest request, ActionResponse response, SessionStatus sessionStatus)
Private Member Functions
String myOpenssl (String opt, String filename, ArrayList< String > errors)
void deleteUploadedFile (ArrayList< String > files)
Private Attributes
CertificateService certificateService
Static Private Attributes
static final Logger log
Detailed Description
Definition at line 47 of file UploadCertController.java.
Member Function Documentation
void portal.registration.controller.UploadCertController.deleteUploadedFile (ArrayList< String > files) [private]
Definition at line 389 of file UploadCertController.java.
                                                                 
                try
                        String cmd = "rm -f /upload_files/" + files.get(0)
                                        + " /upload_files/" + files.get(1);
                        log.info("cmd = " + cmd);
                        Runtime.getRuntime().exec(cmd);
                 catch (IOException e)
                        e.printStackTrace();
                
        
String portal.registration.controller.UploadCertController.myOpenssl (String opt, String filename, ArrayList< String > errors) [private]
Definition at line 294 of file UploadCertController.java.
                                                  
                String result = null;
                try
                        String cmd = "/usr/bin/openssl x509 -in /upload_files/" +
       filename
                                        + " -" + opt + " -noout";
                        log.info("cmd = " + cmd);
                        Process p = Runtime.getRuntime().exec(cmd);
                        InputStream stdout = p.getInputStream();
                        InputStream stderr = p.getErrorStream();
                        BufferedReader output = new BufferedReader(new InputStrea
      mReader(
                                        stdout));
                        String line = null;
                        int posizione;
                        int cursore = (opt.equals("subject") || opt.equals("issue
      r")) ? 2
                                        : 1;
                        while ((line = output.readLine()) != null)
                                log.info("[Stdout] " + line);
                                if ((posizione = line.indexOf("=")) != -1)
                                        result = line.substring(posizione + curso
      re);
                                        log.info(opt + " = " + result);
                                
                        
                        output.close();
                        BufferedReader brCleanUp = new BufferedReader(
                                        new InputStreamReader(stderr));
                        while ((line = brCleanUp.readLine()) != null)
                                errors.add("no-valid-cert-" + opt);
                                log.info("[Stderr] " + line);
                        
                        brCleanUp.close();
                 catch (IOException e)
                        e.printStackTrace();
                
                return result;
        
void portal.registration.controller.UploadCertController.removeCert (ActionRequest request, ActionResponse response, SessionStatus sessionStatus)
Definition at line 366 of file UploadCertController.java.
References portal.registration.services.CertificateService.delete().
                                                     
                int idCert = Integer.parseInt(request.getParameter("idCert"));
                String userId = request.getParameter("userId");
                try
                        log.info("Sto per cancellare il certificato con id = " +
      idCert);
                        certificateService.delete(idCert);
                        log.info("Certificato cancellato");
                        SessionMessages.add(request, "certificate-deleted-success
      ufully");
                 catch (Exception e)
                        SessionErrors.add(request, "error-deleting-certificate");
      
                
                response.setRenderParameter("myaction", "editUserInfoForm");
                response.setRenderParameter("userId", userId);
                sessionStatus.setComplete();
        
void portal.registration.controller.UploadCertController.setDefaultCert (ActionRequest request, ActionResponse response, SessionStatus sessionStatus)
Definition at line 340 of file UploadCertController.java.
References portal.registration.services.CertificateService.setDefault().
                                                     
                int idCert = Integer.parseInt(request.getParameter("idCert"));
                String userId = request.getParameter("userId");
                try
                        log.info("Sto per cancellare il certificato con id = " +
      idCert);
                        if (certificateService.setDefault(idCert))
                                SessionMessages.add(request,
                                                "certificate-updated-successufull
      y");
                        else
                                SessionErrors.add(request, "error-default-certifi
      cate");
                        log.info("Certificato cancellato");
                 catch (Exception e)
                        SessionErrors.add(request, "error-updating-certificate");
      
                
                response.setRenderParameter("myaction", "editUserInfoForm");
                response.setRenderParameter("userId", userId);
                sessionStatus.setComplete();
        
String portal.registration.controller.UploadCertController.showUploadCert (RenderResponse response)
Definition at line 56 of file UploadCertController.java.
                                                              
                return "uploadCert";
        
void portal.registration.controller.UploadCertController.uploadCert (ActionRequest request, ActionResponse response, SessionStatus sessionStatus) throws PortalException, 			SystemException
Definition at line 61 of file UploadCertController.java.
References portal.registration.domain.Certificate.equals(), portal.registration.services.CertificateService.findById(), portal.registration.services.CertificateService.save(), portal.registration.domain.Certificate.setCaonline(), portal.registration.domain.Certificate.setExpirationDate(), portal.registration.domain.Certificate.setIdCert(), portal.registration.domain.Certificate.setIssuer(), portal.registration.domain.Certificate.setPrimaryCert(), portal.registration.domain.Certificate.setSubject(), and portal.registration.utils.MyValidator.validateCert().
                                        
                ArrayList<String> errors = new ArrayList<String>();
                boolean allOk = true;
                HttpServletRequest req = PortalUtil.getHttpServletRequest(request
      );
                if (req != null)
                        log.info("yessssss req");
                 else
                        log.info("noooooo disastro req");
                
                String ns = response.getNamespace();
                String primaryCert = null;
                String pwd = null;
                String pwd1 = null;
                String pwd2 = null;
                String username = null;
                String firstReg = null;
                ArrayList<String> files = new ArrayList<String>();
                int uid = 0;
                File dir = new File("/upload_files");
                if (dir.isDirectory())
                        if (ServletFileUpload.isMultipartContent(req))
                                log.info("yessssss" + ServletFileUpload.isMultipa
      rtContent(req));
                                try
                                        MultipartParser mp = new MultipartParser(
      req,
                                                        1 * 1024 * 1024); // 10MB
      
                                        Part part;
                                        while ((part = mp.readNextPart()) != null
      )
                                                String name = part.getName();
                                                if (part.isParam())
                                                        ParamPart paramPart = (Pa
      ramPart) part;
                                                        String value = paramPart.
      getStringValue();
                                                        if (name.equals(ns + "pas
      sword"))
                                                                pwd1 = value;
                                                        if (name.equals(ns + "pas
      swordVerify"))
                                                                pwd2 = value;
                                                        if (name.equals(ns + "use
      rname"))
                                                                username = value;
      
                                                        if (name.equals(ns + "use
      rId"))
                                                                uid = Integer.par
      seInt(value);
                                                        if (name.equals(ns + "key
      Pass"))
                                                                pwd = value;
                                                        if (name.equals(ns + "pri
      maryCert"))
                                                                primaryCert = val
      ue;
                                                        if (name.equals(ns + "fir
      stReg"))
                                                                firstReg = value;
      
                                                        log.info("param; name=" +
       name + ", value=" + value);
                                                 else if (part.isFile())
                                                        // it's a file part
                                                        FilePart filePart = (File
      Part) part;
                                                        String fileName = filePar
      t.getFileName();
                                                        if (fileName != null)
                                                                // the part actua
      lly contained a file
                                                                long size = fileP
      art.writeTo(dir);
                                                                log.info("file; n
      ame=" + name + "; filename="
                                                                                +
       fileName + ", filePath="
                                                                                +
       filePart.getFilePath()
                                                                                +
       ", content type="
                                                                                +
       filePart.getContentType() + ", size="
                                                                                +
       size);
                                                                files.add(fileNam
      e);
                                                         else
                                                                // the field did
      not contain a file
                                                                log.info("file; n
      ame=" + name + "; EMPTY");
                                                        
                                                
                                        
                                 catch (IOException lEx)
                                        allOk = false;
                                        log.info("error reading or saving file");
      
                                
                         else
                                allOk = false;
                                log.info("nooooooo "
                                                + ServletFileUpload.isMultipartCo
      ntent(req));
                        
                 else
                        allOk = false;
                        log.info("non è un a directory");
                
                if (MyValidator.validateCert(pwd, pwd1, pwd2, errors) && allOk)
      
                        // controllo file
                        // esecuzione myproxy
                        /*
                         * try Runtime.getRuntime().exec("/bin/chmod 600 /uploa
      d_files/" +
                         * files.get(1)); String myproxy =
                         * "/usr/bin/python /upload_files/myproxy2.py " + usernam
      e +
                         * " /upload_files/" + files.get(0) + " /upload_files/" +
      
                         * files.get(1) + " " + pwd + " " + pwd1;
                         * log.info("Myproxy command = " + myproxy); Process p =
                         * Runtime.getRuntime().exec(myproxy); InputStream stdout
       =
                         * p.getInputStream(); InputStream stderr = p.getErrorStr
      eam ();
                         *
                         *
                         * BufferedReader output = new BufferedReader (new InputS
      treamReader
                         * (stdout)); String line = null;
                         *
                         * while (((line = output.readLine ()) != null))
                         *
                         * log.info("[Stdout] " + line); if(line.equals("myproxy
      success"))
                         * log.info("myproxy ok"); pwd+="";
                         * if(line.equals("myproxy verify password failure"))
                         * log.info(line); allOk = false;
                         * if(line.equals("myproxy password userkey failure"))
                         * log.info(line); allOk = false; output.close();
                         *
                         * BufferedReader brCleanUp = new BufferedReader (new
                         * InputStreamReader (stderr)); while ((line = brCleanUp.
      readLine
                         * ()) != null) allOk = false; log.info ("[Stderr] " +
      line);
                         * if(!allOk) errors.add("myproxy-error"); brCleanUp.clos
      e();
                         * catch (IOException e1) allOk = false;
                         * errors.add("myproxy-exception"); e1.printStackTrace();
       
                         */
                        String subject = myOpenssl("subject", files.get(0), error
      s);
                        String issuer = myOpenssl("issuer", files.get(0), errors)
      ;
                        String enddate = myOpenssl("enddate", files.get(0), error
      s);
                        if ((subject != null) && (issuer != null) && (enddate !=
      null)
                                        && allOk)
                                Date date = null;
                                try
                                        DateFormat formatter = new SimpleDateForm
      at(
                                                        "MMM dd HH:mm:ss yyyy z")
      ;
                                        date = (Date) formatter.parse(enddate);
                                        log.info("data formattata = " + date.toSt
      ring());
                                        GregorianCalendar c = new GregorianCalend
      ar();
                                        Date oggi = c.getTime();
                                        log.info("data oggi = " + oggi.toString()
      );
                                        if (date.before(oggi))
                                                log.info("Certificato scaduto");
                                                errors.add("user-certificate-expi
      red");
                                                allOk = false;
                                         else
                                                log.info("Certificato valido");
                                        
                                 catch (ParseException e)
                                        allOk = false;
                                        log.info("Eccezzione data");
                                
                                if (allOk)
                                        Certificate cert = new Certificate();
                                        cert.setIdCert(0);
                                        cert.setCaonline("false");
                                        cert.setExpirationDate(date);
                                        cert.setIssuer(issuer);
                                        cert.setPrimaryCert(primaryCert);
                                        cert.setSubject(subject);
                                        List<Certificate> lc =
      certificateService.findById(uid);
                                        int i = 0;
                                        for (i = 0; i < lc.size(); i++)
                                                if (cert.equals(lc.get(i)))
                                                        allOk = false;
                                                        errors.add("certificate-d
      uplicate");
                                                        break;
                                                
                                        
                                        if (allOk)
                                                int id = certificateService.save(
      cert, uid);
                                                if (id != -1)
                                                        log.info("inserito il cer
      tificato per l'utente con userId = "
                                                                        + uid);
                                                 else
                                                        allOk = false;
                                                
                                        
                                
                         else
                                log.info("errori vari");
                                allOk = false;
                        
                
                log.info("controllo errori");
                if (allOk)
                        log.info("tutto ok!!");
                        SessionMessages.add(request, "upload-cert-successufully")
      ;
                        if (firstReg.equals("true"))
                                response.setRenderParameter("myaction",
                                                "showAddUserToVoPresents");
                                response.setRenderParameter("userId", Integer.toS
      tring(uid));
                                request.setAttribute("userId", uid);
                         else
                                response.setRenderParameter("myaction", "editUser
      InfoForm");
                                response.setRenderParameter("userId", Integer.toS
      tring(uid));
                        
                 else
                        log.info("Trovato errori");
                        errors.add("error-uploading-certificate");
                        for (String error : errors)
                                log.info("Errore: " + error);
                                SessionErrors.add(request, error);
                        
                        sessionStatus.setComplete();
                        response.setRenderParameter("myaction", "showUploadCert")
      ;
                        request.setAttribute("userId", uid);
                        request.setAttribute("username", username);
                        request.setAttribute("password", pwd1);
                        request.setAttribute("passwordVerify", pwd2);
                
                deleteUploadedFile(files);
        
Member Data Documentation
CertificateService portal.registration.controller.UploadCertController.certificateService [private]
Definition at line 53 of file UploadCertController.java.
final Logger portal.registration.controller.UploadCertController.log [static, private]
Initial value:
 Logger
                        .getLogger(UploadCertController.class)
Definition at line 49 of file UploadCertController.java.
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/controller/UploadCertController.java