org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub Class Reference
Public Member Functions
VOMSRegistrationSoapBindingStub () throws org.apache.axis.AxisFault
VOMSRegistrationSoapBindingStub (java.net.URL endpointURL, javax.xml.rpc.Service service) throws org.apache.axis.AxisFault
VOMSRegistrationSoapBindingStub (javax.xml.rpc.Service service) throws org.apache.axis.AxisFault
void submitRegistrationRequest (org.glite.security.voms.service.registration.RegistrationRequest in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void submitRegistrationRequestForUser (java.lang.String in0, java.lang.String in1, org.glite.security.voms.service.registration.RegistrationRequest in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Protected Member Functions
org.apache.axis.client.Call createCall () throws java.rmi.RemoteException
Static Package Functions
[static initializer]
Static Package Attributes
static org.apache.axis.description.OperationDesc[] _operations
Static Private Member Functions
static void _initOperationDesc1 ()
Private Attributes
java.util.Vector cachedSerClasses = new java.util.Vector()
java.util.Vector cachedSerQNames = new java.util.Vector()
java.util.Vector cachedSerFactories = new java.util.Vector()
java.util.Vector cachedDeserFactories = new java.util.Vector()
Detailed Description
Definition at line 10 of file VOMSRegistrationSoapBindingStub.java.
Constructor & Destructor Documentation
org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.VOMSRegistrationSoapBindingStub () throws org.apache.axis.AxisFault
Definition at line 62 of file VOMSRegistrationSoapBindingStub.java.
                                                                              
         this(null);
    
org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.VOMSRegistrationSoapBindingStub (java.net.URL endpointURL, javax.xml.rpc.Service service) throws org.apache.axis.AxisFault
Definition at line 66 of file VOMSRegistrationSoapBindingStub.java.
                                                                                 
                                                          
         this(service);
         super.cachedEndpoint = endpointURL;
    
org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.VOMSRegistrationSoapBindingStub (javax.xml.rpc.Service service) throws org.apache.axis.AxisFault
Definition at line 71 of file VOMSRegistrationSoapBindingStub.java.
References org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.cachedDeserFactories, org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.cachedSerClasses, org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.cachedSerFactories, and org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.cachedSerQNames.
                                                                                 
                                
        if (service == null)
            super.service = new org.apache.axis.client.Service();
         else
            super.service = service;
        
        ((org.apache.axis.client.Service)super.service).setTypeMappingVersion("1.
      2");
            java.lang.Class cls;
            javax.xml.namespace.QName qName;
            javax.xml.namespace.QName qName2;
            java.lang.Class beansf = org.apache.axis.encoding.ser.BeanSerializerF
      actory.class;
            java.lang.Class beandf = org.apache.axis.encoding.ser.BeanDeserialize
      rFactory.class;
            java.lang.Class enumsf = org.apache.axis.encoding.ser.EnumSerializerF
      actory.class;
            java.lang.Class enumdf = org.apache.axis.encoding.ser.EnumDeserialize
      rFactory.class;
            java.lang.Class arraysf = org.apache.axis.encoding.ser.ArraySerialize
      rFactory.class;
            java.lang.Class arraydf = org.apache.axis.encoding.ser.ArrayDeseriali
      zerFactory.class;
            java.lang.Class simplesf = org.apache.axis.encoding.ser.SimpleSeriali
      zerFactory.class;
            java.lang.Class simpledf = org.apache.axis.encoding.ser.SimpleDeseria
      lizerFactory.class;
            java.lang.Class simplelistsf = org.apache.axis.encoding.ser.SimpleLis
      tSerializerFactory.class;
            java.lang.Class simplelistdf = org.apache.axis.encoding.ser.SimpleLis
      tDeserializerFactory.class;
            qName = new javax.xml.namespace.QName("http://glite.org/wsdl/services
      /org.glite.security.voms.service.registration", "RegistrationRequest");
            cachedSerQNames.add(qName);
            cls = org.glite.security.voms.service.registration.RegistrationReques
      t.class;
            cachedSerClasses.add(cls);
            cachedSerFactories.add(beansf);
            cachedDeserFactories.add(beandf);
            qName = new javax.xml.namespace.QName("http://glite.org/wsdl/services
      /org.glite.security.voms", "VOMSException");
            cachedSerQNames.add(qName);
            cls = org.glite.security.voms.VOMSException.class;
            cachedSerClasses.add(cls);
            cachedSerFactories.add(beansf);
            cachedDeserFactories.add(beandf);
    
Member Function Documentation
org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.[static initializer] () [static, package]
static void org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub._initOperationDesc1 () [static, private]
Definition at line 23 of file VOMSRegistrationSoapBindingStub.java.
References org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub._operations.
                                             
        org.apache.axis.description.OperationDesc oper;
        org.apache.axis.description.ParameterDesc param;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("submitRegistrationRequest");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://glite.org/wsdl/services/org.glite.security.voms.service
      .registration", "RegistrationRequest"), org.glite.security.voms.service.registrat
      ion.RegistrationRequest.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.registration", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[0] = oper;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName("submitRegistrationRequestForUser");
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in0"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in1"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://schemas.xmlsoap.org/soap/encoding/", "string"), java.la
      ng.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.names
      pace.QName("", "in2"), org.apache.axis.description.ParameterDesc.IN, new javax.xm
      l.namespace.QName("http://glite.org/wsdl/services/org.glite.security.voms.service
      .registration", "RegistrationRequest"), org.glite.security.voms.service.registrat
      ion.RegistrationRequest.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms.service.registration", "fault"),
                      "org.glite.security.voms.VOMSException",
                      new javax.xml.namespace.QName("http://glite.org/wsdl/servic
      es/org.glite.security.voms", "VOMSException"),
                      true
                     ));
        _operations[1] = oper;
    
org.apache.axis.client.Call org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.createCall () throws java.rmi.RemoteException [protected]
Definition at line 107 of file VOMSRegistrationSoapBindingStub.java.
References org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.cachedDeserFactories, org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.cachedSerClasses, org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.cachedSerFactories, and org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.cachedSerQNames.
Referenced by org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.submitRegistrationRequest().
                                                                                 
            
        try
            org.apache.axis.client.Call _call = super._createCall();
            if (super.maintainSessionSet)
                _call.setMaintainSession(super.maintainSession);
            
            if (super.cachedUsername != null)
                _call.setUsername(super.cachedUsername);
            
            if (super.cachedPassword != null)
                _call.setPassword(super.cachedPassword);
            
            if (super.cachedEndpoint != null)
                _call.setTargetEndpointAddress(super.cachedEndpoint);
            
            if (super.cachedTimeout != null)
                _call.setTimeout(super.cachedTimeout);
            
            if (super.cachedPortName != null)
                _call.setPortName(super.cachedPortName);
            
            java.util.Enumeration keys = super.cachedProperties.keys();
            while (keys.hasMoreElements())
                java.lang.String key = (java.lang.String) keys.nextElement();
                _call.setProperty(key, super.cachedProperties.get(key));
            
            // All the type mapping information is registered
            // when the first call is made.
            // The type mapping information is actually registered in
            // the TypeMappingRegistry of the service, which
            // is the reason why registration is only needed for the first call.
            synchronized (this)
                if (firstCall())
                    // must set encoding style before registering serializers
                    _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP1
      1_CONSTANTS);
                    _call.setEncodingStyle(org.apache.axis.Constants.URI_SOAP11_E
      NC);
                    for (int i = 0; i < cachedSerFactories.size(); ++i)
                        java.lang.Class cls = (java.lang.Class) cachedSerClasses.
      get(i);
                        javax.xml.namespace.QName qName =
                                (javax.xml.namespace.QName) cachedSerQNames.get(i
      );
                        java.lang.Object x = cachedSerFactories.get(i);
                        if (x instanceof Class)
                            java.lang.Class sf = (java.lang.Class)
                                 cachedSerFactories.get(i);
                            java.lang.Class df = (java.lang.Class)
                                 cachedDeserFactories.get(i);
                            _call.registerTypeMapping(cls, qName, sf, df, false);
      
                        
                        else if (x instanceof javax.xml.rpc.encoding.SerializerFa
      ctory)
                            org.apache.axis.encoding.SerializerFactory sf = (org.
      apache.axis.encoding.SerializerFactory)
                                 cachedSerFactories.get(i);
                            org.apache.axis.encoding.DeserializerFactory df = (or
      g.apache.axis.encoding.DeserializerFactory)
                                 cachedDeserFactories.get(i);
                            _call.registerTypeMapping(cls, qName, sf, df, false);
      
                        
                    
                
            
            return _call;
        
        catch (java.lang.Throwable _t)
            throw new org.apache.axis.AxisFault("Failure trying to get the Call o
      bject", _t);
        
    
void org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.submitRegistrationRequest (org.glite.security.voms.service.registration.RegistrationRequest in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.registration.VOMSRegistration.
Definition at line 172 of file VOMSRegistrationSoapBindingStub.java.
References org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub._operations, and org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.createCall().
                                                                                 
                                                                                       
                           
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[0]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.registration", "submitRegistrationReq
      uest"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0)
      ;
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
void org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.submitRegistrationRequestForUser (java.lang.String in0, java.lang.String in1, org.glite.security.voms.service.registration.RegistrationRequest in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implements org.glite.security.voms.service.registration.VOMSRegistration.
Definition at line 204 of file VOMSRegistrationSoapBindingStub.java.
                                                                                 
                                                                                       
                                                                              
        if (super.cachedEndpoint == null)
            throw new org.apache.axis.NoEndPointException();
        
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[1]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI("");
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS)
      ;
        _call.setOperationName(new javax.xml.namespace.QName("http://glite.org/ws
      dl/services/org.glite.security.voms.service.registration", "submitRegistrationReq
      uestForUser"));
        setRequestHeaders(_call);
        setAttachments(_call);
 try java.lang.Object _resp = _call.invoke(new java.lang.Object[] in0,
      in1, in2);
        if (_resp instanceof java.rmi.RemoteException)
            throw (java.rmi.RemoteException)_resp;
        
        extractAttachments(_call);
   catch (org.apache.axis.AxisFault axisFaultException)
    if (axisFaultException.detail != null)
        if (axisFaultException.detail instanceof java.rmi.RemoteException)
              throw (java.rmi.RemoteException) axisFaultException.detail;
         
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSExce
      ption)
              throw (org.glite.security.voms.VOMSException) axisFaultException.de
      tail;
         
   
  throw axisFaultException;
    
Member Data Documentation
org.apache.axis.description.OperationDesc [] org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub._operations [static, package]
Definition at line 16 of file VOMSRegistrationSoapBindingStub.java.
Referenced by org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub._initOperationDesc1(), and org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.submitRegistrationRequest().
java.util.Vector org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.cachedDeserFactories = new java.util.Vector() [private]
Definition at line 14 of file VOMSRegistrationSoapBindingStub.java.
Referenced by org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.createCall(), and org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.VOMSRegistrationSoapBindingStub().
java.util.Vector org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.cachedSerClasses = new java.util.Vector() [private]
Definition at line 11 of file VOMSRegistrationSoapBindingStub.java.
Referenced by org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.createCall(), and org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.VOMSRegistrationSoapBindingStub().
java.util.Vector org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.cachedSerFactories = new java.util.Vector() [private]
Definition at line 13 of file VOMSRegistrationSoapBindingStub.java.
Referenced by org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.createCall(), and org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.VOMSRegistrationSoapBindingStub().
java.util.Vector org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.cachedSerQNames = new java.util.Vector() [private]
Definition at line 12 of file VOMSRegistrationSoapBindingStub.java.
Referenced by org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.createCall(), and org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub.VOMSRegistrationSoapBindingStub().
The documentation for this class was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/registration/VOMSRegistrationSoapBindingStub.java