portal.registration.services.UserToVoService Interface Reference
Public Member Functions
void save (UserToVo transientInstance)
void save (int userId, int idVo)
List< UserToVo > findById (int userId)
List< Vo > findVoByUserId (int userId)
void delete (int userId, int idVo)
boolean setDefault (int userId, int idVo)
UserToVo findById (int userId, int idVo)
void update (UserToVo utv)
String findDefaultVo (int userId)
String getDefaultFqan (int userId)
int getNumberOfUserToVo (int userId)
Detailed Description
Definition at line 8 of file UserToVoService.java.
Member Function Documentation
void portal.registration.services.UserToVoService.delete (int userId, int idVo)
Implemented in portal.registration.services.UserToVoServiceImpl.
Referenced by portal.registration.controller.AddUserToVOController.removeUserToVo(), and portal.registration.controller.AddUserToVOController.removeUserToVoEdit().
List<UserToVo> portal.registration.services.UserToVoService.findById (int userId)
Implemented in portal.registration.services.UserToVoServiceImpl.
Referenced by portal.registration.controller.EditUserToVoController.addUserToVo(), portal.registration.controller.AddUserToVOController.checkVO(), portal.registration.controller.EditUserToVoController.getUserToVo(), portal.registration.controller.EditUserInfoController.showEditUserInfoForm(), and portal.registration.controller.AddUserToVoPresentsController.showUserInfoForm().
UserToVo portal.registration.services.UserToVoService.findById (int userId, int idVo)
Implemented in portal.registration.services.UserToVoServiceImpl.
String portal.registration.services.UserToVoService.findDefaultVo (int userId)
Implemented in portal.registration.services.UserToVoServiceImpl.
Referenced by portal.registration.controller.EditUserInfoController.getDefaultVo().
List<Vo> portal.registration.services.UserToVoService.findVoByUserId (int userId)
Implemented in portal.registration.services.UserToVoServiceImpl.
Referenced by portal.registration.controller.EditUserInfoController.getUserToVoList(), portal.registration.controller.AddUserToVoPresentsController.getUserToVoList(), portal.registration.controller.AddUserToVOController.removeUserToVoEdit(), portal.registration.controller.AddUserToVOController.setDefaultUserToVo(), and portal.registration.controller.AddUserToVOController.setDefaultUserToVoEdit().
String portal.registration.services.UserToVoService.getDefaultFqan (int userId)
Implemented in portal.registration.services.UserToVoServiceImpl.
Referenced by portal.registration.controller.EditUserInfoController.getDefaultFqan().
int portal.registration.services.UserToVoService.getNumberOfUserToVo (int userId)
Implemented in portal.registration.services.UserToVoServiceImpl.
void portal.registration.services.UserToVoService.save (int userId, int idVo)
Implemented in portal.registration.services.UserToVoServiceImpl.
void portal.registration.services.UserToVoService.save (UserToVo transientInstance)
Implemented in portal.registration.services.UserToVoServiceImpl.
Referenced by portal.registration.controller.AddUserToVOController.addUserToVo().
boolean portal.registration.services.UserToVoService.setDefault (int userId, int idVo)
Implemented in portal.registration.services.UserToVoServiceImpl.
Referenced by portal.registration.controller.AddUserToVOController.setDefaultUserToVo(), and portal.registration.controller.AddUserToVOController.setDefaultUserToVoEdit().
void portal.registration.services.UserToVoService.update (UserToVo utv)
Implemented in portal.registration.services.UserToVoServiceImpl.
Referenced by portal.registration.controller.EditUserToVoController.addUserToVo().
The documentation for this interface was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/services/UserToVoService.java