org.glite.security.voms.service.certificates.VOMSCertificates Interface Reference
Public Member Functions
org.glite.security.voms.service.certificates.X509Certificate[] getCertificates (long in0) throws java.rmi.RemoteException
org.glite.security.voms.service.certificates.X509Certificate[] getCertificates (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException
long getUserIdFromDn (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException
void addCertificate (long in0, org.glite.security.voms.service.certificates.X509Certificate in1) throws java.rmi.RemoteException
void addCertificate (java.lang.String in0, java.lang.String in1, org.glite.security.voms.service.certificates.X509Certificate in2) throws java.rmi.RemoteException
void suspendCertificate (org.glite.security.voms.service.certificates.X509Certificate in0, java.lang.String in1) throws java.rmi.RemoteException
void restoreCertificate (org.glite.security.voms.service.certificates.X509Certificate in0) throws java.rmi.RemoteException
void removeCertificate (org.glite.security.voms.service.certificates.X509Certificate in0) throws java.rmi.RemoteException
Detailed Description
Definition at line 10 of file VOMSCertificates.java.
Member Function Documentation
void org.glite.security.voms.service.certificates.VOMSCertificates.addCertificate (long in0, org.glite.security.voms.service.certificates.X509Certificate in1) throws java.rmi.RemoteException
Implemented in org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingImpl, org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton, and org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.
Referenced by org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.addCertificate().
void org.glite.security.voms.service.certificates.VOMSCertificates.addCertificate (java.lang.String in0, java.lang.String in1, org.glite.security.voms.service.certificates.X509Certificate in2) throws java.rmi.RemoteException
Implemented in org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingImpl, org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton, and org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.
org.glite.security.voms.service.certificates.X509Certificate [] org.glite.security.voms.service.certificates.VOMSCertificates.getCertificates (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException
Implemented in org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingImpl, org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton, and org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.
org.glite.security.voms.service.certificates.X509Certificate [] org.glite.security.voms.service.certificates.VOMSCertificates.getCertificates (long in0) throws java.rmi.RemoteException
Implemented in org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingImpl, org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton, and org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.
Referenced by org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.getCertificates().
long org.glite.security.voms.service.certificates.VOMSCertificates.getUserIdFromDn (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException
Implemented in org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingImpl, org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton, and org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.
Referenced by org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.getUserIdFromDn().
void org.glite.security.voms.service.certificates.VOMSCertificates.removeCertificate (org.glite.security.voms.service.certificates.X509Certificate in0) throws java.rmi.RemoteException
Implemented in org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingImpl, org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton, and org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.
Referenced by org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.removeCertificate().
void org.glite.security.voms.service.certificates.VOMSCertificates.restoreCertificate (org.glite.security.voms.service.certificates.X509Certificate in0) throws java.rmi.RemoteException
Implemented in org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingImpl, org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton, and org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.
Referenced by org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.restoreCertificate().
void org.glite.security.voms.service.certificates.VOMSCertificates.suspendCertificate (org.glite.security.voms.service.certificates.X509Certificate in0, java.lang.String in1) throws java.rmi.RemoteException
Implemented in org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingImpl, org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton, and org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingStub.
Referenced by org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingSkeleton.suspendCertificate().
The documentation for this interface was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/certificates/VOMSCertificates.java