portal.registration.dao.VoDAO Interface Reference
Public Member Functions
List< Vo > getAllVo ()
Vo findById (Integer id)
List< String > getAllDiscipline ()
Detailed Description
Definition at line 7 of file VoDAO.java.
Member Function Documentation
Vo portal.registration.dao.VoDAO.findById (Integer id)
Implemented in portal.registration.dao.VoDAOImpl.
Referenced by portal.registration.services.VoServiceImpl.findById(), portal.registration.services.VoServiceImpl.findByVo(), portal.registration.services.UserToVoServiceImpl.findDefaultVo(), and portal.registration.services.UserToVoServiceImpl.save().
List<String> portal.registration.dao.VoDAO.getAllDiscipline ()
Implemented in portal.registration.dao.VoDAOImpl.
Referenced by portal.registration.services.VoServiceImpl.getAllDiscplines().
List<Vo> portal.registration.dao.VoDAO.getAllVo ()
Implemented in portal.registration.dao.VoDAOImpl.
Referenced by portal.registration.services.VoServiceImpl.getAllVo().
The documentation for this interface was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/dao/VoDAO.java