portal.registration.dao.UserInfoDAO Interface Reference
Public Member Functions
Integer save (UserInfo transientInstance)
void delete (UserInfo persistentInstance)
UserInfo findById (Integer id)
List< UserInfo > getAllUserInfo ()
void edit (UserInfo userInfo)
Detailed Description
Definition at line 7 of file UserInfoDAO.java.
Member Function Documentation
void portal.registration.dao.UserInfoDAO.delete (UserInfo persistentInstance)
Implemented in portal.registration.dao.UserInfoDAOImpl.
Referenced by portal.registration.services.UserInfoServiceImpl.delete().
void portal.registration.dao.UserInfoDAO.edit (UserInfo userInfo)
Implemented in portal.registration.dao.UserInfoDAOImpl.
Referenced by portal.registration.services.UserInfoServiceImpl.edit().
UserInfo portal.registration.dao.UserInfoDAO.findById (Integer id)
Implemented in portal.registration.dao.UserInfoDAOImpl.
Referenced by portal.registration.services.UserInfoServiceImpl.delete(), portal.registration.services.UserToVoServiceImpl.findById(), portal.registration.services.UserInfoServiceImpl.findById(), portal.registration.services.CertificateServiceImpl.findById(), portal.registration.services.UserToVoServiceImpl.findVoByUserId(), portal.registration.services.UserToVoServiceImpl.save(), portal.registration.services.CertificateServiceImpl.save(), and portal.registration.services.UserToVoServiceImpl.setDefault().
List<UserInfo> portal.registration.dao.UserInfoDAO.getAllUserInfo ()
Implemented in portal.registration.dao.UserInfoDAOImpl.
Referenced by portal.registration.services.UserInfoServiceImpl.getAllUserInfo().
Integer portal.registration.dao.UserInfoDAO.save (UserInfo transientInstance)
Implemented in portal.registration.dao.UserInfoDAOImpl.
Referenced by portal.registration.services.UserInfoServiceImpl.save().
The documentation for this interface was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/dao/UserInfoDAO.java