org.glite.security.voms.service.admin.VOMSAdmin Interface Reference
Public Member Functions
void createGroup (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.User getUser (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void setUser (org.glite.security.voms.User in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
int getMajorVersionNumber () throws java.rmi.RemoteException
java.lang.String getVOName () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void createUser (org.glite.security.voms.User in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteUser (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteGroup (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void createRole (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteRole (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void createCapability (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteCapability (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void addMember (java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void removeMember (java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void assignRole (java.lang.String in0, java.lang.String in1, java.lang.String in2, java.lang.String in3) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void dismissRole (java.lang.String in0, java.lang.String in1, java.lang.String in2, java.lang.String in3) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void assignCapability (java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void dismissCapability (java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.User[] listMembers (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.User[] listUsersWithRole (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.User[] listUsersWithCapability (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
java.lang.String[] getGroupPath (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
java.lang.String[] listSubGroups (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
java.lang.String[] listGroups (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
java.lang.String[] listRoles () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
java.lang.String[] listRoles (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
java.lang.String[] listCapabilities () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
java.lang.String[] listCapabilities (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
java.lang.String[] listCAs () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.ACLEntry[] getACL (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void setACL (java.lang.String in0, org.glite.security.voms.ACLEntry[] in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void addACLEntry (java.lang.String in0, org.glite.security.voms.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void removeACLEntry (java.lang.String in0, org.glite.security.voms.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.ACLEntry[] getDefaultACL (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void setDefaultACL (java.lang.String in0, org.glite.security.voms.ACLEntry[] in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void addDefaultACLEntry (java.lang.String in0, org.glite.security.voms.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void removeDefaultACLEntry (java.lang.String in0, org.glite.security.voms.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
int getMinorVersionNumber () throws java.rmi.RemoteException
int getPatchVersionNumber () throws java.rmi.RemoteException
Detailed Description
Definition at line 10 of file VOMSAdmin.java.
Member Function Documentation
void org.glite.security.voms.service.admin.VOMSAdmin.addACLEntry (java.lang.String in0, org.glite.security.voms.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.addACLEntry().
void org.glite.security.voms.service.admin.VOMSAdmin.addDefaultACLEntry (java.lang.String in0, org.glite.security.voms.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.addDefaultACLEntry().
void org.glite.security.voms.service.admin.VOMSAdmin.addMember (java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.addMember().
void org.glite.security.voms.service.admin.VOMSAdmin.assignCapability (java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.assignCapability().
void org.glite.security.voms.service.admin.VOMSAdmin.assignRole (java.lang.String in0, java.lang.String in1, java.lang.String in2, java.lang.String in3) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.assignRole().
void org.glite.security.voms.service.admin.VOMSAdmin.createCapability (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.createCapability().
void org.glite.security.voms.service.admin.VOMSAdmin.createGroup (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.createGroup().
void org.glite.security.voms.service.admin.VOMSAdmin.createRole (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.createRole().
void org.glite.security.voms.service.admin.VOMSAdmin.createUser (org.glite.security.voms.User in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.createUser().
void org.glite.security.voms.service.admin.VOMSAdmin.deleteCapability (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.deleteCapability().
void org.glite.security.voms.service.admin.VOMSAdmin.deleteGroup (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.deleteGroup().
void org.glite.security.voms.service.admin.VOMSAdmin.deleteRole (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.deleteRole().
void org.glite.security.voms.service.admin.VOMSAdmin.deleteUser (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.deleteUser().
void org.glite.security.voms.service.admin.VOMSAdmin.dismissCapability (java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.dismissCapability().
void org.glite.security.voms.service.admin.VOMSAdmin.dismissRole (java.lang.String in0, java.lang.String in1, java.lang.String in2, java.lang.String in3) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.dismissRole().
org.glite.security.voms.ACLEntry [] org.glite.security.voms.service.admin.VOMSAdmin.getACL (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getACL().
org.glite.security.voms.ACLEntry [] org.glite.security.voms.service.admin.VOMSAdmin.getDefaultACL (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getDefaultACL().
java.lang.String [] org.glite.security.voms.service.admin.VOMSAdmin.getGroupPath (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getGroupPath().
int org.glite.security.voms.service.admin.VOMSAdmin.getMajorVersionNumber () throws java.rmi.RemoteException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getMajorVersionNumber().
int org.glite.security.voms.service.admin.VOMSAdmin.getMinorVersionNumber () throws java.rmi.RemoteException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getMinorVersionNumber().
int org.glite.security.voms.service.admin.VOMSAdmin.getPatchVersionNumber () throws java.rmi.RemoteException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getPatchVersionNumber().
org.glite.security.voms.User org.glite.security.voms.service.admin.VOMSAdmin.getUser (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getUser().
java.lang.String org.glite.security.voms.service.admin.VOMSAdmin.getVOName () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.getVOName().
java.lang.String [] org.glite.security.voms.service.admin.VOMSAdmin.listCapabilities () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.listCapabilities().
java.lang.String [] org.glite.security.voms.service.admin.VOMSAdmin.listCapabilities (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
java.lang.String [] org.glite.security.voms.service.admin.VOMSAdmin.listCAs () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.listCAs().
java.lang.String [] org.glite.security.voms.service.admin.VOMSAdmin.listGroups (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.listGroups().
org.glite.security.voms.User [] org.glite.security.voms.service.admin.VOMSAdmin.listMembers (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.listMembers().
java.lang.String [] org.glite.security.voms.service.admin.VOMSAdmin.listRoles (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
java.lang.String [] org.glite.security.voms.service.admin.VOMSAdmin.listRoles () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by portal.registration.utils.VOMSAdminCallOut.getUserFQANs(), and org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.listRoles().
java.lang.String [] org.glite.security.voms.service.admin.VOMSAdmin.listSubGroups (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.listSubGroups().
org.glite.security.voms.User [] org.glite.security.voms.service.admin.VOMSAdmin.listUsersWithCapability (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.listUsersWithCapability().
org.glite.security.voms.User [] org.glite.security.voms.service.admin.VOMSAdmin.listUsersWithRole (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.listUsersWithRole().
void org.glite.security.voms.service.admin.VOMSAdmin.removeACLEntry (java.lang.String in0, org.glite.security.voms.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.removeACLEntry().
void org.glite.security.voms.service.admin.VOMSAdmin.removeDefaultACLEntry (java.lang.String in0, org.glite.security.voms.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.removeDefaultACLEntry().
void org.glite.security.voms.service.admin.VOMSAdmin.removeMember (java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.removeMember().
void org.glite.security.voms.service.admin.VOMSAdmin.setACL (java.lang.String in0, org.glite.security.voms.ACLEntry[] in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.setACL().
void org.glite.security.voms.service.admin.VOMSAdmin.setDefaultACL (java.lang.String in0, org.glite.security.voms.ACLEntry[] in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.setDefaultACL().
void org.glite.security.voms.service.admin.VOMSAdmin.setUser (org.glite.security.voms.User in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl, org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton, and org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub.
Referenced by org.glite.security.voms.service.admin.VOMSAdminSoapBindingSkeleton.setUser().
The documentation for this interface was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/admin/VOMSAdmin.java