portal.registration.dao.CertificateDAO Interface Reference
Public Member Functions
Integer save (Certificate transientInstance)
void delete (Certificate persistentInstance)
List< Certificate > findById (UserInfo userInfo)
Certificate findById (Integer id)
void edit (Certificate certificate)
Detailed Description
Definition at line 8 of file CertificateDAO.java.
Member Function Documentation
void portal.registration.dao.CertificateDAO.delete (Certificate persistentInstance)
Implemented in portal.registration.dao.CertificateDAOImpl.
Referenced by portal.registration.services.CertificateServiceImpl.delete().
void portal.registration.dao.CertificateDAO.edit (Certificate certificate)
Implemented in portal.registration.dao.CertificateDAOImpl.
Referenced by portal.registration.services.CertificateServiceImpl.save(), and portal.registration.services.CertificateServiceImpl.setDefault().
Certificate portal.registration.dao.CertificateDAO.findById (Integer id)
Implemented in portal.registration.dao.CertificateDAOImpl.
List<Certificate> portal.registration.dao.CertificateDAO.findById (UserInfo userInfo)
Implemented in portal.registration.dao.CertificateDAOImpl.
Referenced by portal.registration.services.CertificateServiceImpl.delete(), portal.registration.services.CertificateServiceImpl.findById(), portal.registration.services.CertificateServiceImpl.save(), and portal.registration.services.CertificateServiceImpl.setDefault().
Integer portal.registration.dao.CertificateDAO.save (Certificate transientInstance)
Implemented in portal.registration.dao.CertificateDAOImpl.
Referenced by portal.registration.services.CertificateServiceImpl.save().
The documentation for this interface was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/dao/CertificateDAO.java