org.glite.security.voms.service.compatibility.VOMSCompatibility Interface Reference
Public Member Functions
int getMajorVersionNumber () throws java.rmi.RemoteException
int getMinorVersionNumber () throws java.rmi.RemoteException
int getPatchVersionNumber () throws java.rmi.RemoteException
java.lang.String[] getGridmapUsers () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
java.lang.String[] getGridmapUsers (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Detailed Description
Definition at line 10 of file VOMSCompatibility.java.
Member Function Documentation
java.lang.String [] org.glite.security.voms.service.compatibility.VOMSCompatibility.getGridmapUsers () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingImpl, org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton, and org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.getGridmapUsers().
java.lang.String [] org.glite.security.voms.service.compatibility.VOMSCompatibility.getGridmapUsers (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingImpl, org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton, and org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.
int org.glite.security.voms.service.compatibility.VOMSCompatibility.getMajorVersionNumber () throws java.rmi.RemoteException
Implemented in org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingImpl, org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton, and org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.getMajorVersionNumber().
int org.glite.security.voms.service.compatibility.VOMSCompatibility.getMinorVersionNumber () throws java.rmi.RemoteException
Implemented in org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingImpl, org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton, and org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.getMinorVersionNumber().
int org.glite.security.voms.service.compatibility.VOMSCompatibility.getPatchVersionNumber () throws java.rmi.RemoteException
Implemented in org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingImpl, org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton, and org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub.
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.getPatchVersionNumber().
The documentation for this interface was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/compatibility/VOMSCompatibility.java