portal.registration.services.UserInfoService Interface Reference
Public Member Functions
Integer save (UserInfo transientInstance)
void delete (UserInfo persistentInstance)
void delete (int userId)
UserInfo findById (Integer id)
List< UserInfo > getAllUserInfo ()
void edit (UserInfo userInfo)
int save (UserInfo userInfo, int idIDP)
Detailed Description
Definition at line 7 of file UserInfoService.java.
Member Function Documentation
void portal.registration.services.UserInfoService.delete (UserInfo persistentInstance)
Implemented in portal.registration.services.UserInfoServiceImpl.
Referenced by portal.registration.controller.RemoveUserInfoController.removeUserInfo().
void portal.registration.services.UserInfoService.delete (int userId)
Implemented in portal.registration.services.UserInfoServiceImpl.
void portal.registration.services.UserInfoService.edit (UserInfo userInfo)
Implemented in portal.registration.services.UserInfoServiceImpl.
Referenced by portal.registration.controller.AddUserToVOController.activateUser(), portal.registration.controller.EditUserInfoController.deactivateUser(), portal.registration.controller.AddUserToVoPresentsController.deactivateUser(), and portal.registration.controller.EditUserInfoController.editUserInfo().
UserInfo portal.registration.services.UserInfoService.findById (Integer id)
Implemented in portal.registration.services.UserInfoServiceImpl.
Referenced by portal.registration.controller.AddUserToVOController.addUserToVo(), portal.registration.controller.EditUserInfoController.deactivateUser(), portal.registration.controller.AddUserToVoPresentsController.deactivateUser(), portal.registration.controller.EditUserInfoController.editUserInfo(), portal.registration.controller.EditUserToVoController.getUserInfo(), portal.registration.controller.EditUserInfoController.getUserInfo(), and portal.registration.controller.RemoveUserInfoController.removeUserInfo().
List<UserInfo> portal.registration.services.UserInfoService.getAllUserInfo ()
Implemented in portal.registration.services.UserInfoServiceImpl.
Referenced by portal.registration.controller.UserInfoController.getIdpsName(), and portal.registration.controller.UserInfoController.getUserInfos().
int portal.registration.services.UserInfoService.save (UserInfo userInfo, int idIDP)
Implemented in portal.registration.services.UserInfoServiceImpl.
Integer portal.registration.services.UserInfoService.save (UserInfo transientInstance)
Implemented in portal.registration.services.UserInfoServiceImpl.
Referenced by portal.registration.controller.AddUserInfoController.addUserInfo().
The documentation for this interface was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/services/UserInfoService.java