portal.registration.dao.UserToVoDAO Interface Reference
Public Member Functions
void save (UserToVo transientInstance)
List< UserToVo > findById (UserInfo userInfo)
Vo getVoByUserToVo (UserToVo userToVo)
void delete (int userId, int idVo)
UserToVo findByIds (int userId, int idVo)
void update (UserToVo temp)
int getNumberOfUserToVo (int userId)
Detailed Description
Definition at line 9 of file UserToVoDAO.java.
Member Function Documentation
void portal.registration.dao.UserToVoDAO.delete (int userId, int idVo)
Implemented in portal.registration.dao.UserToVoDAOImpl.
Referenced by portal.registration.services.UserToVoServiceImpl.delete().
List<UserToVo> portal.registration.dao.UserToVoDAO.findById (UserInfo userInfo)
Implemented in portal.registration.dao.UserToVoDAOImpl.
Referenced by portal.registration.services.UserToVoServiceImpl.findById(), portal.registration.services.UserToVoServiceImpl.findVoByUserId(), and portal.registration.services.UserToVoServiceImpl.setDefault().
UserToVo portal.registration.dao.UserToVoDAO.findByIds (int userId, int idVo)
Implemented in portal.registration.dao.UserToVoDAOImpl.
Referenced by portal.registration.services.UserToVoServiceImpl.findById(), and portal.registration.services.UserToVoServiceImpl.setDefault().
int portal.registration.dao.UserToVoDAO.getNumberOfUserToVo (int userId)
Implemented in portal.registration.dao.UserToVoDAOImpl.
Referenced by portal.registration.services.UserToVoServiceImpl.getNumberOfUserToVo().
Vo portal.registration.dao.UserToVoDAO.getVoByUserToVo (UserToVo userToVo)
Implemented in portal.registration.dao.UserToVoDAOImpl.
Referenced by portal.registration.services.UserToVoServiceImpl.findVoByUserId().
void portal.registration.dao.UserToVoDAO.save (UserToVo transientInstance)
Implemented in portal.registration.dao.UserToVoDAOImpl.
Referenced by portal.registration.services.UserToVoServiceImpl.save().
void portal.registration.dao.UserToVoDAO.update (UserToVo temp)
Implemented in portal.registration.dao.UserToVoDAOImpl.
Referenced by portal.registration.services.UserToVoServiceImpl.setDefault(), and portal.registration.services.UserToVoServiceImpl.update().
The documentation for this interface was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/dao/UserToVoDAO.java