portal.registration.dao.FqanDAO Interface Reference
Public Member Functions
void save (Fqan transientInstance)
void delete (Fqan persistentInstance)
Fqan findById (Integer id)
List< Fqan > getAllFqan ()
List< Fqan > findByIdVo (Integer id)
Detailed Description
Definition at line 7 of file FqanDAO.java.
Member Function Documentation
void portal.registration.dao.FqanDAO.delete (Fqan persistentInstance)
Implemented in portal.registration.dao.FqanDAOImpl.
Referenced by portal.registration.services.FqanServiceImpl.delete().
Fqan portal.registration.dao.FqanDAO.findById (Integer id)
Implemented in portal.registration.dao.FqanDAOImpl.
Referenced by portal.registration.services.FqanServiceImpl.findByFqan(), and portal.registration.services.FqanServiceImpl.findById().
List<Fqan> portal.registration.dao.FqanDAO.findByIdVo (Integer id)
Implemented in portal.registration.dao.FqanDAOImpl.
Referenced by portal.registration.services.FqanServiceImpl.findByIdVo().
List<Fqan> portal.registration.dao.FqanDAO.getAllFqan ()
Implemented in portal.registration.dao.FqanDAOImpl.
Referenced by portal.registration.services.FqanServiceImpl.getAllFqan().
void portal.registration.dao.FqanDAO.save (Fqan transientInstance)
Implemented in portal.registration.dao.FqanDAOImpl.
Referenced by portal.registration.services.FqanServiceImpl.save().
The documentation for this interface was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/dao/FqanDAO.java