portal.registration.dao.IdpDAO Interface Reference
Public Member Functions
void save (Idp transientInstance)
void delete (Idp persistentInstance)
Idp findById (Integer id)
List< Idp > getAllIdp ()
Detailed Description
Definition at line 7 of file IdpDAO.java.
Member Function Documentation
void portal.registration.dao.IdpDAO.delete (Idp persistentInstance)
Implemented in portal.registration.dao.IdpDAOImpl.
Referenced by portal.registration.services.IdpServiceImpl.delete().
Idp portal.registration.dao.IdpDAO.findById (Integer id)
Implemented in portal.registration.dao.IdpDAOImpl.
Referenced by portal.registration.services.IdpServiceImpl.findById(), portal.registration.services.IdpServiceImpl.findByIdp(), and portal.registration.services.UserInfoServiceImpl.save().
List<Idp> portal.registration.dao.IdpDAO.getAllIdp ()
Implemented in portal.registration.dao.IdpDAOImpl.
Referenced by portal.registration.services.IdpServiceImpl.getAllIdp().
void portal.registration.dao.IdpDAO.save (Idp transientInstance)
Implemented in portal.registration.dao.IdpDAOImpl.
Referenced by portal.registration.services.IdpServiceImpl.save().
The documentation for this interface was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/dao/IdpDAO.java