org.glite.security.voms.service.acl.VOMSACL Interface Reference
Public Member Functions
org.glite.security.voms.service.acl.ACLEntry[] getACL (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void setACL (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry[] in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void addACLEntry (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry in1, boolean in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void removeACLEntry (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry in1, boolean in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.service.acl.ACLEntry[] getDefaultACL (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void setDefaultACL (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry[] in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void addDefaultACLEntry (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void removeDefaultACLEntry (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Detailed Description
Definition at line 10 of file VOMSACL.java.
Member Function Documentation
void org.glite.security.voms.service.acl.VOMSACL.addACLEntry (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry in1, boolean in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.acl.VOMSACLSoapBindingImpl, org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton, and org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.addACLEntry().
void org.glite.security.voms.service.acl.VOMSACL.addDefaultACLEntry (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.acl.VOMSACLSoapBindingImpl, org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton, and org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.addDefaultACLEntry().
org.glite.security.voms.service.acl.ACLEntry [] org.glite.security.voms.service.acl.VOMSACL.getACL (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.acl.VOMSACLSoapBindingImpl, org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton, and org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.getACL().
org.glite.security.voms.service.acl.ACLEntry [] org.glite.security.voms.service.acl.VOMSACL.getDefaultACL (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.acl.VOMSACLSoapBindingImpl, org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton, and org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.getDefaultACL().
void org.glite.security.voms.service.acl.VOMSACL.removeACLEntry (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry in1, boolean in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.acl.VOMSACLSoapBindingImpl, org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton, and org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.removeACLEntry().
void org.glite.security.voms.service.acl.VOMSACL.removeDefaultACLEntry (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.acl.VOMSACLSoapBindingImpl, org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton, and org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.removeDefaultACLEntry().
void org.glite.security.voms.service.acl.VOMSACL.setACL (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry[] in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.acl.VOMSACLSoapBindingImpl, org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton, and org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.setACL().
void org.glite.security.voms.service.acl.VOMSACL.setDefaultACL (java.lang.String in0, org.glite.security.voms.service.acl.ACLEntry[] in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.acl.VOMSACLSoapBindingImpl, org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton, and org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.setDefaultACL().
The documentation for this interface was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/acl/VOMSACL.java