portal.registration.services.CertificateService Interface Reference
Public Member Functions
Integer save (Certificate transientInstance)
void delete (Certificate persistentInstance)
int save (Certificate certificate, int userId)
List< Certificate > findById (int userId)
void delete (int idCert)
boolean setDefault (int idCert)
Detailed Description
Definition at line 7 of file CertificateService.java.
Member Function Documentation
void portal.registration.services.CertificateService.delete (Certificate persistentInstance)
Implemented in portal.registration.services.CertificateServiceImpl.
Referenced by portal.registration.controller.UploadCertController.removeCert().
void portal.registration.services.CertificateService.delete (int idCert)
Implemented in portal.registration.services.CertificateServiceImpl.
List<Certificate> portal.registration.services.CertificateService.findById (int userId)
Implemented in portal.registration.services.CertificateServiceImpl.
Referenced by portal.registration.controller.AddUserToVOController.checkVO(), portal.registration.controller.EditUserInfoController.getListCert(), and portal.registration.controller.UploadCertController.uploadCert().
Integer portal.registration.services.CertificateService.save (Certificate transientInstance)
Implemented in portal.registration.services.CertificateServiceImpl.
Referenced by portal.registration.controller.UploadCertController.uploadCert().
int portal.registration.services.CertificateService.save (Certificate certificate, int userId)
Implemented in portal.registration.services.CertificateServiceImpl.
boolean portal.registration.services.CertificateService.setDefault (int idCert)
Implemented in portal.registration.services.CertificateServiceImpl.
Referenced by portal.registration.controller.UploadCertController.setDefaultCert().
The documentation for this interface was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/services/CertificateService.java