org.glite.security.voms.service.attributes.VOMSAttributes Interface Reference
Public Member Functions
void createAttributeClass (java.lang.String in0, java.lang.String in1, boolean in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void createAttributeClass (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void createAttributeClass (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.service.attributes.AttributeClass getAttributeClass (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void saveAttributeClass (org.glite.security.voms.service.attributes.AttributeClass in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteAttributeClass (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteAttributeClass (org.glite.security.voms.service.attributes.AttributeClass in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.service.attributes.AttributeClass[] listAttributeClasses () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.service.attributes.AttributeValue[] listUserAttributes (org.glite.security.voms.User in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void setUserAttribute (org.glite.security.voms.User in0, org.glite.security.voms.service.attributes.AttributeValue in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteUserAttribute (org.glite.security.voms.User in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteUserAttribute (org.glite.security.voms.User in0, org.glite.security.voms.service.attributes.AttributeValue in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void setGroupAttribute (java.lang.String in0, org.glite.security.voms.service.attributes.AttributeValue in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteGroupAttribute (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteGroupAttribute (java.lang.String in0, org.glite.security.voms.service.attributes.AttributeValue in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.service.attributes.AttributeValue[] listGroupAttributes (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void setRoleAttribute (java.lang.String in0, java.lang.String in1, org.glite.security.voms.service.attributes.AttributeValue in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteRoleAttribute (java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
void deleteRoleAttribute (java.lang.String in0, java.lang.String in1, org.glite.security.voms.service.attributes.AttributeValue in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
org.glite.security.voms.service.attributes.AttributeValue[] listRoleAttributes (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Detailed Description
Definition at line 10 of file VOMSAttributes.java.
Member Function Documentation
void org.glite.security.voms.service.attributes.VOMSAttributes.createAttributeClass (java.lang.String in0, java.lang.String in1, boolean in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton, and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.createAttributeClass().
void org.glite.security.voms.service.attributes.VOMSAttributes.createAttributeClass (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton, and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.
void org.glite.security.voms.service.attributes.VOMSAttributes.createAttributeClass (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton, and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.
void org.glite.security.voms.service.attributes.VOMSAttributes.deleteAttributeClass (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton, and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.deleteAttributeClass().
void org.glite.security.voms.service.attributes.VOMSAttributes.deleteAttributeClass (org.glite.security.voms.service.attributes.AttributeClass in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton, and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.
void org.glite.security.voms.service.attributes.VOMSAttributes.deleteGroupAttribute (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton, and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.deleteGroupAttribute().
void org.glite.security.voms.service.attributes.VOMSAttributes.deleteGroupAttribute (java.lang.String in0, org.glite.security.voms.service.attributes.AttributeValue in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton, and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.
void org.glite.security.voms.service.attributes.VOMSAttributes.deleteRoleAttribute (java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton, and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.deleteRoleAttribute().
void org.glite.security.voms.service.attributes.VOMSAttributes.deleteRoleAttribute (java.lang.String in0, java.lang.String in1, org.glite.security.voms.service.attributes.AttributeValue in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton, and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.
void org.glite.security.voms.service.attributes.VOMSAttributes.deleteUserAttribute (org.glite.security.voms.User in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton, and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.deleteUserAttribute().
void org.glite.security.voms.service.attributes.VOMSAttributes.deleteUserAttribute (org.glite.security.voms.User in0, org.glite.security.voms.service.attributes.AttributeValue in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton, and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.
org.glite.security.voms.service.attributes.AttributeClass org.glite.security.voms.service.attributes.VOMSAttributes.getAttributeClass (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton, and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.getAttributeClass().
org.glite.security.voms.service.attributes.AttributeClass [] org.glite.security.voms.service.attributes.VOMSAttributes.listAttributeClasses () throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton, and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.listAttributeClasses().
org.glite.security.voms.service.attributes.AttributeValue [] org.glite.security.voms.service.attributes.VOMSAttributes.listGroupAttributes (java.lang.String in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton, and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.listGroupAttributes().
org.glite.security.voms.service.attributes.AttributeValue [] org.glite.security.voms.service.attributes.VOMSAttributes.listRoleAttributes (java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton, and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.listRoleAttributes().
org.glite.security.voms.service.attributes.AttributeValue [] org.glite.security.voms.service.attributes.VOMSAttributes.listUserAttributes (org.glite.security.voms.User in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton, and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.listUserAttributes().
void org.glite.security.voms.service.attributes.VOMSAttributes.saveAttributeClass (org.glite.security.voms.service.attributes.AttributeClass in0) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton, and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.saveAttributeClass().
void org.glite.security.voms.service.attributes.VOMSAttributes.setGroupAttribute (java.lang.String in0, org.glite.security.voms.service.attributes.AttributeValue in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton, and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.setGroupAttribute().
void org.glite.security.voms.service.attributes.VOMSAttributes.setRoleAttribute (java.lang.String in0, java.lang.String in1, org.glite.security.voms.service.attributes.AttributeValue in2) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton, and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.setRoleAttribute().
void org.glite.security.voms.service.attributes.VOMSAttributes.setUserAttribute (org.glite.security.voms.User in0, org.glite.security.voms.service.attributes.AttributeValue in1) throws java.rmi.RemoteException, org.glite.security.voms.VOMSException
Implemented in org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton, and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.setUserAttribute().
The documentation for this interface was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/attributes/VOMSAttributes.java