portal.registration.services.IdpService Interface Reference
Public Member Functions
void save (Idp transientInstance)
void delete (Idp persistentInstance)
Idp findById (Integer id)
String findByIdp (Idp idp)
List< Idp > getAllIdp ()
Detailed Description
Definition at line 7 of file IdpService.java.
Member Function Documentation
void portal.registration.services.IdpService.delete (Idp persistentInstance)
Implemented in portal.registration.services.IdpServiceImpl.
Idp portal.registration.services.IdpService.findById (Integer id)
Implemented in portal.registration.services.IdpServiceImpl.
Referenced by portal.registration.controller.AddUserInfoController.addUserInfo().
String portal.registration.services.IdpService.findByIdp (Idp idp)
Implemented in portal.registration.services.IdpServiceImpl.
Referenced by portal.registration.controller.UserInfoController.getIdpsName().
List<Idp> portal.registration.services.IdpService.getAllIdp ()
Implemented in portal.registration.services.IdpServiceImpl.
Referenced by portal.registration.controller.UserInfoController.getIdps(), and portal.registration.controller.AddUserInfoController.getIdps().
void portal.registration.services.IdpService.save (Idp transientInstance)
Implemented in portal.registration.services.IdpServiceImpl.
The documentation for this interface was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/services/IdpService.java