portal.registration.services.VoService Interface Reference
Public Member Functions
List< Vo > getAllVo ()
Vo findById (Integer id)
String findByVo (Vo vo)
List< String > getAllDiscplines ()
Detailed Description
Definition at line 7 of file VoService.java.
Member Function Documentation
Vo portal.registration.services.VoService.findById (Integer id)
Implemented in portal.registration.services.VoServiceImpl.
Referenced by portal.registration.controller.AddUserToVOController.checkVO(), and portal.registration.controller.EditUserToVoController.getVO().
String portal.registration.services.VoService.findByVo (Vo vo)
Implemented in portal.registration.services.VoServiceImpl.
List<String> portal.registration.services.VoService.getAllDiscplines ()
Implemented in portal.registration.services.VoServiceImpl.
Referenced by portal.registration.controller.AddUserToVOController.getDisciplines().
List<Vo> portal.registration.services.VoService.getAllVo ()
Implemented in portal.registration.services.VoServiceImpl.
Referenced by portal.registration.controller.VOListController.getVos(), portal.registration.controller.AddUserToVoPresentsController.getVos(), and portal.registration.controller.AddUserToVOController.getVos().
The documentation for this interface was generated from the following file:
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/portal/registration/services/VoService.java