.TH "org::glite::security::voms::service::acl::VOMSACLService" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org::glite::security::voms::service::acl::VOMSACLService \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBorg.glite.security.voms.service.acl.VOMSACLServiceLocator\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "java.lang.String \fBgetVOMSACLAddress\fP ()"
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.acl.VOMSACL\fP \fBgetVOMSACL\fP ()  throws javax.xml.rpc.ServiceException"
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.acl.VOMSACL\fP \fBgetVOMSACL\fP (java.net.URL portAddress)  throws javax.xml.rpc.ServiceException"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file VOMSACLService.java.
.SH "Member Function Documentation"
.PP 
.SS "\fBorg.glite.security.voms.service.acl.VOMSACL\fP org.glite.security.voms.service.acl.VOMSACLService.getVOMSACL ()  throws javax.xml.rpc.ServiceException"
.PP
Implemented in \fBorg.glite.security.voms.service.acl.VOMSACLServiceLocator\fP.
.SS "\fBorg.glite.security.voms.service.acl.VOMSACL\fP org.glite.security.voms.service.acl.VOMSACLService.getVOMSACL (java.net.URLportAddress)  throws javax.xml.rpc.ServiceException"
.PP
Implemented in \fBorg.glite.security.voms.service.acl.VOMSACLServiceLocator\fP.
.SS "java.lang.String org.glite.security.voms.service.acl.VOMSACLService.getVOMSACLAddress ()"
.PP
Implemented in \fBorg.glite.security.voms.service.acl.VOMSACLServiceLocator\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
