.TH "org::glite::security::voms::service::acl::VOMSACLSoapBindingStub" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org::glite::security::voms::service::acl::VOMSACLSoapBindingStub \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg.glite.security.voms.service.acl.VOMSACL\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVOMSACLSoapBindingStub\fP ()  throws org.apache.axis.AxisFault "
.br
.ti -1c
.RI "\fBVOMSACLSoapBindingStub\fP (java.net.URL endpointURL, javax.xml.rpc.Service service)  throws org.apache.axis.AxisFault "
.br
.ti -1c
.RI "\fBVOMSACLSoapBindingStub\fP (javax.xml.rpc.Service service)  throws org.apache.axis.AxisFault "
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.acl.ACLEntry\fP[] \fBgetACL\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBsetACL\fP (java.lang.String in0, \fBorg.glite.security.voms.service.acl.ACLEntry\fP[] in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBaddACLEntry\fP (java.lang.String in0, \fBorg.glite.security.voms.service.acl.ACLEntry\fP in1, boolean in2)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBremoveACLEntry\fP (java.lang.String in0, \fBorg.glite.security.voms.service.acl.ACLEntry\fP in1, boolean in2)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.acl.ACLEntry\fP[] \fBgetDefaultACL\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBsetDefaultACL\fP (java.lang.String in0, \fBorg.glite.security.voms.service.acl.ACLEntry\fP[] in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBaddDefaultACLEntry\fP (java.lang.String in0, \fBorg.glite.security.voms.service.acl.ACLEntry\fP in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBremoveDefaultACLEntry\fP (java.lang.String in0, \fBorg.glite.security.voms.service.acl.ACLEntry\fP in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "org.apache.axis.client.Call \fBcreateCall\fP ()  throws java.rmi.RemoteException "
.br
.in -1c
.SS "Static Package Functions"

.in +1c
.ti -1c
.RI "\fB[static initializer]\fP"
.br
.in -1c
.SS "Static Package Attributes"

.in +1c
.ti -1c
.RI "static org.apache.axis.description.OperationDesc[] \fB_operations\fP"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static void \fB_initOperationDesc1\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "java.util.Vector \fBcachedSerClasses\fP = new java.util.Vector()"
.br
.ti -1c
.RI "java.util.Vector \fBcachedSerQNames\fP = new java.util.Vector()"
.br
.ti -1c
.RI "java.util.Vector \fBcachedSerFactories\fP = new java.util.Vector()"
.br
.ti -1c
.RI "java.util.Vector \fBcachedDeserFactories\fP = new java.util.Vector()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file VOMSACLSoapBindingStub.java.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.VOMSACLSoapBindingStub ()  throws org.apache.axis.AxisFault "
.PP
Definition at line 168 of file VOMSACLSoapBindingStub.java.
.PP
.nf
                                                                     {
         this(null);
    }
.fi
.SS "org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.VOMSACLSoapBindingStub (java.net.URLendpointURL, javax.xml.rpc.Serviceservice)  throws org.apache.axis.AxisFault "
.PP
Definition at line 172 of file VOMSACLSoapBindingStub.java.
.PP
.nf
                                                                                                                            {
         this(service);
         super.cachedEndpoint = endpointURL;
    }
.fi
.SS "org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.VOMSACLSoapBindingStub (javax.xml.rpc.Serviceservice)  throws org.apache.axis.AxisFault "
.PP
Definition at line 177 of file VOMSACLSoapBindingStub.java.
.PP
References org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.cachedDeserFactories, org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.cachedSerClasses, org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.cachedSerFactories, and org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.cachedSerQNames.
.PP
.nf
                                                                                                  {
        if (service == null) {
            super.service = new org.apache.axis.client.Service();
        } else {
            super.service = service;
        }
        ((org.apache.axis.client.Service)super.service).setTypeMappingVersion('1.2');
            java.lang.Class cls;
            javax.xml.namespace.QName qName;
            javax.xml.namespace.QName qName2;
            java.lang.Class beansf = org.apache.axis.encoding.ser.BeanSerializerFactory.class;
            java.lang.Class beandf = org.apache.axis.encoding.ser.BeanDeserializerFactory.class;
            java.lang.Class enumsf = org.apache.axis.encoding.ser.EnumSerializerFactory.class;
            java.lang.Class enumdf = org.apache.axis.encoding.ser.EnumDeserializerFactory.class;
            java.lang.Class arraysf = org.apache.axis.encoding.ser.ArraySerializerFactory.class;
            java.lang.Class arraydf = org.apache.axis.encoding.ser.ArrayDeserializerFactory.class;
            java.lang.Class simplesf = org.apache.axis.encoding.ser.SimpleSerializerFactory.class;
            java.lang.Class simpledf = org.apache.axis.encoding.ser.SimpleDeserializerFactory.class;
            java.lang.Class simplelistsf = org.apache.axis.encoding.ser.SimpleListSerializerFactory.class;
            java.lang.Class simplelistdf = org.apache.axis.encoding.ser.SimpleListDeserializerFactory.class;
            qName = new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'ACLEntry');
            cachedSerQNames.add(qName);
            cls = org.glite.security.voms.service.acl.ACLEntry.class;
            cachedSerClasses.add(cls);
            cachedSerFactories.add(beansf);
            cachedDeserFactories.add(beandf);

            qName = new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'ArrayOfACLEntry');
            cachedSerQNames.add(qName);
            cls = org.glite.security.voms.service.acl.ACLEntry[].class;
            cachedSerClasses.add(cls);
            qName = new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'ACLEntry');
            qName2 = null;
            cachedSerFactories.add(new org.apache.axis.encoding.ser.ArraySerializerFactory(qName, qName2));
            cachedDeserFactories.add(new org.apache.axis.encoding.ser.ArrayDeserializerFactory());

            qName = new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException');
            cachedSerQNames.add(qName);
            cls = org.glite.security.voms.VOMSException.class;
            cachedSerClasses.add(cls);
            cachedSerFactories.add(beansf);
            cachedDeserFactories.add(beandf);

    }
.fi
.SH "Member Function Documentation"
.PP 
.SS "org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.[static initializer] ()\fC [static, package]\fP"
.SS "static void org.glite.security.voms.service.acl.VOMSACLSoapBindingStub._initOperationDesc1 ()\fC [static, private]\fP"
.PP
Definition at line 23 of file VOMSACLSoapBindingStub.java.
.PP
References org.glite.security.voms.service.acl.VOMSACLSoapBindingStub._operations.
.PP
.nf
                                             {
        org.apache.axis.description.OperationDesc oper;
        org.apache.axis.description.ParameterDesc param;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('getACL');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'ArrayOfACLEntry'));
        oper.setReturnClass(org.glite.security.voms.service.acl.ACLEntry[].class);
        oper.setReturnQName(new javax.xml.namespace.QName('', 'getACLReturn'));
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[0] = oper;

        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('setACL');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in1'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'ArrayOfACLEntry'), org.glite.security.voms.service.acl.ACLEntry[].class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[1] = oper;

        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('addACLEntry');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in1'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'ACLEntry'), org.glite.security.voms.service.acl.ACLEntry.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in2'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://www.w3.org/2001/XMLSchema', 'boolean'), boolean.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[2] = oper;

        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('removeACLEntry');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in1'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'ACLEntry'), org.glite.security.voms.service.acl.ACLEntry.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in2'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://www.w3.org/2001/XMLSchema', 'boolean'), boolean.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[3] = oper;

        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('getDefaultACL');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'ArrayOfACLEntry'));
        oper.setReturnClass(org.glite.security.voms.service.acl.ACLEntry[].class);
        oper.setReturnQName(new javax.xml.namespace.QName('', 'getDefaultACLReturn'));
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[4] = oper;

        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('setDefaultACL');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in1'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'ArrayOfACLEntry'), org.glite.security.voms.service.acl.ACLEntry[].class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[5] = oper;

        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('addDefaultACLEntry');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in1'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'ACLEntry'), org.glite.security.voms.service.acl.ACLEntry.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[6] = oper;

        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('removeDefaultACLEntry');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in1'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'ACLEntry'), org.glite.security.voms.service.acl.ACLEntry.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[7] = oper;

    }
.fi
.SS "void org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.addACLEntry (java.lang.Stringin0, \fBorg.glite.security.voms.service.acl.ACLEntry\fPin1, booleanin2)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.acl.VOMSACL\fP.
.PP
Definition at line 358 of file VOMSACLSoapBindingStub.java.
.PP
.nf
                                                                                                                                                                                        {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[2]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'addACLEntry'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0, in1, new java.lang.Boolean(in2)});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        extractAttachments(_call);
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SS "void org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.addDefaultACLEntry (java.lang.Stringin0, \fBorg.glite.security.voms.service.acl.ACLEntry\fPin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.acl.VOMSACL\fP.
.PP
Definition at line 493 of file VOMSACLSoapBindingStub.java.
.PP
.nf
                                                                                                                                                                                  {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[6]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'addDefaultACLEntry'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0, in1});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        extractAttachments(_call);
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SS "org.apache.axis.client.Call org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.createCall ()  throws java.rmi.RemoteException \fC [protected]\fP"
.PP
Definition at line 222 of file VOMSACLSoapBindingStub.java.
.PP
References org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.cachedDeserFactories, org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.cachedSerClasses, org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.cachedSerFactories, and org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.cachedSerQNames.
.PP
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.getACL().
.PP
.nf
                                                                                       {
        try {
            org.apache.axis.client.Call _call = super._createCall();
            if (super.maintainSessionSet) {
                _call.setMaintainSession(super.maintainSession);
            }
            if (super.cachedUsername != null) {
                _call.setUsername(super.cachedUsername);
            }
            if (super.cachedPassword != null) {
                _call.setPassword(super.cachedPassword);
            }
            if (super.cachedEndpoint != null) {
                _call.setTargetEndpointAddress(super.cachedEndpoint);
            }
            if (super.cachedTimeout != null) {
                _call.setTimeout(super.cachedTimeout);
            }
            if (super.cachedPortName != null) {
                _call.setPortName(super.cachedPortName);
            }
            java.util.Enumeration keys = super.cachedProperties.keys();
            while (keys.hasMoreElements()) {
                java.lang.String key = (java.lang.String) keys.nextElement();
                _call.setProperty(key, super.cachedProperties.get(key));
            }
            // All the type mapping information is registered
            // when the first call is made.
            // The type mapping information is actually registered in
            // the TypeMappingRegistry of the service, which
            // is the reason why registration is only needed for the first call.
            synchronized (this) {
                if (firstCall()) {
                    // must set encoding style before registering serializers
                    _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
                    _call.setEncodingStyle(org.apache.axis.Constants.URI_SOAP11_ENC);
                    for (int i = 0; i < cachedSerFactories.size(); ++i) {
                        java.lang.Class cls = (java.lang.Class) cachedSerClasses.get(i);
                        javax.xml.namespace.QName qName =
                                (javax.xml.namespace.QName) cachedSerQNames.get(i);
                        java.lang.Object x = cachedSerFactories.get(i);
                        if (x instanceof Class) {
                            java.lang.Class sf = (java.lang.Class)
                                 cachedSerFactories.get(i);
                            java.lang.Class df = (java.lang.Class)
                                 cachedDeserFactories.get(i);
                            _call.registerTypeMapping(cls, qName, sf, df, false);
                        }
                        else if (x instanceof javax.xml.rpc.encoding.SerializerFactory) {
                            org.apache.axis.encoding.SerializerFactory sf = (org.apache.axis.encoding.SerializerFactory)
                                 cachedSerFactories.get(i);
                            org.apache.axis.encoding.DeserializerFactory df = (org.apache.axis.encoding.DeserializerFactory)
                                 cachedDeserFactories.get(i);
                            _call.registerTypeMapping(cls, qName, sf, df, false);
                        }
                    }
                }
            }
            return _call;
        }
        catch (java.lang.Throwable _t) {
            throw new org.apache.axis.AxisFault('Failure trying to get the Call object', _t);
        }
    }
.fi
.SS "\fBorg.glite.security.voms.service.acl.ACLEntry\fP [] org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.getACL (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.acl.VOMSACL\fP.
.PP
Definition at line 287 of file VOMSACLSoapBindingStub.java.
.PP
References org.glite.security.voms.service.acl.VOMSACLSoapBindingStub._operations, and org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.createCall().
.PP
.nf
                                                                                                                                                              {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[0]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'getACL'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        else {
            extractAttachments(_call);
            try {
                return (org.glite.security.voms.service.acl.ACLEntry[]) _resp;
            } catch (java.lang.Exception _exception) {
                return (org.glite.security.voms.service.acl.ACLEntry[]) org.apache.axis.utils.JavaUtils.convert(_resp, org.glite.security.voms.service.acl.ACLEntry[].class);
            }
        }
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SS "\fBorg.glite.security.voms.service.acl.ACLEntry\fP [] org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.getDefaultACL (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.acl.VOMSACL\fP.
.PP
Definition at line 422 of file VOMSACLSoapBindingStub.java.
.PP
.nf
                                                                                                                                                                     {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[4]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'getDefaultACL'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        else {
            extractAttachments(_call);
            try {
                return (org.glite.security.voms.service.acl.ACLEntry[]) _resp;
            } catch (java.lang.Exception _exception) {
                return (org.glite.security.voms.service.acl.ACLEntry[]) org.apache.axis.utils.JavaUtils.convert(_resp, org.glite.security.voms.service.acl.ACLEntry[].class);
            }
        }
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SS "void org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.removeACLEntry (java.lang.Stringin0, \fBorg.glite.security.voms.service.acl.ACLEntry\fPin1, booleanin2)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.acl.VOMSACL\fP.
.PP
Definition at line 390 of file VOMSACLSoapBindingStub.java.
.PP
.nf
                                                                                                                                                                                           {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[3]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'removeACLEntry'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0, in1, new java.lang.Boolean(in2)});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        extractAttachments(_call);
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SS "void org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.removeDefaultACLEntry (java.lang.Stringin0, \fBorg.glite.security.voms.service.acl.ACLEntry\fPin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.acl.VOMSACL\fP.
.PP
Definition at line 525 of file VOMSACLSoapBindingStub.java.
.PP
.nf
                                                                                                                                                                                     {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[7]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'removeDefaultACLEntry'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0, in1});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        extractAttachments(_call);
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SS "void org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.setACL (java.lang.Stringin0, \fBorg.glite.security.voms.service.acl.ACLEntry\fP[]in1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.acl.VOMSACL\fP.
.PP
Definition at line 326 of file VOMSACLSoapBindingStub.java.
.PP
.nf
                                                                                                                                                                        {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[1]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'setACL'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0, in1});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        extractAttachments(_call);
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SS "void org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.setDefaultACL (java.lang.Stringin0, \fBorg.glite.security.voms.service.acl.ACLEntry\fP[]in1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.acl.VOMSACL\fP.
.PP
Definition at line 461 of file VOMSACLSoapBindingStub.java.
.PP
.nf
                                                                                                                                                                               {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[5]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.acl', 'setDefaultACL'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0, in1});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        extractAttachments(_call);
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SH "Member Data Documentation"
.PP 
.SS "org.apache.axis.description.OperationDesc [] \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingStub._operations\fP\fC [static, package]\fP"
.PP
Definition at line 16 of file VOMSACLSoapBindingStub.java.
.PP
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingStub._initOperationDesc1(), and org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.getACL().
.SS "java.util.Vector \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingStub.cachedDeserFactories\fP = new java.util.Vector()\fC [private]\fP"
.PP
Definition at line 14 of file VOMSACLSoapBindingStub.java.
.PP
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.createCall(), and org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.VOMSACLSoapBindingStub().
.SS "java.util.Vector \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingStub.cachedSerClasses\fP = new java.util.Vector()\fC [private]\fP"
.PP
Definition at line 11 of file VOMSACLSoapBindingStub.java.
.PP
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.createCall(), and org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.VOMSACLSoapBindingStub().
.SS "java.util.Vector \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingStub.cachedSerFactories\fP = new java.util.Vector()\fC [private]\fP"
.PP
Definition at line 13 of file VOMSACLSoapBindingStub.java.
.PP
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.createCall(), and org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.VOMSACLSoapBindingStub().
.SS "java.util.Vector \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingStub.cachedSerQNames\fP = new java.util.Vector()\fC [private]\fP"
.PP
Definition at line 12 of file VOMSACLSoapBindingStub.java.
.PP
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.createCall(), and org.glite.security.voms.service.acl.VOMSACLSoapBindingStub.VOMSACLSoapBindingStub().

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
