.TH "org::glite::security::voms::service::attributes::VOMSAttributesSoapBindingStub" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org::glite::security::voms::service::attributes::VOMSAttributesSoapBindingStub \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVOMSAttributesSoapBindingStub\fP ()  throws org.apache.axis.AxisFault "
.br
.ti -1c
.RI "\fBVOMSAttributesSoapBindingStub\fP (java.net.URL endpointURL, javax.xml.rpc.Service service)  throws org.apache.axis.AxisFault "
.br
.ti -1c
.RI "\fBVOMSAttributesSoapBindingStub\fP (javax.xml.rpc.Service service)  throws org.apache.axis.AxisFault "
.br
.ti -1c
.RI "void \fBcreateAttributeClass\fP (java.lang.String in0, java.lang.String in1, boolean in2)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBcreateAttributeClass\fP (java.lang.String in0, java.lang.String in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBcreateAttributeClass\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.attributes.AttributeClass\fP \fBgetAttributeClass\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBsaveAttributeClass\fP (\fBorg.glite.security.voms.service.attributes.AttributeClass\fP in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBdeleteAttributeClass\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBdeleteAttributeClass\fP (\fBorg.glite.security.voms.service.attributes.AttributeClass\fP in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.attributes.AttributeClass\fP[] \fBlistAttributeClasses\fP ()  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.attributes.AttributeValue\fP[] \fBlistUserAttributes\fP (\fBorg.glite.security.voms.User\fP in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBsetUserAttribute\fP (\fBorg.glite.security.voms.User\fP in0, \fBorg.glite.security.voms.service.attributes.AttributeValue\fP in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBdeleteUserAttribute\fP (\fBorg.glite.security.voms.User\fP in0, java.lang.String in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBdeleteUserAttribute\fP (\fBorg.glite.security.voms.User\fP in0, \fBorg.glite.security.voms.service.attributes.AttributeValue\fP in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBsetGroupAttribute\fP (java.lang.String in0, \fBorg.glite.security.voms.service.attributes.AttributeValue\fP in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBdeleteGroupAttribute\fP (java.lang.String in0, java.lang.String in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBdeleteGroupAttribute\fP (java.lang.String in0, \fBorg.glite.security.voms.service.attributes.AttributeValue\fP in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.attributes.AttributeValue\fP[] \fBlistGroupAttributes\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBsetRoleAttribute\fP (java.lang.String in0, java.lang.String in1, \fBorg.glite.security.voms.service.attributes.AttributeValue\fP in2)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBdeleteRoleAttribute\fP (java.lang.String in0, java.lang.String in1, java.lang.String in2)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBdeleteRoleAttribute\fP (java.lang.String in0, java.lang.String in1, \fBorg.glite.security.voms.service.attributes.AttributeValue\fP in2)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.attributes.AttributeValue\fP[] \fBlistRoleAttributes\fP (java.lang.String in0, java.lang.String in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "org.apache.axis.client.Call \fBcreateCall\fP ()  throws java.rmi.RemoteException "
.br
.in -1c
.SS "Static Package Functions"

.in +1c
.ti -1c
.RI "\fB[static initializer]\fP"
.br
.in -1c
.SS "Static Package Attributes"

.in +1c
.ti -1c
.RI "static org.apache.axis.description.OperationDesc[] \fB_operations\fP"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static void \fB_initOperationDesc1\fP ()"
.br
.ti -1c
.RI "static void \fB_initOperationDesc2\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "java.util.Vector \fBcachedSerClasses\fP = new java.util.Vector()"
.br
.ti -1c
.RI "java.util.Vector \fBcachedSerQNames\fP = new java.util.Vector()"
.br
.ti -1c
.RI "java.util.Vector \fBcachedSerFactories\fP = new java.util.Vector()"
.br
.ti -1c
.RI "java.util.Vector \fBcachedDeserFactories\fP = new java.util.Vector()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file VOMSAttributesSoapBindingStub.java.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.VOMSAttributesSoapBindingStub ()  throws org.apache.axis.AxisFault "
.PP
Definition at line 374 of file VOMSAttributesSoapBindingStub.java.
.PP
.nf
                                                                            {
         this(null);
    }
.fi
.SS "org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.VOMSAttributesSoapBindingStub (java.net.URLendpointURL, javax.xml.rpc.Serviceservice)  throws org.apache.axis.AxisFault "
.PP
Definition at line 378 of file VOMSAttributesSoapBindingStub.java.
.PP
.nf
                                                                                                                                   {
         this(service);
         super.cachedEndpoint = endpointURL;
    }
.fi
.SS "org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.VOMSAttributesSoapBindingStub (javax.xml.rpc.Serviceservice)  throws org.apache.axis.AxisFault "
.PP
Definition at line 383 of file VOMSAttributesSoapBindingStub.java.
.PP
References org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.cachedDeserFactories, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.cachedSerClasses, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.cachedSerFactories, and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.cachedSerQNames.
.PP
.nf
                                                                                                         {
        if (service == null) {
            super.service = new org.apache.axis.client.Service();
        } else {
            super.service = service;
        }
        ((org.apache.axis.client.Service)super.service).setTypeMappingVersion('1.2');
            java.lang.Class cls;
            javax.xml.namespace.QName qName;
            javax.xml.namespace.QName qName2;
            java.lang.Class beansf = org.apache.axis.encoding.ser.BeanSerializerFactory.class;
            java.lang.Class beandf = org.apache.axis.encoding.ser.BeanDeserializerFactory.class;
            java.lang.Class enumsf = org.apache.axis.encoding.ser.EnumSerializerFactory.class;
            java.lang.Class enumdf = org.apache.axis.encoding.ser.EnumDeserializerFactory.class;
            java.lang.Class arraysf = org.apache.axis.encoding.ser.ArraySerializerFactory.class;
            java.lang.Class arraydf = org.apache.axis.encoding.ser.ArrayDeserializerFactory.class;
            java.lang.Class simplesf = org.apache.axis.encoding.ser.SimpleSerializerFactory.class;
            java.lang.Class simpledf = org.apache.axis.encoding.ser.SimpleDeserializerFactory.class;
            java.lang.Class simplelistsf = org.apache.axis.encoding.ser.SimpleListSerializerFactory.class;
            java.lang.Class simplelistdf = org.apache.axis.encoding.ser.SimpleListDeserializerFactory.class;
            qName = new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'ArrayOfAttributeClass');
            cachedSerQNames.add(qName);
            cls = org.glite.security.voms.service.attributes.AttributeClass[].class;
            cachedSerClasses.add(cls);
            qName = new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'AttributeClass');
            qName2 = null;
            cachedSerFactories.add(new org.apache.axis.encoding.ser.ArraySerializerFactory(qName, qName2));
            cachedDeserFactories.add(new org.apache.axis.encoding.ser.ArrayDeserializerFactory());

            qName = new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'ArrayOfAttributeValue');
            cachedSerQNames.add(qName);
            cls = org.glite.security.voms.service.attributes.AttributeValue[].class;
            cachedSerClasses.add(cls);
            qName = new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'AttributeValue');
            qName2 = null;
            cachedSerFactories.add(new org.apache.axis.encoding.ser.ArraySerializerFactory(qName, qName2));
            cachedDeserFactories.add(new org.apache.axis.encoding.ser.ArrayDeserializerFactory());

            qName = new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'AttributeClass');
            cachedSerQNames.add(qName);
            cls = org.glite.security.voms.service.attributes.AttributeClass.class;
            cachedSerClasses.add(cls);
            cachedSerFactories.add(beansf);
            cachedDeserFactories.add(beandf);

            qName = new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'AttributeValue');
            cachedSerQNames.add(qName);
            cls = org.glite.security.voms.service.attributes.AttributeValue.class;
            cachedSerClasses.add(cls);
            cachedSerFactories.add(beansf);
            cachedDeserFactories.add(beandf);

            qName = new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'User');
            cachedSerQNames.add(qName);
            cls = org.glite.security.voms.User.class;
            cachedSerClasses.add(cls);
            cachedSerFactories.add(beansf);
            cachedDeserFactories.add(beandf);

            qName = new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException');
            cachedSerQNames.add(qName);
            cls = org.glite.security.voms.VOMSException.class;
            cachedSerClasses.add(cls);
            cachedSerFactories.add(beansf);
            cachedDeserFactories.add(beandf);

    }
.fi
.SH "Member Function Documentation"
.PP 
.SS "org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.[static initializer] ()\fC [static, package]\fP"
.SS "static void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub._initOperationDesc1 ()\fC [static, private]\fP"
.PP
Definition at line 24 of file VOMSAttributesSoapBindingStub.java.
.PP
References org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub._operations.
.PP
.nf
                                             {
        org.apache.axis.description.OperationDesc oper;
        org.apache.axis.description.ParameterDesc param;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('createAttributeClass');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in1'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in2'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://www.w3.org/2001/XMLSchema', 'boolean'), boolean.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[0] = oper;

        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('createAttributeClass');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in1'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[1] = oper;

        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('createAttributeClass');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[2] = oper;

        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('getAttributeClass');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'AttributeClass'));
        oper.setReturnClass(org.glite.security.voms.service.attributes.AttributeClass.class);
        oper.setReturnQName(new javax.xml.namespace.QName('', 'getAttributeClassReturn'));
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[3] = oper;

        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('saveAttributeClass');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'AttributeClass'), org.glite.security.voms.service.attributes.AttributeClass.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[4] = oper;

        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('deleteAttributeClass');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[5] = oper;

        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('deleteAttributeClass');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'AttributeClass'), org.glite.security.voms.service.attributes.AttributeClass.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[6] = oper;

        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('listAttributeClasses');
        oper.setReturnType(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'ArrayOfAttributeClass'));
        oper.setReturnClass(org.glite.security.voms.service.attributes.AttributeClass[].class);
        oper.setReturnQName(new javax.xml.namespace.QName('', 'listAttributeClassesReturn'));
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[7] = oper;

        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('listUserAttributes');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'User'), org.glite.security.voms.User.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'ArrayOfAttributeValue'));
        oper.setReturnClass(org.glite.security.voms.service.attributes.AttributeValue[].class);
        oper.setReturnQName(new javax.xml.namespace.QName('', 'listUserAttributesReturn'));
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[8] = oper;

        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('setUserAttribute');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'User'), org.glite.security.voms.User.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in1'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'AttributeValue'), org.glite.security.voms.service.attributes.AttributeValue.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[9] = oper;

    }
.fi
.SS "static void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub._initOperationDesc2 ()\fC [static, private]\fP"
.PP
Definition at line 191 of file VOMSAttributesSoapBindingStub.java.
.PP
References org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub._operations.
.PP
.nf
                                             {
        org.apache.axis.description.OperationDesc oper;
        org.apache.axis.description.ParameterDesc param;
        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('deleteUserAttribute');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'User'), org.glite.security.voms.User.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in1'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[10] = oper;

        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('deleteUserAttribute');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'User'), org.glite.security.voms.User.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in1'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'AttributeValue'), org.glite.security.voms.service.attributes.AttributeValue.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[11] = oper;

        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('setGroupAttribute');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in1'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'AttributeValue'), org.glite.security.voms.service.attributes.AttributeValue.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[12] = oper;

        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('deleteGroupAttribute');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in1'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[13] = oper;

        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('deleteGroupAttribute');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in1'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'AttributeValue'), org.glite.security.voms.service.attributes.AttributeValue.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[14] = oper;

        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('listGroupAttributes');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'ArrayOfAttributeValue'));
        oper.setReturnClass(org.glite.security.voms.service.attributes.AttributeValue[].class);
        oper.setReturnQName(new javax.xml.namespace.QName('', 'listGroupAttributesReturn'));
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[15] = oper;

        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('setRoleAttribute');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in1'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in2'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'AttributeValue'), org.glite.security.voms.service.attributes.AttributeValue.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[16] = oper;

        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('deleteRoleAttribute');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in1'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in2'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[17] = oper;

        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('deleteRoleAttribute');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in1'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in2'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'AttributeValue'), org.glite.security.voms.service.attributes.AttributeValue.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(org.apache.axis.encoding.XMLType.AXIS_VOID);
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[18] = oper;

        oper = new org.apache.axis.description.OperationDesc();
        oper.setName('listRoleAttributes');
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in0'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        param = new org.apache.axis.description.ParameterDesc(new javax.xml.namespace.QName('', 'in1'), org.apache.axis.description.ParameterDesc.IN, new javax.xml.namespace.QName('http://schemas.xmlsoap.org/soap/encoding/', 'string'), java.lang.String.class, false, false);
        oper.addParameter(param);
        oper.setReturnType(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'ArrayOfAttributeValue'));
        oper.setReturnClass(org.glite.security.voms.service.attributes.AttributeValue[].class);
        oper.setReturnQName(new javax.xml.namespace.QName('', 'listRoleAttributesReturn'));
        oper.setStyle(org.apache.axis.constants.Style.RPC);
        oper.setUse(org.apache.axis.constants.Use.ENCODED);
        oper.addFault(new org.apache.axis.description.FaultDesc(
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'fault'),
                      'org.glite.security.voms.VOMSException',
                      new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms', 'VOMSException'), 
                      true
                     ));
        _operations[19] = oper;

    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.createAttributeClass (java.lang.Stringin0, java.lang.Stringin1, booleanin2)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 516 of file VOMSAttributesSoapBindingStub.java.
.PP
References org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub._operations, and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.createCall().
.PP
.nf
                                                                                                                                                                     {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[0]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'createAttributeClass'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0, in1, new java.lang.Boolean(in2)});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        extractAttachments(_call);
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.createAttributeClass (java.lang.Stringin0, java.lang.Stringin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 548 of file VOMSAttributesSoapBindingStub.java.
.PP
.nf
                                                                                                                                                        {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[1]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'createAttributeClass'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0, in1});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        extractAttachments(_call);
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.createAttributeClass (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 580 of file VOMSAttributesSoapBindingStub.java.
.PP
.nf
                                                                                                                                  {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[2]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'createAttributeClass'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        extractAttachments(_call);
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SS "org.apache.axis.client.Call org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.createCall ()  throws java.rmi.RemoteException \fC [protected]\fP"
.PP
Definition at line 451 of file VOMSAttributesSoapBindingStub.java.
.PP
References org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.cachedDeserFactories, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.cachedSerClasses, org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.cachedSerFactories, and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.cachedSerQNames.
.PP
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.createAttributeClass().
.PP
.nf
                                                                                       {
        try {
            org.apache.axis.client.Call _call = super._createCall();
            if (super.maintainSessionSet) {
                _call.setMaintainSession(super.maintainSession);
            }
            if (super.cachedUsername != null) {
                _call.setUsername(super.cachedUsername);
            }
            if (super.cachedPassword != null) {
                _call.setPassword(super.cachedPassword);
            }
            if (super.cachedEndpoint != null) {
                _call.setTargetEndpointAddress(super.cachedEndpoint);
            }
            if (super.cachedTimeout != null) {
                _call.setTimeout(super.cachedTimeout);
            }
            if (super.cachedPortName != null) {
                _call.setPortName(super.cachedPortName);
            }
            java.util.Enumeration keys = super.cachedProperties.keys();
            while (keys.hasMoreElements()) {
                java.lang.String key = (java.lang.String) keys.nextElement();
                _call.setProperty(key, super.cachedProperties.get(key));
            }
            // All the type mapping information is registered
            // when the first call is made.
            // The type mapping information is actually registered in
            // the TypeMappingRegistry of the service, which
            // is the reason why registration is only needed for the first call.
            synchronized (this) {
                if (firstCall()) {
                    // must set encoding style before registering serializers
                    _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
                    _call.setEncodingStyle(org.apache.axis.Constants.URI_SOAP11_ENC);
                    for (int i = 0; i < cachedSerFactories.size(); ++i) {
                        java.lang.Class cls = (java.lang.Class) cachedSerClasses.get(i);
                        javax.xml.namespace.QName qName =
                                (javax.xml.namespace.QName) cachedSerQNames.get(i);
                        java.lang.Object x = cachedSerFactories.get(i);
                        if (x instanceof Class) {
                            java.lang.Class sf = (java.lang.Class)
                                 cachedSerFactories.get(i);
                            java.lang.Class df = (java.lang.Class)
                                 cachedDeserFactories.get(i);
                            _call.registerTypeMapping(cls, qName, sf, df, false);
                        }
                        else if (x instanceof javax.xml.rpc.encoding.SerializerFactory) {
                            org.apache.axis.encoding.SerializerFactory sf = (org.apache.axis.encoding.SerializerFactory)
                                 cachedSerFactories.get(i);
                            org.apache.axis.encoding.DeserializerFactory df = (org.apache.axis.encoding.DeserializerFactory)
                                 cachedDeserFactories.get(i);
                            _call.registerTypeMapping(cls, qName, sf, df, false);
                        }
                    }
                }
            }
            return _call;
        }
        catch (java.lang.Throwable _t) {
            throw new org.apache.axis.AxisFault('Failure trying to get the Call object', _t);
        }
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.deleteAttributeClass (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 683 of file VOMSAttributesSoapBindingStub.java.
.PP
.nf
                                                                                                                                  {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[5]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'deleteAttributeClass'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        extractAttachments(_call);
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.deleteAttributeClass (\fBorg.glite.security.voms.service.attributes.AttributeClass\fPin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 715 of file VOMSAttributesSoapBindingStub.java.
.PP
.nf
                                                                                                                                                                           {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[6]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'deleteAttributeClass'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        extractAttachments(_call);
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.deleteGroupAttribute (java.lang.Stringin0, java.lang.Stringin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 953 of file VOMSAttributesSoapBindingStub.java.
.PP
.nf
                                                                                                                                                        {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[13]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'deleteGroupAttribute'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0, in1});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        extractAttachments(_call);
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.deleteGroupAttribute (java.lang.Stringin0, \fBorg.glite.security.voms.service.attributes.AttributeValue\fPin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 985 of file VOMSAttributesSoapBindingStub.java.
.PP
.nf
                                                                                                                                                                                                 {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[14]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'deleteGroupAttribute'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0, in1});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        extractAttachments(_call);
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.deleteRoleAttribute (java.lang.Stringin0, java.lang.Stringin1, java.lang.Stringin2)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 1088 of file VOMSAttributesSoapBindingStub.java.
.PP
.nf
                                                                                                                                                                             {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[17]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'deleteRoleAttribute'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0, in1, in2});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        extractAttachments(_call);
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.deleteRoleAttribute (java.lang.Stringin0, java.lang.Stringin1, \fBorg.glite.security.voms.service.attributes.AttributeValue\fPin2)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 1120 of file VOMSAttributesSoapBindingStub.java.
.PP
.nf
                                                                                                                                                                                                                      {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[18]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'deleteRoleAttribute'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0, in1, in2});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        extractAttachments(_call);
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.deleteUserAttribute (\fBorg.glite.security.voms.User\fPin0, \fBorg.glite.security.voms.service.attributes.AttributeValue\fPin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 889 of file VOMSAttributesSoapBindingStub.java.
.PP
.nf
                                                                                                                                                                                                            {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[11]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'deleteUserAttribute'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0, in1});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        extractAttachments(_call);
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.deleteUserAttribute (\fBorg.glite.security.voms.User\fPin0, java.lang.Stringin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 857 of file VOMSAttributesSoapBindingStub.java.
.PP
.nf
                                                                                                                                                                   {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[10]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'deleteUserAttribute'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0, in1});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        extractAttachments(_call);
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SS "\fBorg.glite.security.voms.service.attributes.AttributeClass\fP org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.getAttributeClass (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 612 of file VOMSAttributesSoapBindingStub.java.
.PP
.nf
                                                                                                                                                                                    {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[3]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'getAttributeClass'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        else {
            extractAttachments(_call);
            try {
                return (org.glite.security.voms.service.attributes.AttributeClass) _resp;
            } catch (java.lang.Exception _exception) {
                return (org.glite.security.voms.service.attributes.AttributeClass) org.apache.axis.utils.JavaUtils.convert(_resp, org.glite.security.voms.service.attributes.AttributeClass.class);
            }
        }
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SS "\fBorg.glite.security.voms.service.attributes.AttributeClass\fP [] org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.listAttributeClasses ()  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 747 of file VOMSAttributesSoapBindingStub.java.
.PP
.nf
                                                                                                                                                                     {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[7]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'listAttributeClasses'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        else {
            extractAttachments(_call);
            try {
                return (org.glite.security.voms.service.attributes.AttributeClass[]) _resp;
            } catch (java.lang.Exception _exception) {
                return (org.glite.security.voms.service.attributes.AttributeClass[]) org.apache.axis.utils.JavaUtils.convert(_resp, org.glite.security.voms.service.attributes.AttributeClass[].class);
            }
        }
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SS "\fBorg.glite.security.voms.service.attributes.AttributeValue\fP [] org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.listGroupAttributes (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 1017 of file VOMSAttributesSoapBindingStub.java.
.PP
.nf
                                                                                                                                                                                        {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[15]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'listGroupAttributes'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        else {
            extractAttachments(_call);
            try {
                return (org.glite.security.voms.service.attributes.AttributeValue[]) _resp;
            } catch (java.lang.Exception _exception) {
                return (org.glite.security.voms.service.attributes.AttributeValue[]) org.apache.axis.utils.JavaUtils.convert(_resp, org.glite.security.voms.service.attributes.AttributeValue[].class);
            }
        }
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SS "\fBorg.glite.security.voms.service.attributes.AttributeValue\fP [] org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.listRoleAttributes (java.lang.Stringin0, java.lang.Stringin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 1152 of file VOMSAttributesSoapBindingStub.java.
.PP
.nf
                                                                                                                                                                                                             {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[19]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'listRoleAttributes'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0, in1});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        else {
            extractAttachments(_call);
            try {
                return (org.glite.security.voms.service.attributes.AttributeValue[]) _resp;
            } catch (java.lang.Exception _exception) {
                return (org.glite.security.voms.service.attributes.AttributeValue[]) org.apache.axis.utils.JavaUtils.convert(_resp, org.glite.security.voms.service.attributes.AttributeValue[].class);
            }
        }
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SS "\fBorg.glite.security.voms.service.attributes.AttributeValue\fP [] org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.listUserAttributes (\fBorg.glite.security.voms.User\fPin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 786 of file VOMSAttributesSoapBindingStub.java.
.PP
.nf
                                                                                                                                                                                                   {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[8]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'listUserAttributes'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        else {
            extractAttachments(_call);
            try {
                return (org.glite.security.voms.service.attributes.AttributeValue[]) _resp;
            } catch (java.lang.Exception _exception) {
                return (org.glite.security.voms.service.attributes.AttributeValue[]) org.apache.axis.utils.JavaUtils.convert(_resp, org.glite.security.voms.service.attributes.AttributeValue[].class);
            }
        }
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.saveAttributeClass (\fBorg.glite.security.voms.service.attributes.AttributeClass\fPin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 651 of file VOMSAttributesSoapBindingStub.java.
.PP
.nf
                                                                                                                                                                         {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[4]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'saveAttributeClass'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        extractAttachments(_call);
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.setGroupAttribute (java.lang.Stringin0, \fBorg.glite.security.voms.service.attributes.AttributeValue\fPin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 921 of file VOMSAttributesSoapBindingStub.java.
.PP
.nf
                                                                                                                                                                                              {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[12]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'setGroupAttribute'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0, in1});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        extractAttachments(_call);
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.setRoleAttribute (java.lang.Stringin0, java.lang.Stringin1, \fBorg.glite.security.voms.service.attributes.AttributeValue\fPin2)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 1056 of file VOMSAttributesSoapBindingStub.java.
.PP
.nf
                                                                                                                                                                                                                   {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[16]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'setRoleAttribute'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0, in1, in2});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        extractAttachments(_call);
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.setUserAttribute (\fBorg.glite.security.voms.User\fPin0, \fBorg.glite.security.voms.service.attributes.AttributeValue\fPin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 825 of file VOMSAttributesSoapBindingStub.java.
.PP
.nf
                                                                                                                                                                                                         {
        if (super.cachedEndpoint == null) {
            throw new org.apache.axis.NoEndPointException();
        }
        org.apache.axis.client.Call _call = createCall();
        _call.setOperation(_operations[9]);
        _call.setUseSOAPAction(true);
        _call.setSOAPActionURI('');
        _call.setSOAPVersion(org.apache.axis.soap.SOAPConstants.SOAP11_CONSTANTS);
        _call.setOperationName(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.attributes', 'setUserAttribute'));

        setRequestHeaders(_call);
        setAttachments(_call);
 try {        java.lang.Object _resp = _call.invoke(new java.lang.Object[] {in0, in1});

        if (_resp instanceof java.rmi.RemoteException) {
            throw (java.rmi.RemoteException)_resp;
        }
        extractAttachments(_call);
  } catch (org.apache.axis.AxisFault axisFaultException) {
    if (axisFaultException.detail != null) {
        if (axisFaultException.detail instanceof java.rmi.RemoteException) {
              throw (java.rmi.RemoteException) axisFaultException.detail;
         }
        if (axisFaultException.detail instanceof org.glite.security.voms.VOMSException) {
              throw (org.glite.security.voms.VOMSException) axisFaultException.detail;
         }
   }
  throw axisFaultException;
}
    }
.fi
.SH "Member Data Documentation"
.PP 
.SS "org.apache.axis.description.OperationDesc [] \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub._operations\fP\fC [static, package]\fP"
.PP
Definition at line 16 of file VOMSAttributesSoapBindingStub.java.
.PP
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub._initOperationDesc1(), org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub._initOperationDesc2(), and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.createAttributeClass().
.SS "java.util.Vector \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.cachedDeserFactories\fP = new java.util.Vector()\fC [private]\fP"
.PP
Definition at line 14 of file VOMSAttributesSoapBindingStub.java.
.PP
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.createCall(), and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.VOMSAttributesSoapBindingStub().
.SS "java.util.Vector \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.cachedSerClasses\fP = new java.util.Vector()\fC [private]\fP"
.PP
Definition at line 11 of file VOMSAttributesSoapBindingStub.java.
.PP
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.createCall(), and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.VOMSAttributesSoapBindingStub().
.SS "java.util.Vector \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.cachedSerFactories\fP = new java.util.Vector()\fC [private]\fP"
.PP
Definition at line 13 of file VOMSAttributesSoapBindingStub.java.
.PP
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.createCall(), and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.VOMSAttributesSoapBindingStub().
.SS "java.util.Vector \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.cachedSerQNames\fP = new java.util.Vector()\fC [private]\fP"
.PP
Definition at line 12 of file VOMSAttributesSoapBindingStub.java.
.PP
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.createCall(), and org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub.VOMSAttributesSoapBindingStub().

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
