.TH "org::glite::security::voms::service::compatibility::VOMSCompatibility" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org::glite::security::voms::service::compatibility::VOMSCompatibility \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBorg.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingImpl\fP, \fBorg.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBgetMajorVersionNumber\fP ()  throws java.rmi.RemoteException"
.br
.ti -1c
.RI "int \fBgetMinorVersionNumber\fP ()  throws java.rmi.RemoteException"
.br
.ti -1c
.RI "int \fBgetPatchVersionNumber\fP ()  throws java.rmi.RemoteException"
.br
.ti -1c
.RI "java.lang.String[] \fBgetGridmapUsers\fP ()  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "java.lang.String[] \fBgetGridmapUsers\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file VOMSCompatibility.java.
.SH "Member Function Documentation"
.PP 
.SS "java.lang.String [] org.glite.security.voms.service.compatibility.VOMSCompatibility.getGridmapUsers ()  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingImpl\fP, \fBorg.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.getGridmapUsers().
.SS "java.lang.String [] org.glite.security.voms.service.compatibility.VOMSCompatibility.getGridmapUsers (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingImpl\fP, \fBorg.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub\fP.
.SS "int org.glite.security.voms.service.compatibility.VOMSCompatibility.getMajorVersionNumber ()  throws java.rmi.RemoteException"
.PP
Implemented in \fBorg.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingImpl\fP, \fBorg.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.getMajorVersionNumber().
.SS "int org.glite.security.voms.service.compatibility.VOMSCompatibility.getMinorVersionNumber ()  throws java.rmi.RemoteException"
.PP
Implemented in \fBorg.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingImpl\fP, \fBorg.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.getMinorVersionNumber().
.SS "int org.glite.security.voms.service.compatibility.VOMSCompatibility.getPatchVersionNumber ()  throws java.rmi.RemoteException"
.PP
Implemented in \fBorg.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingImpl\fP, \fBorg.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingSkeleton.getPatchVersionNumber().

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
