.TH "org::glite::security::voms::service::attributes::VOMSAttributes" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org::glite::security::voms::service::attributes::VOMSAttributes \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl\fP, \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBcreateAttributeClass\fP (java.lang.String in0, java.lang.String in1, boolean in2)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "void \fBcreateAttributeClass\fP (java.lang.String in0, java.lang.String in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "void \fBcreateAttributeClass\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.attributes.AttributeClass\fP \fBgetAttributeClass\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "void \fBsaveAttributeClass\fP (\fBorg.glite.security.voms.service.attributes.AttributeClass\fP in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "void \fBdeleteAttributeClass\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "void \fBdeleteAttributeClass\fP (\fBorg.glite.security.voms.service.attributes.AttributeClass\fP in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.attributes.AttributeClass\fP[] \fBlistAttributeClasses\fP ()  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.attributes.AttributeValue\fP[] \fBlistUserAttributes\fP (\fBorg.glite.security.voms.User\fP in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "void \fBsetUserAttribute\fP (\fBorg.glite.security.voms.User\fP in0, \fBorg.glite.security.voms.service.attributes.AttributeValue\fP in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "void \fBdeleteUserAttribute\fP (\fBorg.glite.security.voms.User\fP in0, java.lang.String in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "void \fBdeleteUserAttribute\fP (\fBorg.glite.security.voms.User\fP in0, \fBorg.glite.security.voms.service.attributes.AttributeValue\fP in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "void \fBsetGroupAttribute\fP (java.lang.String in0, \fBorg.glite.security.voms.service.attributes.AttributeValue\fP in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "void \fBdeleteGroupAttribute\fP (java.lang.String in0, java.lang.String in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "void \fBdeleteGroupAttribute\fP (java.lang.String in0, \fBorg.glite.security.voms.service.attributes.AttributeValue\fP in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.attributes.AttributeValue\fP[] \fBlistGroupAttributes\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "void \fBsetRoleAttribute\fP (java.lang.String in0, java.lang.String in1, \fBorg.glite.security.voms.service.attributes.AttributeValue\fP in2)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "void \fBdeleteRoleAttribute\fP (java.lang.String in0, java.lang.String in1, java.lang.String in2)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "void \fBdeleteRoleAttribute\fP (java.lang.String in0, java.lang.String in1, \fBorg.glite.security.voms.service.attributes.AttributeValue\fP in2)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.attributes.AttributeValue\fP[] \fBlistRoleAttributes\fP (java.lang.String in0, java.lang.String in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file VOMSAttributes.java.
.SH "Member Function Documentation"
.PP 
.SS "void org.glite.security.voms.service.attributes.VOMSAttributes.createAttributeClass (java.lang.Stringin0, java.lang.Stringin1, booleanin2)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl\fP, \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.createAttributeClass().
.SS "void org.glite.security.voms.service.attributes.VOMSAttributes.createAttributeClass (java.lang.Stringin0, java.lang.Stringin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl\fP, \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub\fP.
.SS "void org.glite.security.voms.service.attributes.VOMSAttributes.createAttributeClass (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl\fP, \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub\fP.
.SS "void org.glite.security.voms.service.attributes.VOMSAttributes.deleteAttributeClass (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl\fP, \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.deleteAttributeClass().
.SS "void org.glite.security.voms.service.attributes.VOMSAttributes.deleteAttributeClass (\fBorg.glite.security.voms.service.attributes.AttributeClass\fPin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl\fP, \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub\fP.
.SS "void org.glite.security.voms.service.attributes.VOMSAttributes.deleteGroupAttribute (java.lang.Stringin0, java.lang.Stringin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl\fP, \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.deleteGroupAttribute().
.SS "void org.glite.security.voms.service.attributes.VOMSAttributes.deleteGroupAttribute (java.lang.Stringin0, \fBorg.glite.security.voms.service.attributes.AttributeValue\fPin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl\fP, \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub\fP.
.SS "void org.glite.security.voms.service.attributes.VOMSAttributes.deleteRoleAttribute (java.lang.Stringin0, java.lang.Stringin1, java.lang.Stringin2)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl\fP, \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.deleteRoleAttribute().
.SS "void org.glite.security.voms.service.attributes.VOMSAttributes.deleteRoleAttribute (java.lang.Stringin0, java.lang.Stringin1, \fBorg.glite.security.voms.service.attributes.AttributeValue\fPin2)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl\fP, \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub\fP.
.SS "void org.glite.security.voms.service.attributes.VOMSAttributes.deleteUserAttribute (\fBorg.glite.security.voms.User\fPin0, java.lang.Stringin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl\fP, \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.deleteUserAttribute().
.SS "void org.glite.security.voms.service.attributes.VOMSAttributes.deleteUserAttribute (\fBorg.glite.security.voms.User\fPin0, \fBorg.glite.security.voms.service.attributes.AttributeValue\fPin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl\fP, \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub\fP.
.SS "\fBorg.glite.security.voms.service.attributes.AttributeClass\fP org.glite.security.voms.service.attributes.VOMSAttributes.getAttributeClass (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl\fP, \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.getAttributeClass().
.SS "\fBorg.glite.security.voms.service.attributes.AttributeClass\fP [] org.glite.security.voms.service.attributes.VOMSAttributes.listAttributeClasses ()  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl\fP, \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.listAttributeClasses().
.SS "\fBorg.glite.security.voms.service.attributes.AttributeValue\fP [] org.glite.security.voms.service.attributes.VOMSAttributes.listGroupAttributes (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl\fP, \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.listGroupAttributes().
.SS "\fBorg.glite.security.voms.service.attributes.AttributeValue\fP [] org.glite.security.voms.service.attributes.VOMSAttributes.listRoleAttributes (java.lang.Stringin0, java.lang.Stringin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl\fP, \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.listRoleAttributes().
.SS "\fBorg.glite.security.voms.service.attributes.AttributeValue\fP [] org.glite.security.voms.service.attributes.VOMSAttributes.listUserAttributes (\fBorg.glite.security.voms.User\fPin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl\fP, \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.listUserAttributes().
.SS "void org.glite.security.voms.service.attributes.VOMSAttributes.saveAttributeClass (\fBorg.glite.security.voms.service.attributes.AttributeClass\fPin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl\fP, \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.saveAttributeClass().
.SS "void org.glite.security.voms.service.attributes.VOMSAttributes.setGroupAttribute (java.lang.Stringin0, \fBorg.glite.security.voms.service.attributes.AttributeValue\fPin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl\fP, \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.setGroupAttribute().
.SS "void org.glite.security.voms.service.attributes.VOMSAttributes.setRoleAttribute (java.lang.Stringin0, java.lang.Stringin1, \fBorg.glite.security.voms.service.attributes.AttributeValue\fPin2)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl\fP, \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.setRoleAttribute().
.SS "void org.glite.security.voms.service.attributes.VOMSAttributes.setUserAttribute (\fBorg.glite.security.voms.User\fPin0, \fBorg.glite.security.voms.service.attributes.AttributeValue\fPin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl\fP, \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.attributes.VOMSAttributesSoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingSkeleton.setUserAttribute().

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
