.TH "org::glite::security::voms::service::acl::VOMSACL" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org::glite::security::voms::service::acl::VOMSACL \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingImpl\fP, \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingStub\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBorg.glite.security.voms.service.acl.ACLEntry\fP[] \fBgetACL\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "void \fBsetACL\fP (java.lang.String in0, \fBorg.glite.security.voms.service.acl.ACLEntry\fP[] in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "void \fBaddACLEntry\fP (java.lang.String in0, \fBorg.glite.security.voms.service.acl.ACLEntry\fP in1, boolean in2)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "void \fBremoveACLEntry\fP (java.lang.String in0, \fBorg.glite.security.voms.service.acl.ACLEntry\fP in1, boolean in2)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.acl.ACLEntry\fP[] \fBgetDefaultACL\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "void \fBsetDefaultACL\fP (java.lang.String in0, \fBorg.glite.security.voms.service.acl.ACLEntry\fP[] in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "void \fBaddDefaultACLEntry\fP (java.lang.String in0, \fBorg.glite.security.voms.service.acl.ACLEntry\fP in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "void \fBremoveDefaultACLEntry\fP (java.lang.String in0, \fBorg.glite.security.voms.service.acl.ACLEntry\fP in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file VOMSACL.java.
.SH "Member Function Documentation"
.PP 
.SS "void org.glite.security.voms.service.acl.VOMSACL.addACLEntry (java.lang.Stringin0, \fBorg.glite.security.voms.service.acl.ACLEntry\fPin1, booleanin2)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingImpl\fP, \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.addACLEntry().
.SS "void org.glite.security.voms.service.acl.VOMSACL.addDefaultACLEntry (java.lang.Stringin0, \fBorg.glite.security.voms.service.acl.ACLEntry\fPin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingImpl\fP, \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.addDefaultACLEntry().
.SS "\fBorg.glite.security.voms.service.acl.ACLEntry\fP [] org.glite.security.voms.service.acl.VOMSACL.getACL (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingImpl\fP, \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.getACL().
.SS "\fBorg.glite.security.voms.service.acl.ACLEntry\fP [] org.glite.security.voms.service.acl.VOMSACL.getDefaultACL (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingImpl\fP, \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.getDefaultACL().
.SS "void org.glite.security.voms.service.acl.VOMSACL.removeACLEntry (java.lang.Stringin0, \fBorg.glite.security.voms.service.acl.ACLEntry\fPin1, booleanin2)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingImpl\fP, \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.removeACLEntry().
.SS "void org.glite.security.voms.service.acl.VOMSACL.removeDefaultACLEntry (java.lang.Stringin0, \fBorg.glite.security.voms.service.acl.ACLEntry\fPin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingImpl\fP, \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.removeDefaultACLEntry().
.SS "void org.glite.security.voms.service.acl.VOMSACL.setACL (java.lang.Stringin0, \fBorg.glite.security.voms.service.acl.ACLEntry\fP[]in1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingImpl\fP, \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.setACL().
.SS "void org.glite.security.voms.service.acl.VOMSACL.setDefaultACL (java.lang.Stringin0, \fBorg.glite.security.voms.service.acl.ACLEntry\fP[]in1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingImpl\fP, \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.acl.VOMSACLSoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.acl.VOMSACLSoapBindingSkeleton.setDefaultACL().

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
