.TH "org::glite::security::voms::service::certificates::VOMSCertificatesService" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org::glite::security::voms::service::certificates::VOMSCertificatesService \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBorg.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "java.lang.String \fBgetVOMSCertificatesAddress\fP ()"
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.certificates.VOMSCertificates\fP \fBgetVOMSCertificates\fP ()  throws javax.xml.rpc.ServiceException"
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.certificates.VOMSCertificates\fP \fBgetVOMSCertificates\fP (java.net.URL portAddress)  throws javax.xml.rpc.ServiceException"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file VOMSCertificatesService.java.
.SH "Member Function Documentation"
.PP 
.SS "\fBorg.glite.security.voms.service.certificates.VOMSCertificates\fP org.glite.security.voms.service.certificates.VOMSCertificatesService.getVOMSCertificates ()  throws javax.xml.rpc.ServiceException"
.PP
Implemented in \fBorg.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator\fP.
.SS "\fBorg.glite.security.voms.service.certificates.VOMSCertificates\fP org.glite.security.voms.service.certificates.VOMSCertificatesService.getVOMSCertificates (java.net.URLportAddress)  throws javax.xml.rpc.ServiceException"
.PP
Implemented in \fBorg.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator\fP.
.SS "java.lang.String org.glite.security.voms.service.certificates.VOMSCertificatesService.getVOMSCertificatesAddress ()"
.PP
Implemented in \fBorg.glite.security.voms.service.certificates.VOMSCertificatesServiceLocator\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
