.TH "org::glite::security::voms::service::attributes::VOMSAttributesService" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org::glite::security::voms::service::attributes::VOMSAttributesService \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBorg.glite.security.voms.service.attributes.VOMSAttributesServiceLocator\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "java.lang.String \fBgetVOMSAttributesAddress\fP ()"
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP \fBgetVOMSAttributes\fP ()  throws javax.xml.rpc.ServiceException"
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP \fBgetVOMSAttributes\fP (java.net.URL portAddress)  throws javax.xml.rpc.ServiceException"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file VOMSAttributesService.java.
.SH "Member Function Documentation"
.PP 
.SS "\fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP org.glite.security.voms.service.attributes.VOMSAttributesService.getVOMSAttributes ()  throws javax.xml.rpc.ServiceException"
.PP
Implemented in \fBorg.glite.security.voms.service.attributes.VOMSAttributesServiceLocator\fP.
.SS "\fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP org.glite.security.voms.service.attributes.VOMSAttributesService.getVOMSAttributes (java.net.URLportAddress)  throws javax.xml.rpc.ServiceException"
.PP
Implemented in \fBorg.glite.security.voms.service.attributes.VOMSAttributesServiceLocator\fP.
.SS "java.lang.String org.glite.security.voms.service.attributes.VOMSAttributesService.getVOMSAttributesAddress ()"
.PP
Implemented in \fBorg.glite.security.voms.service.attributes.VOMSAttributesServiceLocator\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
