.TH "org::glite::security::voms::service::registration::RegistrationRequest" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org::glite::security::voms::service::registration::RegistrationRequest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRegistrationRequest\fP ()"
.br
.ti -1c
.RI "\fBRegistrationRequest\fP (boolean \fBaupAccepted\fP, java.lang.String \fBcomments\fP, java.lang.String \fBemailAddress\fP, java.lang.String \fBinstitute\fP, java.lang.String \fBphoneNumber\fP)"
.br
.ti -1c
.RI "boolean \fBisAupAccepted\fP ()"
.br
.ti -1c
.RI "void \fBsetAupAccepted\fP (boolean \fBaupAccepted\fP)"
.br
.ti -1c
.RI "java.lang.String \fBgetComments\fP ()"
.br
.ti -1c
.RI "void \fBsetComments\fP (java.lang.String \fBcomments\fP)"
.br
.ti -1c
.RI "java.lang.String \fBgetEmailAddress\fP ()"
.br
.ti -1c
.RI "void \fBsetEmailAddress\fP (java.lang.String \fBemailAddress\fP)"
.br
.ti -1c
.RI "java.lang.String \fBgetInstitute\fP ()"
.br
.ti -1c
.RI "void \fBsetInstitute\fP (java.lang.String \fBinstitute\fP)"
.br
.ti -1c
.RI "java.lang.String \fBgetPhoneNumber\fP ()"
.br
.ti -1c
.RI "void \fBsetPhoneNumber\fP (java.lang.String \fBphoneNumber\fP)"
.br
.ti -1c
.RI "synchronized boolean \fBequals\fP (java.lang.Object obj)"
.br
.ti -1c
.RI "synchronized int \fBhashCode\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "boolean \fBaupAccepted\fP"
.br
.ti -1c
.RI "java.lang.String \fBcomments\fP"
.br
.ti -1c
.RI "java.lang.String \fBemailAddress\fP"
.br
.ti -1c
.RI "java.lang.String \fBinstitute\fP"
.br
.ti -1c
.RI "java.lang.String \fBphoneNumber\fP"
.br
.ti -1c
.RI "java.lang.Object \fB__equalsCalc\fP = null"
.br
.ti -1c
.RI "boolean \fB__hashCodeCalc\fP = false"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file RegistrationRequest.java.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org.glite.security.voms.service.registration.RegistrationRequest.RegistrationRequest ()"
.PP
Definition at line 21 of file RegistrationRequest.java.
.PP
Referenced by org.glite.security.voms.service.registration.RegistrationRequest.equals().
.PP
.nf
                                 {
    }
.fi
.SS "org.glite.security.voms.service.registration.RegistrationRequest.RegistrationRequest (booleanaupAccepted, java.lang.Stringcomments, java.lang.StringemailAddress, java.lang.Stringinstitute, java.lang.StringphoneNumber)"
.PP
Definition at line 24 of file RegistrationRequest.java.
.PP
References org.glite.security.voms.service.registration.RegistrationRequest.aupAccepted, org.glite.security.voms.service.registration.RegistrationRequest.comments, org.glite.security.voms.service.registration.RegistrationRequest.emailAddress, org.glite.security.voms.service.registration.RegistrationRequest.institute, and org.glite.security.voms.service.registration.RegistrationRequest.phoneNumber.
.PP
.nf
                                         {
           this.aupAccepted = aupAccepted;
           this.comments = comments;
           this.emailAddress = emailAddress;
           this.institute = institute;
           this.phoneNumber = phoneNumber;
    }
.fi
.SH "Member Function Documentation"
.PP 
.SS "synchronized boolean org.glite.security.voms.service.registration.RegistrationRequest.equals (java.lang.Objectobj)"
.PP
Definition at line 138 of file RegistrationRequest.java.
.PP
References org.glite.security.voms.service.registration.RegistrationRequest.__equalsCalc, org.glite.security.voms.service.registration.RegistrationRequest.aupAccepted, org.glite.security.voms.service.registration.RegistrationRequest.comments, org.glite.security.voms.service.registration.RegistrationRequest.emailAddress, org.glite.security.voms.service.registration.RegistrationRequest.getComments(), org.glite.security.voms.service.registration.RegistrationRequest.getEmailAddress(), org.glite.security.voms.service.registration.RegistrationRequest.getInstitute(), org.glite.security.voms.service.registration.RegistrationRequest.getPhoneNumber(), org.glite.security.voms.service.registration.RegistrationRequest.institute, org.glite.security.voms.service.registration.RegistrationRequest.isAupAccepted(), org.glite.security.voms.service.registration.RegistrationRequest.phoneNumber, and org.glite.security.voms.service.registration.RegistrationRequest.RegistrationRequest().
.PP
.nf
                                                             {
        if (!(obj instanceof RegistrationRequest)) return false;
        RegistrationRequest other = (RegistrationRequest) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            this.aupAccepted == other.isAupAccepted() &&
            ((this.comments==null && other.getComments()==null) || 
             (this.comments!=null &&
              this.comments.equals(other.getComments()))) &&
            ((this.emailAddress==null && other.getEmailAddress()==null) || 
             (this.emailAddress!=null &&
              this.emailAddress.equals(other.getEmailAddress()))) &&
            ((this.institute==null && other.getInstitute()==null) || 
             (this.institute!=null &&
              this.institute.equals(other.getInstitute()))) &&
            ((this.phoneNumber==null && other.getPhoneNumber()==null) || 
             (this.phoneNumber!=null &&
              this.phoneNumber.equals(other.getPhoneNumber())));
        __equalsCalc = null;
        return _equals;
    }
.fi
.SS "java.lang.String org.glite.security.voms.service.registration.RegistrationRequest.getComments ()"Gets the comments value for this \fBRegistrationRequest\fP.
.PP
\fBReturns:\fP
.RS 4
comments 
.RE
.PP

.PP
Definition at line 63 of file RegistrationRequest.java.
.PP
References org.glite.security.voms.service.registration.RegistrationRequest.comments.
.PP
Referenced by org.glite.security.voms.service.registration.RegistrationRequest.equals(), and org.glite.security.voms.service.registration.RegistrationRequest.hashCode().
.PP
.nf
                                          {
        return comments;
    }
.fi
.SS "java.lang.String org.glite.security.voms.service.registration.RegistrationRequest.getEmailAddress ()"Gets the emailAddress value for this \fBRegistrationRequest\fP.
.PP
\fBReturns:\fP
.RS 4
emailAddress 
.RE
.PP

.PP
Definition at line 83 of file RegistrationRequest.java.
.PP
References org.glite.security.voms.service.registration.RegistrationRequest.emailAddress.
.PP
Referenced by org.glite.security.voms.service.registration.RegistrationRequest.equals(), and org.glite.security.voms.service.registration.RegistrationRequest.hashCode().
.PP
.nf
                                              {
        return emailAddress;
    }
.fi
.SS "java.lang.String org.glite.security.voms.service.registration.RegistrationRequest.getInstitute ()"Gets the institute value for this \fBRegistrationRequest\fP.
.PP
\fBReturns:\fP
.RS 4
institute 
.RE
.PP

.PP
Definition at line 103 of file RegistrationRequest.java.
.PP
References org.glite.security.voms.service.registration.RegistrationRequest.institute.
.PP
Referenced by org.glite.security.voms.service.registration.RegistrationRequest.equals(), and org.glite.security.voms.service.registration.RegistrationRequest.hashCode().
.PP
.nf
                                           {
        return institute;
    }
.fi
.SS "java.lang.String org.glite.security.voms.service.registration.RegistrationRequest.getPhoneNumber ()"Gets the phoneNumber value for this \fBRegistrationRequest\fP.
.PP
\fBReturns:\fP
.RS 4
phoneNumber 
.RE
.PP

.PP
Definition at line 123 of file RegistrationRequest.java.
.PP
References org.glite.security.voms.service.registration.RegistrationRequest.phoneNumber.
.PP
Referenced by org.glite.security.voms.service.registration.RegistrationRequest.equals(), and org.glite.security.voms.service.registration.RegistrationRequest.hashCode().
.PP
.nf
                                             {
        return phoneNumber;
    }
.fi
.SS "synchronized int org.glite.security.voms.service.registration.RegistrationRequest.hashCode ()"
.PP
Definition at line 167 of file RegistrationRequest.java.
.PP
References org.glite.security.voms.service.registration.RegistrationRequest.__hashCodeCalc, org.glite.security.voms.service.registration.RegistrationRequest.getComments(), org.glite.security.voms.service.registration.RegistrationRequest.getEmailAddress(), org.glite.security.voms.service.registration.RegistrationRequest.getInstitute(), org.glite.security.voms.service.registration.RegistrationRequest.getPhoneNumber(), and org.glite.security.voms.service.registration.RegistrationRequest.isAupAccepted().
.PP
.nf
                                       {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        _hashCode += (isAupAccepted() ? Boolean.TRUE : Boolean.FALSE).hashCode();
        if (getComments() != null) {
            _hashCode += getComments().hashCode();
        }
        if (getEmailAddress() != null) {
            _hashCode += getEmailAddress().hashCode();
        }
        if (getInstitute() != null) {
            _hashCode += getInstitute().hashCode();
        }
        if (getPhoneNumber() != null) {
            _hashCode += getPhoneNumber().hashCode();
        }
        __hashCodeCalc = false;
        return _hashCode;
    }
.fi
.SS "boolean org.glite.security.voms.service.registration.RegistrationRequest.isAupAccepted ()"Gets the aupAccepted value for this \fBRegistrationRequest\fP.
.PP
\fBReturns:\fP
.RS 4
aupAccepted 
.RE
.PP

.PP
Definition at line 43 of file RegistrationRequest.java.
.PP
References org.glite.security.voms.service.registration.RegistrationRequest.aupAccepted.
.PP
Referenced by org.glite.security.voms.service.registration.RegistrationRequest.equals(), and org.glite.security.voms.service.registration.RegistrationRequest.hashCode().
.PP
.nf
                                   {
        return aupAccepted;
    }
.fi
.SS "void org.glite.security.voms.service.registration.RegistrationRequest.setAupAccepted (booleanaupAccepted)"Sets the aupAccepted value for this \fBRegistrationRequest\fP.
.PP
\fBParameters:\fP
.RS 4
\fIaupAccepted\fP 
.RE
.PP

.PP
Definition at line 53 of file RegistrationRequest.java.
.PP
References org.glite.security.voms.service.registration.RegistrationRequest.aupAccepted.
.PP
.nf
                                                    {
        this.aupAccepted = aupAccepted;
    }
.fi
.SS "void org.glite.security.voms.service.registration.RegistrationRequest.setComments (java.lang.Stringcomments)"Sets the comments value for this \fBRegistrationRequest\fP.
.PP
\fBParameters:\fP
.RS 4
\fIcomments\fP 
.RE
.PP

.PP
Definition at line 73 of file RegistrationRequest.java.
.PP
References org.glite.security.voms.service.registration.RegistrationRequest.comments.
.PP
.nf
                                                       {
        this.comments = comments;
    }
.fi
.SS "void org.glite.security.voms.service.registration.RegistrationRequest.setEmailAddress (java.lang.StringemailAddress)"Sets the emailAddress value for this \fBRegistrationRequest\fP.
.PP
\fBParameters:\fP
.RS 4
\fIemailAddress\fP 
.RE
.PP

.PP
Definition at line 93 of file RegistrationRequest.java.
.PP
References org.glite.security.voms.service.registration.RegistrationRequest.emailAddress.
.PP
.nf
                                                               {
        this.emailAddress = emailAddress;
    }
.fi
.SS "void org.glite.security.voms.service.registration.RegistrationRequest.setInstitute (java.lang.Stringinstitute)"Sets the institute value for this \fBRegistrationRequest\fP.
.PP
\fBParameters:\fP
.RS 4
\fIinstitute\fP 
.RE
.PP

.PP
Definition at line 113 of file RegistrationRequest.java.
.PP
References org.glite.security.voms.service.registration.RegistrationRequest.institute.
.PP
.nf
                                                         {
        this.institute = institute;
    }
.fi
.SS "void org.glite.security.voms.service.registration.RegistrationRequest.setPhoneNumber (java.lang.StringphoneNumber)"Sets the phoneNumber value for this \fBRegistrationRequest\fP.
.PP
\fBParameters:\fP
.RS 4
\fIphoneNumber\fP 
.RE
.PP

.PP
Definition at line 133 of file RegistrationRequest.java.
.PP
References org.glite.security.voms.service.registration.RegistrationRequest.phoneNumber.
.PP
.nf
                                                             {
        this.phoneNumber = phoneNumber;
    }
.fi
.SH "Member Data Documentation"
.PP 
.SS "java.lang.Object \fBorg.glite.security.voms.service.registration.RegistrationRequest.__equalsCalc\fP = null\fC [private]\fP"
.PP
Definition at line 137 of file RegistrationRequest.java.
.PP
Referenced by org.glite.security.voms.service.registration.RegistrationRequest.equals().
.SS "boolean \fBorg.glite.security.voms.service.registration.RegistrationRequest.__hashCodeCalc\fP = false\fC [private]\fP"
.PP
Definition at line 166 of file RegistrationRequest.java.
.PP
Referenced by org.glite.security.voms.service.registration.RegistrationRequest.hashCode().
.SS "boolean \fBorg.glite.security.voms.service.registration.RegistrationRequest.aupAccepted\fP\fC [private]\fP"
.PP
Definition at line 11 of file RegistrationRequest.java.
.PP
Referenced by org.glite.security.voms.service.registration.RegistrationRequest.equals(), org.glite.security.voms.service.registration.RegistrationRequest.isAupAccepted(), org.glite.security.voms.service.registration.RegistrationRequest.RegistrationRequest(), and org.glite.security.voms.service.registration.RegistrationRequest.setAupAccepted().
.SS "java.lang.String \fBorg.glite.security.voms.service.registration.RegistrationRequest.comments\fP\fC [private]\fP"
.PP
Definition at line 13 of file RegistrationRequest.java.
.PP
Referenced by org.glite.security.voms.service.registration.RegistrationRequest.equals(), org.glite.security.voms.service.registration.RegistrationRequest.getComments(), org.glite.security.voms.service.registration.RegistrationRequest.RegistrationRequest(), and org.glite.security.voms.service.registration.RegistrationRequest.setComments().
.SS "java.lang.String \fBorg.glite.security.voms.service.registration.RegistrationRequest.emailAddress\fP\fC [private]\fP"
.PP
Definition at line 15 of file RegistrationRequest.java.
.PP
Referenced by org.glite.security.voms.service.registration.RegistrationRequest.equals(), org.glite.security.voms.service.registration.RegistrationRequest.getEmailAddress(), org.glite.security.voms.service.registration.RegistrationRequest.RegistrationRequest(), and org.glite.security.voms.service.registration.RegistrationRequest.setEmailAddress().
.SS "java.lang.String \fBorg.glite.security.voms.service.registration.RegistrationRequest.institute\fP\fC [private]\fP"
.PP
Definition at line 17 of file RegistrationRequest.java.
.PP
Referenced by org.glite.security.voms.service.registration.RegistrationRequest.equals(), org.glite.security.voms.service.registration.RegistrationRequest.getInstitute(), org.glite.security.voms.service.registration.RegistrationRequest.RegistrationRequest(), and org.glite.security.voms.service.registration.RegistrationRequest.setInstitute().
.SS "java.lang.String \fBorg.glite.security.voms.service.registration.RegistrationRequest.phoneNumber\fP\fC [private]\fP"
.PP
Definition at line 19 of file RegistrationRequest.java.
.PP
Referenced by org.glite.security.voms.service.registration.RegistrationRequest.equals(), org.glite.security.voms.service.registration.RegistrationRequest.getPhoneNumber(), org.glite.security.voms.service.registration.RegistrationRequest.RegistrationRequest(), and org.glite.security.voms.service.registration.RegistrationRequest.setPhoneNumber().

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
