.TH "org::glite::security::voms::service::registration::VOMSRegistration" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org::glite::security::voms::service::registration::VOMSRegistration \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBorg.glite.security.voms.service.registration.VOMSRegistrationSoapBindingImpl\fP, \fBorg.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsubmitRegistrationRequest\fP (\fBorg.glite.security.voms.service.registration.RegistrationRequest\fP in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.ti -1c
.RI "void \fBsubmitRegistrationRequestForUser\fP (java.lang.String in0, java.lang.String in1, \fBorg.glite.security.voms.service.registration.RegistrationRequest\fP in2)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file VOMSRegistration.java.
.SH "Member Function Documentation"
.PP 
.SS "void org.glite.security.voms.service.registration.VOMSRegistration.submitRegistrationRequest (\fBorg.glite.security.voms.service.registration.RegistrationRequest\fPin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.registration.VOMSRegistrationSoapBindingImpl\fP, \fBorg.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.submitRegistrationRequest().
.SS "void org.glite.security.voms.service.registration.VOMSRegistration.submitRegistrationRequestForUser (java.lang.Stringin0, java.lang.Stringin1, \fBorg.glite.security.voms.service.registration.RegistrationRequest\fPin2)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP"
.PP
Implemented in \fBorg.glite.security.voms.service.registration.VOMSRegistrationSoapBindingImpl\fP, \fBorg.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton\fP, and \fBorg.glite.security.voms.service.registration.VOMSRegistrationSoapBindingStub\fP.
.PP
Referenced by org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.submitRegistrationRequestForUser().

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
