.TH "org::glite::security::voms::service::acl::VOMSACLSoapBindingImpl" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org::glite::security::voms::service::acl::VOMSACLSoapBindingImpl \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg.glite.security.voms.service.acl.VOMSACL\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBorg.glite.security.voms.service.acl.ACLEntry\fP[] \fBgetACL\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBsetACL\fP (java.lang.String in0, \fBorg.glite.security.voms.service.acl.ACLEntry\fP[] in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBaddACLEntry\fP (java.lang.String in0, \fBorg.glite.security.voms.service.acl.ACLEntry\fP in1, boolean in2)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBremoveACLEntry\fP (java.lang.String in0, \fBorg.glite.security.voms.service.acl.ACLEntry\fP in1, boolean in2)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.acl.ACLEntry\fP[] \fBgetDefaultACL\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBsetDefaultACL\fP (java.lang.String in0, \fBorg.glite.security.voms.service.acl.ACLEntry\fP[] in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBaddDefaultACLEntry\fP (java.lang.String in0, \fBorg.glite.security.voms.service.acl.ACLEntry\fP in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBremoveDefaultACLEntry\fP (java.lang.String in0, \fBorg.glite.security.voms.service.acl.ACLEntry\fP in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file VOMSACLSoapBindingImpl.java.
.SH "Member Function Documentation"
.PP 
.SS "void org.glite.security.voms.service.acl.VOMSACLSoapBindingImpl.addACLEntry (java.lang.Stringin0, \fBorg.glite.security.voms.service.acl.ACLEntry\fPin1, booleanin2)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.acl.VOMSACL\fP.
.PP
Definition at line 18 of file VOMSACLSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                                        {
    }
.fi
.SS "void org.glite.security.voms.service.acl.VOMSACLSoapBindingImpl.addDefaultACLEntry (java.lang.Stringin0, \fBorg.glite.security.voms.service.acl.ACLEntry\fPin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.acl.VOMSACL\fP.
.PP
Definition at line 31 of file VOMSACLSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                                  {
    }
.fi
.SS "\fBorg.glite.security.voms.service.acl.ACLEntry\fP [] org.glite.security.voms.service.acl.VOMSACLSoapBindingImpl.getACL (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.acl.VOMSACL\fP.
.PP
Definition at line 11 of file VOMSACLSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                              {
        return null;
    }
.fi
.SS "\fBorg.glite.security.voms.service.acl.ACLEntry\fP [] org.glite.security.voms.service.acl.VOMSACLSoapBindingImpl.getDefaultACL (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.acl.VOMSACL\fP.
.PP
Definition at line 24 of file VOMSACLSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                     {
        return null;
    }
.fi
.SS "void org.glite.security.voms.service.acl.VOMSACLSoapBindingImpl.removeACLEntry (java.lang.Stringin0, \fBorg.glite.security.voms.service.acl.ACLEntry\fPin1, booleanin2)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.acl.VOMSACL\fP.
.PP
Definition at line 21 of file VOMSACLSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                                           {
    }
.fi
.SS "void org.glite.security.voms.service.acl.VOMSACLSoapBindingImpl.removeDefaultACLEntry (java.lang.Stringin0, \fBorg.glite.security.voms.service.acl.ACLEntry\fPin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.acl.VOMSACL\fP.
.PP
Definition at line 34 of file VOMSACLSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                                     {
    }
.fi
.SS "void org.glite.security.voms.service.acl.VOMSACLSoapBindingImpl.setACL (java.lang.Stringin0, \fBorg.glite.security.voms.service.acl.ACLEntry\fP[]in1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.acl.VOMSACL\fP.
.PP
Definition at line 15 of file VOMSACLSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                        {
    }
.fi
.SS "void org.glite.security.voms.service.acl.VOMSACLSoapBindingImpl.setDefaultACL (java.lang.Stringin0, \fBorg.glite.security.voms.service.acl.ACLEntry\fP[]in1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.acl.VOMSACL\fP.
.PP
Definition at line 28 of file VOMSACLSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                               {
    }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
