.TH "org::glite::security::voms::service::registration::VOMSRegistrationSoapBindingSkeleton" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org::glite::security::voms::service::registration::VOMSRegistrationSoapBindingSkeleton \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg.glite.security.voms.service.registration.VOMSRegistration\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVOMSRegistrationSoapBindingSkeleton\fP ()"
.br
.ti -1c
.RI "\fBVOMSRegistrationSoapBindingSkeleton\fP (\fBorg.glite.security.voms.service.registration.VOMSRegistration\fP \fBimpl\fP)"
.br
.ti -1c
.RI "void \fBsubmitRegistrationRequest\fP (\fBorg.glite.security.voms.service.registration.RegistrationRequest\fP in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException     "
.br
.ti -1c
.RI "void \fBsubmitRegistrationRequestForUser\fP (java.lang.String in0, java.lang.String in1, \fBorg.glite.security.voms.service.registration.RegistrationRequest\fP in2)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException     "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static java.util.List \fBgetOperationDescByName\fP (java.lang.String methodName)"
.br
.ti -1c
.RI "static java.util.Collection \fBgetOperationDescs\fP ()"
.br
.in -1c
.SS "Static Package Functions"

.in +1c
.ti -1c
.RI "\fB[static initializer]\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBorg.glite.security.voms.service.registration.VOMSRegistration\fP \fBimpl\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static java.util.Map \fB_myOperations\fP = new java.util.Hashtable()"
.br
.ti -1c
.RI "static java.util.Collection \fB_myOperationsList\fP = new java.util.ArrayList()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file VOMSRegistrationSoapBindingSkeleton.java.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.VOMSRegistrationSoapBindingSkeleton ()"
.PP
Definition at line 71 of file VOMSRegistrationSoapBindingSkeleton.java.
.PP
References org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.impl.
.PP
.nf
                                                 {
        this.impl = new org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingImpl();
    }
.fi
.SS "org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.VOMSRegistrationSoapBindingSkeleton (\fBorg.glite.security.voms.service.registration.VOMSRegistration\fPimpl)"
.PP
Definition at line 75 of file VOMSRegistrationSoapBindingSkeleton.java.
.PP
References org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.impl.
.PP
.nf
                                                                                                                   {
        this.impl = impl;
    }
.fi
.SH "Member Function Documentation"
.PP 
.SS "org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.[static initializer] ()\fC [static, package]\fP"
.SS "static java.util.List org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.getOperationDescByName (java.lang.StringmethodName)\fC [static]\fP"Returns List of OperationDesc objects with this name 
.PP
Definition at line 18 of file VOMSRegistrationSoapBindingSkeleton.java.
.PP
References org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton._myOperations.
.PP
.nf
                                                                                     {
        return (java.util.List)_myOperations.get(methodName);
    }
.fi
.SS "static java.util.Collection org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.getOperationDescs ()\fC [static]\fP"Returns Collection of OperationDescs 
.PP
Definition at line 25 of file VOMSRegistrationSoapBindingSkeleton.java.
.PP
References org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton._myOperationsList.
.PP
.nf
                                                           {
        return _myOperationsList;
    }
.fi
.SS "void org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.submitRegistrationRequest (\fBorg.glite.security.voms.service.registration.RegistrationRequest\fPin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP     "
.PP
Implements \fBorg.glite.security.voms.service.registration.VOMSRegistration\fP.
.PP
Definition at line 78 of file VOMSRegistrationSoapBindingSkeleton.java.
.PP
References org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.impl, and org.glite.security.voms.service.registration.VOMSRegistration.submitRegistrationRequest().
.PP
.nf
    {
        impl.submitRegistrationRequest(in0);
    }
.fi
.SS "void org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.submitRegistrationRequestForUser (java.lang.Stringin0, java.lang.Stringin1, \fBorg.glite.security.voms.service.registration.RegistrationRequest\fPin2)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP     "
.PP
Implements \fBorg.glite.security.voms.service.registration.VOMSRegistration\fP.
.PP
Definition at line 83 of file VOMSRegistrationSoapBindingSkeleton.java.
.PP
References org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.impl, and org.glite.security.voms.service.registration.VOMSRegistration.submitRegistrationRequestForUser().
.PP
.nf
    {
        impl.submitRegistrationRequestForUser(in0, in1, in2);
    }
.fi
.SH "Member Data Documentation"
.PP 
.SS "java.util.Map \fBorg.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton._myOperations\fP = new java.util.Hashtable()\fC [static, private]\fP"
.PP
Definition at line 12 of file VOMSRegistrationSoapBindingSkeleton.java.
.PP
Referenced by org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.getOperationDescByName().
.SS "java.util.Collection \fBorg.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton._myOperationsList\fP = new java.util.ArrayList()\fC [static, private]\fP"
.PP
Definition at line 13 of file VOMSRegistrationSoapBindingSkeleton.java.
.PP
Referenced by org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.getOperationDescs().
.SS "\fBorg.glite.security.voms.service.registration.VOMSRegistration\fP \fBorg.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.impl\fP\fC [private]\fP"
.PP
Definition at line 11 of file VOMSRegistrationSoapBindingSkeleton.java.
.PP
Referenced by org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.submitRegistrationRequest(), org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.submitRegistrationRequestForUser(), and org.glite.security.voms.service.registration.VOMSRegistrationSoapBindingSkeleton.VOMSRegistrationSoapBindingSkeleton().

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
