.TH "org::glite::security::voms::service::certificates::VOMSCertificatesSoapBindingImpl" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org::glite::security::voms::service::certificates::VOMSCertificatesSoapBindingImpl \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg.glite.security.voms.service.certificates.VOMSCertificates\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBorg.glite.security.voms.service.certificates.X509Certificate\fP[] \fBgetCertificates\fP (long in0)  throws java.rmi.RemoteException "
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.certificates.X509Certificate\fP[] \fBgetCertificates\fP (java.lang.String in0, java.lang.String in1)  throws java.rmi.RemoteException "
.br
.ti -1c
.RI "long \fBgetUserIdFromDn\fP (java.lang.String in0, java.lang.String in1)  throws java.rmi.RemoteException "
.br
.ti -1c
.RI "void \fBaddCertificate\fP (long in0, \fBorg.glite.security.voms.service.certificates.X509Certificate\fP in1)  throws java.rmi.RemoteException "
.br
.ti -1c
.RI "void \fBaddCertificate\fP (java.lang.String in0, java.lang.String in1, \fBorg.glite.security.voms.service.certificates.X509Certificate\fP in2)  throws java.rmi.RemoteException "
.br
.ti -1c
.RI "void \fBsuspendCertificate\fP (\fBorg.glite.security.voms.service.certificates.X509Certificate\fP in0, java.lang.String in1)  throws java.rmi.RemoteException "
.br
.ti -1c
.RI "void \fBrestoreCertificate\fP (\fBorg.glite.security.voms.service.certificates.X509Certificate\fP in0)  throws java.rmi.RemoteException "
.br
.ti -1c
.RI "void \fBremoveCertificate\fP (\fBorg.glite.security.voms.service.certificates.X509Certificate\fP in0)  throws java.rmi.RemoteException "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file VOMSCertificatesSoapBindingImpl.java.
.SH "Member Function Documentation"
.PP 
.SS "void org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingImpl.addCertificate (longin0, \fBorg.glite.security.voms.service.certificates.X509Certificate\fPin1)  throws java.rmi.RemoteException "
.PP
Implements \fBorg.glite.security.voms.service.certificates.VOMSCertificates\fP.
.PP
Definition at line 23 of file VOMSCertificatesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                           {
    }
.fi
.SS "void org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingImpl.addCertificate (java.lang.Stringin0, java.lang.Stringin1, \fBorg.glite.security.voms.service.certificates.X509Certificate\fPin2)  throws java.rmi.RemoteException "
.PP
Implements \fBorg.glite.security.voms.service.certificates.VOMSCertificates\fP.
.PP
Definition at line 26 of file VOMSCertificatesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                             {
    }
.fi
.SS "\fBorg.glite.security.voms.service.certificates.X509Certificate\fP [] org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingImpl.getCertificates (java.lang.Stringin0, java.lang.Stringin1)  throws java.rmi.RemoteException "
.PP
Implements \fBorg.glite.security.voms.service.certificates.VOMSCertificates\fP.
.PP
Definition at line 15 of file VOMSCertificatesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                      {
        return null;
    }
.fi
.SS "\fBorg.glite.security.voms.service.certificates.X509Certificate\fP [] org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingImpl.getCertificates (longin0)  throws java.rmi.RemoteException "
.PP
Implements \fBorg.glite.security.voms.service.certificates.VOMSCertificates\fP.
.PP
Definition at line 11 of file VOMSCertificatesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                    {
        return null;
    }
.fi
.SS "long org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingImpl.getUserIdFromDn (java.lang.Stringin0, java.lang.Stringin1)  throws java.rmi.RemoteException "
.PP
Implements \fBorg.glite.security.voms.service.certificates.VOMSCertificates\fP.
.PP
Definition at line 19 of file VOMSCertificatesSoapBindingImpl.java.
.PP
.nf
                                                                                                            {
        return -3;
    }
.fi
.SS "void org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingImpl.removeCertificate (\fBorg.glite.security.voms.service.certificates.X509Certificate\fPin0)  throws java.rmi.RemoteException "
.PP
Implements \fBorg.glite.security.voms.service.certificates.VOMSCertificates\fP.
.PP
Definition at line 35 of file VOMSCertificatesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                    {
    }
.fi
.SS "void org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingImpl.restoreCertificate (\fBorg.glite.security.voms.service.certificates.X509Certificate\fPin0)  throws java.rmi.RemoteException "
.PP
Implements \fBorg.glite.security.voms.service.certificates.VOMSCertificates\fP.
.PP
Definition at line 32 of file VOMSCertificatesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                     {
    }
.fi
.SS "void org.glite.security.voms.service.certificates.VOMSCertificatesSoapBindingImpl.suspendCertificate (\fBorg.glite.security.voms.service.certificates.X509Certificate\fPin0, java.lang.Stringin1)  throws java.rmi.RemoteException "
.PP
Implements \fBorg.glite.security.voms.service.certificates.VOMSCertificates\fP.
.PP
Definition at line 29 of file VOMSCertificatesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                           {
    }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
