.TH "org::glite::security::voms::service::compatibility::VOMSCompatibilityServiceLocator" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org::glite::security::voms::service::compatibility::VOMSCompatibilityServiceLocator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg.glite.security.voms.service.compatibility.VOMSCompatibilityService\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVOMSCompatibilityServiceLocator\fP ()"
.br
.ti -1c
.RI "\fBVOMSCompatibilityServiceLocator\fP (org.apache.axis.EngineConfiguration config)"
.br
.ti -1c
.RI "\fBVOMSCompatibilityServiceLocator\fP (java.lang.String wsdlLoc, javax.xml.namespace.QName sName)  throws javax.xml.rpc.ServiceException "
.br
.ti -1c
.RI "java.lang.String \fBgetVOMSCompatibilityAddress\fP ()"
.br
.ti -1c
.RI "java.lang.String \fBgetVOMSCompatibilityWSDDServiceName\fP ()"
.br
.ti -1c
.RI "void \fBsetVOMSCompatibilityWSDDServiceName\fP (java.lang.String name)"
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.compatibility.VOMSCompatibility\fP \fBgetVOMSCompatibility\fP ()  throws javax.xml.rpc.ServiceException "
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.compatibility.VOMSCompatibility\fP \fBgetVOMSCompatibility\fP (java.net.URL portAddress)  throws javax.xml.rpc.ServiceException "
.br
.ti -1c
.RI "void \fBsetVOMSCompatibilityEndpointAddress\fP (java.lang.String address)"
.br
.ti -1c
.RI "java.rmi.Remote \fBgetPort\fP (Class serviceEndpointInterface)  throws javax.xml.rpc.ServiceException "
.br
.ti -1c
.RI "java.rmi.Remote \fBgetPort\fP (javax.xml.namespace.QName portName, Class serviceEndpointInterface)  throws javax.xml.rpc.ServiceException "
.br
.ti -1c
.RI "namespace::QName \fBgetServiceName\fP ()"
.br
.ti -1c
.RI "java.util.Iterator \fBgetPorts\fP ()"
.br
.ti -1c
.RI "void \fBsetEndpointAddress\fP (java.lang.String portName, java.lang.String address)  throws javax.xml.rpc.ServiceException "
.br
.ti -1c
.RI "void \fBsetEndpointAddress\fP (javax.xml.namespace.QName portName, java.lang.String address)  throws javax.xml.rpc.ServiceException "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "java.lang.String \fBVOMSCompatibility_address\fP = 'https://localhost:8443/glite-security-voms-admin-interface/\fBVOMSCompatibility\fP'"
.br
.ti -1c
.RI "java.lang.String \fBVOMSCompatibilityWSDDServiceName\fP = 'VOMSCompatibility'"
.br
.ti -1c
.RI "java.util.HashSet \fBports\fP = null"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file VOMSCompatibilityServiceLocator.java.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.VOMSCompatibilityServiceLocator ()"
.PP
Definition at line 12 of file VOMSCompatibilityServiceLocator.java.
.PP
.nf
                                             {
    }
.fi
.SS "org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.VOMSCompatibilityServiceLocator (org.apache.axis.EngineConfigurationconfig)"
.PP
Definition at line 16 of file VOMSCompatibilityServiceLocator.java.
.PP
.nf
                                                                                       {
        super(config);
    }
.fi
.SS "org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.VOMSCompatibilityServiceLocator (java.lang.StringwsdlLoc, javax.xml.namespace.QNamesName)  throws javax.xml.rpc.ServiceException "
.PP
Definition at line 20 of file VOMSCompatibilityServiceLocator.java.
.PP
.nf
                                                                                                                                            {
        super(wsdlLoc, sName);
    }
.fi
.SH "Member Function Documentation"
.PP 
.SS "java.rmi.Remote org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getPort (ClassserviceEndpointInterface)  throws javax.xml.rpc.ServiceException "For the given interface, get the stub implementation. If this service has no port for the given interface, then ServiceException is thrown. 
.PP
Definition at line 73 of file VOMSCompatibilityServiceLocator.java.
.PP
References org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getVOMSCompatibilityWSDDServiceName(), and org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.VOMSCompatibility_address.
.PP
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getPort().
.PP
.nf
                                                                                                         {
        try {
            if (org.glite.security.voms.service.compatibility.VOMSCompatibility.class.isAssignableFrom(serviceEndpointInterface)) {
                org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub _stub = new org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub(new java.net.URL(VOMSCompatibility_address), this);
                _stub.setPortName(getVOMSCompatibilityWSDDServiceName());
                return _stub;
            }
        }
        catch (java.lang.Throwable t) {
            throw new javax.xml.rpc.ServiceException(t);
        }
        throw new javax.xml.rpc.ServiceException('There is no stub implementation for the interface:  ' + (serviceEndpointInterface == null ? 'null' : serviceEndpointInterface.getName()));
    }
.fi
.SS "java.rmi.Remote org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getPort (javax.xml.namespace.QNameportName, ClassserviceEndpointInterface)  throws javax.xml.rpc.ServiceException "For the given interface, get the stub implementation. If this service has no port for the given interface, then ServiceException is thrown. 
.PP
Definition at line 92 of file VOMSCompatibilityServiceLocator.java.
.PP
References org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getPort(), and org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getVOMSCompatibility().
.PP
.nf
                                                                                                                                             {
        if (portName == null) {
            return getPort(serviceEndpointInterface);
        }
        java.lang.String inputPortName = portName.getLocalPart();
        if ('VOMSCompatibility'.equals(inputPortName)) {
            return getVOMSCompatibility();
        }
        else  {
            java.rmi.Remote _stub = getPort(serviceEndpointInterface);
            ((org.apache.axis.client.Stub) _stub).setPortName(portName);
            return _stub;
        }
    }
.fi
.SS "java.util.Iterator org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getPorts ()"
.PP
Definition at line 113 of file VOMSCompatibilityServiceLocator.java.
.PP
References org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.ports.
.PP
.nf
                                         {
        if (ports == null) {
            ports = new java.util.HashSet();
            ports.add(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.compatibility', 'VOMSCompatibility'));
        }
        return ports.iterator();
    }
.fi
.SS "namespace ::QName org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getServiceName ()"
.PP
Definition at line 107 of file VOMSCompatibilityServiceLocator.java.
.PP
.nf
                                                      {
        return new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.compatibility', 'VOMSCompatibilityService');
    }
.fi
.SS "\fBorg.glite.security.voms.service.compatibility.VOMSCompatibility\fP org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getVOMSCompatibility (java.net.URLportAddress)  throws javax.xml.rpc.ServiceException "
.PP
Implements \fBorg.glite.security.voms.service.compatibility.VOMSCompatibilityService\fP.
.PP
Definition at line 53 of file VOMSCompatibilityServiceLocator.java.
.PP
References org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getVOMSCompatibilityWSDDServiceName().
.PP
.nf
                                                                                                                                                                {
        try {
            org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub _stub = new org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingStub(portAddress, this);
            _stub.setPortName(getVOMSCompatibilityWSDDServiceName());
            return _stub;
        }
        catch (org.apache.axis.AxisFault e) {
            return null;
        }
    }
.fi
.SS "\fBorg.glite.security.voms.service.compatibility.VOMSCompatibility\fP org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getVOMSCompatibility ()  throws javax.xml.rpc.ServiceException "
.PP
Implements \fBorg.glite.security.voms.service.compatibility.VOMSCompatibilityService\fP.
.PP
Definition at line 42 of file VOMSCompatibilityServiceLocator.java.
.PP
References org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.VOMSCompatibility_address.
.PP
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getPort().
.PP
.nf
                                                                                                                                        {
       java.net.URL endpoint;
        try {
            endpoint = new java.net.URL(VOMSCompatibility_address);
        }
        catch (java.net.MalformedURLException e) {
            throw new javax.xml.rpc.ServiceException(e);
        }
        return getVOMSCompatibility(endpoint);
    }
.fi
.SS "java.lang.String org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getVOMSCompatibilityAddress ()"
.PP
Implements \fBorg.glite.security.voms.service.compatibility.VOMSCompatibilityService\fP.
.PP
Definition at line 27 of file VOMSCompatibilityServiceLocator.java.
.PP
References org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.VOMSCompatibility_address.
.PP
.nf
                                                          {
        return VOMSCompatibility_address;
    }
.fi
.SS "java.lang.String org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getVOMSCompatibilityWSDDServiceName ()"
.PP
Definition at line 34 of file VOMSCompatibilityServiceLocator.java.
.PP
References org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.VOMSCompatibilityWSDDServiceName.
.PP
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getPort(), and org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getVOMSCompatibility().
.PP
.nf
                                                                  {
        return VOMSCompatibilityWSDDServiceName;
    }
.fi
.SS "void org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.setEndpointAddress (java.lang.StringportName, java.lang.Stringaddress)  throws javax.xml.rpc.ServiceException "Set the endpoint address for the specified port name. 
.PP
Definition at line 124 of file VOMSCompatibilityServiceLocator.java.
.PP
References org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.setVOMSCompatibilityEndpointAddress().
.PP
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.setEndpointAddress().
.PP
.nf
                                                                                                                              {
        
if ('VOMSCompatibility'.equals(portName)) {
            setVOMSCompatibilityEndpointAddress(address);
        }
        else 
{ // Unknown Port Name
            throw new javax.xml.rpc.ServiceException(' Cannot set Endpoint Address for Unknown Port' + portName);
        }
    }
.fi
.SS "void org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.setEndpointAddress (javax.xml.namespace.QNameportName, java.lang.Stringaddress)  throws javax.xml.rpc.ServiceException "Set the endpoint address for the specified port name. 
.PP
Definition at line 138 of file VOMSCompatibilityServiceLocator.java.
.PP
References org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.setEndpointAddress().
.PP
.nf
                                                                                                                                       {
        setEndpointAddress(portName.getLocalPart(), address);
    }
.fi
.SS "void org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.setVOMSCompatibilityEndpointAddress (java.lang.Stringaddress)"
.PP
Definition at line 64 of file VOMSCompatibilityServiceLocator.java.
.PP
References org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.VOMSCompatibility_address.
.PP
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.setEndpointAddress().
.PP
.nf
                                                                              {
        VOMSCompatibility_address = address;
    }
.fi
.SS "void org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.setVOMSCompatibilityWSDDServiceName (java.lang.Stringname)"
.PP
Definition at line 38 of file VOMSCompatibilityServiceLocator.java.
.PP
References org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.VOMSCompatibilityWSDDServiceName.
.PP
.nf
                                                                           {
        VOMSCompatibilityWSDDServiceName = name;
    }
.fi
.SH "Member Data Documentation"
.PP 
.SS "java.util.HashSet \fBorg.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.ports\fP = null\fC [private]\fP"
.PP
Definition at line 111 of file VOMSCompatibilityServiceLocator.java.
.PP
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getPorts().
.SS "java.lang.String \fBorg.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.VOMSCompatibility_address\fP = 'https://localhost:8443/glite-security-voms-admin-interface/\fBVOMSCompatibility\fP'\fC [private]\fP"
.PP
Definition at line 25 of file VOMSCompatibilityServiceLocator.java.
.PP
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getPort(), org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getVOMSCompatibility(), org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getVOMSCompatibilityAddress(), and org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.setVOMSCompatibilityEndpointAddress().
.SS "java.lang.String \fBorg.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.VOMSCompatibilityWSDDServiceName\fP = 'VOMSCompatibility'\fC [private]\fP"
.PP
Definition at line 32 of file VOMSCompatibilityServiceLocator.java.
.PP
Referenced by org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.getVOMSCompatibilityWSDDServiceName(), and org.glite.security.voms.service.compatibility.VOMSCompatibilityServiceLocator.setVOMSCompatibilityWSDDServiceName().

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
