.TH "org::glite::security::voms::service::compatibility::VOMSCompatibilitySoapBindingImpl" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org::glite::security::voms::service::compatibility::VOMSCompatibilitySoapBindingImpl \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg.glite.security.voms.service.compatibility.VOMSCompatibility\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBgetMajorVersionNumber\fP ()  throws java.rmi.RemoteException "
.br
.ti -1c
.RI "int \fBgetMinorVersionNumber\fP ()  throws java.rmi.RemoteException "
.br
.ti -1c
.RI "int \fBgetPatchVersionNumber\fP ()  throws java.rmi.RemoteException "
.br
.ti -1c
.RI "java.lang.String[] \fBgetGridmapUsers\fP ()  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "java.lang.String[] \fBgetGridmapUsers\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file VOMSCompatibilitySoapBindingImpl.java.
.SH "Member Function Documentation"
.PP 
.SS "java.lang.String [] org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingImpl.getGridmapUsers ()  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.compatibility.VOMSCompatibility\fP.
.PP
Definition at line 23 of file VOMSCompatibilitySoapBindingImpl.java.
.PP
.nf
                                                                                                                       {
        return null;
    }
.fi
.SS "java.lang.String [] org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingImpl.getGridmapUsers (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.compatibility.VOMSCompatibility\fP.
.PP
Definition at line 27 of file VOMSCompatibilitySoapBindingImpl.java.
.PP
.nf
                                                                                                                                           {
        return null;
    }
.fi
.SS "int org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingImpl.getMajorVersionNumber ()  throws java.rmi.RemoteException "
.PP
Implements \fBorg.glite.security.voms.service.compatibility.VOMSCompatibility\fP.
.PP
Definition at line 11 of file VOMSCompatibilitySoapBindingImpl.java.
.PP
.nf
                                                                       {
        return -3;
    }
.fi
.SS "int org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingImpl.getMinorVersionNumber ()  throws java.rmi.RemoteException "
.PP
Implements \fBorg.glite.security.voms.service.compatibility.VOMSCompatibility\fP.
.PP
Definition at line 15 of file VOMSCompatibilitySoapBindingImpl.java.
.PP
.nf
                                                                       {
        return -3;
    }
.fi
.SS "int org.glite.security.voms.service.compatibility.VOMSCompatibilitySoapBindingImpl.getPatchVersionNumber ()  throws java.rmi.RemoteException "
.PP
Implements \fBorg.glite.security.voms.service.compatibility.VOMSCompatibility\fP.
.PP
Definition at line 19 of file VOMSCompatibilitySoapBindingImpl.java.
.PP
.nf
                                                                       {
        return -3;
    }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
