.TH "org::glite::security::voms::service::admin::VOMSAdminService" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org::glite::security::voms::service::admin::VOMSAdminService \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBorg.glite.security.voms.service.admin.VOMSAdminServiceLocator\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "java.lang.String \fBgetVOMSAdminAddress\fP ()"
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.admin.VOMSAdmin\fP \fBgetVOMSAdmin\fP ()  throws javax.xml.rpc.ServiceException"
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.admin.VOMSAdmin\fP \fBgetVOMSAdmin\fP (java.net.URL portAddress)  throws javax.xml.rpc.ServiceException"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file VOMSAdminService.java.
.SH "Member Function Documentation"
.PP 
.SS "\fBorg.glite.security.voms.service.admin.VOMSAdmin\fP org.glite.security.voms.service.admin.VOMSAdminService.getVOMSAdmin ()  throws javax.xml.rpc.ServiceException"
.PP
Implemented in \fBorg.glite.security.voms.service.admin.VOMSAdminServiceLocator\fP.
.SS "\fBorg.glite.security.voms.service.admin.VOMSAdmin\fP org.glite.security.voms.service.admin.VOMSAdminService.getVOMSAdmin (java.net.URLportAddress)  throws javax.xml.rpc.ServiceException"
.PP
Implemented in \fBorg.glite.security.voms.service.admin.VOMSAdminServiceLocator\fP.
.SS "java.lang.String org.glite.security.voms.service.admin.VOMSAdminService.getVOMSAdminAddress ()"
.PP
Implemented in \fBorg.glite.security.voms.service.admin.VOMSAdminServiceLocator\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
