.TH "org::glite::security::voms::service::attributes::VOMSAttributesSoapBindingImpl" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org::glite::security::voms::service::attributes::VOMSAttributesSoapBindingImpl \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBcreateAttributeClass\fP (java.lang.String in0, java.lang.String in1, boolean in2)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBcreateAttributeClass\fP (java.lang.String in0, java.lang.String in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBcreateAttributeClass\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.attributes.AttributeClass\fP \fBgetAttributeClass\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBsaveAttributeClass\fP (\fBorg.glite.security.voms.service.attributes.AttributeClass\fP in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBdeleteAttributeClass\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBdeleteAttributeClass\fP (\fBorg.glite.security.voms.service.attributes.AttributeClass\fP in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.attributes.AttributeClass\fP[] \fBlistAttributeClasses\fP ()  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.attributes.AttributeValue\fP[] \fBlistUserAttributes\fP (\fBorg.glite.security.voms.User\fP in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBsetUserAttribute\fP (\fBorg.glite.security.voms.User\fP in0, \fBorg.glite.security.voms.service.attributes.AttributeValue\fP in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBdeleteUserAttribute\fP (\fBorg.glite.security.voms.User\fP in0, java.lang.String in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBdeleteUserAttribute\fP (\fBorg.glite.security.voms.User\fP in0, \fBorg.glite.security.voms.service.attributes.AttributeValue\fP in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBsetGroupAttribute\fP (java.lang.String in0, \fBorg.glite.security.voms.service.attributes.AttributeValue\fP in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBdeleteGroupAttribute\fP (java.lang.String in0, java.lang.String in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBdeleteGroupAttribute\fP (java.lang.String in0, \fBorg.glite.security.voms.service.attributes.AttributeValue\fP in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.attributes.AttributeValue\fP[] \fBlistGroupAttributes\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBsetRoleAttribute\fP (java.lang.String in0, java.lang.String in1, \fBorg.glite.security.voms.service.attributes.AttributeValue\fP in2)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBdeleteRoleAttribute\fP (java.lang.String in0, java.lang.String in1, java.lang.String in2)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBdeleteRoleAttribute\fP (java.lang.String in0, java.lang.String in1, \fBorg.glite.security.voms.service.attributes.AttributeValue\fP in2)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.attributes.AttributeValue\fP[] \fBlistRoleAttributes\fP (java.lang.String in0, java.lang.String in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file VOMSAttributesSoapBindingImpl.java.
.SH "Member Function Documentation"
.PP 
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl.createAttributeClass (java.lang.Stringin0, java.lang.Stringin1, booleanin2)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 11 of file VOMSAttributesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                     {
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl.createAttributeClass (java.lang.Stringin0, java.lang.Stringin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 14 of file VOMSAttributesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                        {
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl.createAttributeClass (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 17 of file VOMSAttributesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                  {
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl.deleteAttributeClass (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 27 of file VOMSAttributesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                  {
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl.deleteAttributeClass (\fBorg.glite.security.voms.service.attributes.AttributeClass\fPin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 30 of file VOMSAttributesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                           {
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl.deleteGroupAttribute (java.lang.Stringin0, java.lang.Stringin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 53 of file VOMSAttributesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                        {
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl.deleteGroupAttribute (java.lang.Stringin0, \fBorg.glite.security.voms.service.attributes.AttributeValue\fPin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 56 of file VOMSAttributesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                                                 {
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl.deleteRoleAttribute (java.lang.Stringin0, java.lang.Stringin1, java.lang.Stringin2)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 66 of file VOMSAttributesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                             {
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl.deleteRoleAttribute (java.lang.Stringin0, java.lang.Stringin1, \fBorg.glite.security.voms.service.attributes.AttributeValue\fPin2)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 69 of file VOMSAttributesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                                                                      {
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl.deleteUserAttribute (\fBorg.glite.security.voms.User\fPin0, java.lang.Stringin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 44 of file VOMSAttributesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                   {
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl.deleteUserAttribute (\fBorg.glite.security.voms.User\fPin0, \fBorg.glite.security.voms.service.attributes.AttributeValue\fPin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 47 of file VOMSAttributesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                                                            {
    }
.fi
.SS "\fBorg.glite.security.voms.service.attributes.AttributeClass\fP org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl.getAttributeClass (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 20 of file VOMSAttributesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                                    {
        return null;
    }
.fi
.SS "\fBorg.glite.security.voms.service.attributes.AttributeClass\fP [] org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl.listAttributeClasses ()  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 33 of file VOMSAttributesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                     {
        return null;
    }
.fi
.SS "\fBorg.glite.security.voms.service.attributes.AttributeValue\fP [] org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl.listGroupAttributes (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 59 of file VOMSAttributesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                                        {
        return null;
    }
.fi
.SS "\fBorg.glite.security.voms.service.attributes.AttributeValue\fP [] org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl.listRoleAttributes (java.lang.Stringin0, java.lang.Stringin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 72 of file VOMSAttributesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                                                             {
        return null;
    }
.fi
.SS "\fBorg.glite.security.voms.service.attributes.AttributeValue\fP [] org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl.listUserAttributes (\fBorg.glite.security.voms.User\fPin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 37 of file VOMSAttributesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                                                   {
        return null;
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl.saveAttributeClass (\fBorg.glite.security.voms.service.attributes.AttributeClass\fPin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 24 of file VOMSAttributesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                         {
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl.setGroupAttribute (java.lang.Stringin0, \fBorg.glite.security.voms.service.attributes.AttributeValue\fPin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 50 of file VOMSAttributesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                                              {
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl.setRoleAttribute (java.lang.Stringin0, java.lang.Stringin1, \fBorg.glite.security.voms.service.attributes.AttributeValue\fPin2)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 63 of file VOMSAttributesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                                                                   {
    }
.fi
.SS "void org.glite.security.voms.service.attributes.VOMSAttributesSoapBindingImpl.setUserAttribute (\fBorg.glite.security.voms.User\fPin0, \fBorg.glite.security.voms.service.attributes.AttributeValue\fPin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP.
.PP
Definition at line 41 of file VOMSAttributesSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                                                         {
    }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
