.TH "org::glite::security::voms::service::registration::VOMSRegistrationService" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org::glite::security::voms::service::registration::VOMSRegistrationService \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBorg.glite.security.voms.service.registration.VOMSRegistrationServiceLocator\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "java.lang.String \fBgetVOMSRegistrationAddress\fP ()"
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.registration.VOMSRegistration\fP \fBgetVOMSRegistration\fP ()  throws javax.xml.rpc.ServiceException"
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.registration.VOMSRegistration\fP \fBgetVOMSRegistration\fP (java.net.URL portAddress)  throws javax.xml.rpc.ServiceException"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file VOMSRegistrationService.java.
.SH "Member Function Documentation"
.PP 
.SS "\fBorg.glite.security.voms.service.registration.VOMSRegistration\fP org.glite.security.voms.service.registration.VOMSRegistrationService.getVOMSRegistration ()  throws javax.xml.rpc.ServiceException"
.PP
Implemented in \fBorg.glite.security.voms.service.registration.VOMSRegistrationServiceLocator\fP.
.SS "\fBorg.glite.security.voms.service.registration.VOMSRegistration\fP org.glite.security.voms.service.registration.VOMSRegistrationService.getVOMSRegistration (java.net.URLportAddress)  throws javax.xml.rpc.ServiceException"
.PP
Implemented in \fBorg.glite.security.voms.service.registration.VOMSRegistrationServiceLocator\fP.
.SS "java.lang.String org.glite.security.voms.service.registration.VOMSRegistrationService.getVOMSRegistrationAddress ()"
.PP
Implemented in \fBorg.glite.security.voms.service.registration.VOMSRegistrationServiceLocator\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
