.TH "org::glite::security::voms::service::admin::VOMSAdminSoapBindingImpl" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org::glite::security::voms::service::admin::VOMSAdminSoapBindingImpl \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBcreateGroup\fP (java.lang.String in0, java.lang.String in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "\fBorg.glite.security.voms.User\fP \fBgetUser\fP (java.lang.String in0, java.lang.String in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBsetUser\fP (\fBorg.glite.security.voms.User\fP in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "int \fBgetMajorVersionNumber\fP ()  throws java.rmi.RemoteException "
.br
.ti -1c
.RI "java.lang.String \fBgetVOName\fP ()  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBcreateUser\fP (\fBorg.glite.security.voms.User\fP in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBdeleteUser\fP (java.lang.String in0, java.lang.String in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBdeleteGroup\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBcreateRole\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBdeleteRole\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBcreateCapability\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBdeleteCapability\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBaddMember\fP (java.lang.String in0, java.lang.String in1, java.lang.String in2)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBremoveMember\fP (java.lang.String in0, java.lang.String in1, java.lang.String in2)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBassignRole\fP (java.lang.String in0, java.lang.String in1, java.lang.String in2, java.lang.String in3)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBdismissRole\fP (java.lang.String in0, java.lang.String in1, java.lang.String in2, java.lang.String in3)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBassignCapability\fP (java.lang.String in0, java.lang.String in1, java.lang.String in2)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBdismissCapability\fP (java.lang.String in0, java.lang.String in1, java.lang.String in2)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "\fBorg.glite.security.voms.User\fP[] \fBlistMembers\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "\fBorg.glite.security.voms.User\fP[] \fBlistUsersWithRole\fP (java.lang.String in0, java.lang.String in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "\fBorg.glite.security.voms.User\fP[] \fBlistUsersWithCapability\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "java.lang.String[] \fBgetGroupPath\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "java.lang.String[] \fBlistSubGroups\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "java.lang.String[] \fBlistGroups\fP (java.lang.String in0, java.lang.String in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "java.lang.String[] \fBlistRoles\fP ()  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "java.lang.String[] \fBlistRoles\fP (java.lang.String in0, java.lang.String in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "java.lang.String[] \fBlistCapabilities\fP ()  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "java.lang.String[] \fBlistCapabilities\fP (java.lang.String in0, java.lang.String in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "java.lang.String[] \fBlistCAs\fP ()  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "\fBorg.glite.security.voms.ACLEntry\fP[] \fBgetACL\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBsetACL\fP (java.lang.String in0, \fBorg.glite.security.voms.ACLEntry\fP[] in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBaddACLEntry\fP (java.lang.String in0, \fBorg.glite.security.voms.ACLEntry\fP in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBremoveACLEntry\fP (java.lang.String in0, \fBorg.glite.security.voms.ACLEntry\fP in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "\fBorg.glite.security.voms.ACLEntry\fP[] \fBgetDefaultACL\fP (java.lang.String in0)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBsetDefaultACL\fP (java.lang.String in0, \fBorg.glite.security.voms.ACLEntry\fP[] in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBaddDefaultACLEntry\fP (java.lang.String in0, \fBorg.glite.security.voms.ACLEntry\fP in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "void \fBremoveDefaultACLEntry\fP (java.lang.String in0, \fBorg.glite.security.voms.ACLEntry\fP in1)  throws java.rmi.RemoteException, org.glite.security.voms.VOMSException "
.br
.ti -1c
.RI "int \fBgetMinorVersionNumber\fP ()  throws java.rmi.RemoteException "
.br
.ti -1c
.RI "int \fBgetPatchVersionNumber\fP ()  throws java.rmi.RemoteException "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file VOMSAdminSoapBindingImpl.java.
.SH "Member Function Documentation"
.PP 
.SS "void org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.addACLEntry (java.lang.Stringin0, \fBorg.glite.security.voms.ACLEntry\fPin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 119 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                               {
    }
.fi
.SS "void org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.addDefaultACLEntry (java.lang.Stringin0, \fBorg.glite.security.voms.ACLEntry\fPin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 132 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                      {
    }
.fi
.SS "void org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.addMember (java.lang.Stringin0, java.lang.Stringin1, java.lang.Stringin2)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 50 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                   {
    }
.fi
.SS "void org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.assignCapability (java.lang.Stringin0, java.lang.Stringin1, java.lang.Stringin2)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 62 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                          {
    }
.fi
.SS "void org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.assignRole (java.lang.Stringin0, java.lang.Stringin1, java.lang.Stringin2, java.lang.Stringin3)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 56 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                                          {
    }
.fi
.SS "void org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.createCapability (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 44 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                              {
    }
.fi
.SS "void org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.createGroup (java.lang.Stringin0, java.lang.Stringin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 11 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                               {
    }
.fi
.SS "void org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.createRole (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 38 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                        {
    }
.fi
.SS "void org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.createUser (\fBorg.glite.security.voms.User\fPin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 29 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                    {
    }
.fi
.SS "void org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.deleteCapability (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 47 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                              {
    }
.fi
.SS "void org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.deleteGroup (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 35 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                         {
    }
.fi
.SS "void org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.deleteRole (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 41 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                        {
    }
.fi
.SS "void org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.deleteUser (java.lang.Stringin0, java.lang.Stringin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 32 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                              {
    }
.fi
.SS "void org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.dismissCapability (java.lang.Stringin0, java.lang.Stringin1, java.lang.Stringin2)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 65 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                           {
    }
.fi
.SS "void org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.dismissRole (java.lang.Stringin0, java.lang.Stringin1, java.lang.Stringin2, java.lang.Stringin3)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 59 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                                           {
    }
.fi
.SS "\fBorg.glite.security.voms.ACLEntry\fP [] org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.getACL (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 112 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                  {
        return null;
    }
.fi
.SS "\fBorg.glite.security.voms.ACLEntry\fP [] org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.getDefaultACL (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 125 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                         {
        return null;
    }
.fi
.SS "java.lang.String [] org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.getGroupPath (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 80 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                        {
        return null;
    }
.fi
.SS "int org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.getMajorVersionNumber ()  throws java.rmi.RemoteException "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 21 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                       {
        return -3;
    }
.fi
.SS "int org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.getMinorVersionNumber ()  throws java.rmi.RemoteException "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 138 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                       {
        return -3;
    }
.fi
.SS "int org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.getPatchVersionNumber ()  throws java.rmi.RemoteException "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 142 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                       {
        return -3;
    }
.fi
.SS "\fBorg.glite.security.voms.User\fP org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.getUser (java.lang.Stringin0, java.lang.Stringin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 14 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                   {
        return null;
    }
.fi
.SS "java.lang.String org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.getVOName ()  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 25 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                               {
        return null;
    }
.fi
.SS "java.lang.String [] org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.listCapabilities ()  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 100 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                        {
        return null;
    }
.fi
.SS "java.lang.String [] org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.listCapabilities (java.lang.Stringin0, java.lang.Stringin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 104 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                  {
        return null;
    }
.fi
.SS "java.lang.String [] org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.listCAs ()  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 108 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                               {
        return null;
    }
.fi
.SS "java.lang.String [] org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.listGroups (java.lang.Stringin0, java.lang.Stringin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 88 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                            {
        return null;
    }
.fi
.SS "\fBorg.glite.security.voms.User\fP [] org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.listMembers (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 68 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                   {
        return null;
    }
.fi
.SS "java.lang.String [] org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.listRoles (java.lang.Stringin0, java.lang.Stringin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 96 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                           {
        return null;
    }
.fi
.SS "java.lang.String [] org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.listRoles ()  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 92 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                 {
        return null;
    }
.fi
.SS "java.lang.String [] org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.listSubGroups (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 84 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                         {
        return null;
    }
.fi
.SS "\fBorg.glite.security.voms.User\fP [] org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.listUsersWithCapability (java.lang.Stringin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 76 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                               {
        return null;
    }
.fi
.SS "\fBorg.glite.security.voms.User\fP [] org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.listUsersWithRole (java.lang.Stringin0, java.lang.Stringin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 72 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                               {
        return null;
    }
.fi
.SS "void org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.removeACLEntry (java.lang.Stringin0, \fBorg.glite.security.voms.ACLEntry\fPin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 122 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                  {
    }
.fi
.SS "void org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.removeDefaultACLEntry (java.lang.Stringin0, \fBorg.glite.security.voms.ACLEntry\fPin1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 135 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                         {
    }
.fi
.SS "void org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.removeMember (java.lang.Stringin0, java.lang.Stringin1, java.lang.Stringin2)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 53 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                      {
    }
.fi
.SS "void org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.setACL (java.lang.Stringin0, \fBorg.glite.security.voms.ACLEntry\fP[]in1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 116 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                            {
    }
.fi
.SS "void org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.setDefaultACL (java.lang.Stringin0, \fBorg.glite.security.voms.ACLEntry\fP[]in1)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 129 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                                                   {
    }
.fi
.SS "void org.glite.security.voms.service.admin.VOMSAdminSoapBindingImpl.setUser (\fBorg.glite.security.voms.User\fPin0)  throws java.rmi.RemoteException, \fBorg.glite.security.voms.VOMSException\fP "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdmin\fP.
.PP
Definition at line 18 of file VOMSAdminSoapBindingImpl.java.
.PP
.nf
                                                                                                                                 {
    }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
