.TH "org::glite::security::voms::service::admin::VOMSAdminServiceLocator" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org::glite::security::voms::service::admin::VOMSAdminServiceLocator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg.glite.security.voms.service.admin.VOMSAdminService\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVOMSAdminServiceLocator\fP ()"
.br
.ti -1c
.RI "\fBVOMSAdminServiceLocator\fP (org.apache.axis.EngineConfiguration config)"
.br
.ti -1c
.RI "\fBVOMSAdminServiceLocator\fP (java.lang.String wsdlLoc, javax.xml.namespace.QName sName)  throws javax.xml.rpc.ServiceException "
.br
.ti -1c
.RI "java.lang.String \fBgetVOMSAdminAddress\fP ()"
.br
.ti -1c
.RI "java.lang.String \fBgetVOMSAdminWSDDServiceName\fP ()"
.br
.ti -1c
.RI "void \fBsetVOMSAdminWSDDServiceName\fP (java.lang.String name)"
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.admin.VOMSAdmin\fP \fBgetVOMSAdmin\fP ()  throws javax.xml.rpc.ServiceException "
.br
.ti -1c
.RI "\fBorg.glite.security.voms.service.admin.VOMSAdmin\fP \fBgetVOMSAdmin\fP (java.net.URL portAddress)  throws javax.xml.rpc.ServiceException "
.br
.ti -1c
.RI "void \fBsetVOMSAdminEndpointAddress\fP (java.lang.String address)"
.br
.ti -1c
.RI "java.rmi.Remote \fBgetPort\fP (Class serviceEndpointInterface)  throws javax.xml.rpc.ServiceException "
.br
.ti -1c
.RI "java.rmi.Remote \fBgetPort\fP (javax.xml.namespace.QName portName, Class serviceEndpointInterface)  throws javax.xml.rpc.ServiceException "
.br
.ti -1c
.RI "namespace::QName \fBgetServiceName\fP ()"
.br
.ti -1c
.RI "java.util.Iterator \fBgetPorts\fP ()"
.br
.ti -1c
.RI "void \fBsetEndpointAddress\fP (java.lang.String portName, java.lang.String address)  throws javax.xml.rpc.ServiceException "
.br
.ti -1c
.RI "void \fBsetEndpointAddress\fP (javax.xml.namespace.QName portName, java.lang.String address)  throws javax.xml.rpc.ServiceException "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "java.lang.String \fBVOMSAdmin_address\fP = 'https://localhost:8443/glite-security-voms-admin-interface/\fBVOMSAdmin\fP'"
.br
.ti -1c
.RI "java.lang.String \fBVOMSAdminWSDDServiceName\fP = 'VOMSAdmin'"
.br
.ti -1c
.RI "java.util.HashSet \fBports\fP = null"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file VOMSAdminServiceLocator.java.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org.glite.security.voms.service.admin.VOMSAdminServiceLocator.VOMSAdminServiceLocator ()"
.PP
Definition at line 12 of file VOMSAdminServiceLocator.java.
.PP
.nf
                                     {
    }
.fi
.SS "org.glite.security.voms.service.admin.VOMSAdminServiceLocator.VOMSAdminServiceLocator (org.apache.axis.EngineConfigurationconfig)"
.PP
Definition at line 16 of file VOMSAdminServiceLocator.java.
.PP
.nf
                                                                               {
        super(config);
    }
.fi
.SS "org.glite.security.voms.service.admin.VOMSAdminServiceLocator.VOMSAdminServiceLocator (java.lang.StringwsdlLoc, javax.xml.namespace.QNamesName)  throws javax.xml.rpc.ServiceException "
.PP
Definition at line 20 of file VOMSAdminServiceLocator.java.
.PP
.nf
                                                                                                                                    {
        super(wsdlLoc, sName);
    }
.fi
.SH "Member Function Documentation"
.PP 
.SS "java.rmi.Remote org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getPort (ClassserviceEndpointInterface)  throws javax.xml.rpc.ServiceException "For the given interface, get the stub implementation. If this service has no port for the given interface, then ServiceException is thrown. 
.PP
Definition at line 73 of file VOMSAdminServiceLocator.java.
.PP
References org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getVOMSAdminWSDDServiceName(), and org.glite.security.voms.service.admin.VOMSAdminServiceLocator.VOMSAdmin_address.
.PP
Referenced by org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getPort().
.PP
.nf
                                                                                                         {
        try {
            if (org.glite.security.voms.service.admin.VOMSAdmin.class.isAssignableFrom(serviceEndpointInterface)) {
                org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub _stub = new org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub(new java.net.URL(VOMSAdmin_address), this);
                _stub.setPortName(getVOMSAdminWSDDServiceName());
                return _stub;
            }
        }
        catch (java.lang.Throwable t) {
            throw new javax.xml.rpc.ServiceException(t);
        }
        throw new javax.xml.rpc.ServiceException('There is no stub implementation for the interface:  ' + (serviceEndpointInterface == null ? 'null' : serviceEndpointInterface.getName()));
    }
.fi
.SS "java.rmi.Remote org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getPort (javax.xml.namespace.QNameportName, ClassserviceEndpointInterface)  throws javax.xml.rpc.ServiceException "For the given interface, get the stub implementation. If this service has no port for the given interface, then ServiceException is thrown. 
.PP
Definition at line 92 of file VOMSAdminServiceLocator.java.
.PP
References org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getPort(), and org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getVOMSAdmin().
.PP
.nf
                                                                                                                                             {
        if (portName == null) {
            return getPort(serviceEndpointInterface);
        }
        java.lang.String inputPortName = portName.getLocalPart();
        if ('VOMSAdmin'.equals(inputPortName)) {
            return getVOMSAdmin();
        }
        else  {
            java.rmi.Remote _stub = getPort(serviceEndpointInterface);
            ((org.apache.axis.client.Stub) _stub).setPortName(portName);
            return _stub;
        }
    }
.fi
.SS "java.util.Iterator org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getPorts ()"
.PP
Definition at line 113 of file VOMSAdminServiceLocator.java.
.PP
References org.glite.security.voms.service.admin.VOMSAdminServiceLocator.ports.
.PP
.nf
                                         {
        if (ports == null) {
            ports = new java.util.HashSet();
            ports.add(new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.admin', 'VOMSAdmin'));
        }
        return ports.iterator();
    }
.fi
.SS "namespace ::QName org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getServiceName ()"
.PP
Definition at line 107 of file VOMSAdminServiceLocator.java.
.PP
.nf
                                                      {
        return new javax.xml.namespace.QName('http://glite.org/wsdl/services/org.glite.security.voms.service.admin', 'VOMSAdminService');
    }
.fi
.SS "\fBorg.glite.security.voms.service.admin.VOMSAdmin\fP org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getVOMSAdmin (java.net.URLportAddress)  throws javax.xml.rpc.ServiceException "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdminService\fP.
.PP
Definition at line 53 of file VOMSAdminServiceLocator.java.
.PP
References org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getVOMSAdminWSDDServiceName().
.PP
.nf
                                                                                                                                        {
        try {
            org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub _stub = new org.glite.security.voms.service.admin.VOMSAdminSoapBindingStub(portAddress, this);
            _stub.setPortName(getVOMSAdminWSDDServiceName());
            return _stub;
        }
        catch (org.apache.axis.AxisFault e) {
            return null;
        }
    }
.fi
.SS "\fBorg.glite.security.voms.service.admin.VOMSAdmin\fP org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getVOMSAdmin ()  throws javax.xml.rpc.ServiceException "
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdminService\fP.
.PP
Definition at line 42 of file VOMSAdminServiceLocator.java.
.PP
References org.glite.security.voms.service.admin.VOMSAdminServiceLocator.VOMSAdmin_address.
.PP
Referenced by org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getPort(), and portal.registration.utils.VOMSAdminCallOut.getUserFQANs().
.PP
.nf
                                                                                                                {
       java.net.URL endpoint;
        try {
            endpoint = new java.net.URL(VOMSAdmin_address);
        }
        catch (java.net.MalformedURLException e) {
            throw new javax.xml.rpc.ServiceException(e);
        }
        return getVOMSAdmin(endpoint);
    }
.fi
.SS "java.lang.String org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getVOMSAdminAddress ()"
.PP
Implements \fBorg.glite.security.voms.service.admin.VOMSAdminService\fP.
.PP
Definition at line 27 of file VOMSAdminServiceLocator.java.
.PP
References org.glite.security.voms.service.admin.VOMSAdminServiceLocator.VOMSAdmin_address.
.PP
.nf
                                                  {
        return VOMSAdmin_address;
    }
.fi
.SS "java.lang.String org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getVOMSAdminWSDDServiceName ()"
.PP
Definition at line 34 of file VOMSAdminServiceLocator.java.
.PP
References org.glite.security.voms.service.admin.VOMSAdminServiceLocator.VOMSAdminWSDDServiceName.
.PP
Referenced by org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getPort(), and org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getVOMSAdmin().
.PP
.nf
                                                          {
        return VOMSAdminWSDDServiceName;
    }
.fi
.SS "void org.glite.security.voms.service.admin.VOMSAdminServiceLocator.setEndpointAddress (java.lang.StringportName, java.lang.Stringaddress)  throws javax.xml.rpc.ServiceException "Set the endpoint address for the specified port name. 
.PP
Definition at line 124 of file VOMSAdminServiceLocator.java.
.PP
References org.glite.security.voms.service.admin.VOMSAdminServiceLocator.setVOMSAdminEndpointAddress().
.PP
Referenced by org.glite.security.voms.service.admin.VOMSAdminServiceLocator.setEndpointAddress().
.PP
.nf
                                                                                                                              {
        
if ('VOMSAdmin'.equals(portName)) {
            setVOMSAdminEndpointAddress(address);
        }
        else 
{ // Unknown Port Name
            throw new javax.xml.rpc.ServiceException(' Cannot set Endpoint Address for Unknown Port' + portName);
        }
    }
.fi
.SS "void org.glite.security.voms.service.admin.VOMSAdminServiceLocator.setEndpointAddress (javax.xml.namespace.QNameportName, java.lang.Stringaddress)  throws javax.xml.rpc.ServiceException "Set the endpoint address for the specified port name. 
.PP
Definition at line 138 of file VOMSAdminServiceLocator.java.
.PP
References org.glite.security.voms.service.admin.VOMSAdminServiceLocator.setEndpointAddress().
.PP
.nf
                                                                                                                                       {
        setEndpointAddress(portName.getLocalPart(), address);
    }
.fi
.SS "void org.glite.security.voms.service.admin.VOMSAdminServiceLocator.setVOMSAdminEndpointAddress (java.lang.Stringaddress)"
.PP
Definition at line 64 of file VOMSAdminServiceLocator.java.
.PP
References org.glite.security.voms.service.admin.VOMSAdminServiceLocator.VOMSAdmin_address.
.PP
Referenced by org.glite.security.voms.service.admin.VOMSAdminServiceLocator.setEndpointAddress().
.PP
.nf
                                                                      {
        VOMSAdmin_address = address;
    }
.fi
.SS "void org.glite.security.voms.service.admin.VOMSAdminServiceLocator.setVOMSAdminWSDDServiceName (java.lang.Stringname)"
.PP
Definition at line 38 of file VOMSAdminServiceLocator.java.
.PP
References org.glite.security.voms.service.admin.VOMSAdminServiceLocator.VOMSAdminWSDDServiceName.
.PP
.nf
                                                                   {
        VOMSAdminWSDDServiceName = name;
    }
.fi
.SH "Member Data Documentation"
.PP 
.SS "java.util.HashSet \fBorg.glite.security.voms.service.admin.VOMSAdminServiceLocator.ports\fP = null\fC [private]\fP"
.PP
Definition at line 111 of file VOMSAdminServiceLocator.java.
.PP
Referenced by org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getPorts().
.SS "java.lang.String \fBorg.glite.security.voms.service.admin.VOMSAdminServiceLocator.VOMSAdmin_address\fP = 'https://localhost:8443/glite-security-voms-admin-interface/\fBVOMSAdmin\fP'\fC [private]\fP"
.PP
Definition at line 25 of file VOMSAdminServiceLocator.java.
.PP
Referenced by org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getPort(), org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getVOMSAdmin(), org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getVOMSAdminAddress(), and org.glite.security.voms.service.admin.VOMSAdminServiceLocator.setVOMSAdminEndpointAddress().
.SS "java.lang.String \fBorg.glite.security.voms.service.admin.VOMSAdminServiceLocator.VOMSAdminWSDDServiceName\fP = 'VOMSAdmin'\fC [private]\fP"
.PP
Definition at line 32 of file VOMSAdminServiceLocator.java.
.PP
Referenced by org.glite.security.voms.service.admin.VOMSAdminServiceLocator.getVOMSAdminWSDDServiceName(), and org.glite.security.voms.service.admin.VOMSAdminServiceLocator.setVOMSAdminWSDDServiceName().

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
