.TH "portal::registration::dao::FqanDAO" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
portal::registration::dao::FqanDAO \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBportal.registration.dao.FqanDAOImpl\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsave\fP (\fBFqan\fP transientInstance)"
.br
.ti -1c
.RI "void \fBdelete\fP (\fBFqan\fP persistentInstance)"
.br
.ti -1c
.RI "\fBFqan\fP \fBfindById\fP (Integer id)"
.br
.ti -1c
.RI "List< \fBFqan\fP > \fBgetAllFqan\fP ()"
.br
.ti -1c
.RI "List< \fBFqan\fP > \fBfindByIdVo\fP (Integer id)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file FqanDAO.java.
.SH "Member Function Documentation"
.PP 
.SS "void portal.registration.dao.FqanDAO.delete (\fBFqan\fPpersistentInstance)"
.PP
Implemented in \fBportal.registration.dao.FqanDAOImpl\fP.
.PP
Referenced by portal.registration.services.FqanServiceImpl.delete().
.SS "\fBFqan\fP portal.registration.dao.FqanDAO.findById (Integerid)"
.PP
Implemented in \fBportal.registration.dao.FqanDAOImpl\fP.
.PP
Referenced by portal.registration.services.FqanServiceImpl.findByFqan(), and portal.registration.services.FqanServiceImpl.findById().
.SS "List<\fBFqan\fP> portal.registration.dao.FqanDAO.findByIdVo (Integerid)"
.PP
Implemented in \fBportal.registration.dao.FqanDAOImpl\fP.
.PP
Referenced by portal.registration.services.FqanServiceImpl.findByIdVo().
.SS "List<\fBFqan\fP> portal.registration.dao.FqanDAO.getAllFqan ()"
.PP
Implemented in \fBportal.registration.dao.FqanDAOImpl\fP.
.PP
Referenced by portal.registration.services.FqanServiceImpl.getAllFqan().
.SS "void portal.registration.dao.FqanDAO.save (\fBFqan\fPtransientInstance)"
.PP
Implemented in \fBportal.registration.dao.FqanDAOImpl\fP.
.PP
Referenced by portal.registration.services.FqanServiceImpl.save().

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
