.TH "portal.registration" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
portal.registration \- 
.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBcontroller\fP"
.br
.ti -1c
.RI "package \fBdao\fP"
.br
.ti -1c
.RI "package \fBdomain\fP"
.br
.ti -1c
.RI "package \fBserver\fP"
.br
.ti -1c
.RI "package \fBservices\fP"
.br
.ti -1c
.RI "package \fButils\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
