.TH "portal.registration.services" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
portal.registration.services \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBCertificateService\fP"
.br
.ti -1c
.RI "class \fBCertificateServiceImpl\fP"
.br
.ti -1c
.RI "interface \fBFqanService\fP"
.br
.ti -1c
.RI "class \fBFqanServiceImpl\fP"
.br
.ti -1c
.RI "interface \fBIdpService\fP"
.br
.ti -1c
.RI "class \fBIdpServiceImpl\fP"
.br
.ti -1c
.RI "interface \fBUserInfoService\fP"
.br
.ti -1c
.RI "class \fBUserInfoServiceImpl\fP"
.br
.ti -1c
.RI "interface \fBUserToVoService\fP"
.br
.ti -1c
.RI "class \fBUserToVoServiceImpl\fP"
.br
.ti -1c
.RI "interface \fBVoService\fP"
.br
.ti -1c
.RI "class \fBVoServiceImpl\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
