.TH "portal::registration::services::UserToVoServiceImpl" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
portal::registration::services::UserToVoServiceImpl \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBportal.registration.services.UserToVoService\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUserToVoServiceImpl\fP ()"
.br
.ti -1c
.RI "void \fBsave\fP (\fBUserToVo\fP transientInstance)"
.br
.ti -1c
.RI "void \fBsave\fP (int userId, int idVo)"
.br
.ti -1c
.RI "List< \fBUserToVo\fP > \fBfindById\fP (int userId)"
.br
.ti -1c
.RI "List< \fBVo\fP > \fBfindVoByUserId\fP (int userId)"
.br
.ti -1c
.RI "void \fBdelete\fP (int userId, int idVo)"
.br
.ti -1c
.RI "boolean \fBsetDefault\fP (int userId, int idVo)"
.br
.ti -1c
.RI "\fBUserToVo\fP \fBfindById\fP (int userId, int idVo)"
.br
.ti -1c
.RI "void \fBupdate\fP (\fBUserToVo\fP utv)"
.br
.ti -1c
.RI "String \fBfindDefaultVo\fP (int userId)"
.br
.ti -1c
.RI "String \fBgetDefaultFqan\fP (int userId)"
.br
.ti -1c
.RI "int \fBgetNumberOfUserToVo\fP (int userId)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBUserToVoDAO\fP \fBuserToVoDAO\fP"
.br
.ti -1c
.RI "\fBUserInfoDAO\fP \fBuserInfoDAO\fP"
.br
.ti -1c
.RI "\fBVoDAO\fP \fBvoDAO\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static final Logger \fBlog\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Home object for domain model class UserToVo.
.PP
\fBSee also:\fP
.RS 4
portal.registration.services.UserToVo 
.RE
.PP
\fBAuthor:\fP
.RS 4
Hibernate Tools 
.RE
.PP

.PP
Definition at line 28 of file UserToVoServiceImpl.java.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "portal.registration.services.UserToVoServiceImpl.UserToVoServiceImpl ()"
.PP
Definition at line 42 of file UserToVoServiceImpl.java.
.PP
.nf
                                     {

        }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void portal.registration.services.UserToVoServiceImpl.delete (intuserId, intidVo)"
.PP
Implements \fBportal.registration.services.UserToVoService\fP.
.PP
Definition at line 98 of file UserToVoServiceImpl.java.
.PP
References portal.registration.dao.UserToVoDAO.delete(), and portal.registration.services.UserToVoServiceImpl.userToVoDAO.
.PP
.nf
                                                 {

                userToVoDAO.delete(userId, idVo);

        }
.fi
.SS "List<\fBUserToVo\fP> portal.registration.services.UserToVoServiceImpl.findById (intuserId)"
.PP
Implements \fBportal.registration.services.UserToVoService\fP.
.PP
Definition at line 75 of file UserToVoServiceImpl.java.
.PP
References portal.registration.dao.UserToVoDAO.findById(), portal.registration.dao.UserInfoDAO.findById(), portal.registration.services.UserToVoServiceImpl.userInfoDAO, and portal.registration.services.UserToVoServiceImpl.userToVoDAO.
.PP
Referenced by portal.registration.services.UserToVoServiceImpl.findDefaultVo(), and portal.registration.services.UserToVoServiceImpl.getDefaultFqan().
.PP
.nf
                                                   {
                UserInfo userInfo = userInfoDAO.findById(userId);
                return userToVoDAO.findById(userInfo);
        }
.fi
.SS "\fBUserToVo\fP portal.registration.services.UserToVoServiceImpl.findById (intuserId, intidVo)"
.PP
Implements \fBportal.registration.services.UserToVoService\fP.
.PP
Definition at line 132 of file UserToVoServiceImpl.java.
.PP
References portal.registration.dao.UserToVoDAO.findByIds(), and portal.registration.services.UserToVoServiceImpl.userToVoDAO.
.PP
.nf
                                                       {
                return userToVoDAO.findByIds(userId, idVo);
        }
.fi
.SS "String portal.registration.services.UserToVoServiceImpl.findDefaultVo (intuserId)"
.PP
Implements \fBportal.registration.services.UserToVoService\fP.
.PP
Definition at line 143 of file UserToVoServiceImpl.java.
.PP
References portal.registration.dao.VoDAO.findById(), portal.registration.services.UserToVoServiceImpl.findById(), portal.registration.domain.UserToVoId.getIdVo(), portal.registration.domain.Vo.getVo(), and portal.registration.services.UserToVoServiceImpl.voDAO.
.PP
.nf
                                                {
                List<UserToVo> utvs = findById(userId);
                UserToVoId utvId = null;
                Vo vo = null;
                String voName = null;
                for (int i = 0; i < utvs.size(); i++) {
                        if (utvs.get(i).getIsDefault().equals('true')) {
                                utvId = utvs.get(i).getId();
                                vo = voDAO.findById(utvId.getIdVo());
                                voName = vo.getVo();
                                break;
                        }
                }
                return voName;
        }
.fi
.SS "List<\fBVo\fP> portal.registration.services.UserToVoServiceImpl.findVoByUserId (intuserId)"
.PP
Implements \fBportal.registration.services.UserToVoService\fP.
.PP
Definition at line 81 of file UserToVoServiceImpl.java.
.PP
References portal.registration.dao.UserToVoDAO.findById(), portal.registration.dao.UserInfoDAO.findById(), portal.registration.dao.UserToVoDAO.getVoByUserToVo(), portal.registration.services.UserToVoServiceImpl.userInfoDAO, and portal.registration.services.UserToVoServiceImpl.userToVoDAO.
.PP
.nf
                                                   {

                UserInfo userInfo = userInfoDAO.findById(userId);
                List<UserToVo> utvs = userToVoDAO.findById(userInfo);

                List<Vo> vos = new ArrayList<Vo>();

                for (int i = 0; i < utvs.size(); i++) {

                        vos.add(userToVoDAO.getVoByUserToVo(utvs.get(i)));

                }

                return vos;
        }
.fi
.SS "String portal.registration.services.UserToVoServiceImpl.getDefaultFqan (intuserId)"
.PP
Implements \fBportal.registration.services.UserToVoService\fP.
.PP
Definition at line 160 of file UserToVoServiceImpl.java.
.PP
References portal.registration.services.UserToVoServiceImpl.findById().
.PP
.nf
                                                 {
                List<UserToVo> utvs = findById(userId);
                String fqan = null;
                for (int i = 0; i < utvs.size(); i++) {
                        if (utvs.get(i).getIsDefault().equals('true')) {

                                fqan = utvs.get(i).getFqans();
                                break;
                        }
                }
                return fqan;
        }
.fi
.SS "int portal.registration.services.UserToVoServiceImpl.getNumberOfUserToVo (intuserId)"
.PP
Implements \fBportal.registration.services.UserToVoService\fP.
.PP
Definition at line 174 of file UserToVoServiceImpl.java.
.PP
References portal.registration.dao.UserToVoDAO.getNumberOfUserToVo(), and portal.registration.services.UserToVoServiceImpl.userToVoDAO.
.PP
.nf
                                                   {

                return userToVoDAO.getNumberOfUserToVo(userId);
        }
.fi
.SS "void portal.registration.services.UserToVoServiceImpl.save (intuserId, intidVo)"
.PP
Implements \fBportal.registration.services.UserToVoService\fP.
.PP
Definition at line 53 of file UserToVoServiceImpl.java.
.PP
References portal.registration.dao.VoDAO.findById(), portal.registration.dao.UserInfoDAO.findById(), portal.registration.services.UserToVoServiceImpl.log, portal.registration.dao.UserToVoDAO.save(), portal.registration.domain.UserToVo.setId(), portal.registration.domain.UserToVo.setIsDefault(), portal.registration.domain.UserToVo.setUserInfo(), portal.registration.domain.UserToVo.setVo(), portal.registration.services.UserToVoServiceImpl.userInfoDAO, portal.registration.services.UserToVoServiceImpl.userToVoDAO, and portal.registration.services.UserToVoServiceImpl.voDAO.
.PP
.nf
                                               {
                log.debug('persisting UserToVoService instance');

                UserToVo transientInstance = new UserToVo();

                UserToVoId utvid = new UserToVoId(userId, idVo);

                transientInstance.setId(utvid);

                UserInfo userInfo = userInfoDAO.findById(userId);
                Vo vo = voDAO.findById(idVo);

                transientInstance.setUserInfo(userInfo);
                transientInstance.setVo(vo);

                transientInstance.setIsDefault('false');

                userToVoDAO.save(transientInstance);

        }
.fi
.SS "void portal.registration.services.UserToVoServiceImpl.save (\fBUserToVo\fPtransientInstance)"
.PP
Implements \fBportal.registration.services.UserToVoService\fP.
.PP
Definition at line 47 of file UserToVoServiceImpl.java.
.PP
References portal.registration.services.UserToVoServiceImpl.log, portal.registration.dao.UserToVoDAO.save(), and portal.registration.services.UserToVoServiceImpl.userToVoDAO.
.PP
.nf
                                                     {
                log.debug('persisting UserToVoService instance');
                userToVoDAO.save(transientInstance);
        }
.fi
.SS "boolean portal.registration.services.UserToVoServiceImpl.setDefault (intuserId, intidVo)"
.PP
Implements \fBportal.registration.services.UserToVoService\fP.
.PP
Definition at line 105 of file UserToVoServiceImpl.java.
.PP
References portal.registration.dao.UserToVoDAO.findById(), portal.registration.dao.UserInfoDAO.findById(), portal.registration.dao.UserToVoDAO.findByIds(), portal.registration.domain.UserToVo.getIsDefault(), portal.registration.domain.UserToVo.setIsDefault(), portal.registration.dao.UserToVoDAO.update(), portal.registration.services.UserToVoServiceImpl.userInfoDAO, and portal.registration.services.UserToVoServiceImpl.userToVoDAO.
.PP
.nf
                                                        {

                UserToVo toUpdate = userToVoDAO.findByIds(userId, idVo);

                if (!toUpdate.getIsDefault().equals('true')) {

                        UserInfo userInfo = userInfoDAO.findById(userId);

                        List<UserToVo> utvs = userToVoDAO.findById(userInfo);

                        UserToVo temp = null;

                        for (int i = 0; i < utvs.size(); i++) {
                                temp = utvs.get(i);
                                temp.setIsDefault('false');
                                userToVoDAO.update(temp);
                        }

                        toUpdate.setIsDefault('true');
                        userToVoDAO.update(temp);

                        return true;
                }
                return false;
        }
.fi
.SS "void portal.registration.services.UserToVoServiceImpl.update (\fBUserToVo\fPutv)"
.PP
Implements \fBportal.registration.services.UserToVoService\fP.
.PP
Definition at line 137 of file UserToVoServiceImpl.java.
.PP
References portal.registration.dao.UserToVoDAO.update(), and portal.registration.services.UserToVoServiceImpl.userToVoDAO.
.PP
.nf
                                         {
                userToVoDAO.update(utv);

        }
.fi
.SH "Member Data Documentation"
.PP 
.SS "final Logger \fBportal.registration.services.UserToVoServiceImpl.log\fP\fC [static, private]\fP"\fBInitial value:\fP
.PP
.nf
 Logger
                        .getLogger(UserInfoServiceImpl.class)
.fi
.PP
Definition at line 30 of file UserToVoServiceImpl.java.
.PP
Referenced by portal.registration.services.UserToVoServiceImpl.save().
.SS "\fBUserInfoDAO\fP \fBportal.registration.services.UserToVoServiceImpl.userInfoDAO\fP\fC [private]\fP"
.PP
Definition at line 37 of file UserToVoServiceImpl.java.
.PP
Referenced by portal.registration.services.UserToVoServiceImpl.findById(), portal.registration.services.UserToVoServiceImpl.findVoByUserId(), portal.registration.services.UserToVoServiceImpl.save(), and portal.registration.services.UserToVoServiceImpl.setDefault().
.SS "\fBUserToVoDAO\fP \fBportal.registration.services.UserToVoServiceImpl.userToVoDAO\fP\fC [private]\fP"
.PP
Definition at line 34 of file UserToVoServiceImpl.java.
.PP
Referenced by portal.registration.services.UserToVoServiceImpl.delete(), portal.registration.services.UserToVoServiceImpl.findById(), portal.registration.services.UserToVoServiceImpl.findVoByUserId(), portal.registration.services.UserToVoServiceImpl.getNumberOfUserToVo(), portal.registration.services.UserToVoServiceImpl.save(), portal.registration.services.UserToVoServiceImpl.setDefault(), and portal.registration.services.UserToVoServiceImpl.update().
.SS "\fBVoDAO\fP \fBportal.registration.services.UserToVoServiceImpl.voDAO\fP\fC [private]\fP"
.PP
Definition at line 40 of file UserToVoServiceImpl.java.
.PP
Referenced by portal.registration.services.UserToVoServiceImpl.findDefaultVo(), and portal.registration.services.UserToVoServiceImpl.save().

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
