.TH "portal::registration::services::UserToVoService" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
portal::registration::services::UserToVoService \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBportal.registration.services.UserToVoServiceImpl\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsave\fP (\fBUserToVo\fP transientInstance)"
.br
.ti -1c
.RI "void \fBsave\fP (int userId, int idVo)"
.br
.ti -1c
.RI "List< \fBUserToVo\fP > \fBfindById\fP (int userId)"
.br
.ti -1c
.RI "List< \fBVo\fP > \fBfindVoByUserId\fP (int userId)"
.br
.ti -1c
.RI "void \fBdelete\fP (int userId, int idVo)"
.br
.ti -1c
.RI "boolean \fBsetDefault\fP (int userId, int idVo)"
.br
.ti -1c
.RI "\fBUserToVo\fP \fBfindById\fP (int userId, int idVo)"
.br
.ti -1c
.RI "void \fBupdate\fP (\fBUserToVo\fP utv)"
.br
.ti -1c
.RI "String \fBfindDefaultVo\fP (int userId)"
.br
.ti -1c
.RI "String \fBgetDefaultFqan\fP (int userId)"
.br
.ti -1c
.RI "int \fBgetNumberOfUserToVo\fP (int userId)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file UserToVoService.java.
.SH "Member Function Documentation"
.PP 
.SS "void portal.registration.services.UserToVoService.delete (intuserId, intidVo)"
.PP
Implemented in \fBportal.registration.services.UserToVoServiceImpl\fP.
.PP
Referenced by portal.registration.controller.AddUserToVOController.removeUserToVo(), and portal.registration.controller.AddUserToVOController.removeUserToVoEdit().
.SS "List<\fBUserToVo\fP> portal.registration.services.UserToVoService.findById (intuserId)"
.PP
Implemented in \fBportal.registration.services.UserToVoServiceImpl\fP.
.PP
Referenced by portal.registration.controller.EditUserToVoController.addUserToVo(), portal.registration.controller.AddUserToVOController.checkVO(), portal.registration.controller.EditUserToVoController.getUserToVo(), portal.registration.controller.EditUserInfoController.showEditUserInfoForm(), and portal.registration.controller.AddUserToVoPresentsController.showUserInfoForm().
.SS "\fBUserToVo\fP portal.registration.services.UserToVoService.findById (intuserId, intidVo)"
.PP
Implemented in \fBportal.registration.services.UserToVoServiceImpl\fP.
.SS "String portal.registration.services.UserToVoService.findDefaultVo (intuserId)"
.PP
Implemented in \fBportal.registration.services.UserToVoServiceImpl\fP.
.PP
Referenced by portal.registration.controller.EditUserInfoController.getDefaultVo().
.SS "List<\fBVo\fP> portal.registration.services.UserToVoService.findVoByUserId (intuserId)"
.PP
Implemented in \fBportal.registration.services.UserToVoServiceImpl\fP.
.PP
Referenced by portal.registration.controller.EditUserInfoController.getUserToVoList(), portal.registration.controller.AddUserToVoPresentsController.getUserToVoList(), portal.registration.controller.AddUserToVOController.removeUserToVoEdit(), portal.registration.controller.AddUserToVOController.setDefaultUserToVo(), and portal.registration.controller.AddUserToVOController.setDefaultUserToVoEdit().
.SS "String portal.registration.services.UserToVoService.getDefaultFqan (intuserId)"
.PP
Implemented in \fBportal.registration.services.UserToVoServiceImpl\fP.
.PP
Referenced by portal.registration.controller.EditUserInfoController.getDefaultFqan().
.SS "int portal.registration.services.UserToVoService.getNumberOfUserToVo (intuserId)"
.PP
Implemented in \fBportal.registration.services.UserToVoServiceImpl\fP.
.SS "void portal.registration.services.UserToVoService.save (intuserId, intidVo)"
.PP
Implemented in \fBportal.registration.services.UserToVoServiceImpl\fP.
.SS "void portal.registration.services.UserToVoService.save (\fBUserToVo\fPtransientInstance)"
.PP
Implemented in \fBportal.registration.services.UserToVoServiceImpl\fP.
.PP
Referenced by portal.registration.controller.AddUserToVOController.addUserToVo().
.SS "boolean portal.registration.services.UserToVoService.setDefault (intuserId, intidVo)"
.PP
Implemented in \fBportal.registration.services.UserToVoServiceImpl\fP.
.PP
Referenced by portal.registration.controller.AddUserToVOController.setDefaultUserToVo(), and portal.registration.controller.AddUserToVOController.setDefaultUserToVoEdit().
.SS "void portal.registration.services.UserToVoService.update (\fBUserToVo\fPutv)"
.PP
Implemented in \fBportal.registration.services.UserToVoServiceImpl\fP.
.PP
Referenced by portal.registration.controller.EditUserToVoController.addUserToVo().

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
