.TH "portal::registration::services::FqanService" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
portal::registration::services::FqanService \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBportal.registration.services.FqanServiceImpl\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsave\fP (\fBFqan\fP transientInstance)"
.br
.ti -1c
.RI "void \fBdelete\fP (\fBFqan\fP persistentInstance)"
.br
.ti -1c
.RI "\fBFqan\fP \fBfindById\fP (Integer id)"
.br
.ti -1c
.RI "String \fBfindByFqan\fP (\fBFqan\fP fqan)"
.br
.ti -1c
.RI "List< \fBFqan\fP > \fBgetAllFqan\fP ()"
.br
.ti -1c
.RI "List< \fBFqan\fP > \fBfindByIdVo\fP (int idVo)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file FqanService.java.
.SH "Member Function Documentation"
.PP 
.SS "void portal.registration.services.FqanService.delete (\fBFqan\fPpersistentInstance)"
.PP
Implemented in \fBportal.registration.services.FqanServiceImpl\fP.
.SS "String portal.registration.services.FqanService.findByFqan (\fBFqan\fPfqan)"
.PP
Implemented in \fBportal.registration.services.FqanServiceImpl\fP.
.SS "\fBFqan\fP portal.registration.services.FqanService.findById (Integerid)"
.PP
Implemented in \fBportal.registration.services.FqanServiceImpl\fP.
.SS "List<\fBFqan\fP> portal.registration.services.FqanService.findByIdVo (intidVo)"
.PP
Implemented in \fBportal.registration.services.FqanServiceImpl\fP.
.PP
Referenced by portal.registration.controller.EditUserToVoController.getFqans().
.SS "List<\fBFqan\fP> portal.registration.services.FqanService.getAllFqan ()"
.PP
Implemented in \fBportal.registration.services.FqanServiceImpl\fP.
.SS "void portal.registration.services.FqanService.save (\fBFqan\fPtransientInstance)"
.PP
Implemented in \fBportal.registration.services.FqanServiceImpl\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
