.TH "portal::registration::utils::VOMSTest" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
portal::registration::utils::VOMSTest \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)  throws VOMSException, MalformedURLException, RemoteException, ServiceException "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file VOMSTest.java.
.SH "Member Function Documentation"
.PP 
.SS "static void portal.registration.utils.VOMSTest.main (String[]args)  throws \fBVOMSException\fP, MalformedURLException, RemoteException, ServiceException \fC [static]\fP"
.PP
Definition at line 12 of file VOMSTest.java.
.PP
References portal.registration.utils.VOMSAdminCallOut.getUserFQANs().
.PP
.nf
                                                                                                                              {
                
                
                String[] roles = VOMSAdminCallOut.getUserFQANs('/C=IT/O=INFN/OU=Personal Certificate/L=Ferrara/CN=Enrico Vianello', '/C=IT/O=INFN/CN=INFN CA', 'voms-02.pd.infn.it:8443/voms/superbvo.org');

                for (int i = 0; i < roles.length; i++) {

                        System.out.println('roles ' + i + ' = ' + roles[i]);

                }
        }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
