.TH "portal::registration::controller::RemoveUserInfoController" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
portal::registration::controller::RemoveUserInfoController \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBremoveUserInfo\fP (@RequestParam int userId, ActionRequest request)  throws PortalException, SystemException "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBUserInfoService\fP \fBuserInfoService\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBRemoveUserInfoController\fP handles removal of UserInfo from the Catalog.
.PP
\fBAuthor:\fP
.RS 4
asarin 
.RE
.PP

.PP
Definition at line 29 of file RemoveUserInfoController.java.
.SH "Member Function Documentation"
.PP 
.SS "void portal.registration.controller.RemoveUserInfoController.removeUserInfo (@RequestParam intuserId, ActionRequestrequest)  throws PortalException, SystemException "
.PP
Definition at line 35 of file RemoveUserInfoController.java.
.PP
References portal.registration.services.UserInfoService.delete(), portal.registration.services.UserInfoService.findById(), and portal.registration.domain.UserInfo.getUsername().
.PP
.nf
                                                                                                                            {
                
                UserInfo userInfo = userInfoService.findById(userId);
                String username = userInfo.getUsername();
                
                long companyId = PortalUtil.getCompanyId(request);
                
                User user = UserLocalServiceUtil.getUserByScreenName(companyId,
                                username);
                
                UserLocalServiceUtil.deleteUser(user);
        
                userInfoService.delete(userId);
                
                SessionMessages.add(request, 'user-delated-successufully');
        }
.fi
.SH "Member Data Documentation"
.PP 
.SS "\fBUserInfoService\fP \fBportal.registration.controller.RemoveUserInfoController.userInfoService\fP\fC [private]\fP"
.PP
Definition at line 32 of file RemoveUserInfoController.java.

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
