.TH "portal::registration::services::UserInfoService" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
portal::registration::services::UserInfoService \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBportal.registration.services.UserInfoServiceImpl\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Integer \fBsave\fP (\fBUserInfo\fP transientInstance)"
.br
.ti -1c
.RI "void \fBdelete\fP (\fBUserInfo\fP persistentInstance)"
.br
.ti -1c
.RI "void \fBdelete\fP (int userId)"
.br
.ti -1c
.RI "\fBUserInfo\fP \fBfindById\fP (Integer id)"
.br
.ti -1c
.RI "List< \fBUserInfo\fP > \fBgetAllUserInfo\fP ()"
.br
.ti -1c
.RI "void \fBedit\fP (\fBUserInfo\fP userInfo)"
.br
.ti -1c
.RI "int \fBsave\fP (\fBUserInfo\fP userInfo, int idIDP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file UserInfoService.java.
.SH "Member Function Documentation"
.PP 
.SS "void portal.registration.services.UserInfoService.delete (\fBUserInfo\fPpersistentInstance)"
.PP
Implemented in \fBportal.registration.services.UserInfoServiceImpl\fP.
.PP
Referenced by portal.registration.controller.RemoveUserInfoController.removeUserInfo().
.SS "void portal.registration.services.UserInfoService.delete (intuserId)"
.PP
Implemented in \fBportal.registration.services.UserInfoServiceImpl\fP.
.SS "void portal.registration.services.UserInfoService.edit (\fBUserInfo\fPuserInfo)"
.PP
Implemented in \fBportal.registration.services.UserInfoServiceImpl\fP.
.PP
Referenced by portal.registration.controller.AddUserToVOController.activateUser(), portal.registration.controller.EditUserInfoController.deactivateUser(), portal.registration.controller.AddUserToVoPresentsController.deactivateUser(), and portal.registration.controller.EditUserInfoController.editUserInfo().
.SS "\fBUserInfo\fP portal.registration.services.UserInfoService.findById (Integerid)"
.PP
Implemented in \fBportal.registration.services.UserInfoServiceImpl\fP.
.PP
Referenced by portal.registration.controller.AddUserToVOController.addUserToVo(), portal.registration.controller.EditUserInfoController.deactivateUser(), portal.registration.controller.AddUserToVoPresentsController.deactivateUser(), portal.registration.controller.EditUserInfoController.editUserInfo(), portal.registration.controller.EditUserToVoController.getUserInfo(), portal.registration.controller.EditUserInfoController.getUserInfo(), and portal.registration.controller.RemoveUserInfoController.removeUserInfo().
.SS "List<\fBUserInfo\fP> portal.registration.services.UserInfoService.getAllUserInfo ()"
.PP
Implemented in \fBportal.registration.services.UserInfoServiceImpl\fP.
.PP
Referenced by portal.registration.controller.UserInfoController.getIdpsName(), and portal.registration.controller.UserInfoController.getUserInfos().
.SS "int portal.registration.services.UserInfoService.save (\fBUserInfo\fPuserInfo, intidIDP)"
.PP
Implemented in \fBportal.registration.services.UserInfoServiceImpl\fP.
.SS "Integer portal.registration.services.UserInfoService.save (\fBUserInfo\fPtransientInstance)"
.PP
Implemented in \fBportal.registration.services.UserInfoServiceImpl\fP.
.PP
Referenced by portal.registration.controller.AddUserInfoController.addUserInfo().

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
