.TH "portal::registration::services::VoService" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
portal::registration::services::VoService \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBportal.registration.services.VoServiceImpl\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "List< \fBVo\fP > \fBgetAllVo\fP ()"
.br
.ti -1c
.RI "\fBVo\fP \fBfindById\fP (Integer id)"
.br
.ti -1c
.RI "String \fBfindByVo\fP (\fBVo\fP vo)"
.br
.ti -1c
.RI "List< String > \fBgetAllDiscplines\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file VoService.java.
.SH "Member Function Documentation"
.PP 
.SS "\fBVo\fP portal.registration.services.VoService.findById (Integerid)"
.PP
Implemented in \fBportal.registration.services.VoServiceImpl\fP.
.PP
Referenced by portal.registration.controller.AddUserToVOController.checkVO(), and portal.registration.controller.EditUserToVoController.getVO().
.SS "String portal.registration.services.VoService.findByVo (\fBVo\fPvo)"
.PP
Implemented in \fBportal.registration.services.VoServiceImpl\fP.
.SS "List<String> portal.registration.services.VoService.getAllDiscplines ()"
.PP
Implemented in \fBportal.registration.services.VoServiceImpl\fP.
.PP
Referenced by portal.registration.controller.AddUserToVOController.getDisciplines().
.SS "List<\fBVo\fP> portal.registration.services.VoService.getAllVo ()"
.PP
Implemented in \fBportal.registration.services.VoServiceImpl\fP.
.PP
Referenced by portal.registration.controller.VOListController.getVos(), portal.registration.controller.AddUserToVoPresentsController.getVos(), and portal.registration.controller.AddUserToVOController.getVos().

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
