.TH "portal::registration::dao::VoDAO" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
portal::registration::dao::VoDAO \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBportal.registration.dao.VoDAOImpl\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "List< \fBVo\fP > \fBgetAllVo\fP ()"
.br
.ti -1c
.RI "\fBVo\fP \fBfindById\fP (Integer id)"
.br
.ti -1c
.RI "List< String > \fBgetAllDiscipline\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file VoDAO.java.
.SH "Member Function Documentation"
.PP 
.SS "\fBVo\fP portal.registration.dao.VoDAO.findById (Integerid)"
.PP
Implemented in \fBportal.registration.dao.VoDAOImpl\fP.
.PP
Referenced by portal.registration.services.VoServiceImpl.findById(), portal.registration.services.VoServiceImpl.findByVo(), portal.registration.services.UserToVoServiceImpl.findDefaultVo(), and portal.registration.services.UserToVoServiceImpl.save().
.SS "List<String> portal.registration.dao.VoDAO.getAllDiscipline ()"
.PP
Implemented in \fBportal.registration.dao.VoDAOImpl\fP.
.PP
Referenced by portal.registration.services.VoServiceImpl.getAllDiscplines().
.SS "List<\fBVo\fP> portal.registration.dao.VoDAO.getAllVo ()"
.PP
Implemented in \fBportal.registration.dao.VoDAOImpl\fP.
.PP
Referenced by portal.registration.services.VoServiceImpl.getAllVo().

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
