.TH "portal::registration::dao::UserInfoDAO" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
portal::registration::dao::UserInfoDAO \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBportal.registration.dao.UserInfoDAOImpl\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Integer \fBsave\fP (\fBUserInfo\fP transientInstance)"
.br
.ti -1c
.RI "void \fBdelete\fP (\fBUserInfo\fP persistentInstance)"
.br
.ti -1c
.RI "\fBUserInfo\fP \fBfindById\fP (Integer id)"
.br
.ti -1c
.RI "List< \fBUserInfo\fP > \fBgetAllUserInfo\fP ()"
.br
.ti -1c
.RI "void \fBedit\fP (\fBUserInfo\fP userInfo)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file UserInfoDAO.java.
.SH "Member Function Documentation"
.PP 
.SS "void portal.registration.dao.UserInfoDAO.delete (\fBUserInfo\fPpersistentInstance)"
.PP
Implemented in \fBportal.registration.dao.UserInfoDAOImpl\fP.
.PP
Referenced by portal.registration.services.UserInfoServiceImpl.delete().
.SS "void portal.registration.dao.UserInfoDAO.edit (\fBUserInfo\fPuserInfo)"
.PP
Implemented in \fBportal.registration.dao.UserInfoDAOImpl\fP.
.PP
Referenced by portal.registration.services.UserInfoServiceImpl.edit().
.SS "\fBUserInfo\fP portal.registration.dao.UserInfoDAO.findById (Integerid)"
.PP
Implemented in \fBportal.registration.dao.UserInfoDAOImpl\fP.
.PP
Referenced by portal.registration.services.UserInfoServiceImpl.delete(), portal.registration.services.UserToVoServiceImpl.findById(), portal.registration.services.UserInfoServiceImpl.findById(), portal.registration.services.CertificateServiceImpl.findById(), portal.registration.services.UserToVoServiceImpl.findVoByUserId(), portal.registration.services.UserToVoServiceImpl.save(), portal.registration.services.CertificateServiceImpl.save(), and portal.registration.services.UserToVoServiceImpl.setDefault().
.SS "List<\fBUserInfo\fP> portal.registration.dao.UserInfoDAO.getAllUserInfo ()"
.PP
Implemented in \fBportal.registration.dao.UserInfoDAOImpl\fP.
.PP
Referenced by portal.registration.services.UserInfoServiceImpl.getAllUserInfo().
.SS "Integer portal.registration.dao.UserInfoDAO.save (\fBUserInfo\fPtransientInstance)"
.PP
Implemented in \fBportal.registration.dao.UserInfoDAOImpl\fP.
.PP
Referenced by portal.registration.services.UserInfoServiceImpl.save().

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
