.TH "portal::registration::dao::IdpDAO" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
portal::registration::dao::IdpDAO \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBportal.registration.dao.IdpDAOImpl\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsave\fP (\fBIdp\fP transientInstance)"
.br
.ti -1c
.RI "void \fBdelete\fP (\fBIdp\fP persistentInstance)"
.br
.ti -1c
.RI "\fBIdp\fP \fBfindById\fP (Integer id)"
.br
.ti -1c
.RI "List< \fBIdp\fP > \fBgetAllIdp\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file IdpDAO.java.
.SH "Member Function Documentation"
.PP 
.SS "void portal.registration.dao.IdpDAO.delete (\fBIdp\fPpersistentInstance)"
.PP
Implemented in \fBportal.registration.dao.IdpDAOImpl\fP.
.PP
Referenced by portal.registration.services.IdpServiceImpl.delete().
.SS "\fBIdp\fP portal.registration.dao.IdpDAO.findById (Integerid)"
.PP
Implemented in \fBportal.registration.dao.IdpDAOImpl\fP.
.PP
Referenced by portal.registration.services.IdpServiceImpl.findById(), portal.registration.services.IdpServiceImpl.findByIdp(), and portal.registration.services.UserInfoServiceImpl.save().
.SS "List<\fBIdp\fP> portal.registration.dao.IdpDAO.getAllIdp ()"
.PP
Implemented in \fBportal.registration.dao.IdpDAOImpl\fP.
.PP
Referenced by portal.registration.services.IdpServiceImpl.getAllIdp().
.SS "void portal.registration.dao.IdpDAO.save (\fBIdp\fPtransientInstance)"
.PP
Implemented in \fBportal.registration.dao.IdpDAOImpl\fP.
.PP
Referenced by portal.registration.services.IdpServiceImpl.save().

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
