.TH "portal::registration::controller::RequestCertificateController" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
portal::registration::controller::RequestCertificateController \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBshowUserInfoForm\fP (RenderResponse response)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file RequestCertificateController.java.
.SH "Member Function Documentation"
.PP 
.SS "String portal.registration.controller.RequestCertificateController.showUserInfoForm (RenderResponseresponse)"
.PP
Definition at line 14 of file RequestCertificateController.java.
.PP
.nf
                                                                {
                return 'requestCertificate';
        }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
