.TH "portal::registration::dao::CertificateDAO" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
portal::registration::dao::CertificateDAO \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBportal.registration.dao.CertificateDAOImpl\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Integer \fBsave\fP (\fBCertificate\fP transientInstance)"
.br
.ti -1c
.RI "void \fBdelete\fP (\fBCertificate\fP persistentInstance)"
.br
.ti -1c
.RI "List< \fBCertificate\fP > \fBfindById\fP (\fBUserInfo\fP userInfo)"
.br
.ti -1c
.RI "\fBCertificate\fP \fBfindById\fP (Integer id)"
.br
.ti -1c
.RI "void \fBedit\fP (\fBCertificate\fP certificate)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file CertificateDAO.java.
.SH "Member Function Documentation"
.PP 
.SS "void portal.registration.dao.CertificateDAO.delete (\fBCertificate\fPpersistentInstance)"
.PP
Implemented in \fBportal.registration.dao.CertificateDAOImpl\fP.
.PP
Referenced by portal.registration.services.CertificateServiceImpl.delete().
.SS "void portal.registration.dao.CertificateDAO.edit (\fBCertificate\fPcertificate)"
.PP
Implemented in \fBportal.registration.dao.CertificateDAOImpl\fP.
.PP
Referenced by portal.registration.services.CertificateServiceImpl.save(), and portal.registration.services.CertificateServiceImpl.setDefault().
.SS "\fBCertificate\fP portal.registration.dao.CertificateDAO.findById (Integerid)"
.PP
Implemented in \fBportal.registration.dao.CertificateDAOImpl\fP.
.SS "List<\fBCertificate\fP> portal.registration.dao.CertificateDAO.findById (\fBUserInfo\fPuserInfo)"
.PP
Implemented in \fBportal.registration.dao.CertificateDAOImpl\fP.
.PP
Referenced by portal.registration.services.CertificateServiceImpl.delete(), portal.registration.services.CertificateServiceImpl.findById(), portal.registration.services.CertificateServiceImpl.save(), and portal.registration.services.CertificateServiceImpl.setDefault().
.SS "Integer portal.registration.dao.CertificateDAO.save (\fBCertificate\fPtransientInstance)"
.PP
Implemented in \fBportal.registration.dao.CertificateDAOImpl\fP.
.PP
Referenced by portal.registration.services.CertificateServiceImpl.save().

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
