.TH "portal::registration::controller::EditUserInfoController" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
portal::registration::controller::EditUserInfoController \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBshowEditUserInfoForm\fP (@RequestParam int userId, RenderRequest request)"
.br
.ti -1c
.RI "void \fBeditUserInfo\fP (@ModelAttribute('userInfo') UserInfo userInfo, ActionRequest request, ActionResponse response, SessionStatus sessionStatus)  throws SystemException "
.br
.ti -1c
.RI "String \fBgetDefaultVo\fP (@RequestParam int userId)"
.br
.ti -1c
.RI "String \fBgetDefaultFqan\fP (@RequestParam int userId)"
.br
.ti -1c
.RI "\fBUserInfo\fP \fBgetUserInfo\fP (@RequestParam int userId)"
.br
.ti -1c
.RI "List< \fBCertificate\fP > \fBgetListCert\fP (@RequestParam int userId)"
.br
.ti -1c
.RI "List< \fBVo\fP > \fBgetUserToVoList\fP (@RequestParam int userId)"
.br
.ti -1c
.RI "void \fBuploadComplete\fP (ActionResponse response, SessionStatus sessionStatus)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBdeactivateUser\fP (int userId, RenderRequest request)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBUserInfoService\fP \fBuserInfoService\fP"
.br
.ti -1c
.RI "\fBCertificateService\fP \fBcertificateService\fP"
.br
.ti -1c
.RI "\fBUserToVoService\fP \fBuserToVoService\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file EditUserInfoController.java.
.SH "Member Function Documentation"
.PP 
.SS "void portal.registration.controller.EditUserInfoController.deactivateUser (intuserId, RenderRequestrequest)\fC [private]\fP"
.PP
Definition at line 62 of file EditUserInfoController.java.
.PP
References portal.registration.services.UserInfoService.edit(), portal.registration.services.UserInfoService.findById(), portal.registration.domain.UserInfo.getRegistrationComplete(), portal.registration.domain.UserInfo.getUsername(), and portal.registration.domain.UserInfo.setRegistrationComplete().
.PP
.nf
                                                                       {

                UserInfo userInfo = userInfoService.findById(userId);

                if (userInfo.getRegistrationComplete().equals('true')) {
                        String username = userInfo.getUsername();

                        long companyId = PortalUtil.getCompanyId(request);

                        User user;
                        try {
                                user = UserLocalServiceUtil.getUserByScreenName(companyId,
                                                username);

                                UserLocalServiceUtil.deleteRoleUser((long) 10140,
                                                user.getUserId());

                                userInfo.setRegistrationComplete('false');

                                userInfoService.edit(userInfo);

                        } catch (PortalException e) {
                                SessionErrors.add(request, 'exception-deactivation-user');
                                e.printStackTrace();
                        } catch (SystemException e) {
                                SessionErrors.add(request, 'exception-deactivation-user');
                                e.printStackTrace();
                        }
                }

        }
.fi
.SS "void portal.registration.controller.EditUserInfoController.editUserInfo (@ModelAttribute('userInfo') UserInfouserInfo, ActionRequestrequest, ActionResponseresponse, SessionStatussessionStatus)  throws SystemException "
.PP
Definition at line 95 of file EditUserInfoController.java.
.PP
References portal.registration.services.UserInfoService.edit(), portal.registration.services.UserInfoService.findById(), portal.registration.domain.UserInfo.setFirstName(), and portal.registration.utils.MyValidator.validateUpdate().
.PP
.nf
                                                                            {

                ArrayList<String> errors = new ArrayList<String>();
                boolean allOk = true;
                UserInfo check = userInfoService.findById(userInfo.getUserId());
                if (MyValidator.validateUpdate(userInfo, check, errors)) {

                        try {
                                long companyId = PortalUtil.getCompanyId(request);
                                User user = UserLocalServiceUtil.getUserByScreenName(companyId,
                                                userInfo.getUsername());

                                user.setFirstName(userInfo.getFirstName());
                                user.setLastName(userInfo.getLastName());

                                UserLocalServiceUtil.updateUser(user);

                        } catch (Exception e) {
                                errors.add('problem-update-user-liferay');
                                allOk = false;
                        }

                        try {
                                userInfoService.edit(userInfo);
                        } catch (Exception e) {
                                errors.add('problem-update-user');
                                allOk = false;
                        }
                } else {
                        allOk = false;
                }
                if (allOk) {
                        SessionMessages.add(request, 'user-updated-successufully');
                } else {
                        errors.add('error-updating-user');

                        for (String error : errors) {
                                SessionErrors.add(request, error);
                        }
                }

                response.setRenderParameter('myaction', 'editUserInfoForm');
                response.setRenderParameter('userId',
                                Integer.toString(userInfo.getUserId()));
                sessionStatus.setComplete();

        }
.fi
.SS "String portal.registration.controller.EditUserInfoController.getDefaultFqan (@RequestParam intuserId)"
.PP
Definition at line 151 of file EditUserInfoController.java.
.PP
References portal.registration.services.UserToVoService.getDefaultFqan().
.PP
.nf
                                                               {
                return userToVoService.getDefaultFqan(userId);
        }
.fi
.SS "String portal.registration.controller.EditUserInfoController.getDefaultVo (@RequestParam intuserId)"
.PP
Definition at line 146 of file EditUserInfoController.java.
.PP
References portal.registration.services.UserToVoService.findDefaultVo().
.PP
.nf
                                                             {
                return userToVoService.findDefaultVo(userId);
        }
.fi
.SS "List<\fBCertificate\fP> portal.registration.controller.EditUserInfoController.getListCert (@RequestParam intuserId)"
.PP
Definition at line 161 of file EditUserInfoController.java.
.PP
References portal.registration.services.CertificateService.findById().
.PP
.nf
                                                                       {
                return certificateService.findById(userId);
        }
.fi
.SS "\fBUserInfo\fP portal.registration.controller.EditUserInfoController.getUserInfo (@RequestParam intuserId)"
.PP
Definition at line 156 of file EditUserInfoController.java.
.PP
References portal.registration.services.UserInfoService.findById().
.PP
.nf
                                                              {
                return userInfoService.findById(userId);
        }
.fi
.SS "List<\fBVo\fP> portal.registration.controller.EditUserInfoController.getUserToVoList (@RequestParam intuserId)"
.PP
Definition at line 166 of file EditUserInfoController.java.
.PP
References portal.registration.services.UserToVoService.findVoByUserId().
.PP
.nf
                                                                  {

                return userToVoService.findVoByUserId(userId);
        }
.fi
.SS "String portal.registration.controller.EditUserInfoController.showEditUserInfoForm (@RequestParam intuserId, RenderRequestrequest)"
.PP
Definition at line 51 of file EditUserInfoController.java.
.PP
References portal.registration.services.UserToVoService.findById().
.PP
.nf
                                               {

                if (userToVoService.findById(userId).size() == 0) {
                        deactivateUser(userId, request);
                        SessionMessages.add(request, 'user-deactivate');
                }

                return 'editUserInfoForm';
        }
.fi
.SS "void portal.registration.controller.EditUserInfoController.uploadComplete (ActionResponseresponse, SessionStatussessionStatus)"
.PP
Definition at line 172 of file EditUserInfoController.java.
.PP
.nf
                                                     {

                response.setRenderParameter('myaction', 'userInfos');
                sessionStatus.setComplete();

        }
.fi
.SH "Member Data Documentation"
.PP 
.SS "\fBCertificateService\fP \fBportal.registration.controller.EditUserInfoController.certificateService\fP\fC [private]\fP"
.PP
Definition at line 45 of file EditUserInfoController.java.
.SS "\fBUserInfoService\fP \fBportal.registration.controller.EditUserInfoController.userInfoService\fP\fC [private]\fP"
.PP
Definition at line 42 of file EditUserInfoController.java.
.SS "\fBUserToVoService\fP \fBportal.registration.controller.EditUserInfoController.userToVoService\fP\fC [private]\fP"
.PP
Definition at line 48 of file EditUserInfoController.java.

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
