.TH "portal.registration.domain" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
portal.registration.domain \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCertificate\fP"
.br
.ti -1c
.RI "class \fBFqan\fP"
.br
.ti -1c
.RI "class \fBIdp\fP"
.br
.ti -1c
.RI "class \fBUserInfo\fP"
.br
.ti -1c
.RI "class \fBUserToVo\fP"
.br
.ti -1c
.RI "class \fBUserToVoId\fP"
.br
.ti -1c
.RI "class \fBVo\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
