.TH "portal.registration.controller" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
portal.registration.controller \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAddUserInfoController\fP"
.br
.ti -1c
.RI "class \fBAddUserToVOController\fP"
.br
.ti -1c
.RI "class \fBAddUserToVoPresentsController\fP"
.br
.ti -1c
.RI "class \fBEditUserInfoController\fP"
.br
.ti -1c
.RI "class \fBEditUserToVoController\fP"
.br
.ti -1c
.RI "class \fBRemoveUserInfoController\fP"
.br
.ti -1c
.RI "class \fBRequestCertificateController\fP"
.br
.ti -1c
.RI "class \fBUploadCertController\fP"
.br
.ti -1c
.RI "class \fBUserInfoController\fP"
.br
.ti -1c
.RI "class \fBVOListController\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
