.TH "portal::registration::dao::UserToVoDAO" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
portal::registration::dao::UserToVoDAO \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBportal.registration.dao.UserToVoDAOImpl\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsave\fP (\fBUserToVo\fP transientInstance)"
.br
.ti -1c
.RI "List< \fBUserToVo\fP > \fBfindById\fP (\fBUserInfo\fP userInfo)"
.br
.ti -1c
.RI "\fBVo\fP \fBgetVoByUserToVo\fP (\fBUserToVo\fP userToVo)"
.br
.ti -1c
.RI "void \fBdelete\fP (int userId, int idVo)"
.br
.ti -1c
.RI "\fBUserToVo\fP \fBfindByIds\fP (int userId, int idVo)"
.br
.ti -1c
.RI "void \fBupdate\fP (\fBUserToVo\fP temp)"
.br
.ti -1c
.RI "int \fBgetNumberOfUserToVo\fP (int userId)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file UserToVoDAO.java.
.SH "Member Function Documentation"
.PP 
.SS "void portal.registration.dao.UserToVoDAO.delete (intuserId, intidVo)"
.PP
Implemented in \fBportal.registration.dao.UserToVoDAOImpl\fP.
.PP
Referenced by portal.registration.services.UserToVoServiceImpl.delete().
.SS "List<\fBUserToVo\fP> portal.registration.dao.UserToVoDAO.findById (\fBUserInfo\fPuserInfo)"
.PP
Implemented in \fBportal.registration.dao.UserToVoDAOImpl\fP.
.PP
Referenced by portal.registration.services.UserToVoServiceImpl.findById(), portal.registration.services.UserToVoServiceImpl.findVoByUserId(), and portal.registration.services.UserToVoServiceImpl.setDefault().
.SS "\fBUserToVo\fP portal.registration.dao.UserToVoDAO.findByIds (intuserId, intidVo)"
.PP
Implemented in \fBportal.registration.dao.UserToVoDAOImpl\fP.
.PP
Referenced by portal.registration.services.UserToVoServiceImpl.findById(), and portal.registration.services.UserToVoServiceImpl.setDefault().
.SS "int portal.registration.dao.UserToVoDAO.getNumberOfUserToVo (intuserId)"
.PP
Implemented in \fBportal.registration.dao.UserToVoDAOImpl\fP.
.PP
Referenced by portal.registration.services.UserToVoServiceImpl.getNumberOfUserToVo().
.SS "\fBVo\fP portal.registration.dao.UserToVoDAO.getVoByUserToVo (\fBUserToVo\fPuserToVo)"
.PP
Implemented in \fBportal.registration.dao.UserToVoDAOImpl\fP.
.PP
Referenced by portal.registration.services.UserToVoServiceImpl.findVoByUserId().
.SS "void portal.registration.dao.UserToVoDAO.save (\fBUserToVo\fPtransientInstance)"
.PP
Implemented in \fBportal.registration.dao.UserToVoDAOImpl\fP.
.PP
Referenced by portal.registration.services.UserToVoServiceImpl.save().
.SS "void portal.registration.dao.UserToVoDAO.update (\fBUserToVo\fPtemp)"
.PP
Implemented in \fBportal.registration.dao.UserToVoDAOImpl\fP.
.PP
Referenced by portal.registration.services.UserToVoServiceImpl.setDefault(), and portal.registration.services.UserToVoServiceImpl.update().

.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
