.TH "/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/attributes/VOMSAttributes.java" 3 "Wed Jul 13 2011" "Version 4" "Registration" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/mikel8/Documents/Uni/workspace/Registration/src/main/java/org/glite/security/voms/service/attributes/VOMSAttributes.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBorg.glite.security.voms.service.attributes.VOMSAttributes\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBorg.glite.security.voms.service.attributes\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Registration from the source code.
