package portal.registration.domain;

// Generated 16-giu-2011 14.35.16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Idp generated by hbm2java
 */
@Entity
@Table(name = "IDP", catalog = "PortalUser")
public class Idp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8730283017965656825L;
	private int idIdp;
	private String idpname;
	private String idpaddress;
	private String idploginAddress;
	private String idpparameterRequest;
	private String idpattributeRequest;
	private String idpdescription;
	private Set<UserInfo> userInfos = new HashSet<UserInfo>(0);

	public Idp() {
	}

	public Idp(String idpname, String idpaddress, String idploginAddress,
			String idpparameterRequest, String idpattributeRequest,
			String idpdescription) {
		this.idpname = idpname;
		this.idpaddress = idpaddress;
		this.idploginAddress = idploginAddress;
		this.idpparameterRequest = idpparameterRequest;
		this.idpattributeRequest = idpattributeRequest;
		this.idpdescription = idpdescription;
	}

	public Idp(String idpname, String idpaddress, String idploginAddress,
			String idpparameterRequest, String idpattributeRequest,
			String idpdescription, Set<UserInfo> userInfos) {
		this.idpname = idpname;
		this.idpaddress = idpaddress;
		this.idploginAddress = idploginAddress;
		this.idpparameterRequest = idpparameterRequest;
		this.idpattributeRequest = idpattributeRequest;
		this.idpdescription = idpdescription;
		this.userInfos = userInfos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idIDP", unique = true, nullable = false)
	public int getIdIdp() {
		return this.idIdp;
	}

	public void setIdIdp(int idIdp) {
		this.idIdp = idIdp;
	}

	@Column(name = "IDPName", nullable = false, length = 75)
	public String getIdpname() {
		return this.idpname;
	}

	public void setIdpname(String idpname) {
		this.idpname = idpname;
	}

	@Column(name = "IDPAddress", nullable = false, length = 100)
	public String getIdpaddress() {
		return this.idpaddress;
	}

	public void setIdpaddress(String idpaddress) {
		this.idpaddress = idpaddress;
	}

	@Column(name = "IDPLoginAddress", nullable = false, length = 200)
	public String getIdploginAddress() {
		return this.idploginAddress;
	}

	public void setIdploginAddress(String idploginAddress) {
		this.idploginAddress = idploginAddress;
	}

	@Column(name = "IDPParameterRequest", nullable = false, length = 200)
	public String getIdpparameterRequest() {
		return this.idpparameterRequest;
	}

	public void setIdpparameterRequest(String idpparameterRequest) {
		this.idpparameterRequest = idpparameterRequest;
	}

	@Column(name = "IDPAttributeRequest", nullable = false, length = 200)
	public String getIdpattributeRequest() {
		return this.idpattributeRequest;
	}

	public void setIdpattributeRequest(String idpattributeRequest) {
		this.idpattributeRequest = idpattributeRequest;
	}

	@Column(name = "IDPDescription", nullable = false, length = 65535)
	public String getIdpdescription() {
		return this.idpdescription;
	}

	public void setIdpdescription(String idpdescription) {
		this.idpdescription = idpdescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idp")
	public Set<UserInfo> getUserInfos() {
		return this.userInfos;
	}

	public void setUserInfos(Set<UserInfo> userInfos) {
		this.userInfos = userInfos;
	}

}
